### ISSUE TITLE
Stopping a hunt is too hard, Pausing does unexpected things

### ISSUE THREAD

**Issue by destijl** [google/grr#106]
There are a couple of issues around stopping, modifying, and pausing a hunt that need fixing, I'll attempt to summarise here:

1. Pausing a hunt and then pressing "play" again causes the hunt to re-run on all machines, even those it has already completed on.  This is very surprising thing from the user's perspective, but is a compromise made to ensure the hunt completes on all the expected clients without requiring a computationally expensive analysis of all clients to determine their current state for the hunt.

Proposed solution: Eliminate pause.  Create "copy", and "stop" buttons.  Once stopped, a hunt can't be restarted, but you can copy it to a new hunt, modify, and run it again.

2. Once a hunt has started a flow on a client there is no good way to stop it.

Proposed solution: Keep checking for a "TERMINATED" or similar attribute on the flow that we can blind write to all flow children of a hunt, and raise if it is found.  The "stop" button would trigger the write.  This avoids the need to open all the child flows. Incoming messages from the clients will still need to be stored and processed, but we can at least stop any further work from being sent to the client.

**Comment by destijl** [comment]
Blocked by angular forms #115

**Comment by pidydx** [comment]
This is a pretty serious problem.  A hunt got scheduled that was gathering far too much data and didn't get noticed until BadStuff(tm) happened and tons of clients were already scheduled.  Stop/Copy would have allowed a reasonably easy fix to retarget the hunt appropriately and stop some of the incoming data.
