### ISSUE TITLE
Client Communication Issues

### ISSUE THREAD

**Issue by pidydx** [google/grr#108]
The client occasionally seems to stop communicating and requires a restart to bring it back.  I have seen this on a few clients and others I know testing GRR have observed this behavior as well.  GRRlog.txt doesn't have any errors.  It just seems to occasionally stop. 

DEBUG:2015-01-30 13:04:59,842 logging:1619] Request took 1.58099985123 Seconds
DEBUG:2015-01-30 13:04:59,848 logging:1619] aff4:/C.9c490ad3b918904e: Sending 832(34845), Received 0 messages. Sleeping for 0.2
INFO:2015-01-30 13:05:37,431 logging:1611] Sending back client statistics to the server.
INFO:2015-01-30 13:22:12,740 logging:1611] Queue is full, dropping messages.
INFO:2015-01-30 13:22:18,526 logging:1611] Queue is full, dropping messages.
INFO:2015-01-30 13:23:18,536 logging:1611] Sending back client statistics to the server.

**Comment by destijl** [comment]
Check that we are sending client stats from the right thread.

**Comment by pidydx** [comment]
I don't think this is a problem anymore.  I have not observed this behavior in quite a long time.  Will reopen if it is observed again.
