### ISSUE TITLE
install_script_ubuntu.sh fails

### ISSUE THREAD

**Issue by kevthehermit** [google/grr#111]
Running in to a few issues with the installer script. was working fine yesterday. Today 

Ubuntu 14.04 x64

```
##########################################################################################
     Installing GRR from prebuilt package
##########################################################################################
https://72db995be8d9351a447467116a957b52ccdca415.googledrive.com/host/0B1wsLqFoT7i2c3F0ZmI1RDJlUEU/test-grr-server_0.3.1-1_amd64.deb:
2015-02-06 08:35:12 ERROR 404: Not Found.
#########################################################################################
FAILURE RUNNING: wget --no-verbose https://googledrive.com/host/0B1wsLqFoT7i2c3F0ZmI1RDJlUEU/test-grr-server_0.3.1-1_amd64.deb -O test-grr-server_0.3.1-1_amd64.deb
##########################################
```

**Comment by destijl** [comment]
Thanks for the report, there's a small bug in the script that causes it to look for the beta package version, I'll have a fix out for that shortly.  But I'm also getting errors downloading the stable package, which does exist.  I'm looking into that problem now.

**Comment by destijl** [comment]
Fix for the script is here:
https://github.com/google/grr/pull/112

**Comment by destijl** [comment]
It seems we might be running into a google drive problem. I've re-uploaded the server debs and the script with the above patch works now.

**Comment by kevthehermit** [comment]
Thanks very much, appreciate the quick response.
