### ISSUE TITLE
Download ADS streams attached to a directory

### ISSUE THREAD

**Issue by pidydx** [google/grr#114]
Using TSK it will show ADS streams attached to files properly and allow them to be downloaded.  ADS streams attached to Directories appear as Directories and the download button is unavailable.

**Comment by scudette** [comment]
Can you please attach the output of fstat or istate (from the TSK tools) on this directory? I suspect this is not an ADS but an MFT with both $DATA attribute and $I30 attribute (i.e. its not an alternate data stream just a regular data stream on a directory). An ADS typically has a name and so in GRR will actually appear as a different file name.

With the current abstraction in GRR a file/directory on the client can be either a file or a directory. This is clearly not really true on windows as an MFT entry can be both a file and a directory at the same time. We have plans to update the data model so we can store different objects at the same URN which should fix this problem and many others.

**Comment by pidydx** [comment]
I created 2 ADSs.  One attached to a file and one attached to a directory.  Both show up in the GRR UI, but the one attached to the file shows up as a file and allows me to download it.  The one attached to the directory shows up as a directory and has no download option.

test 	VFSDirectory
test.vbs 	VFSFile 	
test.vbs:test.exe 	VFSBlobImage
test:test.exe 	VFSDirectory   <--This should probably be VFSFile even though it is attached to a Directory

**Comment by destijl** [comment]
scudette to try and reproduce and fix

**Comment by grrrrrrrrr** [comment]
This was fixed in https://github.com/google/grr/commit/4b7f9b06d1dfebd3dc86a6fa2eb7592f233b5330 . It's partly a client bug though so you need to rebuild the client or wait for us to release new templates before this works. Still, marking as fixed.
