### ISSUE TITLE
Rekall results not rendered most places in the UI

### ISSUE THREAD

**Issue by destijl** [google/grr#116]
Rekall results don't get rendered properly, you see a json blob in most places.  You can see properly rendered results under the filesystem view, find the right collection, and click the results tab, but this is poor UX.

Suggest we render some of the data, and link to a full rendering of all of the data (can take a while to render large numbers of results).

**Comment by grrrrrrrrr** [comment]
Obsolete, result rendering is now unified and also works for Rekall results.
