### ISSUE TITLE
Datastore backwards compatibilty 

### ISSUE THREAD

**Issue by pidydx** [google/grr#126]
It seems some recent changes broke backwards compatibility.  When we upgraded to the latest from 26 Feb the Hunt Manager failed to load, client search became inconsistent (searching for . got 0 results but host:hostname worked), and all of the statuses for flows became read circles.

I observed the flow status problems in my test environment when upgrading from 23Feb to 26Feb, but it isn't clear why the Hunt Manager or client search appears to be unaffected.

**Comment by destijl** [comment]
ben would this have anything to do with the searching changes?

**Comment by pidydx** [comment]
Did some more testing with another UI server and the Hunt stuff is working fine.  I'm not sure why it was having loading issues, but it appears to be client side.  The client search stuff is still having problems when searching for . though.

**Comment by destijl** [comment]
There's definitely some problems with the hunt manager and client searching that we're investigating now.

**Comment by destijl** [comment]
Fixed in https://github.com/google/grr/commit/3ed6b259dfe7ae0d68a7b9157132d00836296ef7
