### ISSUE TITLE
Having both test_data/numbers.txt and test_data/number.TXT makes GRR development on Mac tedious

### ISSUE THREAD

**Issue by mbushkov** [google/grr#134]

**Comment by scudette** [comment]
that's kind of the point of this test?  Maybe we should generate these files in the test and then just turn the test off on macs.

**Comment by mbushkov** [comment]
Yes, generating them and turning the test off on Macs should be perfectly fine. It's just that we shouldn't keep the files in git repo.

**Comment by pidydx** [comment]
I like this plan.  I do all of my editing on a Mac and have to just ignore all of the git complaints about the files changing.

**Comment by destijl** [comment]
this has also bugged me, but I didn't get around to fixing it :) +1 for generating and disabling.

**Comment by mbushkov** [comment]
This should be fixed now. Closing.
