### ISSUE TITLE
Unable to get updated file

### ISSUE THREAD

**Issue by pidydx** [google/grr#141]
I am able to use OS to get a file, change that file, and then any future OS attempts to get that file via get new button, file finder, or artifacts fails to update the file.  I am able to use TSK to get the modified version, but then further modification is unable to be fetched by either OS or TSK.

**Comment by scudette** [comment]
Hi Sean,
   Because TSK parsing of the MFT is so expensive (can take up to 2-3 minutes of 100% cpu) we cache the filesystem object (since TSK parses the entire MFT before use it can not see changes in the filesystem):

https://github.com/google/grr/blob/master/client/vfs_handlers/sleuthkit.py#L130
```
# A central Cache for vfs handlers. This can be used to keep objects alive
# for a limited time.
DEVICE_CACHE = utils.TimeBasedCache()
```
Default timeout is 10 minutes
https://github.com/google/grr/blob/master/lib/utils.py#L365

File handles are also cached for 300 seconds:
https://github.com/google/grr/blob/master/client/vfs_handlers/files.py#L20

Is this consistent with the behaviour you observe?

**Comment by grrrrrrrrr** [comment]
I just tried this too (with OS) and it works just fine. There is a pitfall though that is absolutely not obvious:

If you are in the UI viewing a directory, you are viewing a historic version of that directory. That means that even if you click on a file in the right pane, you will only get the version of the file that corresponds to the time when the directory was downloaded (there is a timestamp column on the right showing what you will get).

So, unless you don't refresh the directory itself, you also will not see newer versions of the file even though they exist on the server. You can click the date in the timestamp column to see all available versions of the file, even those downloaded later than the directory. If you select a newer version, you should get the new content. Is that the issue?

**Comment by pidydx** [comment]
The stat info for the file is getting updated properly.  It is the contents of the file itself that aren't updating.
I first noticed this using Artifact Collector to get a 1 line crontab file I made.  I then added another line and reran the Artifact Collector and got the same results.  Then I started trying to use File Finder and the browse VFS stuff to figure out what is going on.

Initial run will show a 31 byte file.  Then I modify the file and run again.  It will show a 56 byte file, but if I click download, view text, view hex, or try to use the Artifact Collector parser it uses the original 31byte version of the file.

**Comment by pidydx** [comment]
When I expand the hash history of the file using OS it shows the hash is the same each time despite updating other aspects of the stat like the size and modified time.

**Comment by pidydx** [comment]
TSK behavior appears to be consistent with the behavior described and it is properly updating given time.

**Comment by scudette** [comment]
Its very strange that the stat of the file is being updated but not the data - unless the file finder is not re-downloading the file. Are you telling file finder to actually download the files or just to re-stat them?

Can you please inspect which attributes are being updated using the GUI? The Hash attribute should be updated the same time as the stat attribute if the file finder is re-hashing the file at the same time.

**Comment by pidydx** [comment]
I have used File Finder (hash), File Finder (download), Artifact Collector (File) and none of them make a difference.

The hash entries are "updating" at the same time as the stat entry, they are just repeating the original hash instead of using the proper value.  If I go into the API and look in files/hashes/generic/md5 I am able to find the hashes for the new versions of the files so it appears that it indeed downloading them correctly.

When the VFS stuff updates I am able to see a size 0 until I tell it to download the new version and then the size updates correctly to match the stat size.  It just refuses to display anything other than the original hash or use the original data for Artifact Collector parsers.

Also, I may have to retract my statements about TSK working properly. It is still exhibiting the same behavior, but it seems less consistently so it could still be cache related.

**Comment by pidydx** [comment]
It appears that if I restart the agent between attempts everything works as expected.  This is a 3.0.0.3 agent so I am going to upgrade the agent and see if this problem persists.

**Comment by pidydx** [comment]
Updated client and the problem is solved.  For anyone watching at home this was the bug that caused this in case you see this behavior in your own environments.

https://github.com/google/grr/commit/1ac15d0924018e09a03afd865b54ce713189d3a4
