### ISSUE TITLE
Add a user activity dashboard and make it the default landing page

### ISSUE THREAD

**Issue by pidydx** [google/grr#144]
Is there an easy way to get the status of all the flows I have started?  If not, can a per user Flow Manager be added in a similar fashion to Hunt Manager?

**Comment by destijl** [comment]
There isn't.  A detailed user history view with links to all the things you've done would be very useful.

**Comment by scudette** [comment]
It should probably be a UI element depending on what you need exactly. You can already see all the flows a user has launched (but not their states) in the GUI Show Statistics/Flows/User/7 days. Maybe just turn that report into a table with flow state.

**Comment by pidydx** [comment]
Yeah, I am looking for a slightly different view than the stats.  Basically the problem is that I run a Hunt, I start digging through results, I start firing off followup investigative flows, and then lose track of all the hosts I was running things on unless they report successes in the notifications.  I figure having a Flow Manager in the list of Management links would be useful for showing the Flow history of the logged in user.  

It would also be nice if you could add comments to the flows in that view just so you can quickly see what the outcome was.  "File was missing", "Legitimate usage", "Incident XYZ" etc.

**Comment by destijl** [comment]
I think a personalized user-activity view would be really useful.  Not just flows, but all activity like hunts, approvals etc.  Lots of user time is just checking up on the stuff you were doing before.  It would be nice if that was the default view, rather than the "welcome to grr" message which is a waste of screen real estate.

**Comment by mbushkov** [comment]
+1 to Greg's idea. Having a "user activity" dashboard is a great idea. This
kind of code should be relatively easy to implement with new Angular code.
Let's open an issue on GitHub for this and track it there?

Cheers,
Misha

**Comment by destijl** [comment]
Just renamed this one :)

**Comment by grrrrrrrrr** [comment]
We do have a dashboard now.
