### ISSUE TITLE
Hunt Results from API require index in collections for efficient retrieval

### ISSUE THREAD

**Issue by pidydx** [google/grr#147]
I ran the LaunchAgents hunt across the fleet with the parser and it worked great, but I have >1M results and can't seem to get them out of the API.  It takes a ridiculous amount of time to get it to load any results and I suspect it is having memory issues trying to load the whole thing at once before doing anything.

**Comment by grrrrrrrrr** [comment]
Collections have been replaced by much more efficient versions, I'll close this. @pidydx please ping me if this is still an issue.
