### ISSUE TITLE
Download individual files from hunt

### ISSUE THREAD

**Issue by pidydx** [google/grr#155]
Is there a way (or can a way be added) to download individual files from a hunt without needing separate client approvals for each client?  Right now I use the API to get the aff4path of the file and then use a post request similar to the individual download file buttons to get files, but this requires approvals for each client involved.

Ideally these files could be downloaded through the hunt instead of needing to repeatedly regenerate the tar.gz file and download the entire set.

**Comment by scudette** [comment]
Do you not see a "Generate Zip" button in the results tab of a hunt which collects files? This is the flow which is called:

https://github.com/google/grr/blob/master/lib/flows/general/export.py#L76

The button will only appear on a hunt which collects files though (otherwise it does not make sense).

**Comment by mbushkov** [comment]
Seems like Sean has the button, it's just that he doesn't need all the files and wants to download  individual ones. Is that correct?

Sean, but how do you want choose which files to download? Via the "Results" tab?

**Comment by pidydx** [comment]
We have an artifact that is a "Live Response" artifact that triggers a bunch of other artifacts.  We set up a hunt with a label using that artifact.  When a host is added to an incident we just label it with the label for that hunt, GRR runs the collection scripts. 

There are two problems with the Generate Zip button.
1.  You have to regenerate every time there are new results filling up the database
2.  You have to download an ever growing file of all the results to get the one additional host you want.

There are a few other use cases, but that is the easiest to explain.  The goal is to be able to download individual files that were collected in that hunt without having to trigger the ACL stuff for each individual host.  

As far as choosing which files to download I'm not sure what the best way to display that in the Results tab would be.  Ideally I would like to just be able to do it through the API. I have been writing a script to interact with the API that basically follows the format of grr_api <connection options> <results options> <aff4 path> where <results options> are things like do you want the object, the object's children, or do you want to download the file at that path.  Currently I have to mimic the "Download file" post that is available when browsing the VFS for downloading and that triggers the ACL requirements for that host.

**Comment by vonnopsled** [comment]
Came across this, I'm having a similar issue with the output on large-scale hunts.

Ideally, I think splitting the results apart by a few options would be helpful, regardless of API or UI interaction (though having both would be nice).

My thoughts for splitting them would be:
- Response types or indicators: say I run two collectors for files, one for .exe in temp, and one for .dll in sys32. I could choose to download the first collection of the .exes, and then a second zip of the .dlls.
- Collection time: This hits Sean's point of not having to re-download all the old values, if it just groups the results that came in after timestamp x, and exports them.

**Comment by destijl** [comment]
Discussed this briefly this morning. @mbushkov thinks a good approach would be to use the result filtering code we have to let you filter out the stuff you don't want in the UI, then use the generate zip button to only download the filtered results.  

This should handle downloading new results from particular clients, and targeting particular result types.  The downside is that the filtering is fairly basic (pretty much a string match) so you might get more than you want if there isn't an obvious string to use.

**Comment by destijl** [comment]
This is becoming critical for large hunts. Today we ran into this problem with a number of hunts. To give a specific example we had a 32GB hunt that failed to generate the .tar.gz (notification was "stuck in worker"), which is unsurprising given how large a tarball it was trying to create in the DB. We had ~1000 individual files we were interested in getting from the hunt. I ended up doing this on the console with multiopen.

I think we want an API that you pass a hunt ID and a list of AFF4 urns (or hashes) to. If we keep the current model of all authenticated users being able to access all hunt results we would need to check that the requested URN or hash was collected by the given hunt. That means iterating over the whole result collection.

**Comment by mutedmouse** [comment]
Can you post how you mitigated this issue from console with multiopen. I
ran into a similar case and had to track files in virtual filesystems
manually.

"Bandaids are sometimes better than prosthetic limbs."

**Comment by destijl** [comment]
Here you go:

```
import os

outdir = "/usr/local/out"
paths = []
for line in open("aff4_paths.txt"):
  paths.append(line.strip())

for fileobj in aff4.FACTORY.MultiOpen(paths):
  path = os.path.join(outdir, str(fileobj.urn).replace("aff4:/",""))
  folder = os.path.dirname(path)
  if not os.path.exists(folder):
    os.makedirs(folder)

  if not os.path.exists(path):
    with open(path, mode="w") as out:
      print "writing %s" % path
      out.write(fileobj.read(999999999))

```

**Comment by mutedmouse** [comment]
+1

**Comment by grrrrrrrrr** [comment]
This works now.
