### ISSUE TITLE
Setting user label fails using grr_config_updater

### ISSUE THREAD

**Issue by dptom** [google/grr#157]
Newly installed server on "3.16.0-30-generic #40~14.04.1-Ubuntu". Each attempt to change a user label using the following  command string fails. 

    root@grrsvr1:/home/tom# grr_config_updater --verbose update_user --label user tom

Error message reported is:

File "/usr/lib/python2.7/dist-packages/grr/lib/aff4_objects/users.py", line 104, in SetPassword
    self._value = self._CalculateHash(password, salt=salt)
  File "/usr/lib/python2.7/dist-packages/grr/lib/aff4_objects/users.py", line 101, in _CalculateHash
    return crypt.crypt(password, salt)
TypeError: must be string, not None

**Comment by pidydx** [comment]
What version of the server is installed?  The latest version would use grr_config_updater update_user --add_labels user tom

**Comment by dptom** [comment]
3.0.0.2

—
Tom Arnold, CISSP, ISSMP, CFS, PCI/PA QSA, Visa SA, PCI PFI, GCFE
Principal, Head of Digital Forensics

Payment Software Company (PSC)
591 W. Hamilton Ave. | Suite 200 | Campbell | CA 95008 | USA

email tom@paysw.com | web www.paysw.com
tel. +1.408.228.0961 x 102 | mobile +1.408.406.1758 | fax +1.408.340.5433

This e-mail message is for the sole use of the intended recipient and may contain confidential and privileged information of Payment Software Company, Inc. (PSC). Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message.

**Comment by dptom** [comment]
Just upgraded to 3.0.0.6 and now I'm trying again

—
Tom Arnold, CISSP, ISSMP, CFS, PCI/PA QSA, Visa SA, PCI PFI, GCFE
Principal, Head of Digital Forensics

Payment Software Company (PSC)
591 W. Hamilton Ave. | Suite 200 | Campbell | CA 95008 | USA

email tom@paysw.com | web www.paysw.com
tel. +1.408.228.0961 x 102 | mobile +1.408.406.1758 | fax +1.408.340.5433

This e-mail message is for the sole use of the intended recipient and may contain confidential and privileged information of Payment Software Company, Inc. (PSC). Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message.

**Comment by pidydx** [comment]
If this is a new install you will probably want to reinitialize the datastore and everything with the new client templates if you haven't already done that.

**Comment by dptom** [comment]
Good suggestion. I shall do that. 


—
Tom Arnold, CISSP, ISSMP, CFS, PCI/PA QSA, Visa SA, PCI PFI, GCFE
Principal, Head of Digital Forensics

Payment Software Company (PSC)
591 W. Hamilton Ave. | Suite 200 | Campbell | CA 95008 | USA

email tom@paysw.com | web www.paysw.com
tel. +1.408.228.0961 x 102 | mobile +1.408.406.1758 | fax +1.408.340.5433

This e-mail message is for the sole use of the intended recipient and may contain confidential and privileged information of Payment Software Company, Inc. (PSC). Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message.

**Comment by dptom** [comment]
Thanks. All good and running well.
