### ISSUE TITLE
Missing/Delayed Clients

### ISSUE THREAD

**Issue by pidydx** [google/grr#171]
Due to the changes in search a new client will not appear until Interrogate has run.  If the initial interrogate fails to run then this could potentially be a long time to get access to the client.  Would it be possible to do an initial add of hostname/ip during enrollment and then have the rest of it update during Interrogate?

**Comment by destijl** [comment]
+1 this is annoying when doing dev too, enroll a new client, then wait a few minutes before it will show up with a search and you can do anything with it.  People are used to clients showing up within a few seconds in the UI, now it can be multiple minutes.  Often you just want to know "did that install work", which used to be essentially instantaneous.

**Comment by grrrrrrrrr** [comment]
Hm this is kind of hard. We do not have either of those values - they get sent by the client on interrogation. This is not new behavior though, do you think it's a problem now? Ben is going to send a patch to put the client id in the index right away (that one we have!) so clients will show up if you search for ".". Is that sufficient?

**Comment by pidydx** [comment]
I am actually curious what the delay is since this seems to be a pretty new behavior since the search stuff was changed.  Did the initial Interrogate change to do more than it previously did?  "." would help for dev, but not so much for the live environment.

**Comment by grrrrrrrrr** [comment]
We looked into this a bit more, and we understand what you are seeing now. The difference between the old and the new index is that the old one was updated during the interrogation already. Every piece of information that the client sent back was immediately added to the index. Now, with the new approach, we wait until interrogation is done and only then index all the info.

Going back to an approach that is more like the old one is not trivial but can be done and if this is a real painpoint, we'll just go ahead and do it.

**Comment by pidydx** [comment]
What if we only did it for hostname?  If I need to validate that a host is checking in all I need to be able to search by is the hostname.  Everything else can come later.  The problem is that if a host fails to complete an interrogate for any reason then it won't show up at all and it makes troubleshooting a problem.  If it can at least get its hostname in ASAP then that gives a sort of foothold to ensure you can find an agent and see what it is doing.

Worst case scenario:
Host is compromised and you find it has no agent.  You install agent.  It enrolls, but the full interrogate fails for some reason then you could be stuck waiting for a second attempt with the weekly interrogate hunt.

**Comment by destijl** [comment]
+1 on just doing hostname ASAP, that's the most common way to find clients.

**Comment by bgalehouse** [comment]
I've prepared a change which should better copy the latency behaviour of the previous system - basically it will update the client index at every intermediate step of interrogate. Will try to get it out soonish.

**Comment by pidydx** [comment]
This has been resolved.
