### ISSUE TITLE
Cannot add label to individual host from GUI

### ISSUE THREAD

**Issue by vonnopsled** [google/grr#175]
After searching for a host, using the check box and selecting "add labels" pops up the editor prompt, but selecting "proceed" does not progress or add the label. It just hangs on this view, and you have to cancel.

**Comment by pidydx** [comment]
This might be your problem. :)  I ran into this behavior as well.
https://github.com/google/grr/issues/161

**Comment by vonnopsled** [comment]
Thanks, looking at the other bug, looks like it was the stale JS issue. Label is working now.
