### ISSUE TITLE
Updating 3.0.0.2 to 3.0.0.6 broke client communication

### ISSUE THREAD

**Issue by khaosus** [google/grr#181]
Updating to 3.0.0.6 on Ubuntu server lost all artifacts and clients are no longer checking in.
Reinstalled with a newly repacked 3.0.0.6 client does not start them again.

New installations with 3.0.0.6 client talk just fine.

I read through the user manual (not to say I didnt miss something), but did not see a way to manually add devices (allowing uninstall flow).

**Comment by pidydx** [comment]
What OS for the clients?  The default path for the client config changed on OSX (and maybe linux, but I didn't verify) so installing as an upgrade actually causes them to become enroll as new.  The new search in the latest server won't show clients until they have completed an Interrogate so if they fail their first Interrogate they won't show up until they Interrogate and update the search index.  https://github.com/google/grr/issues/171
  
Artifacts - There was a format change with artifacts.  The easiest solution I have heard is to roll back the UI, delete the artifacts, roll forward, update the artifacts to the new format, and reupload.

**Comment by destijl** [comment]
Did you sort this out? I'm going to close this, re-open if you still need help.
