### ISSUE TITLE
errors uploading YAML artifacts

### ISSUE THREAD

**Issue by Brockway** [google/grr#183]
Hi, apologies if this is a total newb issue ahead of time, just getting my feet wet here w/ GRR. Version 3006, getting a bunch of different errors when trying to upload different YAML files. Reviewed Artifact YAML Style Guide and watched the Blackhat 2014 recording. Created a new YAML artifact file (from the presentation):

![image](https://cloud.githubusercontent.com/assets/5760489/7732063/0401e636-fef3-11e4-8a60-1aa247df1765.png)

Upload to GRR, get this:

Error: Could not write artifact to database Invalid YAML for artifact: while parsing a block mapping in &quot;&lt;string&gt;&quot;, line 1, column 1: name: TestArtifact ^ expected &lt;block end&gt;, but found &#39;&lt;block mapping start&gt;&#39; in &quot;&lt;string&gt;&quot;, line 5, column 2: args: ^.

messed around with different editors, tab settings and OSes (create same file in notepad++ on Win, VIM on ubuntu), no difference.

Tried a different angle, copied the YAML from the example in the YAML Style Guide:

![image](https://cloud.githubusercontent.com/assets/5760489/7732078/1a54866e-fef3-11e4-9a19-4707b53c1521.png)

Uploaded and get this:

Error: Could not write artifact to database Invalid artifact definition for ApplicationEventLogEvtx2: Proto Artifact has no field collectors.

I saw an artifact change note with a version update that required all pre-existing artifacts to be re-created but doesn't look like it applies at this version. YAML is hard or I can no longer Internetz, likely the latter. Please help.

**Comment by destijl** [comment]
Sorry about the confusion.  This is all due to the recent-ish artifact format changes.  Take a look at the new style guide:
https://github.com/ForensicArtifacts/artifacts/blob/master/docs/Artifacts%20definition%20format%20and%20style%20guide.asciidoc

But you probably just want to follow other examples:
https://github.com/ForensicArtifacts/artifacts/blob/master/definitions/windows.yaml

Collectors were replaced with sources and path_list changed for some artifact types where it made sense.  You mention the event log is in the old format in a style guide somewhere?  Can you link me to it?  I thought we had gotten rid of all the outdated documentation.

**Comment by destijl** [comment]
Also, there are a few errors in the YAML itself (missing colons, dashes etc.) best off just copying an existing example from the repo.  If you check out the ForensicArtifacts github repo linked above and put your artifact in the directory, you can run the tests with "nosetests" and they will validate it for you.

**Comment by Brockway** [comment]
Here is the old style guide: http://www.grr-response.com/docs/Developers/artifact_yaml_style.html

**Comment by Brockway** [comment]
Also here https://drive.google.com/file/d/0B1wsLqFoT7i2U3M1X0k5aVFkXzQ/edit?pli=1 which links to here https://github.com/google/grr-doc/blob/master/artifact_yaml_style.adoc

**Comment by destijl** [comment]
Thanks, I've updated https://github.com/google/grr-doc/blob/master/artifact_yaml_style.adoc to point at the actual style guide.  How did you find the grr-response.com link?  That site isn't in use, and needs to be updated (we have a redirect up for the top level).

**Comment by Brockway** [comment]
Google! :) But I forget what my actual search parameters were.
