### ISSUE TITLE
Flows suddenly missing

### ISSUE THREAD

**Issue by Brockway** [google/grr#185]
Hi,

I have been running artifact collection flows over the past couple of weeks in our pilot environment without issue. Today we wanted to add a few more CPUs to the server VM and spun down the ubuntu instance, added CPUs and spun it back up. There are no longer any flow options in Start new flow or hunt manager:

![grr_shot](https://cloud.githubusercontent.com/assets/5760489/7818019/0b37dccc-03a7-11e5-8575-1784be8f2f79.png)

I'm not sure where to start looking for answers on this one, looking for advice. Thanks!

**Comment by scudette** [comment]
Is it possible that non of the flow plugins are imported for you? Can you please show the console output or the logs as you start the admin ui?

**Comment by Brockway** [comment]
Solved, I was playing around in DEBUG mode and it was still set to that. Flows look to only be visible in Basic or Advanced mode.

**Comment by destijl** [comment]
Most users should think of Basic/Advanced/DEBUG as Normal/You-shouldn't-need-this/You-never-want-this.  If you find yourself regularly switching to Advanced to do something we'd like to hear about it.
