### ISSUE TITLE
Add references to the documentation for key sections of code.

### ISSUE THREAD

**Issue by crankyoldgit** [google/grr#190]
To aid better/easier understanding and reduce the learning curve for parts of the code bases which are  non-trivial, it would be good if documentation and examples of how things operate/hang together are clearer or more available.

Also, indicating which parts are not fully implemented yet would be useful.
e.g. regex not fully supported, yet defined in protobufs etc. without a comment etc.

**Comment by destijl** [comment]
If you can provide specifics of things which need improvement we can work on those.

I'm not sure what you're referring to when you say regex not supported: searching for file names? file content? registry keys? database API?

**Comment by destijl** [comment]
Since you opened https://github.com/google/grr/issues/191 I'm going to assume that was the main thing you were after. If there are other specific deficiencies please open a new bug.
