### ISSUE TITLE
Artifact KnowledgeBase users.local_settings missing

### ISSUE THREAD

**Issue by pidydx** [google/grr#197]
The InternetExplorerHistory artifact references users.local_settings and causes any collectors to fail with:
```
Failed to interpolate %%users.local_settings%%\\Application Data\\Microsoft\\Feeds Cache\\index.dat with the knowledgebase. 
```
After looking into UserShellFolders it does not appear that users.local_settings ever gets set.  Does the artifact need to be written differently?

**Comment by destijl** [comment]
Fixed the artifact and removed local_settings from GRR too.
