### ISSUE TITLE
Issue with WMI queries outside of root\CIMv2 namespace

### ISSUE THREAD

**Issue by wootski** [google/grr#199]
I have an issue where my YAML definition is not able to change the WMI Namespace from the default *\root\cimv2* to *\root\subscription*. I have provided my YAML definition below: 
```
name: WMIActiveScriptEventConsumer
doc: List all ActiveScript Event Consumers.
sources:
- type: WMI
  attributes: {'base_object': 'winmgmts:\root\subscription', 'query': 'SELECT * FROM ActiveScriptEventConsumer'}
labels: [Software]
supported_os: [Windows]
urls: ['https://msdn.microsoft.com/en-us/library/aa384749%28v=vs.85%29.aspx']
```

I'm using *base_object* to specify the namespace after reading the code [here](https://github.com/google/grr/blob/919a844c396136bd49c457f18d853dd10b79abed/client/client_actions/windows/windows.py), starting at line #275

The error returned is *0x80041010*, it's basically telling me that the *ActiveScriptEventConsumer* class does not exist in *CIMv2*.

Any assistance would be appreciated!

**Comment by grrrrrrrrr** [comment]
Yeah we are not passing the base_object through to the flow so this won't work. I'll add this, it's fairly simple.

**Comment by wootski** [comment]
That would be great. ;)

**Comment by grrrrrrrrr** [comment]
Ok I submitted a patch, if you sync to head, this should work. I also shamelessly stole your artifact for the test, I hope this is ok.
