### ISSUE TITLE
Interrogate Hunt Performance

### ISSUE THREAD

**Issue by pidydx** [google/grr#200]
The Interrogate hunt appears to be the cause of the excessive updates to subject='aff4:/' attribute='metadata:last'.  The cache fix, reducing the connection pool for the frontends, and increased database server memory has made this a recoverable bottleneck, but it seems like this shouldn't be happening.  

GRR Version: https://github.com/google/grr/commit/8d26b0bc08602d0b452a565ef6b6f309b741dbe3

**Comment by pidydx** [comment]
This should be handled by this: https://github.com/google/grr/commit/e8291e736ba8ab142d8ae95dba491d0c572b52d2

**Comment by pidydx** [comment]
After a ridiculous amount of testing, discussions, debugging, and code wrangling, multiple race conditions and other bugs were discovered leading to a variety of inconsistencies and problems when Hunts ran, particularly as system load increased.  The following fixes have been critical in making GRR stable for use with non BigTable datastores.

This: https://github.com/google/grr/commit/cff82392dccd24e7fe3b2ecb43c301b9e46a27f3
Also this thing from @grrrrrrrrr over here: https://github.com/google/grr/commit/72e66648fbeabf025daab1659b2eda59250c4945
And maybe this setting: AFF4.intermediate_cache_max_size: 20000

Across ~12-15k hosts this has improved Interrogate hunt completion from ~60% or worse over 7 days to ~98% completion of all hosts within 24hrs.

**Comment by scudette** [comment]
+1 Awesome effort all!
