### ISSUE TITLE
File hashes in the UI are unnecessarily base64 encoded

### ISSUE THREAD

**Issue by destijl** [google/grr#201]
The results page for a filefinder hunt has the hash digests base64 encoded.

Hash entry	
Sha256	Jck7c9nf0MrRi7txlqnlauyL4zuci10WFaRsfybhOiE=
Sha1	0vwiVdo+05iAb5YTto+iVcUFCeA=
Md5	Dd+0GX63iKyM91CR5ykAMg==
Source	aff4:/C.e6c2c37bca0d3e70
Args age	1970-01-01 00:00:00 UTC
Args rdf name	FileFinderResult

**Comment by grrrrrrrrr** [comment]
Fixed in 65f6a819db56c9beacfc572f9352c5a6969d5897
