### ISSUE TITLE
Hunts should support OR conditionals

### ISSUE THREAD

**Issue by vonnopsled** [google/grr#203]
Currently to hunt against 4 different labels that don't overlap, you have to create 4 separate hunts for the same artifacts. This leads to a lot of clutter and duplication in the hunt manager interface.

It would be awesome to be able to set an OR conditional on the hunt to look for label_1 OR label_2 OR label_3 so the results can be found with one hunt ID.

Complex conditions would probably be best, like "OS_Win AND (label_1 OR label_2)".

**Comment by miloszlakomy** [comment]
This is going to be resolved after the next sync.
