### ISSUE TITLE
AnalyzeClientMemory add list of plugin names

### ISSUE THREAD

**Issue by joachimmetz** [google/grr#210]
Add a list of plugin names to the AnalyzeClientMemory view.

Now I need to manually obtain them from: http://www.rekall-forensic.com/docs/Manual/Plugins/

**Comment by pidydx** [comment]
+1 I haven't played with AnalyzeClientMemory much, but the few times I have this has been an issue.

**Comment by grrrrrrrrr** [comment]
Using Rekall is discouraged at this point, we are not going to put effort into this.
