### ISSUE TITLE
Download view - allow to download last version if file entry has been updated more recently

### ISSUE THREAD

**Issue by joachimmetz** [google/grr#212]
if for a file entry data was downloaded from the client, but the file entry metadata has been updated afterwards, show in the download view, download previous version or equiv. the system already shows the `Hash was message Hash { md5 : HashDigest: ...` so it knows about the existence of the previous version.

**Comment by scudette** [comment]
Cant you just view the previous version of the file using the version selector?

**Comment by joachimmetz** [comment]
Nope, that yields client versions for me.

**Comment by grrrrrrrrr** [comment]
This is now a dropdown that offers all versions.
