### ISSUE TITLE
Allow clients to set a configurable higher key size 

### ISSUE THREAD

**Issue by the-w-spears** [google/grr#218]
Can we make the client size key configurable in order to facilitate increasing the keysize and letting us have more control over the security of the clients?

**Comment by grrrrrrrrr** [comment]
This is now in, PR is
https://github.com/google/grr/commit/4926b9745c92651e3992fbee00a37c68b85948ab

While already there I increased the client key size default to 2048 bits. The server key size is 2048 bits by default too but it has been 2048 since we first released.
