### ISSUE TITLE
Check requirements on install

### ISSUE THREAD

**Issue by destijl** [google/grr#22]
_From [darrenbilby](https://code.google.com/u/110806102650731584972/) on October 28, 2013 17:34:51_

We have a couple of requirements that people often screw up when installing GRR, e.g. a decent amount of diskspace for Mongo where Mongos database is stored, and a decent amount of memory (1.5G+). 

Would be nice to add some checks somewhere to warn users, or bail if these requirements aren't met, as I've seen a number of people waste time with these. 

The mongo diskspace thing is particularly annoying, as its hard to recover from once it thinks it has an overly full disk.

_Original issue: http://code.google.com/p/grr/issues/detail?id=72_

**Comment by pidydx** [comment]
Is this still necessary?  It seems like most of this has been handled via various install scripts or documentation.  If there are some necessary checks I can add them to the install scripts, but I'm not sure you would want to do anything more than warn a user.
