### ISSUE TITLE
Add ability to copy hunts to make iterating easier

### ISSUE THREAD

**Issue by destijl** [google/grr#221]
Very common workflow:

- Create hunt and send for approval
- Realise something is wrong, or approver suggests modification
- Delete, create again, send for approval
- Realise something else is wrong.....

It's especially bad when the hunt is complicated: lots of custom options, limits, paths etc. So we need a way to copy an old hunt, change some things, and create a new one.  This is something misha is working on already, just filing this for tracking.

Discussed previously here too: https://github.com/google/grr/issues/106

**Comment by grrrrrrrrr** [comment]
Totally done.
