### ISSUE TITLE
Add ability to download flow results similarly to hunts

### ISSUE THREAD

**Issue by destijl** [google/grr#222]
If you have a flow that collects lots of files, being able to pull back a tarball via the UI like for hunts would be very useful.  At the moment you need to use commandline access.

Similarly if you want to export the results of a parsed browser history it would be good to have them in some form you can download. This could potentially be as simple as providing a link to the API endpoint that will give you JSON.

**Comment by bethlogic** [comment]
+1.  I'll start doing these early in the morning so I can bug mbushkov about them instead of destijl.

**Comment by destijl** [comment]
You can now download flow results in the same way as hunts.

**Comment by destijl** [comment]
Actually, this doesn't quite work yet, I get "Can't generate archive: Unknown error."

**Comment by destijl** [comment]
Fixed now.
