### ISSUE TITLE
Add ability to hunt for files via yara rules

### ISSUE THREAD

**Issue by kudowins** [google/grr#226]
In an effort to proactively identify malware it would be beneficial to leverage the power of yara rules related to the filesystem.

**Comment by grrrrrrrrr** [comment]
The next client generation will have this.

**Comment by kudowins** [comment]
Any timeline as to when we might expect this next client release?

Thanks Andreas

**Comment by grrrrrrrrr** [comment]
The client is mostly done so very soon. Outstanding issues we still have is that the windows nanny doesn't start on Windows server 2008 and similar and, for the Linux version, we need to sort out some startup script problems.

**Comment by kudowins** [comment]
Looks like this feature wasn't incorporated into the new release. Will it perhaps make an appearance on the next release?

**Comment by exp0se** [comment]
+1 for this

Yara support would be much appreciated

**Comment by seanthegeek** [comment]
@grrrrrrrrr +1 Any news on this?

**Comment by threatcrowd** [comment]
Performance wise might be worth doing this just for running processes / loadded dlls + drivers

**Comment by scudette** [comment]
Just as an FYI this works in the upcoming release via a rekall plugin.

**Comment by CmdrMichael** [comment]
Any update for this? Any timeline? 
@scudette - Will the upcomming rekall plugin with yara support also have the ability to use the yara rules for filesystem scanning or only for memory forensics?

**Comment by scudette** [comment]
We did this in the recent DFRWS workshop - not sure if you were there... See the slide "Run a yara rule
against all executables in the windows directory." for an explanation of how to do it with Rekall.

http://dfrws2016.rekall-forensic.com/DFRWS2016_Rekall_Workshop.pdf

It should work with GRR as well providing you issue the same request in the Rekall flow (AnalyzeClientMemory) interface although I have not tested yet.

**Comment by grrrrrrrrr** [comment]
This is available now, I'll close this issue. Let us know if this doesn't work for you.
