### ISSUE TITLE
Vertical split bar doesn't slide

### ISSUE THREAD

**Issue by destijl** [google/grr#23]
_From [tory.cullen](https://code.google.com/u/106734163851970541004/) on November 07, 2013 17:12:46_

What steps will reproduce the problem? 1. Log in to Admin Console
2. Click on blue, vertical bar where four dots are located
3. Attempt to drag left or right What is the expected output? What do you see instead? I expect to have the bar drag either way and stay where I leave it.  Instead, the bar will snap back to it's original position. What version of the product are you using? On what operating system? GRR v 0.2-8 in Firefox 25.0 on OS X Mavericks Please provide any additional information below.

_Original issue: http://code.google.com/p/grr/issues/detail?id=76_

**Comment by grrrrrrrrr** [comment]
Bar is gone now.
