### ISSUE TITLE
MACTime Flow unexpected keyword argument  'limit'

### ISSUE THREAD

**Issue by chlete** [google/grr#231]
Hi!

I'm running GRR 3.0.6 on Ubuntu 14.04.2 on x86_64. While executing on the GUI the MACTimes flow, I got the following error:

``` python
Error: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/grr/gui/renderers.py", line 318, in Decorated
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/grr/gui/views.py", line 160, in RenderGenericRenderer
    result = method(request, result) or result
  File "/usr/lib/python2.7/dist-packages/grr/gui/renderers.py", line 955, in Layout
    id="%s_rightTopPane" % self.id).RawHTML(request)
  File "/usr/lib/python2.7/dist-packages/grr/gui/renderers.py", line 373, in RawHTML
    method(request, result, **kwargs)
  File "/usr/lib/python2.7/dist-packages/grr/gui/plugins/fileview.py", line 618, in Layout
    return super(FileTable, self).Layout(request, response)
  File "/usr/lib/python2.7/dist-packages/grr/gui/plugins/fileview.py", line 478, in Layout
    response = super(AbstractFileTable, self).Layout(request, response)
  File "/usr/lib/python2.7/dist-packages/grr/gui/renderers.py", line 656, in Layout
    self.table_contents = delegate_renderer.RenderAjax(request, tmp).content
  File "/usr/lib/python2.7/dist-packages/grr/gui/plugins/fileview.py", line 468, in RenderAjax
    response = super(AbstractFileTable, self).RenderAjax(request, response)
  File "/usr/lib/python2.7/dist-packages/grr/gui/renderers.py", line 691, in RenderAjax
    limit_row + start_row, request)
  File "/usr/lib/python2.7/dist-packages/grr/gui/plugins/fileview.py", line 623, in BuildTable
    return super(FileTable, self).BuildTable(start_row, end_row, request)
  File "/usr/lib/python2.7/dist-packages/grr/gui/plugins/fileview.py", line 528, in BuildTable
    limit=100000))
TypeError: Query() got an unexpected keyword argument 'limit'
```

fileview.py line 528

``` python
 # Open the directory as a directory.
      directory_node = aff4.FACTORY.Open(urn, token=request.token).Upgrade(
          "VFSDirectory")
      if not directory_node:
        raise IOError()

      key += str(directory_node.Get(directory_node.Schema.LAST))
      key += ":" + str(request.token)
      try:
        children = self.content_cache.Get(key)
      except KeyError:
        # Only show the direct children.
        children = sorted(directory_node.Query(filter_string=filter_string, limit=1000))


```

I have seen that Query() is defined in two different classes: 

https://github.com/google/grr/blob/master/lib/aff4.py
- AFF4Volume

``` Python
class AFF4Volume(AFF4Object):
[...]
  def Query(self, filter_string="", limit=1000, age=NEWEST_TIME):
    """Lists all direct children of this object.
```
- AFF4Root

``` Python
class AFF4Root(AFF4Volume):
 [...]
  def Query(self, filter_string="", filter_obj=None, subjects=None, limit=100):

```

 Looks like AFF4Root's Query() overwrites AFF4Volume's Query().

Cheers,
Christian

**Comment by grrrrrrrrr** [comment]
Hey Christian,

Sorry for the late reply, we somehow missed this report :/

I had a quick look. AFF4Root and AFF4Volume both accept a limit in the Query function. However, the GRRTimeSeries class has its own Query method used for something completely different that doesn't accept one.

You should never try to list inside that object though so I'm not sure how you see that error. Can you explain where in the UI this happens? I tried to use the MACTimes flow and everything works as expected...

Cheers,
-Andy

**Comment by chlete** [comment]
Hi Andy,

No worries. Thanks the answer :)

So here are the steps to reproduce:

Start new flows -> Timelines  -> MAC Times 

![1](https://cloud.githubusercontent.com/assets/1978959/10042562/2ad3edf2-61ec-11e5-990f-2c0947826b05.png)

When the flow is finished -> notifications for admin -> click on the aff4 target (which actually takes you to the "Browse Virtual Filesystem"). 

![2](https://cloud.githubusercontent.com/assets/1978959/10042563/2af338ec-61ec-11e5-86b7-25560ce403d0.png)

Error will pop up, and everytime "Browse Virtual Filesystem" is clicked after.

![3](https://cloud.githubusercontent.com/assets/1978959/10042564/2b0ee3ee-61ec-11e5-9304-ef45d62c3a01.png)


Hope this helps.

Cheers,
Christian

**Comment by grrrrrrrrr** [comment]
Oh I see, the notification links to the wrong place. I can reproduce this now. If you just manually navigate to that urn, it should work fine (this is what I did last time and, thus, didn't trigger the bug). This should be an easy fix now...

**Comment by chlete** [comment]
Thanks Andy, do you need something else from my side?

**Comment by DigiAngel** [comment]
Confirmed seeing here as well.

**Comment by grrrrrrrrr** [comment]
Timelines have been converted to Angular and can now be generated on the fly from the UI, the MAC times flow is gone. This is obsolete.
