### ISSUE TITLE
No server on port 8000 and cant search for clients on the server running on port 8080

### ISSUE THREAD

**Issue by zaeemz** [google/grr#232]
Hi,

Heard about the project and it looks exciting. Unfortunately I can't get it to work.

* I installed the latest server 3.0.0.7 using the quickstart script
* Once installed, there is no server running on port 8000. I can only access the one on port 8080.
* Agent installed on client, but clients not appearing in the server running on port 8080

Any ideas?

Thanks

Zaeem

**Comment by grrrrrrrrr** [comment]
Hey Zaeem,

Thanks for trying GRR! The 0.3.0-7 server is brand new, we haven't even announced it yet so there might still be some unpolished edges. However, I tried installing it quickly and for me it works just fine.

Hm I just realized, you have the admin UI running on port 8080, is that correct? You should have two ports open, 8000 should be the web interface and 8080 should be the connection endpoint for the clients. If you can reach the web ui on 8080, this will not work. Did you manually change any ports during the installation?

To fix this issue, I'd recommend to rerun

sudo grr_config_updater initialize

and reconfigure the admin ui to use port 8000, and the frontend server to use 8080. This is what the config_updater on my working instance says:

Found existing settings:
Admin ui urn: http://<ip>:8000
Frontend urn(s): ['http://<ip>:8080/control']

Do you want to keep this configuration? [Yn]: 

Hope that helps!

Cheers,
-Andy

**Comment by zaeemz** [comment]
Hey Andy,

Thanks for getting back to me so quickly. Really excited about the work you
guys are doing, and if I can contribute in anyway then please let me know.

My setup is as follows:

* VirtualBox host only adapator with IP 192.168.X.1

* Windows 7 virtual machine with IP 192.168.X.100

* My host (Ubuntu 14.04) can ping the Windows 7 virtual machine and vice
versa and my virtual machine sees my host on 192.168.X.1 (maybe something
is wrong here and I shouldn't use the host only adaptor?)

* Admin UI URL = http://192.168.X.1:8000

* Frontend URL = http://192.168.X.1:8080/control


With these settings I get an "unable to connect" error from the web browser
when accessing the Admin UI on 192.168.X.1:8000, however I can access a gui
on 192.168.X.1:8080.

Not sure what I am doing wrong.

Thanks

Zaeem

**Comment by grrrrrrrrr** [comment]
Hey Zaeem,

This is weird, it seems like your UI is configured correctly but it's using the wrong port. Can you maybe quickly confirm this by first running:

$ ps -ef |grep grr
root     14502     1  0 Jul30 ?        00:00:34 /usr/bin/python /usr/bin/grr_server --start_ui --disallow_missing_config_definitions --config=/etc/grr/grr-server.yaml
root     14523     1  0 Jul30 ?        00:06:36 /usr/bin/python /usr/bin/grr_server --start_worker --disallow_missing_config_definitions --config=/etc/grr/grr-server.yaml
root     14699     1  0 Jul30 ?        00:01:35 /usr/bin/python /usr/bin/grr_server --start_http_server --disallow_missing_config_definitions --config=/etc/grr/grr-server.yaml

to see all grr processes, maybe you have some old admin ui sticking around. Then, just stop the UI and run it manually:

$ sudo service grr-ui stop
grr-ui stop/waiting

$ sudo /usr/bin/python /usr/bin/grr_server --start_ui --disallow_missing_config_definitions --config=/etc/grr/grr-server.yaml **--verbose**

This should give you lots of output, at the end it should tell you which port it uses:

INFO:2015-07-31 09:34:03,690 admin_ui:59] Serving HTTP on :: port 8000 ...

Cheers,
-Andy

**Comment by destijl** [comment]
There's a non-obvious bug here sorry. If you upgrade an existing server it isn't triggered. The wrong port is written to /etc/grr/server.local.yaml for the AdminUI on a fresh install, probably as a result of the config prompting changes.

Make sure you have:
```
AdminUI.port: '8000'
```
and do a:
```
sudo service grr-ui restart
```

I'll get it fixed and make a new package shortly.

**Comment by Hookapelli** [comment]
Team - this fixed the UI on 8080 for me, but my clients still are not communicating back. Do I need to repackage the binaries after the change?

**Comment by Hookapelli** [comment]
I reran the grr_server --start_ui and got this: 
socket.error: [Errno 98] Address already in use

**Comment by Hookapelli** [comment]
UPDATE - I rebooted the server and it works!!!

**Comment by pidydx** [comment]
Sorry gang, this was my fault.  When I was revamping the config updater questions to make setup a bit easier I wound up reparsing the frontend url to get the AdminUI port instead of the adminui url.  This should fix it. https://github.com/google/grr/pull/235

**Comment by zaeemz** [comment]
Awesome. You guys are stars. All working now!
Thanks

**Comment by destijl** [comment]
I've built and uploaded a new server deb and tested on a clean 14.04 system, all looks good.

**Comment by jolachea** [comment]
I am having the exact same error but on the control server as such:

When I run sudo ps -ef | grep grr 

I see the service at /usr/bin/grr_server --start_http_server --disallow_missing_config_definitions --config=/etc/grr/grr-server.yaml

But am unable to hit it.  I can hit the admin page.

So far I have tried killing the process and restarting the service like:

/usr/bin/grr_server --start_http_server --disallow_missing_config_definitions --config=/etc/grr/grr-server.yaml --verbose

This only hangs but never completes.  Any ideas?
