### ISSUE TITLE
Customize UI Search Results Default View

### ISSUE THREAD

**Issue by Hookapelli** [google/grr#236]
Team-

Most of our hosts have had numerous users. This chews up A LOT of real estate on the host list. Is there a way to limit the returned rows of the 'usernames' field?

**Comment by gleichd** [comment]
I trimmed the user list down, so this is taken care of.

**Comment by grrrrrrrrr** [comment]
Yup, pushed in 49fd562702d97f88050495bddcd27a9ce8dd07f4, thanks Dominik for fixing!

I'll close this now, if you want us to make further changes you can always reopen...
