### ISSUE TITLE
Buffer_Overflow_LongString

### ISSUE THREAD

**Issue by cjdupreez** [google/grr#243]
Currently in file windows_nanny.cc on source line 76, strings[1] is being assigned "Invalid event message (Contains %%)" without first verifying that strings[1] is large enough to contain the string. This is triggering a Buffer_Overflow_LongString detection by our source scanner. Is this something that can be addressed?

**Comment by scudette** [comment]
Hi Cornel,
  The relevant source code is:

```
void WindowsEventLogger::WriteLog(std::string message) {
  const TCHAR *strings[2];

  strings[0] = kNannyConfig->service_name;
  strings[1] = message.c_str();

  // TODO(user): change this into overwriting % with place holder chars
  // or equiv
  if (message.find("%") != std::string::npos) {
    strings[1] = "Invalid event message (Contains %%)";
  }

  if (event_source) {
    ReportEvent(event_source,         // event log handle
                EVENTLOG_ERROR_TYPE,  // event type
                0,                    // event category
                1,                    // event identifier
                NULL,                 // no security identifier
                2,                    // size of lpszStrings array
                0,                    // no binary data
                strings,              // array of strings
                NULL);                // no binary data
  }
};
```

strings[1] is a pointer to a string (TCHAR *), and it is assigned the address of a statically allocated string. The string is not copied into a buffer at all.

The point of this code is to ensure that there are no % escape sequences in event logs reporting to prevent the event logging system from trying to interpolate uninitialized characters into the string. This is why the message contains double % (which after interpolation turns into a single %).

As far as I can see this is not an overflow and may be a false positive of your source scanner?

**Comment by cjdupreez** [comment]
Thanks for the clarification Scudette, I agree, it looks like it was just a false positive. Much appreciated!
