### ISSUE TITLE
Add ability to use two factor via the web ui

### ISSUE THREAD

**Issue by dreifachkodiak** [google/grr#244]
I was curious if you have implemented or know of any implementation of two-factor authentication for the web ui? We are looking to restrict some of our IR roles to that only while some of our developers will have console access etc.

**Comment by destijl** [comment]
We integrate with our single sign on, which is two factor. Open source users have done the same by putting apache (with a single sign on module) in front of the admin ui as a reverse proxy.  Brian just did this and wrote some documentation here:
https://github.com/google/grr-doc/blob/master/admin.adoc#running-the-grr-http-server-behind-apache-reverse-proxy

**Comment by dreifachkodiak** [comment]
Thanks I must of missed that reading through the documentation!

**Comment by destijl** [comment]
I merged the pull request for the documentation just before I updated the bug, it's very new ;)
