### ISSUE TITLE
"UpdateClient" Blob Path Not Rendering

### ISSUE THREAD

**Issue by brian-olson** [google/grr#246]
"UpdateClient" Blob Path Not Rendering

![screen shot 2015-08-19 at 11 47 53 am](https://cloud.githubusercontent.com/assets/6720384/9361179/40346a9a-4668-11e5-9495-b91352fc1ee1.png)

**Comment by brian-olson** [comment]
I've tried this on Chrome, FF, and Safari. No luck :(

**Comment by brian-olson** [comment]
Similar issue with "LaunchBinary." Strange that it renders one field by not the other. The field renders properly under Hunt, but not a singular host. 

![screen shot 2015-09-15 at 4 00 05 pm](https://cloud.githubusercontent.com/assets/6720384/9888413/f43bace6-5bc2-11e5-93be-112095f2e604.png)

**Comment by grrrrrrrrr** [comment]
This is the new Angular based form code, we haven't enabled it for hunts yet therefore the difference. @mbushkov is the right person to look at this, sorry for the long wait...

**Comment by mbushkov** [comment]
This was fixed by https://github.com/google/grr/commit/49fd562702d97f88050495bddcd27a9ce8dd07f4

The problem was due to 2 things:
* There was no UI renderer for RDFURN input controls.
* There was an issue with generating default value for RDFURNs.
