### ISSUE TITLE
Manually added client label doesn't show up in search until next interrogate

### ISSUE THREAD

**Issue by destijl** [google/grr#248]
If you manually add a client label by modifying the client's yaml or registry settings the label will show up attached to the client on the server. But if you search for label:mynewlabel you won't find it, because it hasn't been added to the index. Some people will likely deploy a generic client and override the labels in this way.

The new label will get added to the index on the next interrogate. But this might be 7 days away, which is a long time if you are trying to check if the install was successful, or actually target the clients.

Pretty minor issue, but maybe we can add to the index if a client polls in with an unknown label?

**Comment by nickamon** [comment]
Thanks for this, after 30 minutes of tracing the code, reviewing the logs, I still had no idea why I wasn't able to search on a label that was clearly present in the UI.  After running an interrogation job as you recommend, I was able to successfully search on it. 

Please document this requirement as there was no mention on this on the doc page for searching clients.

**Comment by grrrrrrrrr** [comment]
This works now.
