### ISSUE TITLE
Search within Hunt Manager

### ISSUE THREAD

**Issue by vonnopsled** [google/grr#251]
[This may be related to issue #42]

The current hunt interface does not allow for searching by the hunt ID. To view the hunt run previously, you need to scroll back to find it. Either searching from the search bar above (which looks like it has other complexities to add that) or within the Hunt window would be very helpful in reviewing past hunts and sharing the results with others for verification.

**Comment by pidydx** [comment]
It seems like adding a search similar to how the VFS lets you filter file listings might be the way to go with this.

**Comment by destijl** [comment]
I think most of this use case will be addressed by the user activity dashboard:
https://github.com/google/grr/issues/144

So to share a hunt results with others you would click the hunt link from the landing page (which will be your activity dashboard), and share the URL with whoever. This means they don't need an extra searching step, they are taken straight to the hunt.

**Comment by vonnopsled** [comment]
So if I have scheduled say 100 hunts, do I need to then scroll through my user activity dashboard to get to the hunt, and then share the URL?

**Comment by destijl** [comment]
Sure, but I don't think any one person has scheduled anywhere near that many, and in the vast majority of cases you're going to want to share something recent.

**Comment by destijl** [comment]
Revisit need for this after user dashboard is done.

**Comment by cyberwarrior37** [comment]
+1 this would be a nice feature to have.

**Comment by destijl** [comment]
@cyberwarrior37 use case: do some analysis in BigQuery, share BigQuery queries with others. Those people want to go back and look at how the hunt was run but it was from a year ago and scrolling is horrible.  

All he has is a reference like: aff4:/hunts/H:ED7458F8/Results from the BigQuery data, which isn't easy to translate into a link that would take them to a hunt in a webbrowser.

**Comment by joachimmetz** [comment]
+1

> I think most of this use case will be addressed by the user activity dashboard:

Not for my use case; I was looking for some older hunts that were no longer in the dashboard
Also when searching for a hunt created by someone else

**Comment by destijl** [comment]
We should do this. Sharing URLs is possible but people don't do it, and the expectation is that you can find a hunt easily given an ID. Which you can't.

**Comment by destijl** [comment]
This is done.
