### ISSUE TITLE
Web UI Error: unknown format code 's' for object of type 'int'

### ISSUE THREAD

**Issue by AndrewVi** [google/grr#253]
Hi Everyone,

When I try to view the results of  vmscan plugin (Browse Virtual File System->analysis - >AnalyzeClientMemory) which runs against Linux host I've got the following error: "unknown format code 's' for object of type 'int'"

Thank you in advance.

Regards,

Andrew

**Comment by parkisan** [comment]
Thanks for the report Andrew. This is a stupid bug with a Rekall renderer.
We don't use in the webconsole the same method Rekall uses so it wasn't exposed earlier.

https://codereview.appspot.com/264300043/diff/1/rekall-core/rekall/plugins/renderers/virtualization.py

If you run the webserver from source code you can patch it yourself like shown above.

**Comment by AndrewVi** [comment]
I patched the mentioned above file. It works. Thanks a lot.

Regards,
Andrew

**Comment by parkisan** [comment]
Great to hear! Thanks again for reporting it!
