### ISSUE TITLE
Don't pass the approval reason in HTTP headers

### ISSUE THREAD

**Issue by destijl** [google/grr#257]
Currently we pass the approval reason in HTTP headers for POST and as a URL parameter for GETs.
https://github.com/google/grr/blob/4b7f9b06d1dfebd3dc86a6fa2eb7592f233b5330/gui/http_api.py#L34

We should remove the need to pass the reason at all and just let the server find the approval for the machine/hunt and user.

**Comment by scudette** [comment]
We should never pass anything in a header since custom headers are often stripped depending on environment. Maybe put it in a cookie?

**Comment by destijl** [comment]
Why do we need to pass it at all? The server doesn't need it to find the approval.

**Comment by scudette** [comment]
What do you mean? every API request needs a reason.  The server will raise otherwise.

**Comment by mbushkov** [comment]
The token is expected to have a reason in lots of places. Even if some HTTP API handlers search for approval automatically, in most cases we need the reason.

As for the cookies. Cookies are troublesome if you have multiple tabs open. You can easily have multiple tabs opened with different clients and different reasons.

Re headers stripping. What are the common cases of headers stripping? Proxies? Is it really that typical?

**Comment by mbushkov** [comment]
I agree with Greg that in general we should make passing the reason optional, as the server should be able to find necessary approval by knowing the username and the name of the resource being accessed. We should refactor the code so that we can do it quickly, in 1 roundtrip to the database.

**Comment by scudette** [comment]
I think the main problem with this approach is that HTTP headers can not contain anything but ASCII and we are trying to pass the reason (which is a unicode object) into them without encoding. This will raise when you provide a unicode reason.  I suppose with proper encoding it can be done. 

I stand corrected in that it seems that custom headers are allowed through most things - especially if they are preceded with X- (but not required).

**Comment by mbushkov** [comment]
We'll use encodeURIComponent() JS function to allow the headers and urllib.unquote() to decode them. This will fix the unicode issue.

And prefixing the header with X-  sounds like a good idea if it's a standard practice.

**Comment by destijl** [comment]
Yes, I'm saying we should change how the server searches for approvals to not require the reason to be passed from the UI (or console client). A client ID and username is enough. AFAICT we pass a reason to save DB roundtrips but the same can be achieved by restructuring how we store approvals on the server.

**Comment by destijl** [comment]
Misha to check where this is at, maybe done now?

**Comment by grrrrrrrrr** [comment]
This is indeed done.
