### ISSUE TITLE
Add Hunt Description to Hunt Overview

### ISSUE THREAD

**Issue by vonnopsled** [google/grr#260]
Currently the hunt description is not added to the hunt overview pane, and is only visible in the manager list.

**Comment by destijl** [comment]
This is useful when you share a link to a hunt with somebody since if it's an old hunt you won't see it in the top panel (would be nice to fix that too and show the hunt in context with others).

**Comment by grrrrrrrrr** [comment]
I fixed this, it's a two line change that took me two minutes. We should really have a faster turnaround than >one year...

Closing this issue, the next code push will have this.
