### ISSUE TITLE
Key and IV Missing - Memory Collector

### ISSUE THREAD

**Issue by cybercuffs** [google/grr#262]
In memory collector, it is not generating the Key and IV when I select the send to socket action.

**Comment by grrrrrrrrr** [comment]
Hm key and iv both show up for me. That is for both, flows and hunts, and under the send_to_socket action. Where do you see those problems exactly?

**Comment by cybercuffs** [comment]
It is for both hunts and flows. They key and IV are not populating as they used to be after selecting send_to_socket option in memory collector.

**Comment by mbushkov** [comment]
The bug is caused by recent changes in the UI. I'm working on the issue, will submit the fix soon.

**Comment by mbushkov** [comment]
This is now fixed by the latest commit. Please check that things are working as expected.

**Comment by cybercuffs** [comment]
Great, I see key and iv now there.
