### ISSUE TITLE
Error in repacking Windows clients 3.0.7.1

### ISSUE THREAD

**Issue by cybercuffs** [google/grr#264]
I am getting following error when trying to repack Windows clients 3.0.7.1.

ERROR:2015-10-02 17:48:46,859 build:342] Build Config Error: Logging.path starts with /, probably has Unix path. /var/log/grr
Repacking template /xxx/executables/windows/templates/GRR_3.0.7.1_amd64.exe.zip failed: Bad configuration generated. Terminating.
Failed to repack /xxx/grr/executables/windows/templates/GRR_3.0.7.1_amd64.exe.zip.

ERROR:2015-10-02 17:48:51,352 build:342] Build Config Error: Logging.path starts with /, probably has Unix path. /var/log/grr
Repacking template /xxx/executables/windows/templates/GRR_3.0.7.1_i386.exe.zip failed: Bad configuration generated. Terminating.
Failed to repack /xxx/grr/executables/windows/templates/GRR_3.0.7.1_i386.exe.zip.

**Comment by scudette** [comment]
You configuration seems to be wrong. You should have a windows path
for log files. Make sure you have something like:

Platform:Windows:
  Logging.path: |
    %(WINDIR|env)\\System32\\logfiles\\


in your config file. The Platform:Windows context means that this
parameter will be used when running on windows (i.e. in the windows
client).

**Comment by cybercuffs** [comment]
Yes I figured that out, but not sure which config file needs to be changed. I did not build the template, is this defined while building a template?

**Comment by scudette** [comment]
No the config file is in /etc/ on the server.

**Comment by cybercuffs** [comment]
The config file in /etc/grr/grr-server.yaml  is same as https://github.com/google/grr/blob/master/config/grr-server.yaml - which already has the the logging path defined as above (line 269).

**Comment by destijl** [comment]
Hrm. I attempted to try and reproduce this with the docker build, but there's a different (I think probably unrelated problem) that needs to get fixed there:
https://github.com/google/grr/issues/265

**Comment by cybercuffs** [comment]
Looks like the issue was in Logging.path in /etc/grr/server.local.yaml. Just re-initializing is not enough. I had to delete the existing /etc/grr/server.local.yaml and re-initialize to have this fixed.
