### ISSUE TITLE
OSX - flow for determining mounted DMG files

### ISSUE THREAD

**Issue by jjiixx** [google/grr#267]
Please provide a flow that collects information about mounted DMG files. This can be done e.g. by running "hdiutil info" and collecting the output, but maybe there are other ways that make it easier to get the information in a machine-readable format, or that can even provide info about past mounts that are no longer active.

**Comment by miloszlakomy** [comment]
The coding is done, it'll work as soon as the client template gets synced.

**Comment by grrrrrrrrr** [comment]
As Milosz said, this will work when the next client template gets released so I'll close this issue.
