### ISSUE TITLE
DumpProcessMemory not implemented on OSX?

### ISSUE THREAD

**Issue by 0xdabbad00** [google/grr#269]
I tried run the flow DumpProcessMemory on an OSX client (verison 3071)  and received the error:

```
Could not dump memory image: message GrrStatus { backtrace : u'Traceback (most recent call last):\n File "/Users/[redacted]/workpath/grr/out00-PYZ.pyz/grr.client.actions", line 151, in Execute\n File "/Users/[redacted]/workpath/grr/out00-PYZ.pyz/grr.client.actions", line 216, in Run\nKeyError: u\'Action DumpProcessMemory not available on this platform.\'\n' cpu_time_used : message CpuSeconds { system_cpu_time : 6.14400005361e-06 user_cpu_time : 4.09599997511e-05 } error_message : u"KeyError(u'Action DumpProcessMemory not available on this platform.',): u'Action DumpProcessMemory not available on this platform.'" network_bytes_sent : 553 status : GENERIC_ERROR }
```

I ran the agent with verbose logging by doing `launchctl unload /Library/LaunchDaemons/com.google.code.grr.plist`, ensuring the agent was no longer running, then running `/usr/local/lib/grr/grr_3.0.7.1_amd64/grr --config=/usr/local/lib/grr/grr_3.0.7.1_amd64/grr.yaml --verbose` and it showed the same message.  When I tried running with `--debug` to debug this further though the agent just runs and doesn't seem to receive the flows I've set up for it.

**Comment by destijl** [comment]
@the80srobot

**Comment by scudette** [comment]
Note that DumpProcessMemory is actually only implemented in the experimental c++ client and basically copies /proc/pid/mem and /proc/pid/maps (So it does not use Rekall at all). Since the c++ client is not implemented for windows or OSX this client action is not available for these platforms, nor is it available in the regular GRR client (maybe we can add it?).

**Comment by destijl** [comment]
Wow, that's an awfully large number of caveats. This flow needs to go under advanced and have it's docstring updated to indicate that it requires the C++ client, and probably be renamed to DumpLinuxProcessMemory.

**Comment by scudette** [comment]
I think it would be useful to actually implement something like that for all operating systems and also in the python client. We should keep this bug open and implement the client action on OSX and windows (and linux in python).

**Comment by destijl** [comment]
The flow was moved under advanced and docstring updated in https://github.com/google/grr/commit/95980f5cc3232fff4b26c6698ed1ea2285654866

@scudette I don't think we need a tracking bug for this, but if you want one open a new feature request bug.
