### ISSUE TITLE
API client query limited and undocumented

### ISSUE THREAD

**Issue by 0xdabbad00** [google/grr#272]
I was looking at the API, and wanted to search for clients, so I was running:
`curl -s http://admin:demo@127.0.0.1:8000/api/clients?query=C.418c92f408908112 | sed "s/^)]}\'//" | jq '.'`  My assumption was that this query field could be used to find clients, but it seems it only supports specifying a client id as the query string, which seems very limiting, especially because there exists the API end-point `/api/clients/<client_id>`  This should be better documented, and if this all that querying can do, it should be expanded.  This potentially overlaps with #42 but that seems to discuss a web UI page that I am unable to find.

**Comment by destijl** [comment]
It can be used to find clients, and is the same code used by the search box in the UI. The query can be any of the UI query strings as documented here:
https://github.com/google/grr-doc/blob/master/user_manual.adoc#searching-for-a-client

You have found the API documentation link in the UI right? Bottom right hand corner.

I also updated the bug you referenced so it is clearer what is left to do, it's referring to the search results pane in the UI.

**Comment by 0xdabbad00** [comment]
Ah, that link has the info I was looking for! I was looking at the documentation from the API link in the UI which directs me to http://localhost:8000/#main=ApiDocumentation and that only tells me:
**GET /api/clients**
Renders results of a client search. 
Parameters

Parameter | Type | Description
------ | ------ | ------
query | RDFString | Search query string. 
offset | RDFInteger | Found clients starting offset. 
count | RDFInteger | Number of found client to fetch. 

In attempting to find how to use this API, I had searched the code and only come across this: https://github.com/google/grr/blob/69c81624c281216a45c4bb88a9d4e4b0613a3556/gui/api_plugins/client_test.py#L171


This can be closed.  Might be good to link in the web UI docs to that link though, and add more tests for the other querying capabilities.

**Comment by destijl** [comment]
There's plenty of test coverage for client search, it's just done elsewhere:
https://github.com/google/grr/blob/873a4103818e128ae9defad511d56ff755432408/lib/client_index_test.py#L64

The test in the API docs is there to catch API breakage and force the documentation to be updated.

Not sure a link will get rendered through the auto-generation of these docs, but I'll make it more obvious somehow.
