### ISSUE TITLE
Grr Install Failure (sudo bash install_script_ubuntu.sh)

### ISSUE THREAD

**Issue by ookumusoglu** [google/grr#273]
Hi,

I am trying to configure an Amazon instance to run my GRR master server using quick guide. I am using m4.large with ubuntu 14.04. After I ran the script "sudo bash install_script_ubuntu.sh", it fails in the end with following message:

Run grr_enable_all [Y/n/a]? Y
#### Running #### grr_enable_all
./install_script_ubuntu.sh: line 115: grr_enable_all: command not found
#########################################################################################
FAILURE RUNNING: grr_enable_all
#########################################################################################

I would appreciate any help.

Note: I tried with different instances and amazon linux OS to, some issue happened.

Thanks in advance.

**Comment by destijl** [comment]
I'll fix this tomorrow, the install is essentially complete at this point, it's just a problem with the alias for restarting the services. You should be able to run this by hand:
```
. /usr/share/grr/scripts/shell_helpers.sh
grr_enable_all
```

**Comment by destijl** [comment]
Actually that workaround should probably be:

```
. /usr/share/grr/scripts/shell_helpers.sh
enable_services grr-http-server
enable_services grr-ui
enable_services grr-worker
```

The numpy problem from https://github.com/google/grr/issues/274 is also affecting the install by this method, so I'm fixing both.

**Comment by destijl** [comment]
This is now fixed.
