### ISSUE TITLE
FileFinder Error - Client 3.0.7.1 

### ISSUE THREAD

**Issue by cybercuffs** [google/grr#276]
I am getting this error when running the flow FileFinder:
Flow:
FileFinder

Parameters:
%%users.homedir%%\Downloads\*.pkg

Error:

    Can't start flow FileFinder:
    Invalid attribute users

Operating systems test on:
OS X 10.11
Linux

**Comment by destijl** [comment]
works for me, this was likely the broken interrogate which meant users.homedir hadn't been populated.
