### ISSUE TITLE
Interrogate Fails

### ISSUE THREAD

**Issue by cybercuffs** [google/grr#277]
I notice Interrogate under Admin also fails, tested on OS X 10.10 and 10.11 and Linux with an error as below:

    Artifact LinuxUserProfiles missing from registry. You may need to sync the artifact repo by running make in the artifact directory.

**Comment by pidydx** [comment]
I found the bug.  Working out how to fix it now. :)

There is an error in the windows artifacts from https://github.com/ForensicArtifacts/artifacts.

**Comment by pidydx** [comment]
Fixed here: https://github.com/ForensicArtifacts/artifacts/pull/101

**Comment by destijl** [comment]
Thanks, it's merged now. If your interrogate was broken that was likely responsible for this:
https://github.com/google/grr/issues/276 

so that should be fixed once you can run interrogate successfully.

**Comment by destijl** [comment]
Interrogate works for me, looks like sean fixed it. Reopen this if you still have problems with the latest artifacts and code.
