### ISSUE TITLE
ArtifactCollectorFlow fails - 3.0.7.1

### ISSUE THREAD

**Issue by cybercuffs** [google/grr#278]
When I launch the ArtifactCollectorFlow under Collectors, I get the following error.

    "Can't start flow ArtifactCollectorFlow: 
    Artifact LinuxUserProfiles missing from registry. You may need to sync the artifact repo by running make in the artifact directory. "

Tested on OS X, Linux

**Comment by destijl** [comment]
The cause of this is probably:
https://github.com/google/grr/issues/277

**Comment by destijl** [comment]
Works for me, I think this was the artifact problem from the referenced bug, re-open if it's still a problem after updating.
