### ISSUE TITLE
Upgrade communications from using sha1 to sha2

### ISSUE THREAD

**Issue by 0xdabbad00** [google/grr#280]
Browsers have decided to begin deprecating sha1 because collisions are likely within reach of well-funded attackers and this capability could be used for Man-in-the-Middle attacks.  GRR should do the same as it appears to be using sha1 in some of it's crypto communications.   An example instance of GRR's use of sha1 for it's communications is at https://github.com/google/grr/blob/6cb897ccecf5a0629a6166c782f74334e71ca2c9/lib/communicator.py#L209

**Comment by 0xdabbad00** [comment]
As long as crypto is being updated, you might as well seek higher ground with the crypto in other areas, specifically RSA, and move to all the recommendations in the [NSA Suite B](https://www.nsa.gov/ia/programs/suiteb_cryptography/index.shtml).  These include:

Algorithm | GRR | NSA recommendation | Is acceptable?
------- | -------- | ----- | -------
Symmetric block cipher | AES-256 | AES-256 | Yes
Secure Hash Algorithm | SHA-1 | SHA-384 | No, needs upgrade
Asymmetric algorithm | RSA-2048 | RSA-3072 | No, needs upgrade

**Comment by grrrrrrrrr** [comment]
Thanks for bringing this up and sorry for getting back to you a bit late. 

We last reviewed the key lengths used in GRR earlier this year and we think we are ok for the near future. Our key lengths are based on the NIST recommendations ( http://www.keylength.com/en/4/ ) and they give our key lengths a rating of 2011-2030 for 2048 bit RSA and >2030 for every other key length we use.

Regarding the use of SHA-1 in GRR, note that there is a huge difference between using a hash algorithm for signatures (for example signing certs, what Chrome deprecated) and using it in an HMAC. GRR just uses SHA-1 in the HMAC and this is still ok, NIST gives that a >2030 rating (see columns Hash (A) and Hash (B) in the linked page above).

**Comment by grrrrrrrrr** [comment]
I got a second opinion from knowledgable crypto people and they agree that what we do is good. Closing this bug.
