### ISSUE TITLE
grr_fuse ... bad address

### ISSUE THREAD

**Issue by shinsungchul** [google/grr#282]
After the directory is mounted as a result grr_fuse check all the files size zero. File paths are normally present, but the actual file contents can not be checked.
mount ex) grr_fuse --mountpoint / root / grr --backgroud
log: blobs / 00003d22254e9a1f3a6c031c12c73887d1d377a54063814a75b2caf233512e61: Bad address

What is the problem?
If you need further information, I will reply.

**Comment by destijl** [comment]
What mount command did you use here? The intent of the fuse layer is to be able to mount the client aff4 space and use normal tools against the remote filesystem. Mounting the server namespace where the blobs live might work, but you will likely run into ACL problems.

**Comment by grrrrrrrrr** [comment]
No info received, obsolete.
