### ISSUE TITLE
No Storage System MySQLAdvancedDataStore found.

### ISSUE THREAD

**Issue by 0xdabbad00** [google/grr#286]
I'm getting similar output as in https://github.com/google/grr/issues/237 which ends with the lines:

```
File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/data_store.py", line 764, in Run
    config_lib.CONFIG["Datastore.implementation"])
RuntimeError: No Storage System MySQLAdvancedDataStore found.
```

I'm trying to use MySQL and end up with this error from running `grr_config_updater initialize`.  I tried running `grr_config_updater --list_storage initialize` and this ends up displaying:

```
Configuration parameters set. You can edit these in /etc/grr/server.local.yaml
SqliteDataStore         A file based data store using the SQLite database.
DataStore               Abstract database access.
FakeDataStore           A fake data store - Everything is in memory.
HTTPDataStore           A data store which calls a remote server.
```

This key error is because `cls = DataStore.GetPlugin(config_lib.CONFIG["Datastore.implementation"])` does not know about the `MySQLAdvancedDataStore` but I can't figure out where the other datastores are being added to that.

**Comment by pidydx** [comment]
Do you have the python mysql module and the binary mysql client installed?  This is typically what causes problems with 'No Storage System MySQLAdvancedDataStore' errors.

**Comment by scudette** [comment]
Also please make sure you have mysql 5.6. The tests are failing with mysql
5.5 but the data store is not properly disabled for that version (which
means that it will have subtle bugs).

**Comment by pidydx** [comment]
Specifically 5.6.4 or greater due to this. https://dev.mysql.com/doc/refman/5.6/en/fractional-seconds.html

**Comment by 0xdabbad00** [comment]
Installing mysql 5.6 fixed it, thank you.   I should have read the big warning during install:

```
***WARNING***
Do not continue until a MySQL 5.6 server is installed and running with a user
created with the ability to create the GRR database and tables and the Python
MySQLdb module has been installed on the GRR server.
```
