### ISSUE TITLE
Artifacts list empty

### ISSUE THREAD

**Issue by cybercuffs** [google/grr#287]
The artifacts list is empty again in the start new flows -> Collector -> ArtifactsCollector. 

<img width="662" alt="screen shot 2015-10-30 at 2 27 34 pm" src="https://cloud.githubusercontent.com/assets/11019242/10858457/6b3ec95a-7f12-11e5-8415-bedc5b1232c6.png">

**Comment by mutedmouse** [comment]
Every now and again this happens to me,  reloading the artifact collector
list usually fixes the population issue.

Grimlock

**Comment by cybercuffs** [comment]
Thanks @mutedmouse but it doesn't look like a glitch and reloading is not solving it.

**Comment by destijl** [comment]
I suspect you have a broken artifact. I synced the latest artifact repo and it works for me. Take a look at the admin ui logs and see if there are errors about artifacts.

**Comment by cybercuffs** [comment]
The UI log was showing an error below.

    "Error while processing /api/artifacts (GET) with ApiArtifactsRenderer: type object 'ArtifactRegistry' has no attribute 'artifacts' " 

Rebuilding the GRR fixed the issue.
