### ISSUE TITLE
install_server_from_src.sh not installing init.d files

### ISSUE THREAD

**Issue by 0xdabbad00** [google/grr#289]
I'm trying to install grr from source, and following the instruction on https://github.com/google/grr-doc/blob/master/serverfromscratch.adoc

I then followed the instructions at the end of the script (`install_server_from_src.sh`), which are:
```
sudo grr_config_updater initialize
source scripts/shell_helpers.sh
grr_enable_all
```

When I run the last command I get:
```
# grr_enable_all
Starting grr-http-server
grr-http-server: unrecognized service
Starting grr-ui
grr-ui: unrecognized service
Starting grr-worker
grr-worker: unrecognized service
```

The problem is that nothing has copied the files in `./config/debian/initd/` to `/etc/init.d/` and run `chmod +x` on them.  This step needs to be added to the script.

It is possible that something broke in my installation or that I did not run some script I should have, but looking through the source code I was not able to find any references to these files.

**Comment by dreifachkodiak** [comment]
Did you first run? 
"git clone https://github.com/google/grr.git
cd grr
sudo bash scripts/install_script_ubuntu.sh -d -y"

and then 
"sudo bash scripts/install_server_from_src.sh
sudo grr_config_updater initialize
source scripts/shell_helpers.sh
grr_enable_all"

If you installed mysql make sure to install "python mysqldb" 

You can enable them manually to start at boot time by modifying the follow to yes depending on how you have things setup.
in the /etc/default/ dir 
grr-dataserver-master
grr-http-server
grr-ui
grr-worker

**Comment by destijl** [comment]
This will be covered in the new setup.py michael is writing.

**Comment by grrrrrrrrr** [comment]
This is all new and should work now. I'll close this bug, just reopen it if there are still similar issues.
