### ISSUE TITLE
Memory flows require drivers on client

### ISSUE THREAD

**Issue by archieagr** [google/grr#290]
Hi 
When I start the following flows:
Load Memory Driver  
Memory Collector 
Scan Memory 
Unload Memory Driver
It gives me an error "Cannot find drivers on the client."
Can you help me resolve this!

**Comment by ookumusoglu** [comment]
I was having the same issue while using GRR in AWS. I would appreciate any help.

**Comment by scudette** [comment]
What is the client OS?

**Comment by archieagr** [comment]
The Client OS is Ubuntu14.04

**Comment by scudette** [comment]
On linux GRR only supports memory access via /proc/kcore. If that is disabled then you must compile a kernel driver (pmem from the Rekall releases page) specifically for each version of the kernel.

See https://github.com/google/grr/issues/247 for details.

**Comment by destijl** [comment]
@scudette we should make this more obvious in the UI somehow
