### ISSUE TITLE
Bad artifacts are removed from the DB almost silently

### ISSUE THREAD

**Issue by destijl** [google/grr#291]
We had a private meta artifact that included a public artifact that got renamed. So it was now broken. On the next production push this code:

https://github.com/google/grr/blob/master/lib/artifact_registry.py#L79

Displayed an error to the first person who visited the UI after the push, then removed the artifact from the datastore. So now the artifact isn't in the list and no other error is ever displayed. 

Displaying an error once ever isn't enough. We should keep them in the DB but mark them as invalid.

**Comment by grrrrrrrrr** [comment]
I wrote this code and it should do what you want already. The remove just removes it from the temporary list, not from the artifact registry. The artifact will remain in the registry with the error message set (in the line above the one you linked) which is exactly the behavior that you suggest. This is WAI, just reopen if you disagree.

**Comment by destijl** [comment]
OK, I think the bug is probably just with the UI notification. It only ever gets displayed once.

**Comment by grrrrrrrrr** [comment]
Please tell me what the exact problem is, I still think this is WAI.

I just uploaded a broken artifact. On upload you get a big warning that it doesn't pass validation. After that, the artifact is shown in the artifact manager, again, with a big red warning attached. If you go to the collector, the artifact is in the list. When you click on it, it shows you another big red warning - but it still lets you select it for the collector flow. I just don't see the behavior you describe, please provide more info what exactly you expect here.

**Comment by grrrrrrrrr** [comment]
ping @destijl , is there anything to do here?

**Comment by grrrrrrrrr** [comment]
Seems like there isn't.
