### ISSUE TITLE
install_server_from_src.sh not installing python mysqldb

### ISSUE THREAD

**Issue by dreifachkodiak** [google/grr#293]
This is more of an enhancement but it would be nice if it sets up to use a mysql server it should also install python mysqldb
it would be nice to not have to install other packages prior to the install script getting run.

**Comment by destijl** [comment]
This script doesn't know what database you're going to choose so it assumes defaults (sqlite not mysql), you don't choose it until initialize is run after this script is finished:
https://github.com/google/grr/blob/master/scripts/install_server_from_src.sh#L88

And if you do choose mysql, initialize tells you twice that you need to install it, and even waits for you to do so:
https://github.com/google/grr/blob/master/tools/config_updater.py#L517

I don't want to bloat the default install with unnecessary packages, so I think we're doing enough here.
