### ISSUE TITLE
Hunt UI doesn't allow hunt without rules

### ISSUE THREAD

**Issue by destijl** [google/grr#299]
The hunt UI doesn't allow you to create a hunt with no matching rules. This is a problem if you want to run a hunt on all clients without restrictions by OS etc.

**Comment by mutedmouse** [comment]
Could using a blanket label work as a stopgap?

**Comment by mbushkov** [comment]
Until this issue is resolved, the easiest way to run a fleet-wide hunt
would be having a "Regular Expression" rule with attribute name "System"
and regex ".*".

Cheers,
Misha

**Comment by mutedmouse** [comment]
+1

**Comment by miloszlakomy** [comment]
This is going to be resolved after the next sync.
