### ISSUE TITLE
Hunt network bytes limit applies to the hunt instead of the flow

### ISSUE THREAD

**Issue by destijl** [google/grr#300]
The "Network bytes limit" under advanced in the hunt parameters is a "limit on the total traffic used by this flow". But instead of being applied at the flow level (i.e. per machine), it is being applied at the hunt level.

A hunt level limit, while possibly useful, is less important. We can process and store tons of data on the server.  What's more important is protecting individual machines with unusual amounts of files from being killed by a hunt. There's no way to do this via the UI at present.

This behaviour is new, I suspect it was a result of the hunt UI switch to angular. Fix should be fairly simple.

**Comment by destijl** [comment]
AFAIK this is still a problem. Assigning to misha to take a look.

**Comment by grrrrrrrrr** [comment]
There are now separate per hunt and per flow limits.
