### ISSUE TITLE
Add artifact Registry default value support 

### ISSUE THREAD

**Issue by joachimmetz** [google/grr#303]
In https://github.com/ForensicArtifacts/artifacts/pull/141/files Registry artifacts are added that rely on the default (nameless) Registry values e.g.
```
{key: 'HKEY_LOCAL_MACHINE\Software\Classes\CLSID\*\InprocServer', value: ''}
```

At the moment the key path and value name are joined and the resolution of the default value does not seem to work. Can we add support to GRR to handle this appropriately. Thanks in advance.

**Comment by scudette** [comment]
If you just give it the name of the key it will fill in the data of the
default value.

https://github.com/google/grr/blob/master/client/vfs_handlers/registry.py#L323

Ultimately GRR sees a single path anyway - maybe the prolblem is in how the
artifacts join the key and value to make a path?

For example does this work?

 {key: 'HKEY_LOCAL_MACHINE\Software\Classes\CLSID\*', value: 'lnprocServer'}

**Comment by joachimmetz** [comment]
> Ultimately GRR sees a single path anyway

This will break some Registry locations. E.g. BagMRU keys can have subkey and value names that are the same.

**Comment by grrrrrrrrr** [comment]
The easy workaround for this is to use REGISTRY_KEY instead of REGISTRY_VALUE.

I agree though that specifying an empty value should yield the default value. I'll send a patch soon.

**Comment by scudette** [comment]
I think in regedit, the default value is denoted by "@" - maybe this is a reasonable convention?

**Comment by joachimmetz** [comment]
How do you distinguish between the default value and a value named "@" ?

**Comment by destijl** [comment]
This is now done, empty is default value:
https://github.com/google/grr/blob/master/lib/flows/general/collectors.py#L337
