### ISSUE TITLE
admin UI not updating directory hierarchy tree view after list directory flow

### ISSUE THREAD

**Issue by joachimmetz** [google/grr#305]
Encountering the following issue with the "bleeding edge" version:

* open client in admin UI
* expand directory in tree view
* run list directory via refresh button
* flow completes directory contents list view gets updated but directory hierarchy tree view does not

collapsing/expanding directory in tree view does not update subtree view
reload of page updates subtree view

**Comment by grrrrrrrrr** [comment]
Thanks for reporting this. We have already noticed that issue and fixed it, the code has just not reached the repo yet. I'll leave the bug open until we submit it...

**Comment by grrrrrrrrr** [comment]
Ok this is in now.
