### ISSUE TITLE
GRR silently fails to start with timesketch installed

### ISSUE THREAD

**Issue by mutedmouse** [google/grr#309]
The latest build silently failed to start grr when timesketch and plaso were placed on the same system. Install_script_ubuntu.sh says everything started but there is no process and no traffic. I will continue testing to isolate the package that is causing this silent failure.

To replicate 
    1) install grr from install_script_ubuntu.sh
    2) install python-plaso from apt
    3) install timesketch from github zip
    4) reboot
    5) on reboot I was no longer able to start grr using shell_helpers or fresh install through install_script_ubuntu.sh

SIDE NOTE: GRR operates as expected when installed as a standalone system. This however deprecates the capabilities for collaborative forensics as outline by http://blog.kiddaland.net/2015/07/timesketch-version-20157-released.html and runlog2timeline.py demo in the grrdemos github repository.

**Comment by mutedmouse** [comment]
SIDE NOTE: GRR operates as expected when installed as a standalone system.  This however deprecates the capabilities for collaborative forensics as outline by http://blog.kiddaland.net/2015/07/timesketch-version-20157-released.html and runlog2timeline.py demo in the grrdemos github repository.

**Comment by destijl** [comment]
I'd be interested in the specifics of what the version conflict was: what was the error message? Which package(s) were causing a problem?

But it's likely that making all of these projects agree on dependency versions on the same machine will be difficult. I'd suggest running plaso and log2timeline in docker containers and sharing data between them with volumes. Or using fully separate VMs/machines and transporting data between them.

At any large analysis scale you're going to want to separate these out anyway so you can apportion machine resources appropriately.

**Comment by mutedmouse** [comment]
Bingo greg,

I have isolated it to timesketch from source and now working toward
specific package and version control. It worked at one point.

Interim solution is to have an nfs mount from the grr server to the
timesketch that holds the log2timeline outputs and then uploading them from
the timesketch server from that system via ssh pass or ssh keys and
automated commands.

Once isolated and pinned to pip package I'll post a requirements.txt for
timesketch to this issue.

**Comment by berggren** [comment]
@mutedmouse Hi, Johan (timesketch author) here. Please let me know what the issue was and we will try to resolve it. Timesketch plays nicely in a virtual env of you want to do light weight separation.

**Comment by destijl** [comment]
If you find out the specific problem let us know, going to close this for now.
