### ISSUE TITLE
Install error on OSX El Capitan

### ISSUE THREAD

**Issue by morgoroth** [google/grr#317]
Trying a plain install from Ubuntu 14.04 with the agent on OSX 10.11.2. Installation fails with the below in the error log

```
12/22/15 9:30:10.549 PM sudo[54517]:     root : TTY=unknown ; PWD=/private/tmp/PKInstallSandbox.cOPdPR/Scripts/com.google.code.grr.com.google.code.grr.pkg.7El6wb ; USER=root ; COMMAND=/bin/launchctl unload /Library/LaunchDaemons/com.google.code.grr.plist
12/22/15 9:30:10.560 PM sudo[54519]:     root : TTY=unknown ; PWD=/private/tmp/PKInstallSandbox.cOPdPR/Scripts/com.google.code.grr.com.google.code.grr.pkg.7El6wb ; USER=root ; COMMAND=/bin/rm -f /Library/LaunchDaemons/com.google.code.grr.plist
12/22/15 9:30:10.000 PM kernel[0]: Sandbox: shove(54521) System Policy: deny(1) file-write-create /usr/lib/grr
12/22/15 9:30:11.282 PM UserEventAgent[48]: Failed to send message because the port couldn't be created.
12/22/15 9:30:12.104 PM Installer[54512]: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
```
A bit of searching brought me here, which would make sense to me as the cause of the issue. 

https://apple.stackexchange.com/questions/193368/what-is-the-rootless-feature-in-el-capitan-really

I have not tried to disable SIP since I am not positive that is the root issue. If you would like me to test it out, just let me know.

**Comment by grrrrrrrrr** [comment]
Hey James,

Thanks for reporting this. We already know about the problems with SIP and have a fixed client out that installs to a different directory. In the download section, you will need to get the template with version 3.0.7.1. If you currently use client v3.0.0.7, the update should be a simple repack. If your server is older, you might need to upgrade to a more recent version.

Cheers,
-Andy

**Comment by destijl** [comment]
See release notes:
https://github.com/google/grr-doc/blob/master/releasenotes.adoc#3007-to-3071
