### ISSUE TITLE
Error deleting a client

### ISSUE THREAD

**Issue by jcopeau** [google/grr#328]
Trying to remove dead hosts, but I'm getting an error.

In [9]: aff4.FACTORY.Delete(rdfvalue.ClientURN("C.04688755d5908970"))
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/usr/lib/python2.7/dist-packages/grr/tools/console.pyc in <module>()
----> 1 aff4.FACTORY.Delete(rdfvalue.ClientURN("C.04688755d5908970"))

AttributeError: 'module' object has no attribute 'ClientURN'

**Comment by grrrrrrrrr** [comment]
Hm I don't fully understand your report. Did you type this line (aff4.FACTORY...) into the console? Is this in the documentation somewhere?

The error is that ClientURN is in rdfvalues.client which usually gets imported as rdf_client so that line needs to be

aff4.FACTORY.Delete(rdf_client.ClientURN("C.04688755d5908970"))

Does that help?

**Comment by jcopeau** [comment]
Thanks, you've provided the correct syntax.

aff4.FACTORY.Delete(rdfvalue.ClientURN(client_id)) is the command provided
in the documentation at:

https://github.com/google/grr-doc/blob/master/user_manual.adoc#delete-a-client-and-all-of-its-data


On Thu, Jan 28, 2016 at 9:59 AM, Andreas Moser <notifications@github.com>
wrote:

> Hm I don't fully understand your report. Did you type this line
> (aff4.FACTORY...) into the console? Is this in the documentation somewhere?
>
> The error is that ClientURN is in rdfvalues.client which usually gets
> imported as rdf_client so that line needs to be
>
> aff4.FACTORY.Delete(rdf_client.ClientURN("C.04688755d5908970"))
>
> Does that help?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/grr/issues/328#issuecomment-176247525>.
>



-- 
Rick Whitmore
whitmore.rick@gmail.com

**Comment by grrrrrrrrr** [comment]
Ah yeah I thought that this might be some outdated documentation. I fixed the instructions, thanks for reporting this!
