### ISSUE TITLE
setup.py drops into python shell

### ISSUE THREAD

**Issue by brian-olson** [google/grr#335]
Looks like something in 8b9aee911d1cdb30eabab5b8c101636dea0077a9 broke the setup.py script. I didn't see any changes in the script itself. Since this version "python setup.py install" will execute a few commands then drop into an interactive python shell.

~/grr# git checkout 8b9aee911d1cdb30eabab5b8c101636dea0077a9
Previous HEAD position was 2ffa617... - Build script fixes. - Removing deprecated MySQL data store and the wsgi server.
HEAD is now at 8b9aee9... Overhaul client build system

~/grr# python setup.py install
running install
running bdist_egg
running egg_info
writing grr.egg-info/PKG-INFO
writing top-level names to grr.egg-info/top_level.txt
writing dependency_links to grr.egg-info/dependency_links.txt
writing entry points to grr.egg-info/entry_points.txt
reading manifest file 'grr.egg-info/SOURCES.txt'
writing manifest file 'grr.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.

**Comment by scudette** [comment]
It looks like the problem is in using shell=True for check_call. It should be removed.

```
subprocess.check_call(["python", "makefile.py"])
returncode = subprocess.call(["python", "makefile.py"], cwd="artifacts")
```

This code is under flux at the moment. I am going to work on it next.

**Comment by grrrrrrrrr** [comment]
This is fixed.
