### ISSUE TITLE
Incorrect Nanny error on Linux

### ISSUE THREAD

**Issue by tweksteen** [google/grr#339]
On Linux, when the client is killed by the nanny, the error message returned to the server is 'Nanny starting' which is incorrect.

When the client starts, the nanny thread overwrite the status file *before* reading it to get the previous crash message.

See the [NannyThread](https://github.com/google/grr/blob/master/client/client_utils_linux.py#L137) class and [OnStartup](https://github.com/google/grr/blob/master/client/comms.py#L982) method.

**Comment by destijl** [comment]
This looks fine to me, the error is reported and the current status of the nanny is reported:

```
ClientAction Hang failed. Staus: message GrrStatus { cpu_time_used : message CpuSeconds { } error_message : u'Client killed during transaction' nanny_status : u'Nanny starting.' network_bytes_sent : 139 status : CLIENT_KILLED }
```

I'll change it to "Nanny running", which might make a bit more sense since we only update it if the timeout is reached.
