### ISSUE TITLE
Hunt rules: Specify a client version to run against

### ISSUE THREAD

**Issue by parkisan** [google/grr#345]
The hunt wizard allows for many types of rules to be specified when constraining a hunt.

It would be very useful if we could target client versions (current ==. <, <=, >, >= constrains should be enough). Currently, this is under CLIENT_INFO in a VFSGRRClient (accessible via the "GRR Client" rule), but Integer rules cannot reach the client_version member of it.

**Comment by grrrrrrrrr** [comment]
This has been implemented.
