### ISSUE TITLE
Component not loaded if client goes down between loading and executing a component action

### ISSUE THREAD

**Issue by tweksteen** [google/grr#349]
In case a client goes down after a component is being loaded but before one of its action being executed,   when the client comes back and continue the flow, an error will be triggered since the component is not loaded anymore.

Is there a graceful method to handle such event?

**Comment by scudette** [comment]
Not currently. The component is part of the state of the client and if the
client restarts it will lose its state.

In practice that window should be very short. The flow loads the component
then used it.

**Comment by destijl** [comment]
I don't think there's anything to do here unless we see this causing significant problems, closing it out.
