### ISSUE TITLE
Install issues on ubuntu 14.04.4

### ISSUE THREAD

**Issue by ap-mosaic** [google/grr#350]
Im using the quick install method - sudo bash install_script_ubuntu.sh

One of the installs completes but admin or frontend servers are not responding.
Grr-http-server log shows
root@ubuntu:/var/log/grr# cat grr-http-server.log
ERROR:2016-04-15 08:40:32,482 http_server:159] Had to respond with status 500: oaep decoding error.
ERROR:2016-04-15 08:42:06,150 http_server:159] Had to respond with status 500: padding check failed.
ERROR:2016-04-15 08:43:39,815 http_server:159] Had to respond with status 500: oaep decoding error.
ERROR:2016-04-15 08:45:13,484 http_server:159] Had to respond with status 500: padding check 

Another install fails to enable grr services
     Enable grr services to start automatically on boot
##########################################################################################
Starting grr-http-server

**Comment by ap-mosaic** [comment]
I ran the configuration updater and the admin portal is now running
However when I install a client on windows the grr.exe.yaml file is empty
C:\Users\Administrator>c:\windows\system32\grr\3.0.0.7\grr.exe --config grr.exe.
yaml --verbose
Traceback (most recent call last):
  File "<string>", line 81, in <module>
  File "C:\grr-build-root\workpath\grr\out00-PYZ.pyz\grr.lib.flags", line 107, i
n StartMain
  File "<string>", line 57, in main
  File "C:\grr-build-root\workpath\grr\out00-PYZ.pyz\grr.lib.startup", line 71,
in ClientInit
  File "C:\grr-build-root\workpath\grr\out00-PYZ.pyz\grr.lib.startup", line 38,
in ConfigInit
  File "C:\grr-build-root\workpath\grr\out00-PYZ.pyz\grr.lib.config_lib", line 1
399, in ParseConfigCommandLine
  File "C:\grr-build-root\workpath\grr\out00-PYZ.pyz\grr.lib.config_lib", line 9
85, in Initialize
grr.lib.config_lib.ConfigFormatError: Unable to parse config file grr.exe.yaml

**Comment by destijl** [comment]
Did the repacking step work for the windows client? I didn't see this bug before I filed:
https://github.com/google/grr/issues/353

but lets track it there. I think the solution is to just switch the script over to installing the rc2.

**Comment by ap-mosaic** [comment]
Yes I was able to use the workaround from https://github.com/google/grr/issues/353
Repacking the client also resolved the issue on the client.
