### ISSUE TITLE
Rekall live forensics issues

### ISSUE THREAD

**Issue by biggiesmallsAG** [google/grr#355]
Im having issues running rekall on the remote host. This is for windows/unix. Tried to force reload the driver, this also fails.

LoadDriver traceback:
`Traceback (most recent call last): File "/usr/lib/python2.7/dist-packages/grr/lib/flow_runner.py", line 587, in RunStateMethod responses=responses) File "/usr/lib/python2.7/dist-packages/grr/lib/flow.py", line 349, in Decorated res = f(*args[:f.func_code.co_argcount]) File "/usr/lib/python2.7/dist-packages/grr/lib/flows/general/memory.py", line 497, in GotMemoryInformation responses.status)) FlowError: Failed to query device \\.\pmem (message GrrStatus { backtrace : u'Traceback (most recent call last):\n File "C:\\grr-build-root\\workpath\\grr\\out00-PYZ.pyz\\grr.client.actions", line 151, in Execute\n File "C:\\grr-build-root\\workpath\\grr\\out00-PYZ.pyz\\grr.client.client_actions.grr_rekall", line 310, in Run\n File "C:\\grr-build-root\\workpath\\grr\\out00-PYZ.pyz\\grr.client.vfs", line 400, in VFSOpen\nIOError: Unable to open \\\\.\\pmem: (2, \'CreateFile\', \'The system cannot find the file specified.\'): message PathSpec {\n path : u\'\\\\\\\\.\\\\pmem\'\n pathtype : MEMORY\n}\n' cpu_time_used : message CpuSeconds { system_cpu_time : 0.0 user_cpu_time : 0.0 } error_message : u'IOError("Unable to open \\\\\\\\.\\\\pmem: (2, \'CreateFile\', \'The system cannot find the file specified.\'): message PathSpec {\\n path : u\'\\\\\\\\\\\\\\\\.\\\\\\\\pmem\'\\n pathtype : MEMORY\\n}",): Unable to open \\\\.\\pmem: (2, \'CreateFile\', \'The system cannot find the file specified.\'): message PathSpec {\n path : u\'\\\\\\\\.\\\\pmem\'\n pathtype : MEMORY\n}' network_bytes_sent : 942 status : GENERIC_ERROR })
`

Analyze traceback:
`Traceback (most recent call last): File "/usr/lib/python2.7/dist-packages/grr/lib/flow_runner.py", line 587, in RunStateMethod responses=responses) File "/usr/lib/python2.7/dist-packages/grr/lib/flow.py", line 349, in Decorated res = f(*args[:f.func_code.co_argcount]) File "/usr/lib/python2.7/dist-packages/grr/lib/flows/general/memory.py", line 732, in StoreResults version=response.repository_version File "/usr/lib/python2.7/dist-packages/grr/lib/rekall_profile_server.py", line 72, in GetProfileByName profile_name, version=version) File "/usr/lib/python2.7/dist-packages/grr/lib/rekall_profile_server.py", line 88, in GetProfileByName handle = urllib2.urlopen(url, timeout=10) File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen return _opener.open(url, data, timeout) File "/usr/lib/python2.7/urllib2.py", line 404, in open response = self._open(req, data) File "/usr/lib/python2.7/urllib2.py", line 422, in _open '_open', req) File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain result = func(*args) File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open return self.do_open(httplib.HTTPSConnection, req) File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open raise URLError(err) URLError: <urlopen error [Errno -2] Name or service not known>
`

I am able to perform artefact collection on endpoints without any issue. Any help would be great.

**Comment by scudette** [comment]
The first traceback shows that loading the driver in the client fails. I
assume you are using a really old GRR version because the current version
(3.1.0) does not load drivers with GRR but uses rekall to take care of
drivers. The loaddriver flow will be removed soon.

The second traceback shows that the server is unable to reach the public
profile repository. If you have egress filtering you will need to cache the
profile repository on the server. The documentation describes this better
but essentially you just need to run the getmissingprofiles function
https://github.com/google/grr/blob/master/grr/lib/rekall_profile_server.py#L129

Hope this helps
Michael.

**Comment by biggiesmallsAG** [comment]
Hey Michael,

So as i was walking down the street it dawned on me that i was on my VM host-only network which explains analyze issue. I am however using a recent version of GRR, i only built it up last friday from the install.sh. 

Ill give the cached profiles a crack now.

Thanks mate.

**Comment by biggiesmallsAG** [comment]
Hey Michael,

Im getting timeouts running the function from console. I def have connectivity to the net with the server, it just sits there trying to get files from github and times out after 10 minutes.

From console i perform:

```
from grr.lib import rekall_profile_server as rps
s = rps.GRRRekallProfileServer()
s.GetMissingProfiles()
```

Any ideas? Is there a way i can manually write the profiles?

**Comment by scudette** [comment]
Can you check what URL it's trying to fetch the profiles from? Git hub used
to have one URL but then it stopped working and we changed it to the new
one. It's possible that GRR is still using the old one.

The correct URLs are listed in
https://github.com/google/rekall/blob/master/rekall-core/rekall/constants.py

Thanks
Michael.

**Comment by biggiesmallsAG** [comment]
Thanks for that, seemed to do the trick, it was using the old URL.

Regards,

Daniel.

**Comment by destijl** [comment]
install.sh actually gets you a really old server. We have a release candidate out for a much more modern version, but there are still a few rough edges we need to fix before it's ready for full release (when we will update the script). I'm collecting the release blockers under the 3.1.0 milestone if you want to check out the known issues before trying it out.
