### ISSUE TITLE
Chipsec Failure: Wrong Final Block Size Error

### ISSUE THREAD

**Issue by jolachea** [google/grr#361]
GRR Team,

I wanted to test the DumpFlashImage flow: 

`Traceback (most recent call last): File "/path/GRR_ENV/local/lib/python2.7/site-packages/grr/lib/flow_runner.py", line 594, in RunStateMethod responses=responses) File "/path/GRR_ENV/local/lib/python2.7/site-packages/grr/lib/flow.py", line 352, in Decorated res = f(*args[:f.func_code.co_argcount]) File "/path/GRR_ENV/local/lib/python2.7/site-packages/grr/lib/flows/general/transfer.py", line 925, in ComponentLoaded raise flow.FlowError(responses.status.error_message) FlowError: CipherError(EVPError('wrong final block length',),): wrong final block length`

This error was reported back on both systems (Win10, Ubuntu 16.04) I was testing this against.  I used all the default settings for the flows.  Let me know what else I can provide to help identify the issue.

**Comment by grrrrrrrrr** [comment]
It seems like the clients tried to download the component but failed -
 that error actually indicates an empty response. Do you have the chipsec
component in the database?

**Comment by scudette** [comment]
AFAIK the chipsec component only works on Linux now.

**Comment by jolachea** [comment]
It appears so:

```
find | grep chipsec
./grr-response-templates/components/grr-chipsec_0.1_Linux_debian_glibc_2.2.5_amd64.bin
./grr-response-templates/components/grr-chipsec_0.1_Linux_debian_glibc_2.0_i386.bin
./grr-response-templates/components/grr-chipsec_0.1_Linux_CentOS_glibc_2.0_i386.bin
./grr-response-templates/components/grr-chipsec_0.1_Linux_CentOS_glibc_2.2.5_amd64.bin
./lib/python2.7/site-packages/grr/client/components/chipsec_support
./lib/python2.7/site-packages/grr/client/components/chipsec_support/chipsec_pb2.pyc
./lib/python2.7/site-packages/grr/client/components/chipsec_support/chipsec_pb2.py
./lib/python2.7/site-packages/grr/client/components/chipsec_support/grr_chipsec.py
./lib/python2.7/site-packages/grr/client/components/chipsec_support/chipsec_types.pyc
./lib/python2.7/site-packages/grr/client/components/chipsec_support/__init__.py
./lib/python2.7/site-packages/grr/client/components/chipsec_support/__init__.pyc
./lib/python2.7/site-packages/grr/client/components/chipsec_support/grr_chipsec_test.py
./lib/python2.7/site-packages/grr/client/components/chipsec_support/grr_chipsec.pyc
./lib/python2.7/site-packages/grr/client/components/chipsec_support/setup.pyc
./lib/python2.7/site-packages/grr/client/components/chipsec_support/chipsec_types.py
./lib/python2.7/site-packages/grr/client/components/chipsec_support/chipsec.proto
./lib/python2.7/site-packages/grr/client/components/chipsec_support/grr_chipsec_test.pyc
./lib/python2.7/site-packages/grr/client/components/chipsec_support/setup.py
```

Thanks scudette, that is worth knowing.  I am terminating with the same error on the Ubuntu machine:

`Traceback (most recent call last): File "/path/GRR_ENV/local/lib/python2.7/site-packages/grr/lib/flow_runner.py", line 594, in RunStateMethod responses=responses) File "/path/GRR_ENV/local/lib/python2.7/site-packages/grr/lib/flow.py", line 352, in Decorated res = f(*args[:f.func_code.co_argcount]) File "/path/GRR_ENV/local/lib/python2.7/site-packages/grr/lib/flows/general/transfer.py", line 925, in ComponentLoaded raise flow.FlowError(responses.status.error_message) FlowError: CipherError(EVPError('wrong final block length',),): wrong final block length`

**Comment by destijl** [comment]
Sorry yes I had this in my notes to mention in the meetup but forgot. The Chipsec status is: collection of firmware on Ubuntu (14.04) works, but is still in beta, OS X is next.

**Comment by jolachea** [comment]
No problem.  I know you folks are very busy.  Thanks for all the hard work you are putting in.

**Comment by tweksteen** [comment]
I think the value returned by platform.libc_ver() is different on 16.04, therefore it won't find the correct component version. Could you confirm that by running a Rekall-based flow and check if the component loads successfully?

**Comment by destijl** [comment]
We're going to fix that problem before the release. Lets track it here and re-open if it's still a problem.
https://github.com/google/grr/issues/372
