### ISSUE TITLE
Prelinking breaks client on RHEL 6

### ISSUE THREAD

**Issue by destijl** [google/grr#367]
Pyinstaller has fixed this hopefully forever:
https://github.com/pyinstaller/pyinstaller/issues/1812

in 3.2. So all we need to do here is build new client templates with pyinstaller 3.2

**Comment by destijl** [comment]
@scudette did you file a bug for the pyinstaller windows problem? I don't see it. I'm inclined to just build redhat with that version and leave the rest using the proven version (3.2 is very new).

**Comment by scudette** [comment]
Yes it was fixed but not released yet:
https://github.com/pyinstaller/pyinstaller/issues/1974

I actually found some problems with 3.1.1 and 3.1 as well and the only thing that worked for me was 3.0.0 to build Rekall. Maybe GRR will work later versions?
