### ISSUE TITLE
Make grr installable via PPA

### ISSUE THREAD

**Issue by destijl** [google/grr#368]

**Comment by destijl** [comment]
So after messing with this today I've realised it's a lot harder to get GRR into a PPA than I thought because:

1. Packages *must* be built from source only.
2. All dependencies must be satisfied from the ubuntu repo or other PPAs. No internet access for build.

The second is a major problem since our current deb build process relies on being able to install package from pypi.

This makes sense as a policy for Ubuntu but it means before we can put GRR in a PPA we need to put rekall in one, and any packages we depend on that aren't already in the standard repo (I don't think this list is that big, but it's very hard to tell because there's no consistency between pip name and deb name).

We're also stuck with the deb version of each package, which for example will mean that bigquery is broken because we haven't updated to oauth2 yet, and any other package pins we have for specific reasons that clash with deb versions will need to be resolved...somehow. Trying to make both pip and deb dependency resolution happy is a PITA than will inevitably cause maintenance and release-time pain.

So since I have a working deb build (which btw anyone can reproduce using the Dockerfile), we're going to stick with the slightly icky bash script install method.

**Comment by hillu** [comment]
@satta and I have been working on getting grr and all its dependencies packaged for Debian. Unfortunately, Debian won't include our grr package in the next stable release, we are a bit too late for that, but we intend to make the package available via a backport.

**Comment by destijl** [comment]
@hillu that's great, thanks! Can you send me some links to dependencies you've got packaged?

**Comment by hillu** [comment]
> @hillu that's great, thanks! Can you send me some links to dependencies you've got packaged?

These are our build-dependencies so far, all of them can be satisfied on
a Debian/stretch (upcoming stable) system:

    Build-Depends: debhelper (>= 9), dh-python, python-dev,
     cmake,
     debhelper (>= 10.1~) | dh-systemd,
     protobuf-compiler,
     python-binplist,
     python-crontab,
     python-django,
     python-ipaddr,
     python-m2crypto,
     python-mock,
     python-mox,
     python-pexpect,
     python-protobuf,
     python-psutil,
     python-rekall-core,
     python-requests,
     python-selenium,
     python-setuptools,
     python-tsk,
     python-urllib3,
     python-werkzeug,
     python-yaml,
     txt2man

We have had to work quite a bit around the assumption that grr-server
wants to be installed by using pip though.

Cheers,
-Hilko

**Comment by hillu** [comment]
Our GRR package just arrived in Debian/unstable: https://tracker.debian.org/news/836691

**Comment by satta** [comment]
@destijl BTW, since Debian unstable ships newer versions of protobuf (3.0.0) etc. I was wondering what your plans are for tagging a minor release that includes your more recent commits adding, for example, support for that version (https://github.com/google/grr/commit/c535d6984a407807b64ca24e7ff5649539eecb50)? The currently released 3.1.0.2 still requires an older version of protobuf, and I have seen that a later commit addresses this). There are also various other fixes that would be desirable.
Many thanks!

**Comment by destijl** [comment]
Thanks for the great work here. Looking at:
https://ci.debian.net/packages/g/grr/unstable/amd64/

It looks like tests are failing due to fuse. You install python-fuse, but it looks like the code is actually written for:
https://github.com/terencehonles/fusepy
https://pypi.python.org/pypi/fusepy

We handle fuse not being present gracefully so not installing it at all is also OK.

Re release plans I think we should probably have an official new release in Q2, but I don't think it will happen before then.

**Comment by hillu** [comment]
Meanwhile, fusepy has been accepted into unstable, so we can have the grr-server depend on it.

**Comment by satta** [comment]
Yes, I already noticed the failing tests and have packaged fusepy. Will switch the package to use that instead of python-fuse, which should also fix that part of the tests. I'll also skip the protobuf related tests until the new release adds 3.0 support (if that's OK with you).
Thanks for your feedback!

**Comment by destijl** [comment]
So is the proto problem that on sid you get 3009
https://packages.debian.org/sid/protobuf-compiler

but the code is checking for 2.6.something? I think as long as the build system and the install system uses exactly the same version and it's later than 2.6 it should work. Stuff breaks when you install on a system with a different compiler and want to change something in the proto files, or do anything else that requires a re-compile. That's probably what the tests are trying to avoid by pinning the exact version.

Do you have backtraces for the tests you want to disable?

**Comment by satta** [comment]
The check isn't the problem, I've changed the fixed versions in the `setup.py` anyway since Debian carries newer versions for a lot of the dependencies anyway. For example, I had to make some changes to the Django code since there have been some API changes between 1.8 and 1.10.

The main problem is that related tests are failing, and when trying to track down the reason I figured they are likely protobuf (and AFF4) related, so I disabled some for now:
```
grr_run_tests --exclude_tests TestArtifactCollectorsRealArtifacts,TestArtifactCollectors,RDFStructsTest
```
Here are the tracebacks from these failures:
```
Test name: RDFStructsTest
........EE.........
======================================================================
ERROR: testProtoFileDescriptorIsGeneratedForDynamicAnyValueType (grr.lib.rdfvalues.structs_test.RDFStructsTest)

RDFStructsTest.testProtoFileDescriptorIsGeneratedForDynamicAnyValueType - 

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/grr/lib/test_lib.py", line 455, in run
    testMethod()
  File "/usr/lib/python2.7/dist-packages/grr/lib/rdfvalues/structs_test.py", line 211, in testProtoFileDescriptorIsGeneratedForDynamicAnyValueType
    pool.Add(file_descriptor)
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "dynamicanyvaluetypetest.proto":
  dynamicanyvaluetypetest.proto: Import "grr/proto/semantic.proto" has not been loaded.
  grr_export.DynamicAnyValueTypeTest.dynamic: "AnyValue" is not defined.


======================================================================
ERROR: testProtoFileDescriptorIsGeneratedForDynamicType (grr.lib.rdfvalues.structs_test.RDFStructsTest)

RDFStructsTest.testProtoFileDescriptorIsGeneratedForDynamicType - 

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/grr/lib/test_lib.py", line 455, in run
    testMethod()
  File "/usr/lib/python2.7/dist-packages/grr/lib/rdfvalues/structs_test.py", line 189, in testProtoFileDescriptorIsGeneratedForDynamicType
    pool.Add(file_descriptor)
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "dynamictypetest.proto":
  dynamictypetest.proto: Import "grr/proto/knowledge_base.proto" has not been loaded.
  grr_export.DynamicTypeTest.nested: ".User" is not defined.


----------------------------------------------------------------------
Ran 19 tests in 0.094s
```
```
Test name: TestArtifactCollectors
F......EEF
======================================================================
ERROR: testRunGrrClientActionArtifact (grr.lib.flows.general.collectors_test.TestArtifactCollectors)

TestArtifactCollectors.testRunGrrClientActionArtifact - Test we can get a GRR client artifact.

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/grr/lib/test_lib.py", line 455, in run
    testMethod()
  File "/usr/lib/python2.7/dist-packages/grr/lib/flows/general/collectors_test.py", line 215, in testRunGrrClientActionArtifact
    self.assertTrue(isinstance(list(fd)[0], rdf_client.Process))
TypeError: 'AFF4Volume' object is not iterable

======================================================================
ERROR: testRunGrrClientActionArtifactSplit (grr.lib.flows.general.collectors_test.TestArtifactCollectors)

TestArtifactCollectors.testRunGrrClientActionArtifactSplit - Test that artifacts get split into separate collections.

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/grr/lib/test_lib.py", line 455, in run
    testMethod()
  File "/usr/lib/python2.7/dist-packages/grr/lib/flows/general/collectors_test.py", line 244, in testRunGrrClientActionArtifactSplit
    self.assertTrue(isinstance(list(fd)[0], rdf_client.Process))
TypeError: 'AFF4Volume' object is not iterable

======================================================================
FAIL: testConditions (grr.lib.flows.general.collectors_test.TestArtifactCollectors)

TestArtifactCollectors.testConditions - Test we can get a GRR client artifact with conditions.

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/grr/lib/test_lib.py", line 455, in run
    testMethod()
  File "/usr/lib/python2.7/dist-packages/grr/lib/flows/general/collectors_test.py", line 270, in testConditions
    self.assertEqual(fd.__class__, collects.RDFValueCollection)
AssertionError: <class 'grr.lib.aff4.AFF4Volume'> != <class 'grr.lib.aff4_objects.collects.RDFValueCollection'>

======================================================================
FAIL: testSupportedOS (grr.lib.flows.general.collectors_test.TestArtifactCollectors)

TestArtifactCollectors.testSupportedOS - Test supported_os inside the collector object.

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/grr/lib/test_lib.py", line 455, in run
    testMethod()
  File "/usr/lib/python2.7/dist-packages/grr/lib/flows/general/collectors_test.py", line 357, in testSupportedOS
    self.assertEqual(fd.__class__, collects.RDFValueCollection)
AssertionError: <class 'grr.lib.aff4.AFF4Volume'> != <class 'grr.lib.aff4_objects.collects.RDFValueCollection'>

----------------------------------------------------------------------
Ran 10 tests in 33.415s
```
```
Test name: TestArtifactCollectorsRealArtifacts
E....
======================================================================
ERROR: testRetrieveDependencies (grr.lib.flows.general.collectors_test.TestArtifactCollectorsRealArtifacts)

TestArtifactCollectorsRealArtifacts.testRetrieveDependencies - Test getting an artifact without a KB using retrieve_depdendencies.

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/grr/lib/test_lib.py", line 455, in run
    testMethod()
  File "/usr/lib/python2.7/dist-packages/grr/lib/flows/general/collectors_test.py", line 693, in testRetrieveDependencies
    output="testRetrieveDependencies"):
  File "/usr/lib/python2.7/dist-packages/grr/lib/test_lib.py", line 1876, in TestFlowHelper
    for flow_run in worker_mock.Next():
  File "/usr/lib/python2.7/dist-packages/grr/lib/test_lib.py", line 1771, in Next
    raise RuntimeError(runner.context.backtrace)
RuntimeError: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/grr/lib/flow_runner.py", line 613, in RunStateMethod
    responses=responses)
  File "/usr/lib/python2.7/dist-packages/grr/lib/flow.py", line 353, in Decorated
    res = f(*args[:f.func_code.co_argcount])
  File "/usr/lib/python2.7/dist-packages/grr/lib/artifact.py", line 240, in ProcessBase
    deps = self.SetKBValue(responses.request_data["artifact_name"], responses)
  File "/usr/lib/python2.7/dist-packages/grr/lib/artifact.py", line 332, in SetKBValue
    self.state.knowledge_base.Set(provides, value)
  File "/usr/lib/python2.7/dist-packages/grr/lib/rdfvalues/structs.py", line 1758, in Set
    return self._Set(value, type_info_obj)
  File "/usr/lib/python2.7/dist-packages/grr/lib/rdfvalues/structs.py", line 1741, in _Set
    value = type_descriptor.Validate(value, container=self)
  File "/usr/lib/python2.7/dist-packages/grr/lib/rdfvalues/structs.py", line 440, in Validate
    raise type_info.TypeValueError("%s not a valid string" % value)
TypeValueError: 1 not a valid string


----------------------------------------------------------------------
Ran 5 tests in 13.972s
```
