### ISSUE TITLE
Executables Directory not in AFF4 space

### ISSUE THREAD

**Issue by jessicawilsonsc** [google/grr#369]
Installer files not appearing in web interface, but do exist within `GRR_ENV/executables`

When running the ui daemon in verbose mode, the following message stands out:
`DEBUG:2016-05-06 16:56:13,858 user_managers:53] data_store_access GRANTED by BasicAccessControlManager to admin (([<aff4:/config/executables/darwin/installers age=1970-01-01 00:00:00>], 'rq'), {}) with reason:`

**Comment by grrrrrrrrr** [comment]
hey,

the config_updater will upload the executables to the database (aff4 space) for you. Have you run the initialize?

**Comment by jessicawilsonsc** [comment]
Yes I have.

**Comment by destijl** [comment]
Can't reproduce with docker. Can you re-run initialize and paste the output? I'm really surprised that it succeeds and the binaries aren't there.

**Comment by destijl** [comment]
I just tested from clean (ubuntu xenial) with the pip install instructions, which point at rc2. This is what jessica had. Still works. I'm going to mark this as unreproducible, but I'll definitely check it in the release.
