### ISSUE TITLE
Agent Install .deb errors on Debian 7.4

### ISSUE THREAD

**Issue by b3nw** [google/grr#37]
``` # dpkg -i grr_3.0.0.2_amd64.deb ```
(Reading database ... 29507 files and directories currently installed.) 
Preparing to replace grr 3002-1 (using grr_3.0.0.2_amd64.deb) ... 
invoke-rc.d: unknown initscript, /etc/init.d/grr not found. 
dpkg: warning: subprocess old pre-removal script returned error exit status 100 
dpkg: trying script from the new package instead ... 
invoke-rc.d: unknown initscript, /etc/init.d/grr not found. 
dpkg: error processing grr_3.0.0.2_amd64.deb (--install): 
subprocess new pre-removal script returned error exit status 100 
invoke-rc.d: unknown initscript, /etc/init.d/grr not found. 
dpkg: error while cleaning up: 
subprocess installed post-installation script returned error exit status 100 
Errors were encountered while processing: 
grr_3.0.0.2_amd64.deb

``` # lsb_release -a ```
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.4 (wheezy)
Release:	7.4
Codename:	wheezy
```

**Comment by destijl** [comment]
I've fixed this over a number of different commits.  I updated the init.d scripts to detect if upstart is present and just exit if it is.  So we install both init.d and upstart with the .deb and we prefer upstart if it is present.  Building the package like this requires a modern version of debhelper that understands having init.d and upstart together is a thing.  The vagrant build environment has a version that can do this.

So the short answer is this is fixed if you build debs in the vagrant VM.
