### ISSUE TITLE
Allow download of rekall profiles over proxy

### ISSUE THREAD

**Issue by SleuthKid** [google/grr#381]
It would be nice if grr would have a global variable for a general proxy setting if grr wants to connect to the internet. Especially for downloading the rekall profiles I had to patch the _grr/lib/rekall_profile_server.py_ file with something like:

```
      url = "%s/%s/%s.gz" % (
          config_lib.CONFIG["Rekall.profile_repository"],
          version, profile_name)
      proxy = urllib2.ProxyHandler({'https': '<PROXY_ADDR>'})
      opener = urllib2.build_opener(proxy)
      urllib2.install_opener(opener)
      handle = urllib2.urlopen(url, timeout=10)
```

Maybe this would also be useful for other parts of grr.

**Comment by scudette** [comment]
GRR Just uses urllib.urlopen() and that uses whatever proxy is set in the environment variable http_proxy. 
https://docs.python.org/2/library/urllib.html

Do you need more than that?

**Comment by SleuthKid** [comment]
If setting the environment variable is the preferred solution this can be marked as solved.
