### ISSUE TITLE
ImportError: No module named six

### ISSUE THREAD

**Issue by destijl** [google/grr#383]
Rekall can't install because efilter can't install, we're blocked on release until efilter releases:
https://github.com/google/dotty/issues/18

**Comment by destijl** [comment]
@scudette  I think we're waiting on a rekall release now since efilter is fixed?

**Comment by scudette** [comment]
Unfortunately Adam released 1.3 which was supposed to be a bugfix to the
last broken release. Instead this release introduced major changes to the
API which subsequently broke Rekall. I will need a day or two to fix Rekall
to support the new API.
