### ISSUE TITLE
Install script fails because distorm 3.3.1 was deleted

### ISSUE THREAD

**Issue by destijl** [google/grr#384]
Looks like distorm completely deleted previous releases from pypi somehow.

https://pypi.python.org/simple/distorm3/

Originally reported in:
https://github.com/google/grr-doc/issues/46

**Comment by destijl** [comment]
https://github.com/gdabah/distorm/issues/99

**Comment by destijl** [comment]
I think the solution here is to put the old requirements.txt on cloud storage to keep the install script working until we're ready to make the new release the default. Hopefully distorm 3.3.3 works with the old code.

This isn't the first time someone has deleted code out from under us. It lends weight to the idea of hosting all our own wheels like rekall and not using pypi at all.

**Comment by grrrrrrrrr** [comment]
Turns out, Distorm3 did the version cleanup because they were about to release 3.3.4. They failed to tell us and, as expected, broke us again when they removed v3.3.3.

I upgraded the requirements.txt once more to point at the new version.

**Comment by scudette** [comment]
The next version of GRR which should be out this week or next, does
not use distorm any more. Rekall has switched to capstone a while
back.
