### ISSUE TITLE
_pb2 missing in deb build

### ISSUE THREAD

**Issue by SleuthKid** [google/grr#386]
unsing the deb server build process stated here: 
https://github.com/google/grr-doc/blob/master/admin.adoc#building-the-server-debian-package 

does not bundle the compiled protobuf files.

Reference: https://groups.google.com/forum/#!topic/grr-dev/xXrjUYqJ1r4

**Comment by destijl** [comment]
I built the new deb and it works fine, you can get it here:
https://storage.googleapis.com/grr_releases/3.1.0.2/grr-server_3.1.0-2_amd64.deb
