### ISSUE TITLE
Client.control_urls not being included in client's grr.yaml

### ISSUE THREAD

**Issue by jessicawilsonsc** [google/grr#387]
I'm having issues where when I pack the clients and install them on to Mac OSX, I'm missing the line "Client.control_urls: http://yourgrrserver.yourcompany.com:8080/control"

I've been working around it by manually adding it. Once that happens, it works just fine. I have only tested on Mac, so I am not sure if the problem also occurs on Windows or Linux.

**Comment by destijl** [comment]
This option is deprecated and replaced by Client.server_urls. I've added that to the config variable graveyard and put it in the release notes.

https://github.com/google/grr-doc/blob/master/releasenotes.adoc

**Comment by jessicawilsonsc** [comment]
In that case, Client.server_urls does not appear in my config file by default either.

**Comment by destijl** [comment]
Is it in the .local? does the client actually work? There's code that verifies it's in there after repack.
https://github.com/google/grr/blob/master/grr/lib/build.py#L289

**Comment by jessicawilsonsc** [comment]
The client only works after I run the commands :
> 
$ sudo launchctl unload /Library/LaunchDaemons/com.google.code.grr.plist
$ sudo /usr/local/lib/grr_3.0.7.1_amd64/grrd --config=/usr/local/lib/grr_3.0.7.1_amd64/grrd.yaml --verbose

I do not have any type of .local on the client and I do have  `Client.server_urls:` in in my server.local.yaml

**Comment by destijl** [comment]
Have you been mixing head and 3071? That's not going to work.

What's the error? The commands you list just amount to a stop and restart.

**Comment by jessicawilsonsc** [comment]
Can you define mixing head and 3071? I am a fresh pip install following only from https://github.com/google/grr-doc/blob/master/installfrompip.adoc#installing-grr-server-for-dev-ie-tracking-head . If you are wondering because of the command in the above post, I got lazy and just copy pasted from the documentation instead of my actual command. 

Not sure if this makes a difference at all - my files are are `grr` and `grr.yaml` instead of `grrd` and grrd`.yaml` by default as well.

I assume in `grr.yaml` that `Client.control_urls: http://<ip>:8080/control` was replaced with `Client.server_urls: http://<ip>:8080/`. With both `Client.controls_urls` and `Client.server_urls` added (not at the same time!) and running the start command manually, my host will not connect to the server. I've tried through reboots with no success. 

The error I get before I add in the correct HTTP url is the same as in the documentation, where I get status 406.  I do not get errors when I run the command manually after adding either either variable.

**Comment by destijl** [comment]
I'm out the rest of the week but there is definitely a problem with os x
repacking I experienced today. Michael is going to take a look while I'm
out. Linux worked ok, and I didn't get to test windows yet.

**Comment by destijl** [comment]
There were a couple of problems. On the server control_urls was recognized during initialize, but we never actually wrote the values from there into server_urls, so server_urls wasn't set on upgraded servers. On OS X the installer was failing to find the build.yaml, which was noted in the install log and failed the second part of install, but since we ship with a very basic config it kinda ran anyway, just didn't have any keys and couldn't actually talk to the server.

**Comment by jessicawilsonsc** [comment]
Using the newest templates, rebuilding with the latest git commit, my OSX clients still are not getting `Client.server_urls` in their `grr.yaml`. I see it however in `installer_config.yaml` on the client.

**Comment by destijl** [comment]
OK I re-tested on a clean el cap vm and it works for me. You should see server_urls in /etc/grr.local.yaml.
