### ISSUE TITLE
GRR Client Duplicates

### ISSUE THREAD

**Issue by pidydx** [google/grr#39]
It would be nice to have a report for listing any hosts suspected of being duplicates, usually as a result of cloning an already installed agent.  A flow that forces a client to reenroll could be useful for resolving any detected problems.

**Comment by grrrrrrrrr** [comment]
I pushed a script to find cloned clients based on reported serial numbers - FindClonedClients in the console. It needs lots of data points and will work best if collection of hardware serial numbers has been running for a while...
