### ISSUE TITLE
Can't download requirements.txt

### ISSUE THREAD

**Issue by dfinf2** [google/grr#393]
Cannot download requirements.txt from:
https://storage.googleapis.com/releases.grr-response.com/server-0.3.0-7/requirements.txt

Get the error
`<Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>Anonymous users does not have storage.objects.get access to object releases.grr-response.com/server-0.3.0-7/requirements.txt.</Details></Error>`

**Comment by grrrrrrrrr** [comment]
Oh sorry we had to change a dependency in that file and didn't enable public sharing afterwards. This should be fixed now, please reopen if you still have problems getting the file.
