### ISSUE TITLE
GRR docker latest build: RuntimeError: Bad build.yaml

### ISSUE THREAD

**Issue by sarcarx** [google/grr#394]
I was using grr:v0.3.0-7 as a docker image and I got it working from end-to-end (server client and connexion between both).
Now I would like to use the latest build so I tried to run the docker image:
`docker run -e EXTERNAL_HOSTNAME="my_domain_name" -e ADMIN_PASSWORD="demo" --ulimit nofile=1048576:1048576 -p 0.0.0.0:8000:8000 -p 0.0.0.0:8080:8080 grrdocker/grr:latest grr`
and got the following output:
http://pastebin.com/Wx2aSyqE
To sum up the error:
`RuntimeError: Bad build.yaml from /usr/share/grr-server/grr-response-templates/templates/GRR_3.1.0.0_amd64.exe.zip: expected set(['Client.build_time', 'Template.arch', 'Template.version_minor', 'Template.build_context', 'Template.build_type', 'Template.version_major', 'Template.version_revision', 'Template.version_release', 'Client.build_environment']), got ['Client.build_time', 'Client.build_environment']
`
I don't really understand why this does not work, since the template is supposed to be within the docker image. Is there any fix to this problem?

**Comment by destijl** [comment]
Thanks, this is expected until we release a new client templates package, which is blocked by https://github.com/google/grr/issues/387

working on that one now, should be fixed soon.

**Comment by sarcarx** [comment]
Is there a way with docker to use the latest working build in the meanwhile?

**Comment by destijl** [comment]
It builds fine, but it can't repack the clients. I plan to get the release out today.

**Comment by destijl** [comment]
3.1.0.2 is out, if you use the 3.1.0.2 server release with the 3.1.0.2 templates it will work. See:
https://github.com/google/grr-doc/blob/master/installfrompip.adoc

Make sure you use a fresh virtualenv, or specify 3.1.0.2 versions to get the new ones.
