### ISSUE TITLE
HTTPDatastore Servers not creating logs

### ISSUE THREAD

**Issue by jessicawilsonsc** [google/grr#398]
Running pip tracking head, I have a HTTPDatastore environment. The dataserver_master service does not create logs in `/grr/grr/var/log/`. Other services can successfully create them, such as `grr-ui.log` and `grr-worker.log`

**Comment by grrrrrrrrr** [comment]
Somehow we have not enabled logging for the data server. In
https://github.com/google/grr/blob/master/install_data/etc/grr-server.yaml#L323

you can just add a Logging.filename similar to what happens in the worker context right above to enable logging. I will change this to be enabled by default.

**Comment by grrrrrrrrr** [comment]
This is now enabled by default.
