### ISSUE TITLE
Admin UI Statistics not displaying

### ISSUE THREAD

**Issue by jessicawilsonsc** [google/grr#399]
When I visit "Show Statistics" under "Management" on the left side panel on the UI, it doesn't load the statistics when I use Google Chrome in standard mode. However, they always display when I use incognito mode.

**Comment by chlunde** [comment]
Does it work again if you do a full reload?  And stop working as soon as you hit a stats with "No data Available"?

**Comment by jessicawilsonsc** [comment]
What do you mean "full reload"? I've closed out the standard chrome browser and logged back into the UI with the same results. 

I am trying to visit stats pages with data. Side by side comparison with incognito mode the exact same request will yield results on incognito mode and remain blank in the standard mode.

**Comment by chlunde** [comment]
OK, then it's a different issue than what I had. I'll create a new issue for it if I can reproduce it with the latest version once the clients are ready.

By full reload I meant ctrl-r/ctrl-f5. As soon as I hit a graph like "Last Active 30 days" without any data no other graphs would show until I reloaded the page.  F12/Developer Console would say something like "invalid plot null".  I think it was related to clients with labels.

Maybe you can also see a javascript error if you check the console.

**Comment by chlunde** [comment]
I just switched between 3.0 and 3.1 on localhost:8000 and got many strange errors until I cleared the cache.  Incognito mode runs with a clean cache, so maybe *that's* the same issue as you have?  Try clearing the browser cache.

**Comment by jessicawilsonsc** [comment]
I've cleared the cache on Chrome, yet these issues are still persisting.

**Comment by AadiPapp** [comment]
Please check if you are an admin with User access privileges and file permissions to the Statistics Datasets.

**Comment by jessicawilsonsc** [comment]
Yes. I can tell this is true because I am able to fully access them in incognito mode.

**Comment by destijl** [comment]
Agree with @chlunde here. If it works in incognito it's almost certainly cache that needs clearing, or possibly a chrome extension interfering. You can load with chrome dev tools and check any differences in resources being loaded between the two.

**Comment by ohpaulsen** [comment]
We had the same problem. Traced down to uBlock Origin(Adblocker).

**Comment by jessicawilsonsc** [comment]
@ohpaulsen That fixed it. I disabled uBlock Origin on my browser, and they loaded just fine. Thank you!
