### ISSUE TITLE
Admin UI statistics stops working after visiting item without any data

### ISSUE THREAD

**Issue by chlunde** [google/grr#403]
After visiting for example /Clients/All/GRR Version/1 Day right after starting a new instance, `No data Available` is displayed and and uncaught exception is thrown: `Error: Invalid dimensions for plot, width = null, height = null`.  If the user then clicks on another menu item, which normally works, like /Server/User Breakdown/7 Day, nothing happens.

The initial javascript error is thrown because `grr/gui/plugins/statistics.py` will not render `<div id="{{unique}}"` when there's no data, so `$('#' + unique)` fails.

If I manually call `grr.ExecuteRenderer("ReportRenderer.Layout", {"unique": 255, "renderer": "ReportRenderer", "id": "legacy_1"});` then the menu works again.

Maybe `grr.ExecuteRenderer` should catch and log exceptions?

```
third-party.bundle.js?timestamp=1466452712.42:79433 Uncaught Error: Invalid dimensions for plot, width = null, height = null
Canvas.resize @ third-party.bundle.js?timestamp=1466452712.42:79433
Canvas @ third-party.bundle.js?timestamp=1466452712.42:79412
setupCanvases @ third-party.bundle.js?timestamp=1466452712.42:80611
Plot @ third-party.bundle.js?timestamp=1466452712.42:80005
$.plot @ third-party.bundle.js?timestamp=1466452712.42:82444
Layout @ statistics.js?timestamp=1466452712.42:147
grr.ExecuteRenderer @ renderers.js?timestamp=1466452712.42:50
(anonymous function) @ VM1405:1
globalEval @ third-party.bundle.js?timestamp=1466452712.42:13740
domManip @ third-party.bundle.js?timestamp=1466452712.42:18687
append @ third-party.bundle.js?timestamp=1466452712.42:18827
(anonymous function) @ third-party.bundle.js?timestamp=1466452712.42:18921
access @ third-party.bundle.js?timestamp=1466452712.42:17011
html @ third-party.bundle.js?timestamp=1466452712.42:18888
success_handler @ grr.js?timestamp=1466452712.42:892
success @ grr.js?timestamp=1466452712.42:835
fire @ third-party.bundle.js?timestamp=1466452712.42:16584
fireWith @ third-party.bundle.js?timestamp=1466452712.42:16714
done @ third-party.bundle.js?timestamp=1466452712.42:22182
(anonymous function) @ third-party.bundle.js?timestamp=1466452712.42:22548
```

**Comment by destijl** [comment]
I suspect this just needs some love after the move to angular.

**Comment by AadiPapp** [comment]
@destjil agree with you.Please check if the configuration file is updated for default rendering, if not as suggested exception needs to handled with user friendly message.

**Comment by grrrrrrrrr** [comment]
This has been fully converted to Angular now and the statistics.py that caused the issue no longer exists. Fixed.
