### ISSUE TITLE
 No Storage System MySQLAdvancedDataStore when installing via deb

### ISSUE THREAD

**Issue by destijl** [google/grr#404]
When installing 3.1.0.2 via the deb it doesn't include the libraries necessary for the MySQL backend, it looks like this if you choose MySQL instead of the SQLite default:

```
RuntimeError: No Storage System MySQLAdvancedDataStore found.

dpkg: error processing package grr-server (--install):

 subprocess installed post-installation script returned error exit status 1

Processing triggers for libc-bin (2.23-0ubuntu3) ...

Errors were encountered while processing:

 grr-server
```

The workaround is to install with the default DB then (assuming you have mysql server and client libraries installed and configured):

```
sudo /usr/share/grr-server/local/bin/pip install MySQL-python
grr_config_updater initialize
```

**Comment by destijl** [comment]
Thinking about this some more I don't think it's a code bug, but a documentation bug. We shouldn't install all the mysql libraries, since it isn't the default DB and that's a bunch of bloat (and you can't install the python bindings without the mysql dev client libraries). 

Currently when you run initialize and choose MySQL it pauses and says:

```
***WARNING***

Do not continue until a MySQL server, version 5.6 or greater, is running and a
user with the ability to create the GRR database and tables has been created.
You will need the server, username, password, and database name (if already
created) to continue. If no database has been created this script will attempt
to create the necessary database and tables using the credentials provided.

***WARNING***
```

But that probably isn't detailed enough. You need the server and a user as described, as well as the client libraries AND the python bindings. On ubuntu this is:

```
sudo apt-get install mysql-server
sudo apt-get install libmysqlclient-dev
```

I think the solution is for now to add a bit of documentation to the quickstart page about using mysql.

**Comment by scudette** [comment]
But there is no way for the user to install the python bindings since the virtual env cant see apt installed python code. We should probably build the deb with the python bindings installed into the virtual env but then they will just be disabled until the mysql client library is installed with apt.

**Comment by destijl** [comment]
If this was just a python dependency that would be fine, but the python won't install without the client libraries, so it's a deb dependency that needs to get added to the server deb, docker, travis, and the quickstart install script (and maybe some others I've forgotten). Each one of those we add makes it a little harder for people installing on redhat because they need to track down the equivalents, and a little slower/harder to set up a dev environment - pretty annoying for an optional part of the system.

Alternatively we could remove the datastore choice from the post install script, force you to run initialize with SQLite first, then re-run initialize with a --datastore=mysql flag to setup mysql once you have the server and client libraries installed. This seems slightly better to me: those who want to install mysql need to do slightly more manual installing, but there's no impact on everyone else.

**Comment by demonchild2112** [comment]
We've started working on making MySQL the default datastore for GRR. This issue falls within the scope of what we plan on addressing, so I'm closing it as a dup of #604.

**Comment by mbushkov** [comment]
JFYI: I think this was fixed. Current DEB package works fine with MySQL backend - we bring necessary Python libraries as DEB dependencies.
