### ISSUE TITLE
buildandrepack function does not use templates

### ISSUE THREAD

**Issue by jessicawilsonsc** [google/grr#409]
Referring to the conversation starting on Jun 30 in https://groups.google.com/forum/#!topic/grr-users/PUpiGT9zPuw

The buildandrepack command does not use the supplied templatedir, and will rebuild a template on the architecture running grr.

**Comment by destijl** [comment]
Please see the updated repacking instructions in the admin guide. You will need to break your buildconfig.yaml up into separate files, one per label.
