### ISSUE TITLE
Grr Client and PyInstaller issues

### ISSUE THREAD

**Issue by wspears** [google/grr#41]
All, 
I've gotten a Windows client build environment setup, however even after all build dependencies are satisfied, I'm still seeing an error after PyInstaller is invoked. 
Namely :
UnboundLocalError: local variable 'raw_val' referenced before assignment
Traceback (most recent call last):
  File ".\grr\client\client_build.py", line 188, in <module>
    flags.StartMain(main)
  File "C:\Users\Administrator\grr\lib\flags.py", line 107, in StartMain
    main([sys.argv[0]])
  File ".\grr\client\client_build.py", line 161, in main
    builder_obj.MakeExecutableTemplate()
  File "C:\Users\Administrator\grr\lib\builders\windows.py", line 114, in MakeExecutableTemplate
    self.BuildWithPyInstaller()
  File "C:\Users\Administrator\grr\lib\build.py", line 118, in BuildWithPyInstaller
    subprocess.check_call(cmd)
  File "C:\Python27\lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Python27\\python.exe', u'c:\\grr_build\\pyinstaller\\pyinstaller.py', '--d
istpath', u'./dist', u'./build\\grr.spec']' returned non-zero exit status 1

Digging into the PyInstaller versioninfo.py file, I see it hasn't had a commit against it in quite some time, but there is one comment. Another person encountered a similar error when using PyInstaler and a version file. 
So, I had some questions: 
1. Is there a known way to disable adding the version info for the GRR Client? 
2. What Version if PyInstaller are others using? is 2.1 "too new"?
3. Where is the .spec file? I was assuming I would encounter one at some point, but can't seem to find it. Are we passing anything in here that wouldn't be Unicode? 
4. Is anyone else currently building new GRR (windows) Client Versions on a routine basis? 

Appreciate your time on reading

**Comment by destijl** [comment]
Yep this is pyinstaller being broken.  The workaround is now in the build scripts:
https://github.com/google/grr/blob/0f40ce8827e7fe5894c6b49100a2792d7fa1130a/vagrant/windows/python_deps.bat#L16
