### ISSUE TITLE
Issue when I try to create my own flow

### ISSUE THREAD

**Issue by lorz** [google/grr#410]
Hi guys, I'll try to keep it short:

**\* CASE 1 ***

1) No docker image this time; GRR is installed with the supplied script in a Ubuntu 16.04 machine
2) As soon as the installer ends, I can launch the UI panel and fiddle with the environment
3) I go to -> /usr/share/grr-server/lib/python2.7/site-packages/grr/lib/flows/general and create my own flow; 1st I edit the registry_init.py file and call for "dummy" (I also remove the pyc file); then I create dummy.py file with the code supplied (and cleaned) as in "AnalyzeClientMemory" sample.
4) As I don't know if there are any other dependencies, I reboot the whole system. Get in prompt again and now the server doesn't start. Service is stopped and the port 8000 obviously doesn't exist.

The only log I can get is this (taken from grr-ui.log):

ERROR:2016-07-08 11:48:00,027 config_lib:216] Distribution grr-response-test not found. Is it installed?
ERROR:2016-07-08 11:48:00,052 config_lib:216] Distribution grr-response-test not found. Is it installed?
ERROR:2016-07-08 11:48:00,228 config_lib:216] Distribution grr-response-test not found. Is it installed?

The other files are empty.

So, now the questions:

1) How can I restart the services without rebooting the system? just to be sure I'm doing things right.

2) What am I missing here when I try to make my own flow? there's someting weird here...

**\* CASE 2 **\* (with docker) in the next post...

**Comment by grrrrrrrrr** [comment]
Follow the dev instructions at https://github.com/google/grr-doc/blob/master/installfrompip.adoc

Once you have done that, you should be able to change code and start services using the grr_<component> entry points to see what's going on. No need to reboot for code changes...

**Comment by lorz** [comment]
*** CASE 2 ***

1) I (succesfully) deploy the container and log into the admin console. The artifact manager throws an exception but I don't care about it for this case: FYI [artifact-error.txt](https://github.com/google/grr/files/354098/artifact-error.txt)

2) I edit, as in the previous case, the registry_init.py file and add my own flow. I restart the instance and it throws the following error:

3) Now I can't open the container again nor start the server.

***Editing....

**Comment by lorz** [comment]
Hi @grrrrrrrrr, now I get the following errors:

(GRR_ENV) luis@GRR:~/GRR_ENV/lib/python2.7/site-packages/grr/lib/flows/general$ grr_server
Traceback (most recent call last):
  File "/home/luis/GRR_ENV/bin/grr_server", line 11, in <module>
    sys.exit(GrrServer())
  File "/home/luis/GRR_ENV/local/lib/python2.7/site-packages/grr/lib/distro_entry.py", line 80, in GrrServer
    from grr.tools import grr_server
  File "/home/luis/GRR_ENV/local/lib/python2.7/site-packages/grr/tools/grr_server.py", line 11, in <module>
    from grr.lib import server_plugins
  File "/home/luis/GRR_ENV/local/lib/python2.7/site-packages/grr/lib/server_plugins.py", line 33, in <module>
    from grr.lib.flows.general import registry_init
  File "/home/luis/GRR_ENV/local/lib/python2.7/site-packages/grr/lib/flows/general/registry_init.py", line 37, in <module>
    from grr.lib.flows.general import kk
  File "/home/luis/GRR_ENV/local/lib/python2.7/site-packages/grr/lib/flows/general/kk.py", line 1, in <module>
    class Kk(flow.GRRFlow):
NameError: name 'flow' is not defined
(GRR_ENV) luis@GRR:~/GRR_ENV/lib/python2.7/site-packages/grr/lib/flows/general$

And this is the dummy code:

class Kk(flow.GRRFlow):
  """No hago nada."""

  category = "/Pruebas/"

  @flow.StateHandler(next_state=["Fin"])
  def Start(self):
    self.Notify("ViewObject", self.device_urn,"Funcion START.")

  def Fin(self):
    self.Notify("ViewObject", self.device_urn,"Funcion FIN.")


Any comment would be helpful... Thanks!

**Comment by grrrrrrrrr** [comment]
This is a standard Python error, you need to import modules before you use them. Example: https://github.com/google/grr/blob/master/grr/lib/flows/general/administrative.py#L20

**Comment by lorz** [comment]
Still nothing. I've just created a simple hello-world pyhton file in flows folder and this is the result:

> Traceback (most recent call last):
>   File "/usr/share/grr-server//bin/grr_server", line 11, in <module>
>     sys.exit(GrrServer())
>   File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/distro_entry.py", line 82, in GrrServer
>     flags.StartMain(grr_server.main)
>   File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flags.py", line 121, in StartMain
>     main([sys.argv[0]])
>   File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/tools/grr_server.py", line 31, in main
>     if flags.FLAGS.component.startswith("worker"):
> AttributeError: 'NoneType' object has no attribute 'startswith'

In addition, I've installed a GRR client into a virtualized Win7 (x86) and can't find it, neither by its ip address nor machine name. Of course, firewall is disabled and both machines can view each other.

Thank you.

**Comment by destijl** [comment]
For the client problems follow the troubleshooting steps:
https://github.com/google/grr-doc/blob/master/troubleshooting.adoc#i-dont-see-my-clients

The backtrace shows you aren't calling with the correct parameters. You should just source the virtualenv and run

```
grr_worker --verbose
```

or similar.
