### ISSUE TITLE
Account created during approval process

### ISSUE THREAD

**Issue by jessicawilsonsc** [google/grr#413]
A new account is created during the approval process if it didn't exist before.

Example: 
User Jessica is requesting access for a client from user Bob. Bob is not a currently valid user on GRR. `grr_config_updater show_user` does not display the name "Bob". Jessica requests access for client putting "Bob" into the approvers field on the Authorization Required modal on the Admin UI. `grr_config_updater show_user` now displays the name "Bob" with no labels set and no password set.

**Comment by grrrrrrrrr** [comment]
Thanks for reporting this! Fixed via 93192b41650f552b6b295dde5cbbcd2b12e44099
