### ISSUE TITLE
Agent and server cant communicate

### ISSUE THREAD

**Issue by NisaTurkmen** [google/grr#415]
I downloaded the **grr_3.1.0.2_amd64.exe** for windows and run as administrator but it can't connect the GRR UI. How can i solve this problem ? If i look the grr_installer.txt file i get this message.

Loading configuration from GRR.exe.yaml
Loading configuration from build.yaml
Starting installation procedure for GRR client.
Initializing Installer
Initializing CheckForWow64, required by CopyToSystemDir
Initializing CopyToSystemDir
Attempting to stop service GRR Monitor
Applying filter env for SystemRoot.
Installing binaries C:\Users\ADMINI~1\AppData\Local\Temp\TMPA25E.tmp -> C:\Windows\System32\GRR\3.1.0.2
Initializing UpdateClients
Loading configuration from reg://HKEY_LOCAL_MACHINE/Software\GRR
Configuration writeback is set to reg://HKEY_LOCAL_MACHINE/Software\GRR
mapping HKEY_LOCAL_MACHINE\Software\GRR\certificate->Client.private_key ignored: [Error 2] The system cannot find the file specified
mapping HKEY_LOCAL_MACHINE\Software\GRR\Client\private_key->Client.private_key ignored: [Error 2] The system cannot find the file specified
mapping HKEY_LOCAL_MACHINE\Software\GRR\server_serial_number->Client.server_serial_number ignored: [Error 2] The system cannot find the file specified
Writing back configuration to key \Software\GRR
Initializing WindowsInstaller
Loading configuration from reg://HKEY_LOCAL_MACHINE/Software\GRR
Configuration writeback is set to reg://HKEY_LOCAL_MACHINE/Software\GRR
Applying filter env for SystemRoot.
Writing back configuration to key \Software\GRR
Calling ([u'C:\Windows\System32\GRR\3.1.0.2\GRRservice.exe', '--service_key', u'Software\GRR', 'install'],)
(null)
Stopping Service
Service is already stopped.
Service: GRR Monitor started as: C:\Windows\System32\GRR\3.1.0.2\GRRservice.exe

**Comment by Dymo28** [comment]
https://github.com/google/grr-doc/blob/master/troubleshooting.adoc#i-dont-see-my-clients

Have you given this page a go? I know it helped me when I was having issues connecting them.

**Comment by grrrrrrrrr** [comment]
Sorry we missed this one. The installer log looks fine, did you figure this out in the end or is there anything we can still help with?
