### ISSUE TITLE
Debian client won't package version 3.1.0.2

### ISSUE THREAD

**Issue by seasalt7** [google/grr#417]
Recently downloaded version 3.1.0.2, did a clean install, and began testing and everything looked ok. We have Mac and Windows machines that can connect ok. Moved on to testing Linux and the Debian client wasn't in the list of executables to download from the console. Tried repacking the clients and they all work except Debian, with the below errors. Have verified that debian/rules is executable.

Repacking template: /usr/share/grr-server/grr-response-templates/templates/grr_3.1.0.2_amd64.deb.zip
ERROR:2016-07-26 08:58:13,612 build:705] Error calling ['/usr/bin/dpkg-buildpackage', '-uc', '-d', '-b', u'-aamd64'].
ERROR:2016-07-26 08:58:13,615 build:706] dpkg-buildpackage: source package grr
dpkg-buildpackage: source version 3102-1
dpkg-buildpackage: source distribution unstable
dpkg-buildpackage: source changed by GRR <grr-dev@googlegroups.com>
dpkg-buildpackage: warning: debian/rules is not executable; fixing that
 dpkg-source --before-build dist
dpkg-buildpackage: host architecture amd64
 debian/rules clean
Can't exec "debian/rules": Permission denied at /usr/bin/dpkg-buildpackage line 659.
dpkg-buildpackage: error: debian/rules clean failed with unknown exit code -1

Repacking template /usr/share/grr-server/grr-response-templates/templates/grr_3.1.0.2_amd64.deb.zip failed: Command '['/usr/bin/dpkg-buildpackage', '-uc', '-d', '-b', u'-aamd64']' returned non-zero exit status 13
Failed to repack /usr/share/grr-server/grr-response-templates/templates/grr_3.1.0.2_amd64.deb.zip.
Repacking template: /usr/share/grr-server/grr-response-templates/templates/grr_3.1.0.2_i386.deb.zip
ERROR:2016-07-26 08:58:14,715 build:705] Error calling ['/usr/bin/dpkg-buildpackage', '-uc', '-d', '-b', u'-ai386'].
ERROR:2016-07-26 08:58:14,718 build:706] dpkg-buildpackage: source package grr
dpkg-buildpackage: source version 3102-1
dpkg-buildpackage: source distribution unstable
dpkg-buildpackage: source changed by GRR <grr-dev@googlegroups.com>
dpkg-architecture: warning: specified GNU system type i686-linux-gnu does not match CC system type x86_64-linux-gnu, try setting a correct CC environment variable
dpkg-buildpackage: warning: debian/rules is not executable; fixing that
 dpkg-source --before-build dist
dpkg-buildpackage: host architecture i386
 debian/rules clean
Can't exec "debian/rules": Permission denied at /usr/bin/dpkg-buildpackage line 659.
dpkg-buildpackage: error: debian/rules clean failed with unknown exit code -1

Repacking template /usr/share/grr-server/grr-response-templates/templates/grr_3.1.0.2_i386.deb.zip failed: Command '['/usr/bin/dpkg-buildpackage', '-uc', '-d', '-b', u'-ai386']' returned non-zero exit status 13
Failed to repack /usr/share/grr-server/grr-response-templates/templates/grr_3.1.0.2_i386.deb.zip.

**Comment by destijl** [comment]
I've repacked 3102 lots of times and haven't seen this. Perhaps the directory where your source is has been mounted with noexec?

**Comment by seasalt7** [comment]
Thank you, I will give that a shot.

**Comment by seasalt7** [comment]
Setting /tmp to exec fixed the issue.

**Comment by mbushkov** [comment]
I see `make: dh: Command not found` in your output. This is likely the issue. Does installing dh-make package (`sudo apt-get install dh-make`) help?
