### ISSUE TITLE
Make client version visible in client search results

### ISSUE THREAD

**Issue by pidydx** [google/grr#42]
This is just a small wish list for tracking, and I think some of these are already coming.  
1.  Agent versions displayed and searchable. (3000, 3003, etc)
2.  Sortable columns
3.  Pagination for results over 50
4.  Label removal (Making the label displays in each row clickable for removal might work well)

**Comment by destijl** [comment]
We think we should:

Put the version in the main list, it's very useful.
Add info icon that pops modal dialog with detailed client info, not requiring approval.
When requesting client approval you should also be able to see the detailed client information.

**Comment by destijl** [comment]
We have finished 3 and 4 from the original list. I'm going to rename this to cover the agent version issue.

**Comment by destijl** [comment]
Versions are in search results.
