### ISSUE TITLE
Rekall component 1.5.3 doesn't load on OS X

### ISSUE THREAD

**Issue by destijl** [google/grr#421]

**Comment by nacazzaro** [comment]
Anyone has a solution for this?

**Comment by zbuc** [comment]
I am also having difficulty with Rekall I haven't had time to debug yet.

All I know so far is that when I run a memory acquisition flow, the status is listed as successful, however no results are ever returned.

**Comment by grrrrrrrrr** [comment]
We now use Rekall 1.6.0. I'm afraid Rekall on OSX is still broken and we probably won't have time to fix it at this point but this issue is obsolete.
