### ISSUE TITLE
AnalyzeClientMemory Flow & OS compatibility Issue

### ISSUE THREAD

**Issue by hkshin98** [google/grr#427]
I tested the AnalyzeClientMemory flow in two client environments - windows7(en-us) and windows7(korean)

The execution results of the flow proceed as follows.
- windows7(en-us) : Error(no), results(yes)
- windows7(korean) : Error(no), results(no)

Is "the AnalyzeClientMemory flow" affected by client's os language?

**Comment by grrrrrrrrr** [comment]
sorry for the late reply. This seems like a rekall problem to me. Could you maybe try to run rekall directly on the korean windows machine and see if it works without grr? Also, could you rerun the AnalyzeClientMemory flow with debug logging enabled and post the output? Maybe there is something in there...

**Comment by grrrrrrrrr** [comment]
I'll assume this was a profile issue (as in #425).
