### ISSUE TITLE
Ubuntu 12.04 Can't Install From QuickInstall

### ISSUE THREAD

**Issue by mkunz7** [google/grr#43]
Using the quick install script and commenting out --pre during the rekall install. Causes an error on grr deb installation.

ImportError: cannot import name message_factory

Installing protobuf from source or packages allows it to finish, but when you go to the web server I get this message.

"A server error occurred. Please contact the administrator."

**Comment by akpotter** [comment]
My solution:
Simple hack in 12.04 (Update python protobuf in 12.04) :

1. sudo pip install protobuf --upgrade
2. sudo cp -R /usr/local/lib/python2.7/dist-packages/google/protobuf /usr/lib/python2.7/dist-packages/google/protobuf

Then you can use "sudo bash install_script_ubuntu.sh".
