### ISSUE TITLE
[RFC] Ansible role grr

### ISSUE THREAD

**Issue by juju4** [google/grr#432]
Hello,

Just to inform you that I have a role to deploy grr available.
Continuous integration is available through kitchen/vagrant, kitchen/lxd (preferred) and travis (with glitches)
It also include a packer config
https://github.com/juju4/ansible-grr

I did it initially a while ago and refreshed it more recently.
It's not perfect but usable.
Target systems are xenial (deb), trusty and centos7 (pip)

One remark, I did not find a way to automate initialize.
I push a template of server.local.yaml, do a 'grr_config_updater generate_keys --overwrite'
sadly the latter reset the files instead of updating only keys field.
Ideally keys are generated into a separate file
Any advices to automate this part of the configuration? any existing options?

Thanks

**Comment by pidydx** [comment]
When I was deploying with Chef we just templated server.local.yaml after an initialize and used a MySQL datastore that had been initialized.  It was primarily used for software management and scaling the GRR server cluster rather than end to end deployment.  We could tear down all the GRR servers and redeploy them or easily push code changes to all of them.

**Comment by scudette** [comment]
You can use the "filename|file" filter on any configuration parameter to
read that value from an external file.

**Comment by juju4** [comment]
Thanks for the quick feedback Sean!

I did the same
https://github.com/juju4/ansible-grr/blob/master/templates/server.local.yaml

but after for each setup you generate new keys, right and this command is not preserving other fields.
Ansible for now has no official module to edit yaml fine so it would be a lineinfile/replace modifications to fix contents.
That's why I was suggesting separating content.
new setup = new keys
for the rest = template

configuration process is here
https://github.com/juju4/ansible-grr/blob/master/tasks/grr-configure.yml

@scudette 
when you talk about "filename|file" filter, you are talking on grr command or ipython option? or ansible or other?
example command? googling got mostly java stuff

**Comment by scudette** [comment]
When you write the config file you can add a filter to the value and then the config system will use the filter to interpolate the value when the program wants to use it.

So if you want to have say "PrivateKeys.server_key" in an external file you do:

```
PrivateKeys.server_key: "myfilename.pem|file"
```

Then you can use some other way to create the file different on each instance.

Also you can include another config file as part of the main config file by adding:

```
Config.includes:
     - file1.yaml
```
and the extra file will be included over the top of the main config file. The included file in this second case is a yaml config file and will override any setting.

**Comment by juju4** [comment]
Ah! that seems the perfect option :)
Thanks @scudette !
