### ISSUE TITLE
Error running AnalyzeClientMemory "pslist" plugin: Client action u'RekallAction' not known

### ISSUE THREAD

**Issue by zbuc** [google/grr#433]
Getting this error in the server logs when I try running an `AnalyzeClientMemory` flow while specifying the `pslist` plugin:

```
ERROR:2016-09-12 18:17:55,761 flow_runner:618] Flow aff4:/C.c6259a0da13eab27/flows/F:8E4F11AB raised Error running plugins: Client action u'RekallAction' not known.
Traceback (most recent call last):
  File "/home/grr_user/GRR_NEW/local/lib/python2.7/site-packages/grr/lib/flow_runner.py", line 603, in RunStateMethod
    direct_response=direct_response, request=request, responses=responses)
  File "/home/grr_user/GRR_NEW/local/lib/python2.7/site-packages/grr/lib/flow.py", line 303, in Decorated
    res = f(*args[:f.func_code.co_argcount])
  File "/home/grr_user/GRR_NEW/local/lib/python2.7/site-packages/grr/lib/flows/general/memory.py", line 271, in End
    raise flow.FlowError("Error running plugins: %s" % all_errors)
FlowError: Error running plugins: Client action u'RekallAction' not known
ERROR:2016-09-12 18:17:55,813 flow_runner:937] Error in flow aff4:/C.c6259a0da13eab27/flows/F:8E4F11AB (aff4:/C.c6259a0da13eab27). Trace: Traceback (most recent call last):
  File "/home/grr_user/GRR_NEW/local/lib/python2.7/site-packages/grr/lib/flow_runner.py", line 603, in RunStateMethod
    direct_response=direct_response, request=request, responses=responses)
  File "/home/grr_user/GRR_NEW/local/lib/python2.7/site-packages/grr/lib/flow.py", line 303, in Decorated
    res = f(*args[:f.func_code.co_argcount])
  File "/home/grr_user/GRR_NEW/local/lib/python2.7/site-packages/grr/lib/flows/general/memory.py", line 271, in End
    raise flow.FlowError("Error running plugins: %s" % all_errors)
FlowError: Error running plugins: Client action u'RekallAction' not known
```

**Comment by grrrrrrrrr** [comment]
Hm something went wrong when loading the component. What OS is you client? What version are you running (server and client)?

**Comment by zbuc** [comment]
OS X 10.11.6 client

Server is running checkout 85d29757e2eba0ee26ab6835617e5d39beb6985f from git

Client is running the `3.1.0.2_amd64` binary.

Do I have to do anything special to rebuild the OS X binaries with Rekall support?

I also have a few off-topic questions about updating (maybe these could be addressed in docs/FAQ somewhere, I didn't see it anywhere):

Does the GRR client have auto-updating built in?
When is it necessary to update the GRR client?

Thanks!

**Comment by grrrrrrrrr** [comment]
Sorry I looked into this yesterday but forgot to update this bug. This is actually a server side problem, the next code push will contain a fix. Sadly, the current Rekall OSX support is not great -  there are some profiles missing - but you should at least be able to run Rekall and try.

**Comment by zbuc** [comment]
I receive a stack trace now (on e3495c614102b122bc41ea03b1f8864565c3faef)

```
Traceback (most recent call last):
  File "/home/grr_user/grr/grr/gui/http_api.py", line 440, in HandleRequest
    rendered_data = self.CallApiHandler(handler, args, token=token)
  File "/home/grr_user/grr/grr/gui/http_api.py", line 193, in CallApiHandler
    result = handler.Handle(args, token=token)
  File "/home/grr_user/grr/grr/gui/api_plugins/flow.py", line 957, in Handle
    runner_args=args.flow.runner_args)
  File "/home/grr_user/grr/grr/lib/flow.py", line 632, in StartFlow
    flow_obj.Start()
  File "/home/grr_user/grr/grr/lib/flow.py", line 306, in Decorated
    res = f(*args[:f.func_code.co_argcount])
  File "/home/grr_user/grr/grr/lib/flows/general/memory.py", line 133, in Start
    next_state="StartAnalysis")
  File "/home/grr_user/grr/grr/lib/flows/general/transfer.py", line 912, in LoadComponentOnClient
    request_data=request_data)
  File "/home/grr_user/grr/grr/lib/flow.py", line 725, in CallStateInline
    getattr(self, next_state)(self.runner, direct_response=responses)
  File "/home/grr_user/grr/grr/lib/flow.py", line 289, in Decorated
    return f(self, direct_response)
  File "/home/grr_user/grr/grr/lib/flows/general/transfer.py", line 944, in LoadComponentAfterFlushOldComponent
    raise IOError("Required component not found: %s" % e)
IOError: Required component not found: Object aff4:/config/components/grr-rekall_1.5.3 is of type AFF4Volume, but required_type is ComponentObject
```

**Comment by scudette** [comment]
This means you did not upload the component to the data store. Use the
grr_config_updater with upload_component to upload it.

**Comment by zbuc** [comment]
It's not clear to me from the documentation where to get the component from.

I see in the components readme that there's a `client_build.py` script: https://github.com/google/grr/blob/master/grr/client/components/README.txt#L96 that can build the component.

However, I don't see any way of specifying which platform to build the component for: https://github.com/google/grr/blob/5c7d3b6d99ad14a29c506308d571412c8fe83c3d/grr/lib/builders/component.py#L231

Can the components be cross-compiled from Linux, or do I need an OS X system to build the Rekall component for OS X endpoints?

**Comment by scudette** [comment]
No the components must be built on the target system.

The directions are here:
https://github.com/google/grr-doc/blob/master/installfrompip.adoc

basically once the grr-response-template package is installed the
components are in there. You just re-upload them. You can do it
separately or if you just grr_config_updater initialize it will
re-upload the templates and components for you in one go.

**Comment by zbuc** [comment]
There was an issue in `config_updater.py` that kept me from running it with my `python2.7` interpreter. I made a quick patch for my purposes but I'm not sure what your upstream fix should be:

```
   virtualenv_bin = os.path.dirname(sys.executable)
   extension = os.path.splitext(sys.executable)[1]
-  pip = "%s/pip%s" % (virtualenv_bin, extension)
+  pip = virtualenv_bin + "/pip"
```

I have the components uploaded now, but receive a 404 when they try downloading:

`Component Loading failed: RuntimeError(u'Error 404 while downloading component /static/components/57e32143930afde3/cp27-cp27m-macosx_10_8_x86_64.',): Error 404 while downloading component /static/components/57e32143930afde3/cp27-cp27m-macosx_10_8_x86_64.`

It looks like it's missing the extension?

**Comment by zbuc** [comment]
The log output from running the `grr_config_updater initialize` command had a different hash in the aff4 path from what the client tried to load: `Storing signed component at aff4:/web/static/components/57a3ffbe632517a4/cp27-cp27m-macosx_10_8_x86_64`

**Comment by zbuc** [comment]
Still having this issue with the mismatch between the paths, any ideas?

**Comment by grrrrrrrrr** [comment]
Hm are you sure you are using the same component versions? There is a field
in the advanced section of AnalyzeClientMemory that lets you specify which
version you want to use. Also, you can use grr_config_updater
list_components to see which versions of each component are available. Hope
that helps!

Cheers,
-Andy

**Comment by zbuc** [comment]
I see the same behavior when trying to run the Memory Collector flow which doesn't seem to have the component version field available.

```
$ grr_config_updater list_components
Using configuration <GrrConfigManager  file="/home/grr_user/grr/install_data/etc/grr-server.yaml"  file="/home/grr_user/grr/install_data/etc/server.local.yaml" >
* Component grr-rekall (version 1.5.2.post1)
Available platform signatures:
- cp27-cp27mu-linux_x86_64
* Component grr-chipsec-component (version 1.2.2.2)
Available platform signatures:
- cp27-cp27mu-linux_x86_64
* Component grr-chipsec-component (version 1.2.4.1)
Available platform signatures:
- cp27-cp27mu-linux_x86_64
* Component grr-rekall (version 0.4)
Available platform signatures:
- cp27-cp27m-macosx_10_8_x86_64
- cp27-cp27m-win32
- cp27-cp27m-win_amd64
- cp27-cp27mu-linux_i686
- cp27-cp27mu-linux_x86_64
* Component grr-chipsec-component (version 1.2.2)
Available platform signatures:
- cp27-cp27m-macosx_10_8_x86_64
- cp27-cp27m-win32
- cp27-cp27m-win_amd64
- cp27-cp27mu-linux_i686
- cp27-cp27mu-linux_x86_64
* Component grr-test-component (version 1.0)
Available platform signatures:
- cp27-cp27m-macosx_10_8_x86_64
- cp27-cp27m-win32
- cp27-cp27m-win_amd64
- cp27-cp27mu-linux_i686
- cp27-cp27mu-linux_x86_64
* Component grr-rekall (version 1.5.3)
Available platform signatures:
- cp27-cp27mu-linux_x86_64
```

I tried running the `AnalyzeClientMemory` flow with the version field set to 0.4 and it did run on the client, but the results didn't come through... I think that might be due to a firewall configuration on my end:

```
Traceback (most recent call last):
  File "/home/grr_user/grr/grr/lib/flow_runner.py", line 637, in RunStateMethod
    direct_response=direct_response, request=request, responses=responses)
  File "/home/grr_user/grr/grr/lib/flow.py", line 306, in Decorated
    res = f(*args[:f.func_code.co_argcount])
  File "/home/grr_user/grr/grr/lib/flows/general/memory.py", line 207, in StoreResults
    response.repository_version)
  File "/home/grr_user/grr/grr/lib/flows/general/memory.py", line 302, in GetProfileByName
    return profile_server.GetProfileByName(name, version=version)
  File "/home/grr_user/grr/grr/lib/rekall_profile_server.py", line 77, in GetProfileByName
    profile_name, version=version)
  File "/home/grr_user/grr/grr/lib/rekall_profile_server.py", line 93, in GetProfileByName
    handle = urllib2.urlopen(url, timeout=10)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1242, in https_open
    context=self._context)
  File "/usr/lib64/python2.7/urllib2.py", line 1199, in do_open
    raise URLError(err)
URLError: <urlopen error timed out>
```

**Comment by zbuc** [comment]
If I first run the `AnalyzeClientMemory` flow with the version manually set to 0.4, then try running the `Memory Collector` flow, I wind up receiving a message in the client log:

    2016-12-01 15:48:22,413:ERROR:root:Component grr-rekall is already loaded at version 0.4. Exiting!

and then the client kills itself.

**Comment by grrrrrrrrr** [comment]
The first error is that you don't have the profile needed stored on your
server. It tried to get it from the repository but fails. You can just
download all profiles to your server using
config_updater download_missing_rekall_profiles (on a machine with internet
access). See also
https://github.com/google/grr-doc/blob/master/troubleshooting.adoc#missing-rekall-profiles


The second behavior is intended. A client can only have one component
version loaded at a time so if you request a component that is different to
the currently loaded one, it will restart to get rid of the old one. It
should just come back after some time and continue with the flow.

**Comment by zbuc** [comment]
I fixed the first error by opening up outbound connections to GitHub's IP block on my GRR worker server (https://help.github.com/articles/what-ip-addresses-does-github-use-that-i-should-whitelist/), where the Rekall components are hosted.

I can't manage to make `Memory Collector` run with version 0.4 though, since it doesn't have a version advanced configuration like the `AnalyzeClientMemory` flow does. It seems to default to 1.5.3 which isn't available for OS X as far as I can tell?

**Comment by zbuc** [comment]
I spoke too soon re: the first issue, the URLError is gone but now the client reports back a `2016-12-01 16:34:21,544:ERROR:rekall.3:No profiles match this image. Try specifying manually.` message. This happens when trying to run a plugin like `psaux` that should run on OS X.

I tried running the `grr_config_updater download_missing_rekall_profiles` command but am receiving an error that I need to supply an authorization token:

```
$ grr_config_updater download_missing_rekall_profiles
Using configuration <GrrConfigManager  file="/home/grr_user/grr/install_data/etc/grr-server.yaml"  file="/home/grr_user/grr/install_data/etc/server.local.yaml" >
Downloading missing Rekall profiles.
Traceback (most recent call last):
  File "/home/grr_user/GRR_NEW/bin/grr_config_updater", line 11, in <module>
    load_entry_point('grr-response-server', 'console_scripts', 'grr_config_updater')()
  File "/home/grr_user/grr/grr/lib/distro_entry.py", line 76, in ConfigUpdater
    flags.StartMain(config_updater.main)
  File "/home/grr_user/grr/grr/lib/flags.py", line 112, in StartMain
    main([sys.argv[0]])
  File "/home/grr_user/grr/grr/tools/config_updater.py", line 910, in main
    s.GetMissingProfiles()
  File "/home/grr_user/grr/grr/lib/rekall_profile_server.py", line 157, in GetMissingProfiles
    for metadata in aff4.FACTORY.Stat(urn_to_profile):
  File "/home/grr_user/grr/grr/lib/aff4.py", line 894, in Stat
    urns, ["aff4:type", "metadata:last"], token=token):
  File "/home/grr_user/grr/grr/lib/data_stores/mysql_advanced_data_store.py", line 279, in MultiResolvePrefix
    limit=limit)
  File "/home/grr_user/grr/grr/lib/data_stores/mysql_advanced_data_store.py", line 299, in ResolvePrefix
    token, [subject], self.GetRequiredResolveAccess(attribute_prefix))
  File "/home/grr_user/grr/grr/lib/aff4_objects/user_managers.py", line 45, in Decorated
    result = func(this, token, *args, **kwargs)
  File "/home/grr_user/grr/grr/lib/aff4_objects/user_managers.py", line 299, in CheckDataStoreAccess
    ValidateToken(token, subjects))
  File "/home/grr_user/grr/grr/lib/aff4_objects/user_managers.py", line 129, in ValidateToken
    subject=GetSubjectForError())
grr.lib.access_control.UnauthorizedAccess: Must give an authorization token for [<aff4:/rekall_profiles/v1.0/nt/GUID/DFEF9132713A43689FC9FB795CC7567E2 age=2016-12-01 21:52:06>]
```

I have two questions:

1) is there an OS X Rekall 1.5.3 component available for GRR? I didn't see it in the template tarball
2) how do I get the correct profile loaded and working?

**Comment by grrrrrrrrr** [comment]
There might be no profile on the rekall profile server either. Do you know which one you need? You can enable debug logging when running the flow, it will show which profiles the client requests...

Lately, Rekall support for MacOS was a bit lacking. There is just nobody really working on it and the kernel keeps changing a lot so I would not be surprised if there was no profile available. If you provide info about which profile you need, maybe Michael can help.

Oh and that backtrace you got is actually a bug, I'll send a fix soon.

**Comment by grrrrrrrrr** [comment]
https://github.com/google/grr/commit/6ee1c18e64ccb03c24d1a4c1140563ca16b613ae should fix the download_missing_rekall_profiles issue.

**Comment by zbuc** [comment]
Thank you!

We got a bit further, however we are seeing two problems we don't know how to resolve correctly.

1) the `client.build_environment` was set to `cp27-cp27m-macosx_10_8_x86_64` but we expected `cp27-cp27m-macosx_10_12_intel`. I have run `grr_config_updater initialize` and had it repackage all the clients, and reinstalled it, but the `build_environment` in `/usr/local/lib/grr/grr_3.1.0.2_amd64/build.yaml` and `/usr/local/lib/grr/grr_3.1.0.2_amd64/installer_config.yaml` on my client was still for 10.8.

I manually edited the two yaml files on my client and was able to successfully pull down the component, but need to know how to properly repackage the client for distribution with the right build environment.

Also, does this mean we need to reinstall GRR whenever there is a new OS X update?

2) The rekall component itself crashed after running because it can't import the `rekall_pb2` module. I searched the source code and don't see it defined anywhere.

```
DEBUG:2016-12-23 15:44:25,552 actions:176] Traceback (most recent call last):
  File "site-packages/grr/client/actions.py", line 149, in Execute
  File "site-packages/grr/client/client_actions/components.py", line 212, in Run
  File "site-packages/grr/client/client_actions/components.py", line 105, in LoadComponent
  File "importlib/__init__.py", line 37, in import_module
  File "/usr/local/lib/grr/grr_3.1.0.2_amd64/components/grr-rekall/1.6.0/grr_rekall.py", line 31, in <module>
    import rekall_types
  File "/usr/local/lib/grr/grr_3.1.0.2_amd64/components/grr-rekall/1.6.0/rekall_types.py", line 9, in <module>
    import rekall_pb2
ImportError: No module named rekall_pb2
```

**Comment by grrrrrrrrr** [comment]
Rekall support was dropped from GRR, in part because of issues like this one. Obsolete.
