### ISSUE TITLE
LDAP Authentication Integration

### ISSUE THREAD

**Issue by theshades** [google/grr#434]
Since this is acting as forensics platform, ability to allow LDAP to handle user auth would be super handy, or giving a guide to have apache do it for you.

**Comment by destijl** [comment]
We don't do this internally, and it's a lot of work to go to documenting something we will never use ourselves. Even if we did that we likely wouldn't flush out most of the real-world problems just setting it up once in a test environment. Happy to accept contributions to the documentation.
