### ISSUE TITLE
Accessing re-enrolled client results in InstantiationError type error after removal

### ISSUE THREAD

**Issue by zbuc** [google/grr#444]
We had been testing GRR and accumulated about 30 GB of data and decided to clean out our data.

I saw a method in the documentation for "clearing a client and all their data" which seemed like what we wanted, so I used `grr_console` to run the following:

```
i = aff4.FACTORY.Create(rdfvalue.RDFURN("aff4:/client_index"), aff4_type=client_index.ClientIndex)
for client_id in i.ReadClientPostingLists("")["."]:
    print "Deleting ", client_id
    aff4.FACTORY.Delete(rdf_client.ClientURN(client_id))
```

After it completed, when clicking in clients in the UI, I receive the following error:

```
Traceback (most recent call last):
  File "/home/grr_user/grr/grr/gui/http_api.py", line 440, in HandleRequest
    rendered_data = self.CallApiHandler(handler, args, token=token)
  File "/home/grr_user/grr/grr/gui/http_api.py", line 193, in CallApiHandler
    result = handler.Handle(args, token=token)
  File "/home/grr_user/grr/grr/gui/api_plugins/client.py", line 200, in Handle
    args.client_id, aff4_type=aff4_grr.VFSGRRClient, age=age, token=token)
  File "/home/grr_user/grr/grr/lib/aff4.py", line 790, in Open
    (urn, result.__class__.__name__, aff4_type.__name__))
InstantiationError: Object aff4:/C.13fe56818f04b5c2 is of type AFF4Volume, but required_type is VFSGRRClient
```

How can I get them back in a working state? What happened exactly to cause this type confusion error?

Thanks!

**Comment by zbuc** [comment]
Additionally, after running the deletion script we didn't really see any reduction in size of the `aff4` table (using the MySQLDataStore backend).

Is there a better way to remove unneeded data? What is the procedure to remove data from GRR after an IR has been conducted?

**Comment by scudette** [comment]
whats happening here is that the client index contains these clients but the data is missing for them. You deleted the client records but not the index itself.

If the clients are still alive they will re-enroll and the client record will be rebuilt in time.

**Comment by scudette** [comment]
The client records do not contain much data - when you grab a file with GRR it puts the file in the file store (aff4:/blob/ area) stored by hash and the files written in the client's area just refer to these hashes. This is how we do file de-duplication. I don't imagine that deleting the client records will reduce total space usage much. Probably deleting the blobs will show better reduction.

**Comment by zbuc** [comment]
After rebooting the grr client on one of them it re-renrolled successfully, thanks!

Do you have a recommendation on how to delete the blobs? A quick search of the docs isn't showing much.

**Comment by destijl** [comment]
I think this is done, re-open if not.
