### ISSUE TITLE
"Download" button missing after downloading file from volume snapshot

### ISSUE THREAD

**Issue by joachimmetz** [google/grr#446]
"Download" button missing on "download tab" after downloading file from volume snapshot

Feel free to ping me on chat if you need more details

work around: download from results

**Comment by joachimmetz** [comment]
Per chat will follow up with @mbushkov

**Comment by grrrrrrrrr** [comment]
Is this still a problem?

**Comment by joachimmetz** [comment]
I don't recall, I'll close it out. I'll file a new issue / reopen if I encounter this again.
