### ISSUE TITLE
MemoryCollector Flow Failing (Temporary failure in name resolution)

### ISSUE THREAD

**Issue by James-Hall** [google/grr#448]
I am attempting to run the MemoryCollector flow on a Win7 x64 virtual machine. The host and GRR server are in the same isolated network with no other devices.

The agent has installed correctly and I can run other flows (netstat etc.) but every time I attempt to run the MemoryCollector flow it fails with the following log.

`Traceback (most recent call last): File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flow_runner.py", line 613, in RunStateMethod responses=responses) File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flow.py", line 353, in Decorated res = f(*args[:f.func_code.co_argcount]) File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flows/general/memory.py", line 93, in CheckAnalyzeClientMemory raise flow.FlowError("Unable to image memory: %s." % responses.status) FlowError: Unable to image memory: message GrrStatus { child_session_id : SessionID: aff4:/C.01b40726fe6d7f77/flows/F:EBE42AC8/F:B4DE2DA5 cpu_time_used : message CpuSeconds { system_cpu_time : 0.0 user_cpu_time : 0.0 } error_message : u'Traceback (most recent call last):\n File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flow_runner.py", line 613, in RunStateMethod\n responses=responses)\n File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flow.py", line 353, in Decorated\n res = f(*args[:f.func_code.co_argcount])\n File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flows/general/memory.py", line 141, in ComponentLoaded\n self.CallStateInline(next_state=responses.request_data["next_state"])\n File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flow.py", line 774, in CallStateInline\n getattr(self, next_state)(self.runner, direct_response=responses)\n File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flow.py", line 331, in Decorated\n return f(self, direct_response)\n File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flows/general/memory.py", line 163, in StartAnalysis\n "inventory", constants.PROFILE_REPOSITORY_VERSION))\n File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flows/general/memory.py", line 284, in GetProfileByName\n return profile_server.GetProfileByName(name, version=version)\n File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/rekall_profile_server.py", line 78, in GetProfileByName\n profile_name, version=version)\n File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/rekall_profile_server.py", line 94, in GetProfileByName\n handle = urllib2.urlopen(url, timeout=10)\n File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen\n return opener.open(url, data, timeout)\n File "/usr/lib/python2.7/urllib2.py", line 429, in open\n response = self._open(req, data)\n File "/usr/lib/python2.7/urllib2.py", line 447, in _open\n \'_open\', req)\n File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain\n result = func(*args)\n File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open\n context=self._context)\n File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open\n raise URLError(err)\nURLError: <urlopen error [Errno -3] Temporary failure in name resolution>\n' network_bytes_sent : 386 status : GENERIC_ERROR`

Any ideas on what I can do to get this working?

**Comment by grrrrrrrrr** [comment]
Whenever you want to use a Rekall based flow, you will need a profile. The server is configured to download it from the official rekall profile repository but since your server can't reach the network, it raises this error.

One solution to this is to use the GetMissingProfiles functionality to cache all profiles on your server.

https://github.com/google/grr-doc/blob/master/troubleshooting.adoc#missing-rekall-profiles

**Comment by jcampbell13772** [comment]
I had a similar issue with this.  It looks like the GRR server is trying to resolve the name of the client via DNS.  I setup a fakedns server to resolve the client (It is all on an internal host-based virtual network).  That resolved the name resolution issue, but now I get a network connection rejected error.  It appears that the GRR server tries to establish a connection to the client via SSL (tcp port 443) only the client is not listening on 443.  Is there something I am missing?

**Comment by voilaviola** [comment]
Hello,
I got a similar error as below when running _grr_config_updater download_missing_rekall_profiles_:

> URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
ERROR:2018-04-20 06:36:09,207 threadpool:107] Caught exception in worker thread (Unnamed task): <urlopen error [Errno -3] Temporary failure in name resolution>
Traceback (most recent call last):
  File "/home/User/GRR_ENV/local/lib/python2.7/site-packages/grr/server/threadpool.py", line 99, in ProcessTask
    target(*args)
  File "/home/User/GRR_ENV/local/lib/python2.7/site-packages/grr/server/rekall_profile_server.py", line 78, in GetProfileByName
    profile_name, version=version)
  File "/home/User/GRR_ENV/local/lib/python2.7/site-packages/grr/server/rekall_profile_server.py", line 94, in GetProfileByName
    handle = urllib2.urlopen(url, timeout=10)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
And I verified that my firewall isn't blocking the download. My GRR machine is Ubuntu Xenial 16.04, and I install GRR in a virtualenv GRR_ENV.

**Comment by grrrrrrrrr** [comment]
It looks like your server can't resolve the url of the Rekall profile repository (should be github.com). Are you sure that the internet connection on the server is working?

**Comment by voilaviola** [comment]
Hi, yes I have internet access. After adding nameserver 8.8.8.8 to /etc/resolv.conf, the error message changes to below: 

> Using configuration <GrrConfigManager  file="/home/User/GRR_ENV/install_data/etc/grr-server.yaml"  file="/home/User/GRR_ENV/install_data/etc/server.local.yaml" >
Downloading missing Rekall profiles.
ERROR:2018-04-20 07:24:17,437 threadpool:107] Caught exception in worker thread (Unnamed task): <urlopen error ('_ssl.c:574: The handshake operation timed out',)>
Traceback (most recent call last):
  File "/home/User/GRR_ENV/local/lib/python2.7/site-packages/grr/server/threadpool.py", line 99, in ProcessTask
    target(*args)
  File "/home/User/GRR_ENV/local/lib/python2.7/site-packages/grr/server/rekall_profile_server.py", line 78, in GetProfileByName
    profile_name, version=version)
  File "/home/User/GRR_ENV/local/lib/python2.7/site-packages/grr/server/rekall_profile_server.py", line 94, in GetProfileByName
    handle = urllib2.urlopen(url, timeout=10)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)

**Comment by grrrrrrrrr** [comment]
It really seems like your internet connection isn't working. Maybe you need to configure a proxy?

Please try to download a profile from the command line and see if this works. Here is a link GRR would use, I can download it using wget:

https://github.com/google/rekall-profiles/raw/master/v1.0/ntdll/GUID/00C54168286C479D81823570A9C442462.gz

**Comment by voilaviola** [comment]
I restarted my VMs and tried again download_missing_rekall_profiles, and got no error message. However the profiles don't seem to work, because I got the same error when trying AllVADBinaryFiles artifact collector on win10 and win7 client:

> ERROR:rekall.1:No profiles match this image. Try specifying manually.

> Artifact FullVADBinaryList data collection failed. Status: message GrrStatus { child_session_id : SessionID: aff4:/C.765845b62623e42e/flows/F:4E2AE3C5/F:3FAF8515/F:FD3F5ED6 cpu_time_used : message CpuSeconds { system_cpu_time : 36.90625 user_cpu_time : 314.859375 } error_message : u'Traceback (most recent call last):\n File "/home/User/GRR_ENV/local/lib/python2.7/site-packages/grr/server/flow_runner.py", line 589, in RunStateMethod\n direct_response=direct_response, request=request, responses=responses)\n File "/home/User/GRR_ENV/local/lib/python2.7/site-packages/grr/server/flow.py", line 300, in Decorated\n res = f(*args[:f.func_code.co_argcount])\n File "/home/User/GRR_ENV/local/lib/python2.7/site-packages/grr/server/flows/general/memory.py", line 287, in End\n raise flow.FlowError("Error running plugins: %s" % all_errors)\nFlowError: Error running plugins: Traceback (most recent call last):\n File "site-packages\\grr_response_client\\components\\rekall_support\\grr_rekall.py", line 278, in Run\n File "site-packages\\rekall\\session.py", line 869, in RunPlugin\n File "site-packages\\rekall\\session.py", line 862, in RunPlugin\n File "site-packages\\rekall\\session.py", line 912, in _GetPluginObj\n File "site-packages\\rekall\\session.py", line 155, in __getattr__\n File "site-packages\\rekall\\session.py", line 135, in GetPluginClass\n File "site-packages\\rekall\\plugin.py", line 982, in GetActivePlugin\n File "site-packages\\rekall\\plugin.py", line 434, in is_active\n File "site-packages\\rekall_lib\\utils.py", line 1079, in __get__\n File "site-packages\\rekall\\session.py", line 1062, in profile\n File "site-packages\\rekall\\session.py", line 768, in GetParameter\n File "site-packages\\rekall\\session.py", line 803, in _RunParameterHook\n File "site-packages\\rekall\\plugins\\guess_profile.py", line 764, in calculate\nRuntimeError: Unable to find a valid profile for this image. Try using -v for more details.\n\n' network_bytes_sent : 5094 status : GENERIC_ERROR }.

Firewalls on these clients are both turned off, and other artifact collector such as FirefoxHistory functions well.

**Comment by grrrrrrrrr** [comment]
Do you know that Rekall works on those machines without GRR? It seems like there is no profile for the kernels you are running. You could run the Rekall flow in GRR with debug logging enabled (there is an argument to the flow) and paste the logs - it should have the UUIDs you need the profile for.

In general, this is one of the reasons why we deprecated Rekall in GRR. There are just too many things that can go wrong (and frequently do!) and troubleshooting is hard and tedious.

**Comment by voilaviola** [comment]
Yes, Rekall runs well on my Win10 and Win7 machine. I actually tested Rekall before installing GRR :) Anyway thanks a lot for your help. I'll comment here if I find any solution.

**Comment by grrrrrrrrr** [comment]
If you have Rekall running, you can check for the matching profile UUID and see if GRR downloads it while running the flow. The Rekall flow debug logs should also show the same information.
