### ISSUE TITLE
Documentation for Exporting Data needs updating

### ISSUE THREAD

**Issue by mkunz7** [google/grr#45]
It appears the functionality of grr_file_exporter got rolled into grr/tools/export.py

```
db@grrhost: ~$ grr_file_exporter --collection=aff4:/hunts/W:123456/Results --output=/tmp
```
^^ That was the previous command, but grr_file_exporter doesn't exist anymore.

Excuse my lack knowledge in this area. But why doesn't something like this work. 
```
sudo python export.py collection --path aff4:/hunts/W:FB094358/Results csv
```

Also I was reading things about there being an export button in the gui. I dug for a while and couldn't find it, where the heck is that at? I'm running a build from latest source.

**Comment by destijl** [comment]
The UI now gives you the export command to use.
