### ISSUE TITLE
Anti-Virus

### ISSUE THREAD

**Issue by 1stnooby** [google/grr#450]
Folks,

Setting up GRR, I went to install the first agent on a wintel machine and AV kicked off binning the file (grr_3.1.0.2_amd64.exe) as known malware.

Is this expected?

Thanks

**Comment by destijl** [comment]
No, but it's interesting. Which AV? Did it give you a virus name, or was it
something generic? Signing your installer and getting AV to trust it is the
solution.

**Comment by 1stnooby** [comment]
Hi

Thanks for the reply...Symantec see it as, Risk: WS.Reputation.1, Risk Type: Insight Network Threat

Thanks
