### ISSUE TITLE
Automate housekeeping

### ISSUE THREAD

**Issue by SleuthKid** [google/grr#452]
It would be nice to have a tool/script to do some general housekeeping of a running grr server.
Some time when hunts crash or when other failures occure the datebases and references are missing.

Without deeper insight in the inner workings of a running grr server it is quite hard to debug such things at the moment.

**Comment by destijl** [comment]
I'm not sure what you're suggesting here. Is there something specific you'd like to automate? It sounds like you're trying to workaround a bug. We should diagnose and fix the bug rather than automate the workaround.
