### ISSUE TITLE
Unresponsive Script - Hanging JavaScript on Host information page

### ISSUE THREAD

**Issue by n3x77** [google/grr#453]
Hi guys,

on some hosts the host information page in the web browser gets unresponsive leading to an unresponsive script error in third-party.bundle.js. It's seems that is has something to do with corrupted versions of the host information page. The version dropdown shoes some entries with the value grrTimestamp$. 

On Some clients this could be fixed with deleting the client with the grr_console and start an interrogate cronjob. Is there a possibilite to just delete the corrupted versions?

Thx

**Comment by mbushkov** [comment]
Hi,
For the clients that have the issue - can you please check how many
versions are there? The easiest way to do that is to trigger this URL:
https://[your AdminUI url]/api/clients/[YOUR_CLIENT_ID]/version-times

The issue may be not with corrupted data but with the number of versions
being so big that it freezes the UI.

Cheers,
Misha

**Comment by n3x77** [comment]
Hi Misha,

thanks for the fast response.
I've checked it for two clients. One has about 9000 entries, the other one about 40.000 entries. Is there a way to drop any version except the latest one or initialize the version history?

Regards,
Sven

**Comment by mbushkov** [comment]
Hi Sven,
How often do you run interrogate on these clients? Also, what datastore do
you use?

Deleting the client with grr_console seems like the easiest solution. It
will be reinterrogated within 10 minutes (as soon as the client checks in).
Is there a reason you want to preserve the client?

Cheers,
Misha

**Comment by n3x77** [comment]
Hi Misha,

we're using sqlite databases. We had some issues a few days before with these. So many flows get stuck. Maybe this lead to many interrogate flows. The problem is that i've already deleted that client with the grr_console. After that he connects back with the same problem. I'm going to delete that client now and will check later if the problem still exists.

Thanks for your help!

Sven

**Comment by mbushkov** [comment]
Hi Sven,
It sounds strange. If you're not manually running Interrogate flows very
often, then Interrogate should run periodically (weekly, IIRC) or first
time when client enrolls. Every interrogate adds 3-4 versions to client
versions list. So having 40000 versions on a single client is surprising.

How many clients do you have? Are you sure you're not sharing a client id
between multiple clients? (this may happen if you use an image of a machine
where GRR was already installed). I.e. if all your GRR clients use the same
config, they will all report to the server with a same client id, and this
behavior may lead to you having 40000 entries in the client versions list.

Cheers,
Misha

**Comment by n3x77** [comment]
Hi Misha,

we have round about 1000 clients in our server. The client on this site has been delpoyed manually for each system.

After deleting the client via the grr_console. The clients can now be found in the grr-server via the urn. With an red state. As soon as you click on the system the following error message is thrown: "
Object aff4:/C.xxxxxxxxx is of type AFF4Volume, but required_type is VFSGRRClient. 
I think this is because the interrogate is missing. Should I start it manually?

Looking at the sqlite database for that system the statistics table only has one entry. The table tbl is very big and includes the old entries. This seems strange for me. I thought  after deleting a client via the grr_console all data concerning this client would be deleted.

By
Sven

**Comment by destijl** [comment]
Which server version are you running?

**Comment by n3x77** [comment]
The version is 3.1.0.2.

**Comment by n3x77** [comment]
Hi, 
after deleting the files with grr_console, i started to wait until the systems came back. After a few hours the systems got a online state without any further information. After waiting for another few hours the system information was updated. It there a way to increase the speed of the initialization? Because starting the Interrogate flow on the system lead to this high number of versions.

**Comment by mbushkov** [comment]
Hi Sven,
Can you try backing up your datastore files in some safe location and then
deleting them from their original location, so that GRR starts with a clean
state?
If you don't change server configuration files, then clients will soon
appear again in the UI. The biggest question: whether you'll witness the
same weird behaviour with clients having thousands of versions after this
kind of state reset.

Cheers,
Misha

**Comment by n3x77** [comment]
Hi Misha,

after deleting the Systems and the grr_console and moving the sqlite Databases the systems came back online without any error. Due tue the weekly interrogate job, flows were started on the systems. 
3 Systems worked well and the flows were finished sucessfully. 

Only one system had a very strange behaviour. The interrogate flow did not finish and run for a long time. The System Informations were fine and could be opened in the ui, but when opening the managed flows tab we get the same error as descriped above for the host information tab. 

So it seems that it is a problem with flows, that did not run/finish in a clear state. 

I'm going to delete the system and start a new try.

By,
Sven

**Comment by grrrrrrrrr** [comment]
Closing this. Please reopen if this is still a problem.
