### ISSUE TITLE
Error when attempting to run agent on WIN2003 machine

### ISSUE THREAD

**Issue by zecchino1** [google/grr#454]
When running the 32 bit agent in debug mode get the following UnZIP error:
error: must specify directory to which to extract with -d option

**Comment by destijl** [comment]
Hi, this is at install time? or after? Can you follow the troubleshooting steps
https://github.com/google/grr-doc/blob/master/troubleshooting.adoc#i-dont-see-my-clients

and paste your terminal output?

**Comment by zecchino1** [comment]
Hi Greg,  Thank you for the response.  When I run the agent as an administrator it will show up for a split second in the process list, then die.  I ran the debug agent and got the same results, and attached is the print out from the terminal window.  This is running on a Win 2003 machine (I have disabled A/V and tried it also with the same results), It does work awesome on my Win 2012 servers..... W/r Shawn

**Comment by destijl** [comment]
Can you add the output into the bug?

**Comment by zecchino1** [comment]
![grr_degug](https://cloud.githubusercontent.com/assets/9440195/21356367/665d59f8-c69f-11e6-9239-bfe2cb2fde5d.PNG)

**Comment by grrrrrrrrr** [comment]
This is just the installer, it doesn't need a config and also doesn't
understand --verbose. Can you just execute the file as admin?

**Comment by zecchino1** [comment]
I ran the agent as an administrator by right clicking and selecting run as admin, and it would start then terminate. 

The output I posted was based on the direction in this section of the troubleshooting guide:

You can troubleshoot by running the services in the foreground, e.g. to run the HTTP Front-end server in the foreground:

sudo grr_server --start_http_server --verbose

**Comment by destijl** [comment]
The installer is supposed to install then exit. Those instructions are for the server, this is the client. See here for client troubleshooting:

https://github.com/google/grr-doc/blob/master/troubleshooting.adoc#i-dont-see-my-clients

**Comment by destijl** [comment]
Reopen if you still need help.
