### ISSUE TITLE
GRR agent doesn't resume pending flows after crash/timeout

### ISSUE THREAD

**Issue by piningforthefnords** [google/grr#458]
Hi all,

We have a troublesome WMI artifact that sometimes causes the agent to hang, and Nanny does what it should by killing and restarting it after no heartbeat is received. The flow is marked as crashed in GRR's web UI, also as expected. However, at this point we usually have several other flows running as well, and the agent never resumes any of them, and they're not marked as crashed or killed in the GRR UI. Is this normal behavior for the agent?

**Comment by superponible** [comment]
Specifically, it's WMIAccountUsersDomain hanging, but running the following on the command line also fail:

wmic useraccount list brief 
or
wmic path Win32_UserAccount Get *

I'm sure the failure is something specific to this system, but the bigger question as asked above is why the rest of the flows don't run.

**Comment by grrrrrrrrr** [comment]
Hey,

So what happens here is that the server sends request for all those flows
at the same time and then starts waiting for responses. When the client
gets killed, all those pending requests are lost and all the flows become
stuck except the one the client reports back as broken which errors out.

However, the server should retransmit the requests when there are no
responses for a long time - I think the current setting for that is one
hour. Have you tried waiting for that long to see if the retransmission
occurs?

Cheers,
-Andy

**Comment by piningforthefnords** [comment]
Hey Andy, 

I let it sit overnight, and none of the old flows ever ran; they're still in waiting status. I did start a new flow and it completed successfully.

Thanks!
