### ISSUE TITLE
GRR Config Updater Initialize gets held up after the email section

### ISSUE THREAD

**Issue by dyizah** [google/grr#462]
I executed {grr_config_updater initialize} and when I get to the section right after the "Monitoring/Email Domain" (default, I don't use this) section it just get held up after it displays "Configuration parameters set. You can edit these in /etc/grr//server.local.yaml"  It doesn't freeze my system but just hang until I ctrl+c out of it. This worked fine previously, but I made a modification to my server.local.yaml file (changed an IP address). I even tried to change the IP back to original IP but still no joy.

**Comment by grrrrrrrrr** [comment]
Hm the next step would be to create user accounts in the DB. What data store are you using? Maybe there is a problem with the DB connection.

**Comment by dyizah** [comment]
I think you are right. I am using Mysql for my DB. I was trying to scale GRR with multiple front end pointing to a single DB. I'll take a look and see if that was actually the issue.

**Comment by dyizah** [comment]
@grrrrrrrrr You were right. It was a connection issue with the DB. Thanks!
