### ISSUE TITLE
Server cert is invalid from client side

### ISSUE THREAD

**Issue by seabaz** [google/grr#463]
Hi,

Was installing agent 3.1.0.2, and encountered server cert issue. No proxy is used and has followed the guide to troubleshoot the client https://github.com/google/grr-doc/blob/master/troubleshooting.adoc
Is there anyone having similar issue before? and how to fix this? thanks

/# sudo /usr/sbin/grrd --config=/usr/lib/grr/grr_3.1.0.2_amd64/grrd.yaml --verbose
INFO:2017-01-06 04:40:59,208 log:197] Starting GRR Prelogging buffer.
INFO:2017-01-06 04:40:59,282 config_lib:1103] Loading configuration from /usr/lib/grr/grr_3.1.0.2_amd64/grrd.yaml
INFO:2017-01-06 04:40:59,286 config_lib:1103] Loading configuration from /usr/lib/grr/grr_3.1.0.2_amd64/build.yaml
INFO:2017-01-06 04:40:59,289 config_lib:1103] Loading configuration from /etc/grr.local.yaml
INFO:2017-01-06 04:40:59,289 config_lib:809] Configuration writeback is set to /etc/grr.local.yaml
DEBUG:2017-01-06 04:40:59,289 log:155] Initializing Logging subsystem.
DEBUG:2017-01-06 04:40:59,289 log:107] Will use logging engines ['stderr']
DEBUG:2017-01-06 04:40:59,290 registry:166] Initializing CommunicatorInit
DEBUG:2017-01-06 04:40:59,291 registry:166] Initializing CommsInit
DEBUG:2017-01-06 04:40:59,291 registry:166] Initializing VFSInit
DEBUG:2017-01-06 04:40:59,292 registry:166] Initializing InitHook
INFO:2017-01-06 04:40:59,307 comms:1490] Starting client aff4:/C.38c9329fdd82c403
DEBUG:2017-01-06 04:40:59,314 admin:314] Sending startup information.
INFO:2017-01-06 04:40:59,604 comms:1178] Unable to verify server certificate at http://grr_server:8080/server.pem: Server cert is invalid.
INFO:2017-01-06 04:40:59,605 comms:228] Could not connect to GRR servers ['http://grr_server:8080/'], directly or through these proxies: [''].
...

**Comment by grrrrrrrrr** [comment]
When you wget that url http://grr_server:8080/server.pem from the same machine, do you actually get a cert?

**Comment by seabaz** [comment]
yes, got the cert. no issue accessing server.pem

**Comment by grrrrrrrrr** [comment]
Ok. In that case your client probably uses different keys than the server. Have you ever recreated the server keys? Or do you use multiple servers without moving the keys between them?

In any case, to fix this you will need to repack and reinstall the client. Repacking will put the correct keys in the package, it should work afterwards.

**Comment by seabaz** [comment]
yes run the grr_config_updater and overwrite the keys. would that cause this keys issue?
Is there clean procedure to reinstall the client in linux?

**Comment by seabaz** [comment]
Hi grrrrrrrrrr, it works fine after repackage and reinstall, the cert synch-ed correctly.
Thanks

**Comment by grrrrrrrrr** [comment]
Awesome!
