### ISSUE TITLE
client rate < 1 in hunts is handled (but not displayed) correctly

### ISSUE THREAD

**Issue by hillu** [google/grr#471]
Hi,

when I define a hunt with a client rate between 0 and 1, the correct value seems to be stored: In my lab setup it has been possible to reliably schedule one flow per 20min or so. (I need this to be able to run resource-intensive flows on machines that run in overbooked VM environments without risking to bring everything to a halt.)

However, the hunt overview page tells me "No client limit". I found this in the templates:
```
  <dt>Client Rate (clients/min)</dt>
  {% if this.client_rate == 0.0 %}
    <dd>No rate limit</dd>
  {% else %}
    <dd>{{ this.client_rate|escape }}</dd>
  {% endif %}
```
Apparently, `client_rate` has been truncated to an integer value somewhere... Indeed, while `HuntRunnerArgs.client_rate` defines `flows.proto` as a float, but `api.proto` defines `ApiHunt.client_rate` as an int64.

Would it make sense to change it like this?

``` diff
diff --git a/grr/proto/api.proto b/grr/proto/api.proto
index 29ed33e..6de1e6c 100644
--- a/grr/proto/api.proto
+++ b/grr/proto/api.proto
@@ -1414,7 +1414,7 @@ message ApiHunt {
   optional int64 client_limit = 10 [(sem_type) = {
       description: "Client limit.",
     }];
-  optional int64 client_rate = 11 [(sem_type) = {
+  optional float client_rate = 11 [(sem_type) = {
       description: "Client rate.",
     }];
   optional uint64 created = 12 [(sem_type) = {
```

**Comment by grrrrrrrrr** [comment]
In general changing live protobufs is not a good idea but in this case it might actually be ok since this protobuf is never stored anywhere, just shipped to the UI and to API clients. Have you tried it? Does that fix the issues?

**Comment by hillu** [comment]
Yeah, this works. After applying the change discussed above, I now get "Client Rate (clients/min): 0.10000000149011612" after entering 0.1.

**Comment by hillu** [comment]
So I found that that view is rendered in Angular (`hunt-overview.html`). Having more than 3 or 4 digits after the point seems too much, so what should I do here to format that number?
```
    <dt>Client Rate (clients/min)</dt>
    <dd ng-if="!controller.hunt.client_rate">-</dd>
    <dd ng-if="controller.hunt.client_rate"><grr-semantic-value value="controller.hunt.client_rate" /></dd>
```
