### ISSUE TITLE
SQlite configuration may lead to data loss

### ISSUE THREAD

**Issue by hillu** [google/grr#472]
With the SQLite backend, when any of the server processes (or for some reason, the entire server) crashes, one may end up with corrupted database files which will lead to symptoms such as server processes not being able to start up again or crashing when accessing individual bits of client or flow information. Here are the settings from `sqlite_data_store.py`:
``` python
cursor.execute("PRAGMA count_changes = OFF")
cursor.execute("PRAGMA cache_size = 10000")
cursor.execute("PRAGMA journal_mode = OFF")
# Make sure the database is fully written to disk.
cursor.execute("PRAGMA synchronous = ON")
```
The [SQLite documentation](http://sqlite.org/pragma.html#pragma_journal_mode) warns: "If the application crashes in the middle of a transaction when the OFF journaling mode is set, then the database file will very likely go corrupt."

Setting `synchronous=ON` is not [documented](http://sqlite.org/pragma.html#pragma_synchronous), it has the same effect as `synchronous=NORMAL`.

It would probably be best to set `synchronous=NORMAL`, `journal_mode=WAL` or `synchronous=FULL`, `journal_mode=TRUNCATE`. The write-ahead-log feature requires SQLite >= 3.7.0 which has been available since Debian/wheezy and at least Ubuntu/precise, so I would probably go with WAL.

Here's a script that I have successfully used to deal with the corrupted SQLite containers:
``` shell
#!/bin/sh
set -e
if [ -z "$1" ]; then
    echo "Usage: $0 <directory>" >&2
    echo "    e.g. $0 /var/lib/grr-server/datastore" >&2
    exit 1
fi
repair_file() {
    local db=$1
    local dump=$(mktemp)
    echo "Dumping $db to $dump ..."
    cat | sqlite3 "$f" <<EOF
.output $dump
.dump
EOF
    mv $db $db.orig
    echo "Reading $db back from $dump ..."
    sqlite3 $db < $dump
    echo "Done."
    rm -f $dump
}
find "$1" -type f -name \*.sqlite | while read f; do
    sqlite3 "$f" vacuum || repair_file "$f"
done
```

**Comment by grrrrrrrrr** [comment]
Thanks for looking into this! I agree that WAL would be the right thing to do. Do you have any performance numbers though? I am a bit worried about the tables we constantly hit with writes like worker queues.

**Comment by hillu** [comment]
I do not have any performance numbers. The SQLite documentation states that generally WAL provides better concurrency, is faster, leads to less blocking, and uses fewer `fsync()` operations. (I'd expect the lower number of fsync operations to be the main reason for increased performance.)

**Comment by destijl** [comment]
Since you have the DB set up anyway can you run the performance benchmark tests with current and proposed configurations and post the results?

https://github.com/google/grr-doc/blob/92e94b3dfc6845cd8ed7dbb41026a82e91d61bc9/implementation.adoc#running-the-datastore-benchmark-tests

**Comment by hillu** [comment]
I have tried to run the test against the installed Debian package, but that is broken, so I'll have to try to set up a PIP-based GRR instance instead. This may take some time. The database does not need to be populated with real(istic) data, does it?

**Comment by grrrrrrrrr** [comment]
No, the tests are completely self contained, they generate all the needed test data. Thanks for trying this!!

**Comment by hj0x3** [comment]
I happened to have an environment up with latest git installed through pip. Ran the tests with the noted settings. 

Micro benchmarks:

**(current) synchronous=ON, journal_mode=OFF**
```
Running test ./lib/python2.7/site-packages/grr/lib/data_stores/sqlite_data_store_test.py
..............................................................
----------------------------------------------------------------------
Ran 62 tests in 10.365s

OK
```

**synchronous=NORMAL, journal_mode=WAL**
```
Running test ./lib/python2.7/site-packages/grr/lib/data_stores/sqlite_data_store_test.py
..............................................................
----------------------------------------------------------------------
Ran 62 tests in 11.998s

OK
```

**synchronous=FULL, journal_mode=TRUNCATE**
```
Running test ./lib/python2.7/site-packages/grr/lib/data_stores/sqlite_data_store_test.py
..............................................................
----------------------------------------------------------------------
Ran 62 tests in 12.549s

OK
```

Full benchmarks attached, summaries:
[472_sqlite_config_tests.zip](https://github.com/google/grr/files/780763/472_sqlite_config_tests.zip)

**(current) synchronous=ON, journal_mode=OFF**
```
# python ./lib/python2.7/site-packages/grr/lib/data_stores/sqlite_data_store_benchmark_test.py  --test=SqliteDataStoreCSVBenc
hmarks.manySubjectsFewAttrs > manySubjectsFewAttrs.csv
.
----------------------------------------------------------------------
Ran 1 test in 48.414s

OK
# python ./lib/python2.7/site-packages/grr/lib/data_stores/sqlite_data_store_benchmark_test.py  --test=SqliteDataStoreCSVBenc
hmarks.manySubjectsFewWithManyAttrs > manySubjectsFewWithManyAttrs.csv
.
----------------------------------------------------------------------
Ran 1 test in 58.514s

OK
# python ./lib/python2.7/site-packages/grr/lib/data_stores/sqlite_data_store_benchmark_test.py  --test=SqliteDataStoreCSVBenc
hmarks.fewSubjectsManyAttrs > fewSubjectsManyAttrs.csv
.
----------------------------------------------------------------------
Ran 1 test in 20.248s

OK
# python ./lib/python2.7/site-packages/grr/lib/data_stores/sqlite_data_store_benchmark_test.py  --test=SqliteDataStoreCSVBenc
hmarks.blobs > blobs.csv

.
----------------------------------------------------------------------
Ran 1 test in 1117.020s

OK
# python ./lib/python2.7/site-packages/grr/lib/data_stores/sqlite_data_store_benchmark_test.py  --test=SqliteDataStoreCSVBenc
hmarks.manySubjectsManyAttrs > manySubjectsManyAttrs.csv
.
----------------------------------------------------------------------
Ran 1 test in 239.070s

OK
```

**synchronous=NORMAL, journal_mode=WAL**
```
# python ./lib/python2.7/site-packages/grr/lib/data_stores/sqlite_data_store_benchmark_test.py  --test=SqliteDataStoreCSVBenc
hmarks.manySubjectsFewAttrs > manySubjectsFewAttrs.csv
.
----------------------------------------------------------------------
Ran 1 test in 46.631s

OK
# python ./lib/python2.7/site-packages/grr/lib/data_stores/sqlite_data_store_benchmark_test.py  --test=SqliteDataStoreCSVBenc
hmarks.manySubjectsFewWithManyAttrs > manySubjectsFewWithManyAttrs.csv
.
----------------------------------------------------------------------
Ran 1 test in 56.770s

OK
# python ./lib/python2.7/site-packages/grr/lib/data_stores/sqlite_data_store_benchmark_test.py  --test=SqliteDataStoreCSVBenc
hmarks.fewSubjectsManyAttrs > fewSubjectsManyAttrs.csv
.
----------------------------------------------------------------------
Ran 1 test in 19.327s

OK
# python ./lib/python2.7/site-packages/grr/lib/data_stores/sqlite_data_store_benchmark_test.py  --test=SqliteDataStoreCSVBenc
hmarks.blobs > blobs.csv

.
----------------------------------------------------------------------
Ran 1 test in 1096.955s

OK
# python ./lib/python2.7/site-packages/grr/lib/data_stores/sqlite_data_store_benchmark_test.py  --test=SqliteDataStoreCSVBenc
hmarks.manySubjectsManyAttrs > manySubjectsManyAttrs.csv
.
----------------------------------------------------------------------
Ran 1 test in 246.257s

OK
```

**synchronous=FULL, journal_mode=TRUNCATE**
```
# python ./lib/python2.7/site-packages/grr/lib/data_stores/sqlite_data_store_benchmark_test.py  --test=SqliteDataStoreCSVBenchmarks.manySubjectsFewAttrs > manySubjectsFewAttrs.csv
.
----------------------------------------------------------------------
Ran 1 test in 49.887s

OK
# python ./lib/python2.7/site-packages/grr/lib/data_stores/sqlite_data_store_benchmark_test.py  --test=SqliteDataStoreCSVBenchmarks.manySubjectsFewWithManyAttrs > manySubjectsFewWithManyAttrs.csv
.
----------------------------------------------------------------------
Ran 1 test in 56.342s

OK
# python ./lib/python2.7/site-packages/grr/lib/data_stores/sqlite_data_store_benchmark_test.py  --test=SqliteDataStoreCSVBenchmarks.fewSubjectsManyAttrs > fewSubjectsManyAttrs.csv

.
----------------------------------------------------------------------
Ran 1 test in 19.135s

OK
# python ./lib/python2.7/site-packages/grr/lib/data_stores/sqlite_data_store_benchmark_test.py  --test=SqliteDataStoreCSVBenchmarks.blobs > blobs.csv
.
----------------------------------------------------------------------
Ran 1 test in 1097.929s

OK
# python ./lib/python2.7/site-packages/grr/lib/data_stores/sqlite_data_store_benchmark_test.py  --test=SqliteDataStoreCSVBenchmarks.manySubjectsManyAttrs > manySubjectsManyAttrs.csv
.
----------------------------------------------------------------------
Ran 1 test in 245.619s

OK
```

**Comment by hillu** [comment]
@hj0x3 did you change the settings in both `SqliteConnectionCache` and `SqliteConnection`? Also, what kinds of disks are you using?

My workstation has mechanical disks and changing from **synchronous=ON / journal_mode=OFF** to **synchronous=NORMAL / journal_mode=WAL** in `SqliteConnectionCache` increases the microbenchmark run time from ~30s to ~38s. Also changing those values in `SqliteConnection` increases the run time to around 100s.

**Comment by hj0x3** [comment]
@hillu changes made only to SqliteConnectionCache::_CreateModelDatabase; didn't touch SqliteConnection. 

Tests ran on an environment running in VirtualBox VMs, with the underlying volumes on a mechanical disk (10,000 rpm drive, ntfs file system).
