### ISSUE TITLE
i386 agent fails in Windows 7

### ISSUE THREAD

**Issue by lorz** [google/grr#477]
As I don't know where logs are stored, [here](https://drive.google.com/open?id=0B-PKTERBImsGRzVHRmxxY3FiU0k) is the pic.

**Comment by destijl** [comment]
This looks like it's successful. Follow the troubleshooting steps if it doesn't turn up in the server UI when you search:

https://github.com/google/grr-doc/blob/master/troubleshooting.adoc#i-dont-see-my-clients

Re-open if that doesn't solve your problems.
