### ISSUE TITLE
Fail installing client on Win7 machine

### ISSUE THREAD

**Issue by CGO00** [google/grr#482]
Hello,

I'm using a Win7 computer and i tried to install the x64 client (GRRNanny_x64.exe), but nothing happen. After launching the .EXE, nothing happen, no message, no error, no GRR folder into ..\System32\, no GRR process, just nothing.

Any tricks ? Prerequisite ? Any way to launch it in verbose mode ?

Thank you

**Comment by grrrrrrrrr** [comment]
the Nanny is not the client, you want the installer downloaded from the UI, have a look at https://github.com/google/grr-doc/blob/master/quickstart.adoc#install-the-clients

**Comment by CGO00** [comment]
Thank you, i saw the doc but it says : 

> The pre-packaged clients should be visible under Manage Binaries → executables → Windows → installers. Download the client you need.

No information for dummies saying "Hey, please download it from the Web UI Server"

Maybe we can add it ? :)

**Comment by destijl** [comment]
done, https://github.com/google/grr-doc/commit/6e544b132b9acbaa13c52caf306376d86e947c95
