### ISSUE TITLE
grr_fuse and fusepy

### ISSUE THREAD

**Issue by nywss** [google/grr#485]
Any ideas why grr_fuse is complaining about installing fusepy (ubuntu server xenial - latest grr) ?
fusepy is installed but i still get 

"fuse_mount:562] Could not start!
fusepy must be installed to run fuse_mount.py!
Try:
  sudo pip install fusepy"

No matter what i try.

**Comment by mutedmouse** [comment]
Are you running pup install fusepy inside virtualenv?

**Comment by nywss** [comment]
No, i've installed fusepy directly on the os.
I've also installed grr on an another server (same os, same version) and still have this issue.

**Comment by mutedmouse** [comment]
Just for clarification, did you install grr with pip and virtualenv?

**Comment by grrrrrrrrr** [comment]
Even if you install grr from deb it uses a virtualenv. You need to use the virtualenv python/pip to install fuse. Most likely you want to:

sudo /usr/share/grr-server/bin/pip install fusepy

**Comment by nywss** [comment]
Thank you for your answer. 
Indeed, it was a little bit confusing to me...
It works great now !
