### ISSUE TITLE
Rekall live analysis mode failing

### ISSUE THREAD

**Issue by bobbypistol** [google/grr#486]
**GRR version:**

version 3.1.6.2 (HEAD)

**Operating system GRR is running on:**

Debian 

**Installation method:**

Pip install

**Description of problem:**

Running Rekall in live API mode.

Running AnalyzeClientMemory flow with session parameter [ live = API or Memory] or [ live_mode = API or Memory] is not working as intended. At least API mode should use OS implementation of the memory and not rely on the rekall-profiles. However the above mentioned session parameters results in the following traceback.

`Traceback (most recent call last): File "/home/dev/grr/grr/lib/flow_runner.py", line 586, in RunStateMethod direct_response=direct_response, request=request, responses=responses) File "/home/dev/grr/grr/lib/flow.py", line 307, in Decorated res = f(*args[:f.func_code.co_argcount]) File "/home/dev/grr/grr/lib/flows/general/memory.py", line 140, in ComponentLoaded self.CallStateInline(next_state=responses.request_data["next_state"]) File "/home/dev/grr/grr/lib/flow.py", line 732, in CallStateInline getattr(self, next_state)(self.runner, direct_response=responses) File "/home/dev/grr/grr/lib/flow.py", line 290, in Decorated return f(self, direct_response) File "/home/dev/grr/grr/lib/flows/general/memory.py", line 155, in StartAnalysis constants.PROFILE_REPOSITORY_VERSION)) File "/home/dev/grr/grr/lib/flows/general/memory.py", line 286, in GetProfileByName return profile_server.GetProfileByName(name, version=version) File "/home/dev/grr/grr/lib/rekall_profile_server.py", line 77, in GetProfileByName profile_name, version=version) File "/home/dev/grr/grr/lib/rekall_profile_server.py", line 93, in GetProfileByName handle = urllib2.urlopen(url, timeout=10) File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen return opener.open(url, data, timeout) File "/usr/lib/python2.7/urllib2.py", line 431, in open response = self._open(req, data) File "/usr/lib/python2.7/urllib2.py", line 449, in _open '_open', req) File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain result = func(*args) File "/usr/lib/python2.7/urllib2.py", line 1240, in https_open context=self._context) File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open raise URLError(err) URLError: <urlopen error [Errno -2] Name or service not known> `

It seems AnalyzeClientMemory always tries to fetch the corresponding rekall-profile regarding which session parameters is passed.

**Comment by grrrrrrrrr** [comment]
I was working with @bobbypistol on this and it seems like there is no way to trigger live mode in Rekall when not running from the command line?! @scudette is this something that should work?

**Comment by scudette** [comment]
You always need a profile server since GRR always sends the inventory to the client regardless of the specific parameters. It probably only needs to have the basic profiles cached in GRR (maybe only the inventory). Maybe you can get away with uploading an empty inventory?

**Comment by bobbypistol** [comment]
This works however this might not be the best solution for the problem.

**Comment by grrrrrrrrr** [comment]
This is not really supported at this point so I'll close this issue.
