### ISSUE TITLE
Uploading YAML artifact fails using config_updater tool

### ISSUE THREAD

**Issue by jcaluda** [google/grr#488]
When trying to upload YAML artifacts using the upload_artifact function of the config_updater tool, I'm seeing the following error.  I'm using GRR version 3.1.0.2 installed via Pip.

`Traceback (most recent call last):
  File "/usr/share/grr-server/bin/grr_config_updater", line 11, in <module>
    load_entry_point('grr-response-server==3.1.0.post2', 'console_scripts', 'grr_config_updater')()
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/distro_entry.py", line 76, in ConfigUpdater
    flags.StartMain(config_updater.main)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flags.py", line 121, in StartMain
    main([sys.argv[0]])
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/tools/config_updater.py", line 977, in main
    json.load(open(flags.FLAGS.file))  # Check it will parse.
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded`

It appears the tool is trying to parse YAML artifacts as JSON.

**Comment by mbushkov** [comment]
This seems like a bug indeed. I wonder how it ever worked. Have you tried
uploading the artifact through the Admin UI?
You can use the "Artifact Manager" tab, or just go to the URL directly:
<your admin UI address>/#/artifacts.
"Artifact Manager" has an upload button which you can use and it works
correctly with the YAML data. Most likely we never noticed the bug in the
config_updater because we always either updated the artifact definition
files directly or used Artifact Manager to upload custom artifacts.

Cheers,
Misha

**Comment by jcaluda** [comment]
The admin UI works fine, but I'm trying to automate the uploads.  Using the config_updater tool seems like the perfect way to do this.  Looking at the artifact_upload code block of config_updater, I think `json.load(open(flags.FLAGS.file, "rb")) ` should be removed and the token passed to the UploadArtifactYamlFile function since it's currently set to None.

Here's the full block with my suggestions.

```python
elif flags.FLAGS.subparser_name == "upload_artifact":
    base_urn = aff4.ROOT_URN.Add("artifact_store")
    try:
      artifact.UploadArtifactYamlFile(
          open(flags.FLAGS.file, "rb").read(1000000),
          base_urn=base_urn,
          token=token,
          overwrite=flags.FLAGS.overwrite_artifact)
    except artifact_registry.ArtifactDefinitionError as e:
      print "Error %s. You may need to set --overwrite_artifact." % e```

**Comment by mbushkov** [comment]
Removing the json.load line sounds good to me. I'll be able to submit the fix around Tuesday next week.

**Comment by mike-bailey** [comment]
bump because I caused this too recently

**Comment by mbushkov** [comment]
Sorry, this slipped from my radar. Will handle this.

**Comment by grrrrrrrrr** [comment]
This should be fixed now.
