### ISSUE TITLE
Issues with setting up mysql 5.6 as a datastore

### ISSUE THREAD

**Issue by karan1337** [google/grr#489]
I am trying to install GRR server on a rhel 7 host using pip. I was able to successfully figure out the dependencies for the the installation to work. However when I run "grr_config_updater initialize", it seems to be stuck at the lines which stores grr-rekall signed component. The following are the last lines of the log seen on stdout.

"Opened component grr-chipsec-component.
Storing component summary at aff4:/config/components/grr-chipsec-component_1.2.2
Storing signed component at aff4:/web/static/components/58f7baa73d623af4/cp27-cp27m-win_amd64
Signing and uploading component /home/myusername/GRR_ENV/grr-response-templates/components/grr-rekall_0.4_cp27-cp27m-win32.bin
Opened component grr-rekall.
Storing component summary at aff4:/config/components/grr-rekall_0.4
**Storing signed component at aff4:/web/static/components/58f7b93adea37dda/cp27-cp27m-win32**"

Details:
Mysql version: 5.6.36 MySQL Community Server (GPL)
The way I installed mysql dependencies is as follows:-
`sudo yum install mysql-devel`
`pip install MYSQL-python (within the GRR_ENV virtualenv)
`

Output of strace for the grr_config_updater process id is as follows:-

`gettimeofday({1492631867, 491236}, NULL) = 0
select(0, NULL, NULL, NULL, {1, 0})     = 0 (Timeout)
gettimeofday({1492631868, 492928}, NULL) = 0
socket(PF_LOCAL, SOCK_STREAM, 0)        = 6
connect(6, {sa_family=AF_LOCAL, sun_path="/var/lib/mysql/mysql.sock"}, 110) = 0
setsockopt(6, SOL_IP, IP_TOS, [8], 4)   = -1 EOPNOTSUPP (Operation not supported)
setsockopt(6, SOL_SOCKET, SO_KEEPALIVE, [1], 4) = 0
recvfrom(6, "J\0\0\0\n5.6.36\0\255\6\0\0\\v[F.O$c\0\377\367\10\2\0\177\200"..., 16384, 0, NULL, NULL) = 78
sendto(6, "\247\0\0\1\215\242?\0\0\0\0@\10\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 171, 0, NULL, 0) = 171
recvfrom(6, "\7\0\0\2\0\0\0\2\0\0\0", 16384, 0, NULL, NULL) = 11
sendto(6, "\17\0\0\0\3SET NAMES utf8", 19, 0, NULL, 0) = 19
recvfrom(6, "\7\0\0\1\0\0\0\2\0\0\0", 16384, 0, NULL, NULL) = 11
sendto(6, "\21\0\0\0\3set autocommit=0", 21, 0, NULL, 0) = 21
recvfrom(6, "\7\0\0\1\0\0\0\0\0\0\0", 16384, 0, NULL, NULL) = 11
sendto(6, "\21\0\0\0\3set autocommit=1", 21, 0, NULL, 0) = 21
recvfrom(6, "\7\0\0\1\0\0\0\2\0\0\0", 16384, 0, NULL, NULL) = 11
sendto(6, "\21\0\0\0\3SET NAMES binary", 21, 0, NULL, 0) = 21
recvfrom(6, "\7\0\0\1\0\0\0\2\0\0\0", 16384, 0, NULL, NULL) = 11
sendto(6, "\22\0\0\0\3START TRANSACTION", 22, 0, NULL, 0) = 22
recvfrom(6, "\7\0\0\1\0\0\0\3\0\0\0", 16384, 0, NULL, NULL) = 11
sendto(6, "\334\237n\0\3INSERT INTO aff4 (subject_h"..., 8192, 0, NULL, 0) = 8192
sendto(6, "b3837ee020ab1930ab7bb32b640eb938"..., 7241696, 0, NULL, 0) = -1 EPIPE (Broken pipe)
--- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=9459, si_uid=1000} ---
shutdown(6, SHUT_RDWR)                  = 0
close(6)                                = 0`

Tagging @grrrrrrrrr @destijl @dionyziz : Please let me know if this is the appropriate place to discuss about this issue or you prefer the grr user's google group. Thanks.

**Comment by mbushkov** [comment]
Seems like Mysql works for a bit, but the connection gets broken. Do you by chance see anything suspicious in Mysql logs?
Also, what happens if you run grr_admin_ui? Does it work?

**Comment by karan1337** [comment]
`13 Query     INSERT IGNORE INTO attributes (hash, attribute) VALUES(unhex(md5('index:dir/00000000DD')), 'index:dir/00000000DD'), (unhex(md5('index:dir/00000000DE')), 'index:dir/00000000DE'), (unhex(md5('in      dex:dir/00000000DF')), 'index:dir/00000000DF'), (unhex(md5('index:dir/00000000E0')), 'index:dir/00000000E0'), (unhex(md5('index:dir/00000000E1')), 'index:dir/00000000E1'), (unhex(md5('metadata:content_last')), 'metadata:cont      ent_last'), (unhex(md5('aff4:size')), 'aff4:size'), (unhex(md5('aff4:type')), 'aff4:type'), (unhex(md5('index:dir/grr-chipsec-component_1.2.2')), 'index:dir/grr-chipsec-component_1.2.2'), (unhex(md5('metadata:last')), 'metad      ata:last'), (unhex(md5('index:dir/components')), 'index:dir/components'), (unhex(md5('index:dir/cp27-cp27m-win_amd64')), 'index:dir/cp27-cp27m-win_amd64'), (unhex(md5('index:dir/5930acbd97c789d8')), 'index:dir/5930acbd97c789      d8'), (unhex(md5('index:dir/static')), 'index:dir/static'), (unhex(md5('index:dir/web')), 'index:dir/web'), (unhex(md5('index:dir/grr-rekall_0.4')), 'index:dir/grr-rekall_0.4')
19799                    13 Query     INSERT IGNORE INTO subjects (hash, subject) VALUES(unhex(md5('aff4:/config/executables/windows/installers/dbg_GRR_3.1.0.2_amd64.exe/collection/UnversionedStream')), 'aff4:/config/executables/w      indows/installers/dbg_GRR_3.1.0.2_amd64.exe/collection/UnversionedStream'), (unhex(md5('aff4:/config/executables/windows/installers/dbg_GRR_3.1.0.2_amd64.exe/collection')), 'aff4:/config/executables/windows/installers/dbg_GR      R_3.1.0.2_amd64.exe/collection'), (unhex(md5('aff4:/config/components')), 'aff4:/config/components'), (unhex(md5('aff4:/config')), 'aff4:/config'), (unhex(md5('aff4:/web/static/components/5930acbd97c789d8')), 'aff4:/web/stat      ic/components/5930acbd97c789d8'), (unhex(md5('aff4:/web/static/components')), 'aff4:/web/static/components'), (unhex(md5('aff4:/web/static')), 'aff4:/web/static'), (unhex(md5('aff4:/web')), 'aff4:/web'), (unhex(md5('aff4:/')      ), 'aff4:/')
19800                    13 Query     COMMIT
19801 170602  0:09:35    12 Query     START TRANSACTION
19802 170602  0:09:36    10 Query     START TRANSACTION
19803 170602  0:09:37    11 Query     START TRANSACTION
19804 170602  0:09:38    13 Query     START TRANSACTION
19805 170602  0:09:39    14 Connect   root@localhost on grr
19806                    14 Query     SET NAMES utf8
19807                    14 Query     set autocommit=0
19808                    14 Query     set autocommit=1
19809                    14 Query     SET NAMES binary
19810                    14 Query     START TRANSACTION
19811 170602  0:09:40    15 Connect   root@localhost on grr
19812                    15 Query     SET NAMES utf8
19813                    15 Query     set autocommit=0
19814                    15 Query     set autocommit=1
19815                    15 Query     SET NAMES binary
19816                    15 Query     START TRANSACTION
19817 170602  0:09:41    16 Connect   root@localhost on grr
19818                    16 Query     SET NAMES utf8
19819                    16 Query     set autocommit=0
19820                    16 Query     set autocommit=1
19821                    16 Query     SET NAMES binary
19822                    16 Query     START TRANSACTION
19823 170602  0:09:42    17 Connect   root@localhost on grr
19824                    17 Query     SET NAMES utf8
19825                    17 Query     set autocommit=0
19826                    17 Query     set autocommit=1
19827                    17 Query     SET NAMES binary
19828                    17 Query     START TRANSACTION
19829 170602  0:09:43    18 Connect   root@localhost on grr
19830                    18 Query     SET NAMES utf8
19831                    18 Query     set autocommit=0
19832                    18 Query     set autocommit=1
19833                    18 Query     SET NAMES binary
19834                    18 Query     START TRANSACTION
19835 170602  0:09:44    19 Connect   root@localhost on grr
19836                    19 Query     SET NAMES utf8
19837                    19 Query     set autocommit=0
19838                    19 Query     set autocommit=1
19839                    19 Query     SET NAMES binary
19840                    19 Query     START TRANSACTION
19841 170602  0:09:46    20 Connect   root@localhost on grr
19842                    20 Query     SET NAMES utf8
                                                                                                                                                                                                                    19811,37-39   97%
19798                    13 Query     INSERT IGNORE INTO attributes (hash, attribute) VALUES(unhex(md5('index:dir/00000000DD')), 'index:dir/00000000DD'), (unhex(md5('index:dir/00000000DE')), 'index:dir/00000000DE'), (unhex(md5('in      dex:dir/00000000DF')), 'index:dir/00000000DF'), (unhex(md5('index:dir/00000000E0')), 'index:dir/00000000E0'), (unhex(md5('index:dir/00000000E1')), 'index:dir/00000000E1'), (unhex(md5('metadata:content_last')), 'metadata:cont      ent_last'), (unhex(md5('aff4:size')), 'aff4:size'), (unhex(md5('aff4:type')), 'aff4:type'), (unhex(md5('index:dir/grr-chipsec-component_1.2.2')), 'index:dir/grr-chipsec-component_1.2.2'), (unhex(md5('metadata:last')), 'metad      ata:last'), (unhex(md5('index:dir/components')), 'index:dir/components'), (unhex(md5('index:dir/cp27-cp27m-win_amd64')), 'index:dir/cp27-cp27m-win_amd64'), (unhex(md5('index:dir/5930acbd97c789d8')), 'index:dir/5930acbd97c789      d8'), (unhex(md5('index:dir/static')), 'index:dir/static'), (unhex(md5('index:dir/web')), 'index:dir/web'), (unhex(md5('index:dir/grr-rekall_0.4')), 'index:dir/grr-rekall_0.4')
19799                    13 Query     INSERT IGNORE INTO subjects (hash, subject) VALUES(unhex(md5('aff4:/config/executables/windows/installers/dbg_GRR_3.1.0.2_amd64.exe/collection/UnversionedStream')), 'aff4:/config/executables/w      indows/installers/dbg_GRR_3.1.0.2_amd64.exe/collection/UnversionedStream'), (unhex(md5('aff4:/config/executables/windows/installers/dbg_GRR_3.1.0.2_amd64.exe/collection')), 'aff4:/config/executables/windows/installers/dbg_GR      R_3.1.0.2_amd64.exe/collection'), (unhex(md5('aff4:/config/components')), 'aff4:/config/components'), (unhex(md5('aff4:/config')), 'aff4:/config'), (unhex(md5('aff4:/web/static/components/5930acbd97c789d8')), 'aff4:/web/stat      ic/components/5930acbd97c789d8'), (unhex(md5('aff4:/web/static/components')), 'aff4:/web/static/components'), (unhex(md5('aff4:/web/static')), 'aff4:/web/static'), (unhex(md5('aff4:/web')), 'aff4:/web'), (unhex(md5('aff4:/')      ), 'aff4:/')
19800                    13 Query     COMMIT
19801 170602  0:09:35    12 Query     START TRANSACTION
19802 170602  0:09:36    10 Query     START TRANSACTION
19803 170602  0:09:37    11 Query     START TRANSACTION
19804 170602  0:09:38    13 Query     START TRANSACTION
19805 170602  0:09:39    14 Connect   root@localhost on grr
19806                    14 Query     SET NAMES utf8
19807                    14 Query     set autocommit=0
19808                    14 Query     set autocommit=1
19809                    14 Query     SET NAMES binary
19810                    14 Query     START TRANSACTION
19811 170602  0:09:40    15 Connect   root@localhost on grr
19812                    15 Query     SET NAMES utf8
19813                    15 Query     set autocommit=0
19814                    15 Query     set autocommit=1
19815                    15 Query     SET NAMES binary
19816                    15 Query     START TRANSACTION
19817 170602  0:09:41    16 Connect   root@localhost on grr
19818                    16 Query     SET NAMES utf8
19819                    16 Query     set autocommit=0
19820                    16 Query     set autocommit=1
19821                    16 Query     SET NAMES binary
19822                    16 Query     START TRANSACTION`

**Comment by pidydx** [comment]
What is your max_allowed_packet in MySQL set at?  100M should be safe, but 16M is too small, at least for initialization.  I also released some patches that have not been merged to the main project, but refactor a lot of datastore code and add a MySQLExperimentalDataStore that dramatically outperforms MySQLAdvancedDataStore. https://github.com/pidydx/grr/commit/d68ed14b4541e7e1d0bcd765a784672eee868fbd  

Hope that helps!

**Comment by karan1337** [comment]
@pidydx @mbushkov 

I do not see max_allowed_packet set explicitly in /etc/my.cnf so i think it is set as the default.

The other defaults i see in my.cnf file are as follows:-
# The server defaults are faster for transactions and fast SELECTs.
# Adjust sizes as needed, experiment to find the optimal values.
# join_buffer_size = 128M
# sort_buffer_size = 2M
# read_rnd_buffer_size = 2M

**Comment by karan1337** [comment]
@pidydx Thank you so much. The max_allowed_packet did the trick.
