### ISSUE TITLE
Remote User not Recognised

### ISSUE THREAD

**Issue by hannahshort** [google/grr#490]
Hello, 

I've set up a GRR instance behind Apache as a reverse proxy with Shibboleth authentication. My META variables are being set correctly, including HTTP_REMOTE_USER, but I am still being prompted for local credentials after authenticating through Shibboleth. 

Reading https://github.com/google/grr-doc/blob/master/admin.adoc#authentication-to-the-admin-ui, I got the impression that it shouldn't be necessary to create a new WebAuth Manager. 

Am I missing something or is a new WebAuth Manager required? Happy to contribute code as needed.
Cheers,
Hannah

**Comment by mbushkov** [comment]
By default GRR has BasicWebAuthManager enabled:
https://github.com/google/grr/blob/master/grr/gui/webauth.py#L53

This plugin expects "Authorization: Basic XXXXXX" header to be present and then checks that provided password is equal to the password set in the user object. This is likely not the behaviour you want when you're using external authentication system (Shibboleth in your case). I.e. you don't want GRR to do any password management, but just to pick up the user name that Shibboleth reports.

Seems like the way to go is to write a custom WebAuthManager that will pick the user name from the appropriate source (HTTP header, or env variable). It probably makes sense to use BasicWebAuthManager or FirebaseWebAuthManager as examples.

**Comment by hannahshort** [comment]
Ok, that's the path I've gone down already. If I end up with something generic I'll try and contribute back. 
Cheers :)

**Comment by mbushkov** [comment]
Sounds good, thanks! I'll close the issue for now. Feel free to open a new one in case you have issues.
