### ISSUE TITLE
AnalyzeClientMemory on Windows 2008 problem

### ISSUE THREAD

**Issue by pettai** [google/grr#498]
Server/Client is running GRR 3.1.0.2
Tested both AnalyzeClientMemory and MemoryCollector Flows

AnalyzeClientMemory server-side error message: 
Traceback (most recent call last): File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flow_runner.py", line 613, in RunStateMethod responses=responses) File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flow.py", line 353, in Decorated res = f(*args[:f.func_code.co_argcount]) File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flows/general/memory.py", line 138, in ComponentLoaded raise flow.FlowError("Component load failed.") FlowError: Component load failed.

GRR client running with --verbose (logging) says:
INFO <timestamp> actions:173] Job Error (LoadComponent): NotImplementedError ('cannot determine number of cpus',): cannot determine number of cpus 

See this thread for all details:
https://groups.google.com/forum/#!topic/grr-users/pjepjt2v8sM

**Comment by mbushkov** [comment]
This feels like a Rekall-specific issue to me. The error is likely triggered by https://github.com/google/rekall/blob/e13d794542052de0d138acb07ef3f032b008ae94/rekall-core/rekall/plugins/tools/repository_manager.py#L41

@scudette - do you know what could have caused this?

**Comment by scudette** [comment]
i think this is correct. The relevant code from the python multiprocessing library is:

```
def cpu_count():
    '''
    Returns the number of CPUs in the system
    '''
    if sys.platform == 'win32':
        try:
            num = int(os.environ['NUMBER_OF_PROCESSORS'])
        except (ValueError, KeyError):
            num = 0
    elif 'bsd' in sys.platform or sys.platform == 'darwin':
        comm = '/sbin/sysctl -n hw.ncpu'
        if sys.platform == 'darwin':
            comm = '/usr' + comm
        try:
            with os.popen(comm) as p:
                num = int(p.read())
        except ValueError:
            num = 0
    else:
        try:
            num = os.sysconf('SC_NPROCESSORS_ONLN')
        except (ValueError, OSError, AttributeError):
            num = 0

    if num >= 1:
        return num
    else:
        raise NotImplementedError('cannot determine number of cpus')
```

So this looks like a python bug on this platform.  Can you please install python on this OS version and run the command manually:
```
import multiprocessing
print multiprocessing.cpu_count()
```

**Comment by pettai** [comment]
Spot on!

<img width="666" alt="screen shot 2017-05-13 at 22 35 10" src="https://cloud.githubusercontent.com/assets/3317462/26029050/81962f20-382c-11e7-944f-d65ab4b9d096.png">

**Comment by grrrrrrrrr** [comment]
This is a Rekall issue so I'm going to close this one here. I sent https://github.com/google/rekall/pull/320 which should eventually fix Rekall.
