### ISSUE TITLE
Can't start flow GetMRU: 'NoneType' object has no attribute 'users'

### ISSUE THREAD

**Issue by mike-bailey** [google/grr#499]
When running GetMRU along with various other flows, getting
>'NoneType' object has no attribute 'users'

Deployed, per active docs, via:

mkdir ~/grr-docker
docker run \
--name sqlitedb -v ~/grr-docker/db:/var/grr-datastore \
--name logs -v ~/grr-docker/logs:/var/log \
-e EXTERNAL_HOSTNAME="nothingtoseeherefolks" \
-e ADMIN_PASSWORD="nothingtoseeherefolks" \
--ulimit nofile=1048576:1048576 \
-p 0.0.0.0:8000:8000 -p 0.0.0.0:8080:8080 \
-d grrdocker/grr:v0.3.0-7-latest grr

Client is a Win7 VM

**Comment by mbushkov** [comment]
Hi Michael!
In GRR's HEAD, GetMRU flow was deprecated in favor of a more generic
ArtifactCollectorFlow. But unfortunately the WindowsOpenSaveMRU artifact
didn't make it to the artifact collection that's shipped with GRR.

Can you please do the following:
1. Use the latest GRR docker image (-d grrdocker/grr:latest).
2. Upload the WindowsOpenSaveMRU artifact using "Artifact Manager" tab. The
artifact can be found here:
https://github.com/ForensicArtifacts/artifacts/blob/e3d0f6f34bf99f5e9bdf87ec23f22ffa33032443/definitions/windows.yaml#L1049
You only need a single artifact: WindowsOpenSaveMRU. Just put its YAML
definiition into a YAML file and upload it to GRR.
3. Check if running Collectors->ArtifactCollectorFlow works for
WindowsOpenSaveMRU artifact.

Cheers,
Misha

**Comment by mike-bailey** [comment]
I get 
```
Can't start flow :
No artifacts to collect.
```

**Comment by mike-bailey** [comment]
Got Errors 0 but Collected 0


Then tried running browserhistory as another example:
```
Artifact BrowserHistory data collection failed. Status: message GrrStatus { child_session_id : SessionID: aff4:/C.6e283f61116d0573/flows/F:DE9BED32/F:2E4C7860 cpu_time_used : message CpuSeconds { system_cpu_time : 0.0 user_cpu_time : 0.0 } error_message : u'Traceback (most recent call last):\n File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flow_runner.py", line 586, in RunStateMethod\n direct_response=direct_response, request=request, responses=responses)\n File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flow.py", line 307, in Decorated\n res = f(*args[:f.func_code.co_argcount])\n File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flows/general/collectors.py", line 145, in StartCollection\n self.Collect(artifact_obj)\n File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flows/general/collectors.py", line 194, in Collect\n self.GetFiles(source, self.GetPathType(), self.args.max_file_size)\n File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flows/general/collectors.py", line 245, in GetFiles\n ignore_errors=self.args.ignore_interpolation_errors))\n File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/artifact_utils.py", line 110, in InterpolateKbAttributes\n e))\nKnowledgeBaseInterpolationError: Failed to interpolate %%users.localappdata%%\\Google\\Chrome\\User Data\\*\\Archived History with the knowledgebase. users.localappdata\n' network_bytes_sent : 0 status : GENERIC_ERROR }.
```

**Comment by mike-bailey** [comment]
FYI fixed grr docs since you asked:
>1. Use the latest GRR docker image (-d grrdocker/grr:latest).

And that's not what the docs say to do
[Issue for reference](https://github.com/google/grr-doc/pull/76)

**Comment by mbushkov** [comment]
Thanks for opening the issue! Will comment there directly.

A few questions:
* What happens if you run interrogate on a machine? Does it succeed?
* Do you see any users listed on the machine's summary page (left column, in the bottom)?
* Does the machine actually have any users? I.e. did anybody login into it?

**Comment by grrrrrrrrr** [comment]
I'm not sure if there is much more to do here?

@demonchild2112 can you please check that the WindowsOpenSaveMRU works on the server 3.2 RC and close this issue?

**Comment by demonchild2112** [comment]
Artifact collection works for that artifact.
