### ISSUE TITLE
Pin artifacts collection to the latest artifacts release

### ISSUE THREAD

**Issue by mbushkov** [google/grr#500]
See: https://github.com/google/grr/blob/master/grr/artifacts/makefile.py#L16

For context: GetMRU flow got deprecated a while ago, but its subsititute - WindowsOpenSaveMRU artifact - is not shipped with GRR.

**Comment by grrrrrrrrr** [comment]
Is this fixed now? It's not entirely clear what this issue is about.

**Comment by grrrrrrrrr** [comment]
@mbushkov please verify if this is still a problem and fix or close this issue.
