### ISSUE TITLE
Latest Docker Image PATH

### ISSUE THREAD

**Issue by mike-bailey** [google/grr#501]
Not sure where to put this but the binaries for the tools for [documented stuff like repacking clients](https://github.com/google/grr-doc/blob/master/admin.adoc#repacking-the-client-with-a-new-configuration) isn't actually set properly in the latest Docker image. Probably a minor path issue or something. I'll look at the Dockerfile in the repo after this and if it's trivial I'll possibly issue a PR.

Pulled from `grr:latest`:
Entering with `docker exec -it $containerid /bin/bash`
```
root@013b037cef23:/# grr_config_updater repack_clients
bash: grr_config_updater: command not found
root@013b037cef23:/# /usr/share/grr-server/bin/grr_config_updater repack_clients                  
Using configuration <GrrConfigManager  file="/usr/share/grr-server/install_data/etc/grr-server.yaml"  file="/usr/share/grr-server/install_data/etc/server.local.yaml" >
```

**Comment by mike-bailey** [comment]
PR #502 should fix

**Comment by mbushkov** [comment]
Amended the docs: https://github.com/google/grr-doc/commit/49392483a2f1b9de6165a87e04d2665ee91950d5

Closing the issue.

**Comment by mike-bailey** [comment]
Thank you!
