### ISSUE TITLE
--component flag is not marked as required

### ISSUE THREAD

**Issue by mbushkov** [google/grr#503]
--component flag is not marked as required, meaning that AttributeError: 'NoneType' object has no attribute 'startswith' is raised if it's not specified. We should have a proper error message instead.

https://github.com/google/grr/blob/master/grr/tools/grr_server.py#L21

**Comment by grrrrrrrrr** [comment]
Made required in https://github.com/google/grr/commit/a384b4bd8d4c156119c5b258e20b7fd5d555945a
