### ISSUE TITLE
OAuth2Client not being updated

### ISSUE THREAD

**Issue by jawilson0502** [google/grr#506]
The python lib oauth2client is not being maintained through a `setup.py` to contain the necessary version.  This in turn causes https://github.com/google/grr/blob/1dfc4d4cb37924db064d4f36245773bb74678068/grr/lib/bigquery.py#L17 to break because it cannot find ServiceAccountCredentials, but since it is in a try and except block it is not a noisy problem.

I can fix this issue but I am unsure of which `setup.py` to put this dependency. I would guess in `grr/grr/config/grr-response-server/setup.py`

**Comment by mbushkov** [comment]
Hi Jessica, thanks for the help! Yes, `grr/grr/config/grr-response-server/setup.py` is the right place. Probably makes sense to bind it to the latest version: `4.1.0`

**Comment by grrrrrrrrr** [comment]
I assume this was fixed by the attached PR. Please reopen if that's not correct.
