### ISSUE TITLE
[Docker] Mismatched Rekall component version between installed file and config DB

### ISSUE THREAD

**Issue by r3dham** [google/grr#508]
With Docker image(grrdocker/grr:latest), Memory Flow doesn't work. Installed component version(1.6.0) and saved config version(0.4) are different. 

#### [ WEB ADMIN GUI ] Manage Binaries > Components
grr-rekall_**0.4**/5935680b6f6d2d0f / cp27-cp27m-win_amd64

#### [ CONTAINER ] docker exec -it grr ls -al /usr/share/grr-server/grr-response-templates/components
-rw-r--r-- 1 root root 3613110 Jun  1 13:33 grr-rekall_**1.6.0**_cp27-cp27m-win_amd64.bin

#### Error messages from Memory Flow
---
Can't start flow :
Required component not found: Object aff4:/config/components/grr-rekall_1.6.0 is of type AFF4Volume, but required_type is ComponentObject

> Traceback (most recent call last):
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/gui/http_api.py", line 473, in HandleRequest
    result = self.CallApiHandler(handler, args, token=token)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/gui/http_api.py", line 291, in CallApiHandler
    result = handler.Handle(args, token=token)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/gui/api_plugins/flow.py", line 910, in Handle
    runner_args=args.flow.runner_args)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flow.py", line 639, in StartFlow
    flow_obj.Start()
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flow.py", line 307, in Decorated
    res = f(*args[:f.func_code.co_argcount])
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flows/general/memory.py", line 130, in Start
    next_state="StartAnalysis")
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flows/general/transfer.py", line 979, in LoadComponentOnClient
    request_data=request_data)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flow.py", line 732, in CallStateInline
    getattr(self, next_state)(self.runner, direct_response=responses)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flow.py", line 290, in Decorated
    return f(self, direct_response)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flows/general/transfer.py", line 1010, in LoadComponentAfterFlushOldComponent
    raise IOError("Required component not found: %s" % e)
IOError: Required component not found: Object aff4:/config/components/grr-rekall_1.6.0 is of type AFF4Volume, but required_type is ComponentObject

**Comment by mbushkov** [comment]
What happens if you upload grr-rekall_1.6.0_cp27-cp27m-win_amd64.bin to GRR using config_updater (see "Sign and upload the component to the data store" at https://github.com/google/grr/blob/master/grr/client/components/README.txt)?

**Comment by r3dham** [comment]
Not changed. GUI shows the same result.

#### grr_config_updater upload_component /usr/share/grr-server/grr-response-templates/components/grr-rekall_1.6.0_cp27-cp27m-win_amd64.bin
> Using configuration <GrrConfigManager  file="/usr/share/grr-server/install_data/etc/grr-server.yaml"  file="/usr/share/grr-server/install_data/etc/server.local.yaml" >
Signing and uploading component /usr/share/grr-server/grr-response-templates/components/grr-rekall_**1.6.0**_cp27-cp27m-win_amd64.bin
Opened component grr-rekall.
Using seed from stored component summary at aff4:/config/components/grr-rekall_**0.4**
Storing signed component at aff4:/web/static/components/5935680b6f6d2d0f/cp27-cp27m-win_amd64

**Comment by mbushkov** [comment]
This is likely to be a problem:
> Using seed from stored component summary at aff4:/config/components/grr-rekall0.4

Seems like a new component files get written into the old component's destination.  Does specifying `--overwrite_component` flag help? (https://github.com/google/grr/blob/master/grr/tools/config_updater.py#L246)

If not, does removing the component using grr_console and then uploading a new one helps? I.e. in grr_console:
```
aff4.FACTORY.Delete("aff4:/config/components/grr-rekall_0.4")
# And then upload a new one via grr_config_updater.
```

**Comment by r3dham** [comment]
Thanks for your advice. Unfortunately, no change.

grr_config_updater upload_component **--overwrite_component** /usr/share/grr-server/grr-response-templates/components/grr-rekall_1.6.0_cp27-cp27m-win_amd64.bin

> Using configuration <GrrConfigManager  file="/usr/share/grr-server/install_data/etc/grr-server.yaml"  file="/usr/share/grr-server/install_data/etc/server.local.yaml" >
Signing and uploading component /usr/share/grr-server/grr-response-templates/components/grr-rekall_1.6.0_cp27-cp27m-win_amd64.bin
Opened component grr-rekall.
Storing component summary at aff4:/config/components/grr-rekall_0.4
Storing signed component at aff4:/web/static/components/5937ec12c707899f/cp27-cp27m-win_amd64

**Comment by mbushkov** [comment]
Got it. What about the second suggestion - removing the component using grr_console and then uploading a new one?

**Comment by r3dham** [comment]
Updated for second suggestion above.

**Comment by mbushkov** [comment]
A few questions:
* Can you please post a docker command you used to setup the Docker image?
* Did you manually upload the grr_rekall ver. 0.4 component? When I start a docker image using the command from https://github.com/google/grr-doc/blob/master/docker.adoc#how-to-use-the-image, then there are no binaries in "Manage Binaries" at all and I have to manually upload the binary.
* Does the flow run successfully if you specify "component version" as 0.4 in AnalyzeClientMemory's Advanced -> Component Version argument?

**Comment by r3dham** [comment]
My answers:

* docker run --name grr -d -e EXTERNAL_HOSTNAME="localhost" -e ADMIN_PASSWORD="demo" -p 0.0.0.0:8000:8000 -p 0.0.0.0:8080:8080 grrdocker/grr grr
* No. I initialized to get client binaries and components after running. **docker exec -it grr /usr/share/grr-server/bin/grr_config_updater initialize**
* It works if I set it to 0.4.

**Comment by mbushkov** [comment]
Short update on this: there's apparently a bug in the system, which occurs when an older version of the component gets overwritten with a newer one. The bug doesn't seem to occur when components are installed on a clean GRR server install.

I'll keep this issue open, but we'll likely treat it as a lower priority issue, because:
* We plan to refactor the components implementation soon (the most important reason).
* As mentioned above, there should be no problems when component is not overwritten.
* A workaround with specifying component's version works.

**Comment by r3dham** [comment]
Got it. Thanks. Could you let me know how to update "component version" as 0.4 permanently in Config DB?

**Comment by mbushkov** [comment]
Do you mean setting a default for AnalyzeClientMemory flow? I'm afraid there's no way to set a default in the config file. There are 2 possible workarounds:
* Set it manually to 0.4 whenever you run the flow.
* Don't run grr_config_updater after initializing GRR Docker container and upload the Rekall component manually. This way you won't be overwriting a preexisting component and the bug won't be triggered.

**Comment by grrrrrrrrr** [comment]
Rekall is not supported anymore so this is obsolete.
