### ISSUE TITLE
SearchClients command error

### ISSUE THREAD

**Issue by kta01** [google/grr#510]
Hello,

I encounter following error when running SearchClients command from grr_console.
Could you please give me a hand with it?

Complete error below:

In [1]: SearchClients(".")
KeyError                                  Traceback (most recent call last)
/usr/share/grr-server/local/lib/python2.7/site-packages/grr/tools/console.pyc in <module>()
----> 1 SearchClients(".")

/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/console_utils.pyc in SearchClients(query_str, token, limit)
     36 def SearchClients(query_str, token=None, limit=1000):
     37   """Search indexes for clients. Returns list (client, hostname, os version)."""
---> 38   client_schema = aff4.AFF4Object.classes[aff4_grr.VFSGRRClient].SchemaCls
     39   index = aff4.FACTORY.Create(client_index.MAIN_INDEX,
     40                               aff4_type=client_index.ClientIndex,

KeyError: <class 'grr.lib.aff4_objects.aff4_grr.VFSGRRClient'>

Thank you!

**Comment by mbushkov** [comment]
Seems like the code at https://github.com/google/grr/blob/89ff26ec9799412ff3ff74006555a3712f4f634d/grr/lib/console_utils.py#L36 is not properly tested and supported. I think that SearchClients function should be deleted from console_utils.

The better way of querying the clients is by using the GRR API: https://github.com/google/grr/tree/master/api_client/python

Can you please try using grr_api_shell like described here? https://github.com/google/grr/tree/master/api_client/python#api-shell-command-line-one-liners

The difference between grr_console and grr_api_shell, is that grr_console gives you to GRR internals, i.e. to the objects used in GRR implementation, whereas grr_api_shell gives you access to public GRR API interface. Consequently, grr_api_shell-based scripts are much more stable.

**Comment by kta01** [comment]
Thank you for your suggestion. I have installed "grr-api-client", but when running grr_api_shell command I get following error:

$ grr_api_shell --basic_auth_username "user" --basic_auth_password "pwd"   --exec_code 'print "\n".join(c.client_id for c in grrapi.SearchClients(""))' http://localhost:1234
Traceback (most recent call last):
  File "/usr/local/bin/grr_api_shell", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/grr_api_client/api_shell.py", line 81, in main
    exec (flags.exec_code, dict(grrapi=grrapi))
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/grr_api_client/api.py", line 24, in SearchClients
    return client.SearchClients(query, context=self._context)
  File "/usr/local/lib/python2.7/dist-packages/grr_api_client/client.py", line 225, in SearchClients
    items = context.SendIteratorRequest("SearchClients", args)
  File "/usr/local/lib/python2.7/dist-packages/grr_api_client/context.py", line 48, in SendIteratorRequest
    first_page = pages.next()
  File "/usr/local/lib/python2.7/dist-packages/grr_api_client/context.py", line 31, in _GeneratePages
    result = self.connector.SendRequest(handler_name, args_copy)
  File "/usr/local/lib/python2.7/dist-packages/grr_api_client/connectors/http_connector.py", line 225, in SendRequest
    self._InitializeIfNeeded()
  File "/usr/local/lib/python2.7/dist-packages/grr_api_client/connectors/http_connector.py", line 116, in _InitializeIfNeeded
    self._FetchRoutingMap()
  File "/usr/local/lib/python2.7/dist-packages/grr_api_client/connectors/http_connector.py", line 78, in _FetchRoutingMap
    self._CheckResponseStatus(response)
  File "/usr/local/lib/python2.7/dist-packages/grr_api_client/connectors/http_connector.py", line 186, in _CheckResponseStatus
    raise errors.ResourceNotFoundError(message)
grr_api_client.errors.ResourceNotFoundError: No API router was found for (/api/v2/reflection/api-methods) GET

Any idea on how to solve that would be very much appreciated.

**Comment by mbushkov** [comment]
Seems like you're running a release version of GRR server. grr-api-client only works with the version from HEAD :(

Upgrading the server to HEAD version may be the simplest option (see https://github.com/google/grr-doc/blob/master/installfrompip.adoc#installing-grr-server-for-dev-ie-tracking-head). Please note that you don't have to upgrade the clients - HEAD version of the server talks normally with existing clients.

Anyway, can you provide a bit more context about what you're trying to do? Do you want to automate/script something?

**Comment by kta01** [comment]
Sure, my intentions are to run GRR, Plaso, Elasticsearch and Timesketch on the same host.
For ease of investigation, I would like to collect artifacts through GRR agents and analyze them in a common format through Timesketch, similar to what is presented in following demo: https://www.youtube.com/watch?v=JciAp0uB7AY.

I intend to further adapt referenced script "runlog2timeline.py", but I'm having difficulties in identifying the hosts reporting in GRR. That's why I've been asking about the SearchClients command.

Would you have any recommendations?

**Comment by mbushkov** [comment]
I think it makes sense to upgrade your GRR server to GitHub HEAD version (see https://github.com/google/grr-doc/blob/master/installfrompip.adoc#installing-grr-server-for-dev-ie-tracking-head and https://groups.google.com/d/msg/grr-users/kpx6rLj2Fp4/it_PTW0-AAAJ). This way it would be much easier for us to debug the issues, in case you have any, and to fix bugs. The "GRR Fuse, Plaso and Timesketch" video is pretty old and there were a lot of changes done to GRR implementation since the video was recorded.

grr_api_shell-based clients search should start working after the upgrade. Then you can pretty much run runlog2timeline.py inside grr_api_shell or, alternatively, refactor the script into a standalone program that depends on grr_api_client package (see https://github.com/google/grr/tree/master/api_client/python#initializing-the-grr-api-object).

**Comment by kta01** [comment]
Tank you mbushkov for your help! I have taken your advice and upgraded to github HEAD version using the instructions provided at https://github.com/google/grr-doc/blob/master/installfrompip.adoc#installing-grr-server-for-dev-ie-tracking-head.

After changing /etc/default/grr-server to include the new path, when starting grr_service server it does start, but no http listeners opened:
# service grr-server start
# service grr-server status
● grr-server.service - GRR Service
   Loaded: loaded (/lib/systemd/system/grr-server.service; enabled; vendor preset: enabled)
   Active: active (exited) since Fri 2017-06-23 13:04:18 UTC; 3s ago
     Docs: https://github.com/google/grr
  Process: 7067 ExecStop=/bin/systemctl --no-block stop grr-server@ui.service grr-server@http_server.service grr-server@worker.service grr-server@worker2.service (code=exited, status=0/SUCCESS)
  Process: 7696 ExecStart=/bin/systemctl --no-block start grr-server@ui.service grr-server@http_server.service grr-server@worker.service grr-server@worker2.service (code=exited, status=0/SUCCESS)
 Main PID: 7696 (code=exited, status=0/SUCCESS)
    Tasks: 0
   Memory: 0B
      CPU: 0
   CGroup: /system.slice/grr-server.service
Jun 23 13:04:18 grr001 systemd[1]: Starting GRR Service...
Jun 23 13:04:18 grr001 systemd[1]: Started GRR Service.


Comparing to what components started previous at installation, I have tried to start them manually:
/bin/bash /usr/bin/grr_server --component worker --disallow_missing_config_definitions -p StatsStore.process_id=worker_e5a3155a08e64ad893e69f6583eb2906
	OK
/bin/bash /usr/bin/grr_server --component worker2 --disallow_missing_config_definitions -p StatsStore.process_id=worker2_e5a3155a08e64ad893e69f6583eb2906
	OK
/bin/bash /usr/bin/grr_server --component http_server --disallow_missing_config_definitions -p StatsStore.process_id=http_server_e5a3155a08e64ad893e69f6583eb2906
Traceback (most recent call last):
  File "/usr/local/GRR_NEW//bin/grr_server", line 11, in <module>
    load_entry_point('grr-response-server', 'console_scripts', 'grr_server')()
  File "/usr/local/grr/grr/lib/distro_entry.py", line 82, in GrrServer
    flags.StartMain(grr_server.main)
  File "/usr/local/grr/grr/lib/flags.py", line 112, in StartMain
    main([sys.argv[0]])
  File "/usr/local/grr/grr/tools/grr_server.py", line 55, in main
    "%s." % flags.FLAGS.component)
RuntimeError: No valid component specified. Got: http_server.

Am I missing something? Any advice on how to further debug?

**Comment by mbushkov** [comment]
Please see https://groups.google.com/forum/#!msg/grr-users/kpx6rLj2Fp4/it_PTW0-AAAJ:

> just edit the /etc/systemd/system/grr-server.service file to change "http_server" to "frontend" and "ui" to "admin_ui"


Please tell me if this helps and if it does, I'll update the docs accordingly.

**Comment by kta01** [comment]
Yes, that fixed it. I was able to start GRR http server.

Unfortunately, when I try to run grr_api_shell from the new location, I basically get the same error as previously:

/usr/local/GRR_NEW/bin/grr_api_shell --basic_auth_username "user" --basic_auth_password "xxx" --exec_code 'print "\n".join(c.client_id for c in grrapi.SearchClients(""))' http://localhost:1234
Traceback (most recent call last):
  File "/usr/local/GRR_NEW/bin/grr_api_shell", line 11, in <module>
    load_entry_point('grr-api-client', 'console_scripts', 'grr_api_shell')()
  File "/usr/local/grr/api_client/python/grr_api_client/api_shell.py", line 81, in main
    exec (flags.exec_code, dict(grrapi=grrapi))
  File "<string>", line 1, in <module>
  File "/usr/local/grr/api_client/python/grr_api_client/api.py", line 24, in SearchClients
    return client.SearchClients(query, context=self._context)
  File "/usr/local/grr/api_client/python/grr_api_client/client.py", line 227, in SearchClients
    items = context.SendIteratorRequest("SearchClients", args)
  File "/usr/local/grr/api_client/python/grr_api_client/context.py", line 48, in SendIteratorRequest
    first_page = pages.next()
  File "/usr/local/grr/api_client/python/grr_api_client/context.py", line 31, in _GeneratePages
    result = self.connector.SendRequest(handler_name, args_copy)
  File "/usr/local/grr/api_client/python/grr_api_client/connectors/http_connector.py", line 214, in SendRequest
    self._InitializeIfNeeded()
  File "/usr/local/grr/api_client/python/grr_api_client/connectors/http_connector.py", line 105, in _InitializeIfNeeded
    self._FetchRoutingMap()
  File "/usr/local/grr/api_client/python/grr_api_client/connectors/http_connector.py", line 72, in _FetchRoutingMap
    self._CheckResponseStatus(response)
  File "/usr/local/grr/api_client/python/grr_api_client/connectors/http_connector.py", line 175, in _CheckResponseStatus
    raise errors.ResourceNotFoundError(message)
grr_api_client.errors.ResourceNotFoundError: No API router was found for (/api/v2/reflection/api-methods) GET

"/usr/local/grr/" is the location where I cloned https://github.com/google/grr.git.

Thank you!

**Comment by mbushkov** [comment]
Just double checking: in the example above, `http://localhost:1234` is the address of the GRR Admin UI, right?

Can you please try manually triggering these 3 URLs in the browser:
* http://localhost:1234/api/v2/reflection/api-methods
* http://localhost:1234/api/reflection/api-methods
* http://localhost:1234/api/clients

What do you get as results?

**Comment by kta01** [comment]
Yes, localhost:1234 is the location of Admin web UI.
I have tried the three mentioned URLs:
    http://localhost:1234/api/v2/reflection/api-methods - File not found.
    http://localhost:1234/api/reflection/api-methods - File not found.
    http://localhost:1234/api/clients - response.json file returned containing lots of information, including machines info where agents reside.

**Comment by mbushkov** [comment]
Thanks for the answers! The behaviour you describe means that the requests hit the old AdminUI process. Can it be that there're stale AdminUI processes still running on the system that still handle the requests?

**Comment by kta01** [comment]
A machine reboot sorted the things out. I was able to run grr_api_shell successfully.
Thank you very much for your support mbushkov, ver much appreciated! 
Kind regards.
