### ISSUE TITLE
grrdocker/grr:latest grr Error and missing excecutables

### ISSUE THREAD

**Issue by kalle44** [google/grr#512]
Hi,  

in reference to my last issue #511, I tried to install the latest GRR Version by using docker _grrdocker/grr:latest grr_.

I could start the Admin UI, but the excecutables are missing. How could that be?

![docker grr latest4](https://user-images.githubusercontent.com/29337312/27050679-c1120626-4fb3-11e7-9c95-398dcc73236f.PNG)

After I pointed my browser on the Admin UI, this Error appeared: 

![docker grr latest3](https://user-images.githubusercontent.com/29337312/27050836-399ebda0-4fb4-11e7-8529-9c3e4100411e.PNG)

Did someone else tried to install this grr-version, too?
The shell ist doing some kind of logging, is it intended that way? 

Greetings from Germany, 
John

**Comment by kalle44** [comment]
Maybe these screenshots of the installation using docker could help to find out what was going wrong :)

![docker grr latest](https://user-images.githubusercontent.com/29337312/27051774-a6792462-4fb7-11e7-8a98-a23ee7f0107e.PNG)
![docker grr latest2](https://user-images.githubusercontent.com/29337312/27051776-aa080e04-4fb7-11e7-8175-57fb5d0e81ee.PNG)

Hopefully somone could solve this issue :)

**Comment by mbushkov** [comment]
Regarding the http exception - it's not really an error. It's an HTTP 404 triggered by the browser trying to fetch a favicon (see https://en.wikipedia.org/wiki/Favicon). It's safe to ignore this error.

As for not seeing the binaries, please do the following in the Docker container's shell (assuming it's bash):
```
source /usr/share/grr-server/bin/activate
grr_config_updater initialize
```

Make sure to answer "Y" to following questions:
```
Step 4: Installing template package and repackaging clients with new configuration.
Download client templates? You can skip this if templates are already installed.[Yn]: y
Repack client templates?[Yn]: y
```

This will download and repack GRR agents and you'll see them in "Manage Binaries".

If you just want to quickly run a test GRR agent within GRR server's container (maybe useful for testing), this should work:
```
source /usr/share/grr-server/bin/activate
grr_client -pClient.poll_max=5 --verbose
```

**Comment by kalle44** [comment]
Ok, I resolve my Issue attaching to the running docker-container via
_sudo docker exec CLIENT_ID bash_ and then using your commands.

I downloaded the excecutable and installed it on the Windows10x64 Client.
Server-Client connection is working. 

When I try to start a "AnalyzeClientMemory" flow this Error appeared.

![grr-rekall_1-6-0 not found2](https://user-images.githubusercontent.com/29337312/27070713-6f7aa1f8-501a-11e7-887a-11351c4d6d56.PNG)

The Traceback: 
![grr-rekall_1-6-0 not found](https://user-images.githubusercontent.com/29337312/27070724-7bc3b026-501a-11e7-8111-12da91b80cb1.PNG)

The same Issue is discripted in here #508 
Changing the component-version to 0.4 worked.

**Comment by demonchild2112** [comment]
Update: The latest docker image should now have client templates.
