### ISSUE TITLE
HTTP-API Yarascan Parse Error!?

### ISSUE THREAD

**Issue by kalle44** [google/grr#513]
Hi, 

when I try to run this curl-command: 

![image](https://user-images.githubusercontent.com/29337312/27091686-29844360-5061-11e7-9293-7e62adbd26ab.png)

This output appeard in the bash
![image](https://user-images.githubusercontent.com/29337312/27091792-7e844680-5061-11e7-90e2-5c405a17553d.png)

The term $signature is missing, so this error occured:
_SyntaxError: syntax error, unexpected '=', expecting _STRING_IDENTIFIER__ 

Maybe it's more a bash-issue then a grr problem, but hopefully somone can help me on this error.

Greetings from Germany,
John

**Comment by mbushkov** [comment]
Hi John! This looks as if bash interprets $signature as a variable. We should either escape it or change the command a bit.

I noticed you closed the issue. Did you find a workaround?

**Comment by kalle44** [comment]
Hi,

when you place a \ in front of the $signature1, bash doesn't interprets it as a variable.
So I used sed to replace the $-char with \$ 

![image](https://user-images.githubusercontent.com/29337312/27096148-61a42698-5070-11e7-9707-6936dd32c622.png)

As you can see I substitute $sig for \$sig because of the sed-internals. Just writing \\$ gives you a \$ at the end of every line :D 
It's a workaround, but it works well for me.
