### ISSUE TITLE
Automating grr_config_updater initialize

### ISSUE THREAD

**Issue by karan1337** [google/grr#515]
Is there a way to pass configuration parameters to grr_config_updater so that it does not prompt for user input?

This requirement is to automate deployment without user intervention. Any help is appreciated.

@grrrrrrrrr @pidydx Any ideas?

**Comment by mbushkov** [comment]
There's apparently some support for "no prompt" behavior built into grr_config_updater. This is what I get by running `grr_config_updater initialize --help`:

```
usage: grr_config_updater initialize [-h]
                                     [--external_hostname EXTERNAL_HOSTNAME]
                                     [--admin_password ADMIN_PASSWORD]
                                     [--noprompt] [--no_templates_download]

optional arguments:
  -h, --help            show this help message and exit
  --external_hostname EXTERNAL_HOSTNAME
                        External hostname to use.
  --admin_password ADMIN_PASSWORD
                        Admin password for web interface.
  --noprompt            Set to avoid prompting during initialize.
  --no_templates_download
                        Set to avoid downloading the templates during
                        initialize.
```

This command works for me:
```
grr_config_updater initialize --noprompt --external_hostname localhost --admin_password demo
```

What is your intended workflow? Do you need to install GRR server on demand? Do you plan to do it on a VM or on a real machine?

**Comment by karan1337** [comment]
@mbushkov Thanks for the reply. 

Yes the intended use case is to install a GRR server on demand on a real machine.

**Comment by mbushkov** [comment]
@karan1337 Thank for a quick response!

I'm still curious about your use-case :) Do you need to install GRR server on demand as part of an autoscaling procedure of some sort? I mean, normally GRR server is the stable part of GRR that gets installed once and then just sits there and waits for the clients to connect to it. GRR clients are usually the ones to be installed on demand in all kinds of environments.

**Comment by karan1337** [comment]
@mbushkov Yes I would put it like that. GRR-servers on demand. The idea is to automate setup as much as possible to serve at scale.

**Comment by pidydx** [comment]
grr_config_updater only needs to be run once for an entire deployment to initialize the datastore.  Individual GRR servers will just need a copy of the server.local.yaml

**Comment by karan1337** [comment]
@pidydx Makes sense. Thanks for pointing that out.

**Comment by grrrrrrrrr** [comment]
This is solved as by @pidydx 's comment.

**Comment by wiredaem0n** [comment]
I see the case is closed, not sure if we can re-open it.
Got a case where it would be great to be able to initialize it using MySQL DataSstore and not the default SQLLite.  Any idea if we could pass such parameters besides whats on the help page?
