### ISSUE TITLE
Implement "hits" counter in the hunt info page

### ISSUE THREAD

**Issue by ghost** [google/grr#516]
When reading the hunt info (that's basically the overview tap in the UI) we get the completed clients count. Besides that an analyst would like to see if anything and how many hits were already found with a hunt. 
So one would like to know in one shot how many clients are completed and how many hits were found ("total_count").

It could be a quick way to see if there are any hits by showing a "hits" count that will display number of clients with >0 results in the hunt info page.

**Comment by Karneades** [comment]
Is there any update or plan to implement that feature?

**Comment by grrrrrrrrr** [comment]
Sorry we haven't started working on this one yet. We think it's a good feature to have but we just don't have the cycles atm. We do accept PRs though! :)

**Comment by grrrrrrrrr** [comment]
A quick update on this, since 35797795b9088e3378c91c82a109651d8b8edb6e we do display those counters in the UI.
