### ISSUE TITLE
grr_api_shell "AnalyzeClientMemory" How to change the Component Version?

### ISSUE THREAD

**Issue by kalle44** [google/grr#520]
Hi, 

I try scripting GRR by using the grr_api_shell.

My Python-Code to start the flow:
_c = grrapi.Client("C.70ccc6cdf8209c28")
args = grrapi.types.CreateFlowArgs("AnalyzeClientMemory")
plugin = args.request.plugins.add()
plugin.plugin = "yarascan"
data = plugin.args.dat.add()
data.k.string = "yara_expression"
data.v.string = "bla"
flow = c.CreateFlow("AnalyzeClientMemory", args)_

The job chrashes with this error:
![grr_api_shell_componenterror](https://user-images.githubusercontent.com/29337312/27275432-a9952a36-54d7-11e7-9723-b212f3013c20.PNG)

I'm using the GRR-Version from HEAD, so I changed the component version from 1.6.0(default) to 0.4 to run the "AnalyzeClientMemory" Flow on AdminGUI. Otherwise the flow chrashes with the same error.

Because of the "flow hint" the GUI gives to start the flow using the API:

![grr_api_shell_componenterror_flowhint](https://user-images.githubusercontent.com/29337312/27275918-b0cdd01c-54d9-11e7-9a68-0a2a69021e79.PNG)

I thought about something like  this:
_componentVersion = args.____
When using _args._ I can get the COMPONET_VERSION_FIELD_NUMBER, which return "6"

I can't figure out ,what line of code i have to add to my code to change the component version from 1.6.0 (default) to 0.4?
Hopefully someone knows how to do it? :)

Greetings from Germany

**Comment by mbushkov** [comment]
This should work:
```
args.component_version = "0.4"
```

"args" is a protobuf (https://developers.google.com/protocol-buffers/docs/pythontutorial) and you can see the name of the protobuf in the ```@type``` field of the API hint. Knowing the protobuf name you normally can look up its definitition in the code: https://github.com/google/grr/search?l=Protocol+Buffer&q=AnalyzeClientMemoryArgs&type=&utf8=%E2%9C%93 - this may help a lot when figuring out what parameters a flow has

**Comment by kalle44** [comment]
Thank you, :)

that is exactly what I was looking for!
