### ISSUE TITLE
Two Python traces related to broken FS and entrypoint killing

### ISSUE THREAD

**Issue by mike-bailey** [google/grr#526]
I've found which I'm not nearly senior enough to debug. We're deploying Docker instances at a relatively large scale, and every third basically launches. Launching via Docker Remote API and building the host mounts via SSH (first host mounts then create), the docker/latest is running errors:

[Scenario 1: Kill Shell](https://pastebin.com/0etzH1aR)
[Scenario 2: Broken FS](https://pastebin.com/H4C4MUwK)

On Ubuntu host but I'd imagine that doesn't help since it's all dockerized. As far as I can tell it's not any sort of resource crunch. The calls are being made via Ruby. 

Exact ruby SDK call (as far as I can tell works) which immediately follows the SSH command:
```
@container = Docker::Container.create('Image' => 'grrdocker/grr', 'Cmd' => 'grr', 
		'ENV' => ["EXTERNAL_HOSTNAME=test.subdomain.com","ADMIN_PASSWORD=test"], 
		'Volumes' => {
		"/docker/#{engagement}/grr-docker/db": { },
		"/docker/#{engagement}/grr-docker/logs": { }
		},
		'PortBindings' => { "8080/tcp": [{ "HostPort": "#{firstport}" }], "8000/tcp": [{ "HostPort": "#{secondport}" }]}, 
		'Binds' => [ "/docker/#{engagement}/grr-docker/db:/var/grr-datastore:rw", "/docker/#{engagement}/grr-docker/logs:/var/log:rw" ])
```

**Comment by grrrrrrrrr** [comment]
Sorry we never got around to look at this issue. I expect this is now obsolete? Please reopen if this is still a problem with the latest GRR version.
