### ISSUE TITLE
300 clients. All check in once, and then never come back online again.

### ISSUE THREAD

**Issue by ss105** [google/grr#529]
Hey all,

I have grr installed on Windows 7/10.  About 300 clients.  I started with 6 clients for testing.  When I had 6 clients, they all polled consistently and all my hunts and flows worked.  I then installed it for testing on every technology workstation in my enterprise.  That is about 300 machines.  What happens at that point is all 300 or so workstations will check in successfully only ONE time.  They never are seen again and I can't hunt or flow.  The server is Ubuntu Xenial 32 gb of ram and 2800 mhz 16 core AMD Opteron.  My company gave me a retired HP ILO server.  HTOP shows no issues.  IFTOP shows nothing crazy either as far as bandwidth, at times 5 mb/s.  As I run IFTOP now I see my workstations sending and receiving data(much less though) yet they are not seen by GRR since the first check in.  At 300 workstations can I not use an HP ILO?  I know this is the adapter the GRR server is using:

Adapter 2 - HP Ethernet 1Gb 4-port 331FLR Adapter

**Comment by grrrrrrrrr** [comment]
Hey sorry we missed this report. Do you still have the same issues? 300 machines isn't all that many, I don't expect that there are any issues with resources. Have you tried to troubleshoot using https://github.com/google/grr-doc/blob/master/troubleshooting.adoc#i-dont-see-my-clients ?

**Comment by ss105** [comment]
Hi,

Thanks for reply.  We are now at 1000 or so clients because the 300 clients seemed to of randomly resolved itself.  I don't remember but running the cron jobs may of fixed that.  It has come back again with a vengeance unfortunately.  A few clients check in then die.  Hundreds more never check in.  In the logs I can see HUGE amounts of table issues and IO errors like : too many files open.  The clients are all talking to the server as I can see it in IFTOP but it doesn't seem to be reflected in the web gui.

**Comment by ss105** [comment]
pic1.
![grrr2](https://user-images.githubusercontent.com/30242135/30722003-b970b96a-9efc-11e7-8b33-e25247135ee5.png)
pic 2
![grr1](https://user-images.githubusercontent.com/30242135/30722001-b6f71486-9efc-11e7-9999-f056c95ca7e2.png)

**Comment by ss105** [comment]
I increased my max connections to 50 and min connections to 10.  WAY more hosts check in but then seem to not poll again.

**Comment by grrrrrrrrr** [comment]
It seems like you run into some limit on the number of open files for a single process. I found this page: https://easyengine.io/tutorials/linux/increase-open-files-limit/ which gives you suggestions on how to increase the various limits that could be to blame in this case.

Note that this is not really a GRR issue but rather some quirk on your OS. You could try running GRR on MySQL instead of Sqlite which would reduce the number of open files.

**Comment by grrrrrrrrr** [comment]
Is this still an issue or can we close it?

**Comment by ss105** [comment]
Never resolved.

On May 14, 2018, at 7:44 AM, Andreas Moser <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this still an issue or can we close it?

**Comment by ss105** [comment]
My boss and I agreed that trying to use this at the enterprise level with 4000 endpoints with SQLlite was a mistake.  I had to abandon the project because of other priorities.

Shawn Seaman
Information Security
Lazard
30 Rockefeller Plaza
New York, NY 10112
shawn.seaman@lazard.com<mailto:shawn.seaman@lazard.com>
+1 212 632 6796 phone

**Comment by grrrrrrrrr** [comment]
We have a much better data store based on MySQL now, would be perfect for this use case! :)
