### ISSUE TITLE
Client/Server Connection Issues: "None is not a valid HKEY"

### ISSUE THREAD

**Issue by jturner900** [google/grr#532]
After downloading the .exe to the client machine, I ran it.  Nothing registered on server machine GUI, so I went back to the client machine and ran the dbg_*.exe.  I navigated to the GRR/3.1.0.2 directory and entered the following:

_prompt% GRR.exe --config=GRR.exe.yaml --verbose_

I got a series of logging text ending with 

_prompt% TypeError: None is not a valid HKEY in this context
client returned -1_

What could be the problem?  I placed the entire log dump below.

_C:\Windows\System32\GRR\3.1.0.2>GRR.exe --config=GRR.exe.yaml --verbose
INFO:2017-07-27 22:41:26,700 log:197] Starting GRR Prelogging buffer.
INFO:2017-07-27 22:41:26,757 config_lib:1101] Loading configuration from GRR.exe.yaml
INFO:2017-07-27 22:41:26,759 config_lib:1101] Loading configuration from build.yaml
DEBUG:2017-07-27 22:41:26,760 regconfig:43] Unable to open config registry key: [Error 5] Access is denied
INFO:2017-07-27 22:41:26,760 config_lib:1101] Loading configuration from reg://HKEY_LOCAL_MACHINE/Software\GRR
INFO:2017-07-27 22:41:26,760 config_lib:810] Configuration writeback is set to reg://HKEY_LOCAL_MACHINE/Software\GRR
DEBUG:2017-07-27 22:41:26,760 log:155] Initializing Logging subsystem.
DEBUG:2017-07-27 22:41:26,762 log:107] Will use logging engines ['file', 'stderr', 'event_log']
DEBUG:2017-07-27 22:41:26,762 config_lib:660] Applying filter env for WINDIR.
INFO:2017-07-27 22:41:26,762 log:137] Writing log file to C:\Windows\System32\logfiles\\GRR.log
ERROR:2017-07-27 22:41:26,762 log:150] Unable to create logger file
Traceback (most recent call last):
  File "site-packages\grr\lib\log.py", line 141, in GetLogHandlers
  File "logging\__init__.py", line 905, in __init__
  File "logging\__init__.py", line 935, in _open
IOError: [Errno 13] Permission denied: u'C:\\Windows\\System32\\logfiles\\GRR.log'
ERROR:2017-07-27 22:41:26,763 log:150] Unable to create logger event_log
Traceback (most recent call last):
  File "site-packages\grr\lib\log.py", line 118, in GetLogHandlers
  File "logging\handlers.py", line 972, in __init__
  File "site-packages\win32\lib\win32evtlogutil.py", line 42, in AddSourceToRegistry
error: (5, 'RegSetValueEx', 'Access is denied.')
DEBUG:2017-07-27 22:41:26,773 registry:166] Initializing CommunicatorInit
DEBUG:2017-07-27 22:41:26,773 registry:166] Initializing CommsInit
DEBUG:2017-07-27 22:41:26,775 registry:166] Initializing VFSInit
DEBUG:2017-07-27 22:41:26,776 registry:166] Initializing InitHook
DEBUG:2017-07-27 22:41:26,778 config_lib:660] Applying filter env for SystemRoot.
DEBUG:2017-07-27 22:41:26,780 config_lib:660] Applying filter env for SystemRoot.
DEBUG:2017-07-27 22:41:26,782 config_lib:660] Applying filter env for WINDIR.
DEBUG:2017-07-27 22:41:26,785 client_utils_windows:175] Found proxy servers: []
INFO:2017-07-27 22:41:27,568 comms:1502] Client pending enrolment aff4:/C.f4a46e488896b6a1
INFO:2017-07-27 22:41:27,569 regconfig:65] Writing back configuration to key \Software\GRR
Traceback (most recent call last):
  File "<string>", line 66, in <module>
  File "site-packages\grr\lib\flags.py", line 121, in StartMain
  File "<string>", line 53, in main
  File "site-packages\grr\client\comms.py", line 1134, in __init__
  File "site-packages\grr\lib\communicator.py", line 342, in __init__
  File "site-packages\grr\client\comms.py", line 1509, in _LoadOurCertificate
  File "site-packages\grr\client\comms.py", line 1533, in SavePrivateKey
  File "site-packages\grr\lib\config_lib.py", line 952, in Write
  File "site-packages\grr\client\windows\regconfig.py", line 75, in SaveData
TypeError: None is not a valid HKEY in this context
client returned -1_

**Comment by grrrrrrrrr** [comment]
IIRC this happens when you run the client with insufficient privileges. Does your cmd prompt have admin rights?

**Comment by jturner900** [comment]
Yes, that appears to have solved that issue, thanks.  Now the error log from GRR_installer is 

Loading configuration from GRR.exe.yaml
Loading configuration from build.yaml
Starting installation procedure for GRR client.
Initializing Installer
Initializing CheckForWow64, required by CopyToSystemDir
Initializing CopyToSystemDir
Attempting to stop service GRR Monitor
Applying filter env for SystemRoot.
Installing binaries C:\Users\jt\AppData\Local\Temp\TMP6731.tmp -> C:\Windows\System32\GRR\3.1.0.2
Initializing UpdateClients
Loading configuration from reg://HKEY_LOCAL_MACHINE/Software\GRR
Configuration writeback is set to reg://HKEY_LOCAL_MACHINE/Sof0tware\GRR
mapping HKEY_LOCAL_MACHINE\Software\GRR\certificate->Client.private_key ignored: [Error 2] The system cannot find the file specified
mapping HKEY_LOCAL_MACHINE\Software\GRR\Client\private_key->Client.private_key ignored: [Error 2] The system cannot find the file specified
mapping HKEY_LOCAL_MACHINE\Software\GRR\server_serial_number->Client.server_serial_number ignored: [Error 2] The system cannot find the file specified
Writing back configuration to key \Software\GRR
Initializing WindowsInstaller
Loading configuration from reg://HKEY_LOCAL_MACHINE/Software\GRR
Configuration writeback is set to reg://HKEY_LOCAL_MACHINE/Software\GRR
Applying filter env for SystemRoot.
Writing back configuration to key \Software\GRR
Calling ([u'C:\\Windows\\System32\\GRR\\3.1.0.2\\GRRservice.exe', '--service_key', u'Software\\GRR', 'install'],)
(null)
Stopping Service
Service is already stopped.
Service: GRR Monitor started as: C:\Windows\System32\GRR\3.1.0.2\GRRservice.exe

**Comment by grrrrrrrrr** [comment]
So it's working now? This log indicates success, are there any issues?

**Comment by jturner900** [comment]
Someone else in the office got it to work.  Thanks for checking on me.
