### ISSUE TITLE
prelink breaks grrd binary

### ISSUE THREAD

**Issue by mmb** [google/grr#534]
When prelink cron jobs run they modify and break the grrd binary.

Could the agent .deb and .rpm include a blacklist entry so that prelink will not change grrd?

For the RPM adding `/etc/prelink.conf.d/grr` with contents:

```
-b /usr/lib{,64}/grr
```

will fix it.

**Comment by demonchild2112** [comment]
Prelink is deprecated, and we recently removed it as a dependency. Are you running GRR 3.2.0.0?

**Comment by demonchild2112** [comment]
For rpms, this should be fixed by https://github.com/google/grr/commit/1a631a36b5bff2dd561f91ecc03624900ebb7297
