### ISSUE TITLE
MySQLAdvancedDataStore makes grr_datastore crash on startup

### ISSUE THREAD

**Issue by B3N4K** [google/grr#535]
Hello,

I did fresh install of latest version using PIP and did grr_config_updater initialize successfully but my grr_datastore crashes on startup with following error:

```
DEBUG:2017-08-24 11:30:07,921 config_lib:697] Applying filter resource for install_data/etc.
DEBUG:2017-08-24 11:30:07,923 auth_manager:37] Adding 0 authorizations
DEBUG:2017-08-24 11:30:07,923 registry:137] Initializing IPResolverInit
DEBUG:2017-08-24 11:30:07,923 ip_resolver:82] Using ip resolver: IPResolver
Traceback (most recent call last):
  File "/usr/local/GRR/bin/grr_dataserver", line 11, in <module>
    load_entry_point('grr-response-server', 'console_scripts', 'grr_dataserver')()
  File "/usr/local/grr/grr/lib/distro_entry.py", line 137, in DataServer
    flags.StartMain(data_server.main)
  File "/usr/local/grr/grr/lib/flags.py", line 114, in StartMain
    main(sys.argv)
  File "/usr/local/grr/grr/server/data_server/data_server.py", line 881, in main
    is_master=flags.FLAGS.master)
  File "/usr/local/grr/grr/server/data_server/data_server.py", line 793, in Start
    reqhandler_cls.SERVICE = store.DataStoreService(db)
  File "/usr/local/grr/grr/server/data_server/store.py", line 104, in __init__
    self.db.RecreatePathing(self.pathing)
AttributeError: 'MySQLAdvancedDataStore' object has no attribute 'RecreatePathing'
```

Worker, frontend and adminui works well (well it starts up) but grr_datastore always crashes. Is MySQL fully supported at the moment and is this normal error everyone gets? From the error it seems to me like  MySQLAdvancedDataStore is not fully implemented yet and thus it crashes.

What should I do, does anyone have any advice?

Thanks for any help!

EDIT: PS - Using SQLite datasore makes the error not show up and all works well. But we'd really like to use MySQL so any and all help would be much appreciated.

**Comment by grrrrrrrrr** [comment]
Hey,

So maybe this is not super clear in the docs but the combination you are trying to run doesn't make much sense. The data_server provides remote capabilities to a data store that doesn't have them - SQLite. If you want to use MySQL, you can just connect to it directly, no need to use the data server, and this is why it's not supported.

This is all assuming you mean grr_dataserver crashes for you, there is no grr_datastore binary.

Cheers,
-Andy

**Comment by B3N4K** [comment]
Ohhhhh that absolutely makes sense. This was clearly mistake on my end, i misunderstood the role of grr_dataserver. Thank you for your help!
