### ISSUE TITLE
Missing CSV Output Plugin

### ISSUE THREAD

**Issue by PhalanxSecurity** [google/grr#537]
Hi All,

I'm testing out grr and ran into an issue on an Ubuntu 16.04 freshly installed box where I am missing the CSV Output Plugin option and have "UnknownOutputPlugin" in its place. I had followed the quick-start guide using the deb install. Could you provide any help on how to fix this?

Thanks,
Josh

**Comment by grrrrrrrrr** [comment]
Hey Josh,

The reason that the plugin doesn't show up anymore is that we have deprecated it. With the new version, you just run your hunt, go to the results tab, and chose download as CSV, YAML, or Sqlite. No planning ahead when starting the hunt needed anymore.

I'm wondering though why you see the UnknownOutputPlugin. When this was first reported I assumed old data in the data store but you are running a clean install. We'll have a look...

**Comment by grrrrrrrrr** [comment]
Output plugin is not shown in the list anymore after
https://github.com/google/grr/commit/9248765d6bbc799de1511971c6c3af75e4847f6b

Thanks for the report!
