### ISSUE TITLE
Q: Is there a way how to execute pre-packed code on linux (as artifact)?

### ISSUE THREAD

**Issue by B3N4K** [google/grr#539]
Hello,

I have a small problem that i just cannot find good enough solution to myself. We have a forensic tool that we are using to collect some data on the machines. This is essential tool collecting stuff that we will want to collect on pretty much all machines so it would be best to pre-pack it in the GRR agent.

I was able to pre-pack it on windows, then add custom COMMAND artifact that executes it as a command. However when i try to do the same thing on Linux i run into a problem. First of all, the command needs to be specified as absolute path but GRR is installed into different folder every time depending on system/architecture/grr version. Therefore it is impossible to simply point to the pre-packaged tool because its not clear where the GRR is installed. I found out that the LD_LIBRARY_PATH envvar is available and contains the path to where the GRR is installed when running COMMAND artifact, however the variable is not getting expanded when passed as argument, so for example following command artifact does not work:

```
- type: COMMAND
  attributes:
    args: ["$LD_LIBRARY_PATH/custom-script.sh"]
    cmd: /bin/bash
```

Now it would be possible to do this with LaunchBinary flow but this is essential tool that we will want to use often so it would be best to have it already pre-packed and available on the system and not have to send it every time.

Is this already implemented and possible to do in some elegant and good way that i cannot see, or do i have to modify client to allow this functionality?

Thank you for any help and tips. Just for the record i really tried everything that came into my mind and already sunk several hours into this, but i just cannot think of any solution that wouldn't be terrible hack and i think that i must not be the only one who needs this so there just has to be some way that i simply cannot see (ideally as artifact). Thank you!

**Comment by grrrrrrrrr** [comment]
Hey,

This is not easily done via an artifact, the changing path of the client directory will make the whitelist block your executions. Would writing a python hack that locates and executes the file work here? It's a bit hackish too but at least it would work. There is an example of a python hack that executes a binary in https://github.com/google/grr/blob/master/executables/python_hacks/shutdown_host.py

One last thing, this is not really an issue, I'd recommend asking questions like this on grr-users@ instead...

**Comment by B3N4K** [comment]
Thank you for reply. I didnt't know that there is another channel that would be more suitable, i will post questions like this there from now on. Sorry and thank you for your answer!
