### ISSUE TITLE
Why i can´t  see in TSK mode metadata files of NTFS file system?

### ISSUE THREAD

**Issue by jmmalcala** [google/grr#541]
When I browse virtual filesystem, TSK is able to view Metadate files of NTFS like $MFT or $Extend/$UsnJrnl:$J but with GRR i can´t see these. is this correct?  I this option is very important to download these files and parses locally or maybe parse remotely.
Thanks.

**Comment by grrrrrrrrr** [comment]
Hey,

All the functionality you listed should work with GRR out of the box. What exactly did you try? The way to do this is to go to the tsk branch in the vfs ( /fs/tsk/\\Volume{...}/ ) and update the directory there. All the files you mentioned show up for me, does this not work?

Cheers,
-Andy

**Comment by jmmalcala** [comment]
I´m sorry!

You´re right.

Thanks for replying so fast.

2017-10-11 12:51 GMT+02:00 Andreas Moser <notifications@github.com>:
