### ISSUE TITLE
Repack_clients fail during initialization or on demand

### ISSUE THREAD

**Issue by Xyrodileas** [google/grr#543]
After the installation of the GRR server with the .deb, if launch the command grr_config_updater initialize or grr_config_updater repack_clients, the repacking of the client seems to fail and only the windows client is packaged:

ubuntu@GRRfront:~$ sudo grr_config_updater repack_clients
Using configuration <GrrConfigManager  file="/usr/share/grr-server/install_data/etc/grr-server.yaml"  file="/etc/grr//server.local.yaml" >
Repacking template: /usr/share/grr-server/grr-response-templates/templates/GRR_3.2.0.1_amd64.exe.zip
Using context: ['ClientBuilder Context', 'ClientBuilder Context', 'Arch:amd64', 'Platform:Windows', 'Target:Windows', 'Target:Windows'] and labels: []
Repacked into /usr/share/grr-server/executables/installers/GRR_3.2.0.1_amd64.exe
/usr/bin/grr_config_updater: line 35: 16230 Killed                  "${GRR_PREFIX}/bin/${NAME}" "${GRR_EXTRA_ARGS[@]}" "${@}"

**Comment by grrrrrrrrr** [comment]
In your error it says killed, are you running out of memory?

**Comment by Xyrodileas** [comment]
Indeed, my VM had the wrong RAM. Sorry for this non-issue!
