### ISSUE TITLE
Cannot install GRR client on RHEL 6.9

### ISSUE THREAD

**Issue by coonsmatthew** [google/grr#545]
Hello GRR Community. 

I'm trying to install a GRR client on a RHEL 6.9 box. I'm getting errors related to the GLIB version installed on the system. My GRR server is Ubuntu 16.04. 

The error I'm getting is: 
```/usr/lib64/grr/grr_3.2.0.1_amd64/grrd: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/lib64/grr/grr_3.2.0.1_amd64/libz.so.1)```

I'm guessing that is because the server that the client was complied on has a newer version of GLIBC installed on it. I'm also guessing the best way to get around this is to re-compile the client on a system that has GLIBC_2.14 installed on it? 

If that's so, what's the easiest way to achieve this? I was just going to install the GRR server on a CentOS 6.9 server, but I don't see any good documentation for that. Is there a way to *just* re-compile the RPM on 6.9, so it can be used for that architecture? 

Thank you.

**Comment by mbushkov** [comment]
Hi Matthew,
As for the GRR server, we only support Ubuntu/Debian (see
https://github.com/google/grr-doc/blob/master/faq.adoc#what-operating-system-versions-does-the-server-support).
It's certainly possible to install it on CentOS, but there's no "official"
way of doing that (although this may help:
https://github.com/google/grr-doc/blob/master/installfrompip.adoc).

I checked our client build configuration and it seems that we build GRR
client RPMs on CentOS 7. I'll check whether we can use an earlier CentOS
version to provide better compatibility with earlier CentOS/RedHat releases.

Regarding building a client yourself:
To rebuild a client for a specific RedHat version, you need to first
rebuild the client template and then repack that template with your
server's configuration.

We use Travis+Docker to build GRR client templates that are shipped with
GRR. Please see https://hub.docker.com/r/grrdocker/centos_i686/ and
https://travis-ci.org/google/grr/jobs/289436087/config

You can build/use your own Docker image with a RedHat version you need. If
you redo the steps described in the Travis config (see the scripts here:
https://github.com/google/grr/tree/master/travis), then you should be able
to build your own RPM client template and then to repack it following the
instructions here
<https://github.com/google/grr-doc/blob/3b6c2b6b948957f350c70647eb79ae2a9a703aeb/admin.adoc#repacking-the-client-with-a-new-configuration>
.

Cheers,
Misha

**Comment by coonsmatthew** [comment]
Hello Misha, 

Were you able to find any client RPM's that were built on CentOS 6? Thank you.

**Comment by mbushkov** [comment]
Hi Matthew!
We didn't have free cycles to build a Cent OS 6 client yet, but one of GRR users on grr-users mailing list apparently built it successfully: https://groups.google.com/forum/#!topic/grr-users/zQ3dlzB_A70

I'll update this issue as soon as we have some progress on building a Cent OS 6 client regularly on Travis (unfortunately no ETA yet).

**Comment by demonchild2112** [comment]
I've added a Travis job that will build templates for Centos 6: https://github.com/google/grr/commit/55d5dac7d4ab17af94c688f43f2501783c409c61

The rpm templates included in release server debs are for Centos 7. You can download the latest Centos 6 templates from the 'gs://autobuilds.grr-response.com' GCS bucket.

**Comment by coonsmatthew** [comment]
SWEET! Thanks.
