### ISSUE TITLE
How do I change the UTC time of Web_UI to KST?

### ISSUE THREAD

**Issue by ehdwnssdj** [google/grr#547]
How do I change the UTC time of Web_UI to KST?

**Comment by mbushkov** [comment]
Sorry, there's no support for timezone switch at the moment. I'll mark this issue as a feature request.

**Comment by grrrrrrrrr** [comment]
Hey,

I'm not sure what this feature request is about. @ehdwnssdj are you suggesting to convert all times in the UI? That seems like the wrong thing to do, using UTC everywhere makes much more sense from a forensics standpoint?!
