### ISSUE TITLE
ClientFileFinder "Can\\\'t handle path...

### ISSUE THREAD

**Issue by hannahshort** [google/grr#548]
Hi there, 

I'm trying to use the Client File Finder and receiving an error `"Can\\\'t handle path: %%users.homedir%%/**10/myfile.py"`. I recently enabled ADVANCED mode in settings and haven't repacked the clients since (should I?). According to the ClientFileFinder documentation I think my path is valid: "paths description: A path to glob that can contain %% expansions." I successfully ran the same hunt with the server side FileFinder but it's not scalable for large systems apparently (currently debugging 😃 ). 

Any help appreciated! :)

Example path: 
```
%%users.homedir%%/**10/myfile.py
```

Full error:

message GrrStatus { child_session_id : SessionID: aff4:/hunts/H:678D4D45/C.85972eac3a1c58b0/H:E91B5AF0 cpu_time_used : message CpuSeconds { system_cpu_time : 0.0 user_cpu_time : 0.0 } error_message : u'Traceback (most recent call last):\n File ".../lib/python2.7/site-packages/grr/server/flow_runner.py", line 588, in RunStateMethod\n direct_response=direct_response, request=request, responses=responses)\n File ".../lib/python2.7/site-packages/grr/server/flow.py", line 306, in Decorated\n res = f(*args[:f.func_code.co_argcount])\n File ".../GRR_ENV/lib/python2.7/site-packages/grr/server/flows/general/file_finder.py", line 401, in StoreResults\n raise flow.FlowError(responses.status)\nFlowError: message GrrStatus {\n backtrace : u\'Traceback (most recent call last):\\n File "site-packages\\\\grr\\\\client\\\\actions.py", line 144, in Execute\\n File "site-packages\\\\grr\\\\client\\\\client_actions\\\\file_finder.py", line 152, in Run\\n File "site-packages\\\\grr\\\\client\\\\client_actions\\\\file_finder.py", line 268, in CollectGlobs\\n File "site-packages\\\\grr\\\\client\\\\client_actions\\\\file_finder.py", line 309, in _SplitInitialPathComponent\\nValueError: Can\\\'t handle path: %%users.homedir%%/**10/myfile.py\\n\'\n cpu_time_used : message CpuSeconds {\n system_cpu_time : 0.0\n user_cpu_time : 0.0\n }\n error_message : u\'ValueError("Can\\\'t handle path: %%users.homedir%%/**10/myfile.py",): Can\\\'t handle path: %%users.homedir%%/**10/myfile.py\'\n network_bytes_sent : 691\n status : GENERIC_ERROR\n}\n' network_bytes_sent : 691 status : GENERIC_ERROR }

**Comment by grrrrrrrrr** [comment]
Hey,

This is sadly an expected error at the moment. We haven't really gotten around to implement knowledge base interpolation with the client file finder yet. I'll try to prioritize this.

Cheers,
-Andy

**Comment by mrhania** [comment]
This is now done - client-side file finder can use paths with knowledgebase parameters.
