### ISSUE TITLE
Rekall broken after upgrade to git HEAD

### ISSUE THREAD

**Issue by jah23** [google/grr#550]
I upgraded from .deb installation to git HEAD. Having done this, attempts to run a Memory Collector flow fail with;

`Traceback (most recent call last): File "/home/routergod/grr/grr/server/flow_runner.py", line 589, in RunStateMethod direct_response=direct_response, request=request, responses=responses) File "/home/routergod/grr/grr/server/flow.py", line 301, in Decorated res = f(*args[:f.func_code.co_argcount]) File "/home/routergod/grr/grr/server/flows/general/memory.py", line 103, in CheckAnalyzeClientMemory raise flow.FlowError("Unable to image memory: %s." % responses.status) FlowError: Unable to image memory: message GrrStatus { child_session_id : SessionID: aff4:/C.32283e0d2a3c97a7/flows/F:ECEA8A57/F:5A0FE89D cpu_time_used : message CpuSeconds { system_cpu_time : 0.0 user_cpu_time : 0.187201201916 } error_message : u'Traceback (most recent call last):\n File "/home/routergod/grr/grr/server/flow_runner.py", line 589, in RunStateMethod\n direct_response=direct_response, request=request, responses=responses)\n File "/home/routergod/grr/grr/server/flow.py", line 301, in Decorated\n res = f(*args[:f.func_code.co_argcount])\n File "/home/routergod/grr/grr/server/flows/general/memory.py", line 291, in End\n raise flow.FlowError("Error running plugins: %s" % all_errors)\nFlowError: Error running plugins: Traceback (most recent call last):\n File "site-packages\\grr\\client\\components\\rekall_support\\grr_rekall.py", line 278, in Run\n File "site-packages\\rekall\\session.py", line 862, in RunPlugin\n File "site-packages\\rekall\\session.py", line 859, in RunPlugin\n File "site-packages\\rekall\\plugin.py", line 726, in render\n File "site-packages\\rekall\\plugins\\tools\\aff4acquire.py", line 577, in collect\n File "site-packages\\rekall\\plugins\\tools\\aff4acquire.py", line 589, in collect_acquisition\n File "site-packages\\pyaff4\\rdfvalue.py", line 142, in NewURNFromFilename\n File "site-packages\\pyaff4\\rdfvalue.py", line 136, in FromFileName\n File "nturl2path.py", line 60, in pathname2url\nIOError: Bad path: file:GRR\n\n' network_bytes_sent : 1354 status : GENERIC_ERROR }.
`
 
On the client, a simlar error message;

```
2017-11-23 10:52:41,312:INFO:root:Job Error (RekallAction): Traceback (most recent call last):
  File "site-packages\grr\client\components\rekall_support\grr_rekall.py", line 278, in Run
  File "site-packages\rekall\session.py", line 862, in RunPlugin
  File "site-packages\rekall\session.py", line 859, in RunPlugin
  File "site-packages\rekall\plugin.py", line 726, in render
  File "site-packages\rekall\plugins\tools\aff4acquire.py", line 577, in collect
  File "site-packages\rekall\plugins\tools\aff4acquire.py", line 589, in collect_acquisition
  File "site-packages\pyaff4\rdfvalue.py", line 142, in NewURNFromFilename
  File "site-packages\pyaff4\rdfvalue.py", line 136, in FromFileName
  File "nturl2path.py", line 60, in pathname2url
IOError: Bad path: file:GRR
```

Not sure if this is a bug or the result of something I did in the upgrade process, but non-Rekall flows appear to be working correctly.

**Comment by bandit91** [comment]
I also have a 100% match symptom problem. 
I saw similar questions on the issue board, but it did not work out. 
What I found is that I installed the agent program on the GRR server PC, and that agent program is extracting memory artifacts well.
The memory artifacts could not be extracted from the agent program installed on all other clients. Help me Please..

**Comment by grrrrrrrrr** [comment]
This issue is another case of Rekall/pyaff4/... dependency breaking on us despite us pinning the version. This is really not a good state to be in, I'll reopen the issue we had about this.

This bug can be fixed quite easily, I'll send a commit shortly.

@bandit91 your issue is unrelated, please file a separate bug if you want and provide some more information there, OSs involved would be good to know and an actual error message.

**Comment by grrrrrrrrr** [comment]
https://github.com/google/grr/commit/c1f98adca273448f10f4f732b2aed22fd469dd48 has the workaround for this, let me know if this doesn't fix the problem for you.

**Comment by jah23** [comment]
Looks to be working now - many thanks.

**Comment by bandit91** [comment]
Thank you. It works fine!
