### ISSUE TITLE
SSO - stricter rights for "first-time" auto-provisioned users

### ISSUE THREAD

**Issue by pettai** [google/grr#556]
Then first-time users are "auto-provisioned" they get the normal GRR user level rights.
While I think this is ok for GRR users created on GRR itself, I think it's too open/unrestricted for an SSO authenticated & "auto-provisioned" user.
Normal users are able to add/delete Artifacts in the Artifact Manager, list all the Clients (and interrogated info), look at the GRR server configuration, etc.

In an SSO system there are probably a lot of users in the IdP that never should use the GRR administrative interface, so per default a more stricter role/label should be added for them if they ever sign in & get "auto-provisioned" in GRR.

I suggest that if AdminUI.webauth_manager: RemoteUserWebAuthManager is set, 
users that are auto-provisioned based on Env Remove-User are created with a "remoteuser" label, and that this label could be configured to restrict access to things available in the GRR WebUI even more, so authorisation controls is tighten.

**Comment by mbushkov** [comment]
Fredrik, would it make sense for you to have a following setup?

In GRR config:
``` yaml
API.DefaultRouter: DisabledApiCallRouter
API.RouterACLConfigFile: /etc/grr_api_acls.yaml
```

In /etc/grr_api_acls.yaml:

``` yaml
router: "ApiCallRouterWithoutChecks"
users:
  - "super-admin"
---
router: "ApiCallRouterWithApprovalChecks"
users:
  - "user-foo"
  - "user-bar"
```

With this setup any SSO user that is not explicitly mentioned in api_acls.yaml won't be able to do anything, "super-admin" user will have a blanket access to the system and "user-foo" and "user-bar" will be able to use GRR with approvals process turned on.

This way you'd be able to add new users to either ApiCallRouterWithoutChecks or ApiCallRouterWithApprovalChecks sections, thus granting them access when necessary.

**Comment by pettai** [comment]
Yes, This will be sufficient for now.
Thx, I will close this issue.

**Comment by pettai** [comment]
It worked fine for users that haven't been granted access, and regular users that are under the policy router: "ApiCallRouterWithApprovalChecks"

However, then I try to put myself as a policy router: "ApiCallRouterWithoutChecks", I get this in the WebGUI:

User: NOT IMPLEMENTED

And the only error logs I find are syslog messages, that suggest I have no access at all:

Dec  6 13:29:26 grr grr_server[8152]: ::ffff:127.0.0.1 - - [06/Dec/2017 13:29:26] "GET / HTTP/1.1" 200 3801
Dec  6 13:29:27 grr grr_server[8152]: ::ffff:127.0.0.1 - - [06/Dec/2017 13:29:27] "GET /api/reflection/rdfvalue/all HTTP/1.1" 501 20
Dec  6 13:29:27 grr grr_server[8152]: ::ffff:127.0.0.1 - - [06/Dec/2017 13:29:27] "GET /api/users/me HTTP/1.1" 501 20
Dec  6 13:29:27 grr grr_server[8152]: ::ffff:127.0.0.1 - - [06/Dec/2017 13:29:27] "GET /api/users/me/notifications/pending/count HTTP/1.1" 501 20
Dec  6 13:29:27 grr grr_server[8152]: ::ffff:127.0.0.1 - - [06/Dec/2017 13:29:27] "GET /api/clients/labels HTTP/1.1" 501 20
Dec  6 13:29:27 grr grr_server[8152]: ::ffff:127.0.0.1 - - [06/Dec/2017 13:29:27] "GET /api/users/me/notifications/pending/global HTTP/1.1" 501 20
Dec  6 13:29:27 grr grr_server[8152]: ::ffff:127.0.0.1 - - [06/Dec/2017 13:29:27] "GET /api/users/me/approvals/client?count=7 HTTP/1.1" 501 20
Dec  6 13:29:27 grr grr_server[8152]: ::ffff:127.0.0.1 - - [06/Dec/2017 13:29:27] "GET /api/hunts?active_within=31d&count=5&created_by=me HTTP/1.1" 501 20
Dec  6 13:29:37 grr grr_server[8152]: ::ffff:127.0.0.1 - - [06/Dec/2017 13:29:37] "GET /api/users/me/notifications/pending?timestamp=1512566966913000 HTTP/1.1" 501 20
Dec  6 13:29:37 grr grr_server[8152]: ::ffff:127.0.0.1 - - [06/Dec/2017 13:29:37] "GET /api/users/me/notifications/pending/count HTTP/1.1" 501 20


This is exactly what a non-authorised user looks like. So, it seems router: "ApiCallRouterWithoutChecks" is not honoured for some reason?

I've copied the example above, only difference is that I'm using SSO with username that has "@" in them.

**Comment by mbushkov** [comment]
I've tried a sample configuration like this:

``` yaml
router: "ApiCallRouterWithoutChecks"
users:
  - "admin@blah"
---
router: "ApiCallRouterWithApprovalChecks"
users:
  - "foo@blah2"
```

It worked for me as expected: user "admin@blah" had unrestricted access, user "foo@blah2" had restricted access and user "bar@blah2" was disabled since it wasn't mentioned in the rules.

What do you see in the logs if you run admin_ui with `--verbose` flag? To do that:
``` bash
sudo service grr-server stop
sudo grr_server --component admin_ui --verbose
```

You should see something like: `No router ACL rule match for user foo@bar` in the logs. Does the username look correct to you?

**Comment by pettai** [comment]
Yes, I get:

```
[...]
INFO:2017-12-06 20:44:57,241 admin_ui:90] Serving HTTP on :: port 5000 ...
/usr/share/grr-server/local/lib/python2.7/site-packages/werkzeug/filesystem.py:63: BrokenFilesystemWarning: Detected a misconfigured UNIX filesystem: Will use UTF-8 as filesystem encoding instead of 'ANSI_X3.4-1968'
  BrokenFilesystemWarning)
DEBUG:2017-12-06 20:44:58,080 api_auth_manager:141] No router ACL rule match for user pettai@nordu.net. Using default router DisabledApiCallRouter
DEBUG:2017-12-06 20:44:58,094 api_auth_manager:141] No router ACL rule match for user pettai@nordu.net. Using default router DisabledApiCallRouter
INFO:2017-12-06 20:44:58,283 server_logging:54] 1512593098281694:grr:14294 API call [GetPendingUserNotificationsCount] by pettai@nordu.net (reason: none): /api/users/me/notifications/pending/count? [501]
[...]
```

**Comment by pettai** [comment]
The reason it worked the first time for me, might be that I didn't explicitly set:
```
API.DefaultRouter: DisabledApiCallRouter
```
in ```/etc/grr/server.local.yaml```

Did you do that in your configuration?
If I don't do it, I'm automatically logged with ApiCallRouterWithoutChecks permissions...

```
DEBUG:2017-12-06 21:05:12,209 api_auth_manager:141] No router ACL rule match for user pettai@nordu.net. Using default router ApiCallRouterWithoutChecks
```

**Comment by mbushkov** [comment]
Fredrik, yes, I had API.DefaultRouter set to DisabledApiCallRouter in my sample.

Do you think you can copy/paste here a snippet of your RouterACLConfigFile?

**Comment by pettai** [comment]
```
router: "ApiCallRouterWithoutChecks"
users:
  - "pettai@nordu.net"
  - "admin"

router: "ApiCallRouterWithApprovalChecks"
users:
  - "berra@nordu.net"
```

**Comment by mbushkov** [comment]
Fredrik, one thing that I see right away is that you're missing `---` between the router entries. It should be:

```
router: "ApiCallRouterWithoutChecks"
users:
  - "pettai@nordu.net"
  - "admin"
---
router: "ApiCallRouterWithApprovalChecks"
users:
  - "berra@nordu.net"
```

Note the `---`. `---` sequence is a "document separator" in YAML. As we expect to have multiple entries in the RouterACLConfigFile, we use `---` to separate these entries.

If you don't use `---` then GRR thinks that your whole configuration is a single entry, it treats it as a dictionary and if a key is defined multiple times then the later one wins. So in your case you effectively have configuration for ApiCallRouterWithApprovalChecks for a list of users ["berra@nordu.net"].

Adding `---` should fix the issue.

**Comment by pettai** [comment]
Right, your correct.
The reason I never put it there was because the example in the api_acls.yaml didn't have that.
thx, closing again
