### ISSUE TITLE
Python hack kills GRR client

### ISSUE THREAD

**Issue by coonsmatthew** [google/grr#561]
Hello all, 
 
I recently tried to run a python hack from my GRR server. I followed instructions here: http://grr-doc.readthedocs.io/en/v3.2.0/investigating-with-grr/pushing-code.html

My script was designed for Linux, and was pretty simple, to run an RPM Verify command. 

I created the script, below: 

```
import commands
status, output = commands.getstatusoutput("rpm -Va")
magic_return_str = "RPM Verify results %s" % output
```

And used the GRR Config Updater to upload it to the admin console. 

Everything seemed to be going well until I tried to run the hack on a client. 

It seemed that it killed my client's GRR agent, and when I tried again, it killed the agent a second time. 

I was logged into the client, and noticed this returned to the screen: 
`ERROR:2018-01-09 09:20:52,083 client_utils_linux:144] Suicide by nanny thread.`

Is there something that I'm doing wrong?

**Comment by mlkm** [comment]
It looks like this GRR client consumed a large amount of time or memory and committed a suicide.
Does rpm -Va return immediately when you run it without GRR, manually in a terminal?

**Comment by coonsmatthew** [comment]
There are quite a few number of lines on the specific server that we're running it on. 

Does the GRR client not like to run commands that take a while to execute? 

Running RPM -Va took around 10 minutes on the system.

Perhaps it would be better to have it run the command and disconnect it from the console, but save the results to a file? 

Something like this perhaps? 

```
import commands
status, output = commands.getstatusoutput("rpm -Va > /tmp/rpm_verify_results &")
magic_return_str = "RPM Verify executed successfully"
```

At least that way you could keep refreshing the /tmp/ directory until the results are there....Or would that not work?

**Comment by grrrrrrrrr** [comment]
We have used hacks like https://pastebin.com/ZfcEKp0x before that call Progress periodically so the the client doesn't get terminated due to timeout. It's not pretty but it works..

**Comment by grrrrrrrrr** [comment]
I'll close this issue, feel free to reopen if you still encounter any issues.
