### ISSUE TITLE
Artifact Uploading Error

### ISSUE THREAD

**Issue by mandadianwesh** [google/grr#562]
When i tried to upload windows.yaml artifact file from https://github.com/ForensicArtifacts/artifacts/tree/master/data the following error was occured.

Artifact WindowsEnvironmentVariableProfilesDirectory has broken provides: 'environ_profilesdirectory' not in KB fields: ['code_page', 'current_control_set', 'domain', 'environ_allusersappdata', 'environ_allusersprofile', 'environ_path', 'environ_programfiles', 'environ_programfilesx86', 'environ_systemdrive', 'environ_systemroot', 'environ_temp', 'environ_windir', 'hostname', 'os', 'os_major_version', 'os_minor_version', 'os_release', 'time_zone', 'users.appdata', 'users.cookies', 'users.desktop', 'users.full_name', 'users.gid', 'users.gids', 'users.homedir', 'users.internet_cache', 'users.last_logon', 'users.localappdata', 'users.localappdata_low', 'users.personal', 'users.pw_entry', 'users.recent', 'users.shell', 'users.sid', 'users.startup', 'users.temp', 'users.uid', 'users.userdomain', 'users.username', 'users.userprofile']
![error](https://user-images.githubusercontent.com/35360377/34861545-9a78c362-f78b-11e7-9e78-14ffbabab9b9.PNG)

**Comment by grrrrrrrrr** [comment]
Hey,

The full ForensicArtifacts repository is available in GRR by default, you don't have to upload it. The format of the Artifacts changes over time and we only guarantee that the latest GRR server accepts the latest Artifacts data, if your server is older you might see problems as the one you posted. But, as I said, there is no reason to upload the artifacts, they should just work out of the box.

**Comment by grrrrrrrrr** [comment]
I'll close this issue since it doesn't seem like there is an actual problem. Let me know if you need additional help.
