### ISSUE TITLE
Failing client install - Ubuntu 14.0.4.5

### ISSUE THREAD

**Issue by ID1010TERROR** [google/grr#563]
### Background: 
I've installed GRR Server on-top of a SecurityOnion Beta3 (based on Ubuntu 14.0.4.5) using the docker image you guys provided here: 
https://github.com/google/grr-doc/blob/master/docker.adoc 
and the install script provided by the folks at SecurityOnion here: 
https://github.com/Security-Onion-Solutions/security-onion/wiki/GRR

**For the _Server_ this appears to work without any issues.**

### The Problem
When I attempt to install the client (on the same system as the server - SecurityOnion) 
by pulling the .deb file from the server as shown here:
https://grr-doc.readthedocs.io/en/v3.2.1/deploying-grr-clients/overview.htmls
and installing the .deb file as shown here:
https://grr-doc.readthedocs.io/en/v3.2.1/deploying-grr-clients/on-linux.html

The install of package grr_3.2.1.1_i386.deb fails and gives the following error:
sudo dpkg -i grr_3.2.1.1_i386.deb 

```
sudo dpkg -i grr_3.2.1.1_i386.deb 
(Reading database ... 157274 files and directories currently installed.)
Preparing to unpack grr_3.2.1.1_i386.deb ...
Unpacking grr (3211-1) over (3211-1) ...
Setting up grr (3211-1) ...
/var/lib/dpkg/info/grr.postinst: 13: /var/lib/dpkg/info/grr.postinst: /usr/lib/grr/grr_3.2.1.1_i386/grrd: not found
dpkg: error processing package grr (--install):
 subprocess installed post-installation script returned error exit status 127
Processing triggers for ureadahead (0.100.0-16) ...
Errors were encountered while processing:
 grr
```

But I have verified that grrd is indeed in the specified path:  /usr/lib/grr/grr_3.2.1.1_i386/

I know I'm stackin' beta on beta here but any ideas would be greatly appreciated. 

Thanks, 
Jay

**Comment by grrrrrrrrr** [comment]
Hey Jay,

You are using the 32 bit installer. Is that intentional? Is your machine 32 bit?

**Comment by ID1010TERROR** [comment]
You're correct this was my issue. Problem was resolved on the seconion
github.

https://github.com/weslambert/securityonion-grr/issues/1

For whatever reason the 64bit option wasn't available but this was resolved
with a fresh install.

This issue can be closed. Thank you.
