### ISSUE TITLE
grr_api_client SearchClients() api call does not work over HTTPS

### ISSUE THREAD

**Issue by soundwave01** [google/grr#565]
**Problem**
The SearchClients api call does work over HTTPS, as it makes HTTP calls, even when the API endpoint is set as https://

This is present in the latest version of the api installed via pip 3.2.1.post1  

**Expected behaviour** 
Once the API endpoint is specified as https://  all other api calls should run over https as well.

**Code to replicate the issue**

I have been able to replicate the issue with
```

import grr_api_client
import os

from grr_api_client import api

os.environ['REQUESTS_CA_BUNDLE'] = "/etc/ssl/certs/"

grrapi = grr_api_client.api.InitHttp(api_endpoint="https://grr.xxxxxxxxxxxx:8000/",auth=("xxxxxxxx", "xxxxxxxxx"))
target = "xxxxxx"
clients = grrapi.SearchClients("host:%s" % (target))
```

GRR server is configured to https for the admin gui.  cert is signed with an internal CA.

This produces the following stack trace

```
/usr/bin/python2.7 /home/xxxxxx/PycharmProjects/xxxxxx/https-broken.py
Traceback (most recent call last):
  File "/home/xxxxxx/PycharmProjects/xxxxxx/https-broken.py", line 11, in <module>
    clients = grrapi.SearchClients("host:%s" % (target))
  File "/home/xxxxxx/.local/lib/python2.7/site-packages/grr_api_client/api.py", line 26, in SearchClients
    return client.SearchClients(query, context=self._context)
  File "/home/xxxxxx/.local/lib/python2.7/site-packages/grr_api_client/client.py", line 266, in SearchClients
    items = context.SendIteratorRequest("SearchClients", args)
  File "/home/xxxxxx/.local/lib/python2.7/site-packages/grr_api_client/context.py", line 48, in SendIteratorRequest
    first_page = pages.next()
  File "/home/xxxxxx/.local/lib/python2.7/site-packages/grr_api_client/context.py", line 31, in _GeneratePages
    result = self.connector.SendRequest(handler_name, args_copy)
  File "/home/xxxxxx/.local/lib/python2.7/site-packages/grr_api_client/connectors/http_connector.py", line 219, in SendRequest
    response = session.send(prepped_request)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 426, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

While I have not found the exact lines of code that is responsible, having debugged the program I can see the request object contains

url = 'http://grr.xxxxxxxxxxxx:8000/api/v2/clients?count=50&offset=0&query=host%3Axxxxxxxxxxx'

as it trys to make an http connection to an https site, this results in the "BadStatusLine"

any help in fixing this would be greatly appreciated

**Comment by mbushkov** [comment]
I've fixed an immediately obvious bug that led to "http://" urls being used instead of "https://" ones ( https://github.com/google/grr/commit/9e35eb10d806a1ad4f4635fbbe9f9a1b2364a27a).

However, there seems to also be a problem with certificates validation when doing iterator-based requests (like SearchClients). Looking into this now. Will also add a proper test to test grr_api_client working through HTTPS protocol (currently only HTTP is tested).

**Comment by mbushkov** [comment]
I've fixed the certificates validation issue and added a test in https://github.com/google/grr/commit/3cbe03250d4f2c5b3fb1cbf1461af5521fa82430.
I've also updated the PIP package on PyPI.
Things should work fine now. Please reopen the issue if updated grr-api-client still fails in your case.
