### ISSUE TITLE
GRR Rekall Profile server

### ISSUE THREAD

**Issue by prats84** [google/grr#567]
GRR server: 3.2.1
Clients OS: Windows Server, Ubuntu 16.04 (4.4.0 Kernel) 
Rekall is enabled 
Even after running download_missing_rekall_profiles the client get only handful of the profiles and on running the flow AnalyzeMemory with Pslist or any other plugins the flow fails are it is unable to find the right profile. 

Since, rekall is enabled and I can review that the clients are able to download the Rekall_profiles into appropriate location on the client. The issue I have is that 

1 How & where to change the Rekall-profile download link so clients can get all the profiles may be from a custom host 
2. How to create the inventory.gz or index.gz files within the Rekall-profile folder when we add new custom profiles

**Comment by mbushkov** [comment]
1. The link is configured by `Rekall.profile_repository` configuration entry in GRR server configuration, it's default value is `https://github.com/google/rekall-profiles/raw/master` (https://github.com/google/grr/blob/e8542de2f131ba647d3430d7b9a14cba5ba214c2/grr/config/server.py#L134). More about changing GRR server configuration options [here](http://grr-doc.readthedocs.io/en/v3.2.1/maintaining-and-tuning/configuration/index.html).

2. Do you mean Rekall-profile folder on an endpoint machine (i.e. on GRR client)? GRR clients download profiles that are known to GRR server. So the only way to make Rekall in a GRR client aware of additional profiles is to point GRR server to a custom Rekall.profile_repository that would have necessary profiles and then run `grr_config_updater download_missing_rekall_profiles`.

**Comment by prats84** [comment]
@mbushkov  Thanks this is what i needed.
