### ISSUE TITLE
Stupid Question about wildcards

### ISSUE THREAD

**Issue by melorium** [google/grr#573]
Hi.

How do I list every files on a system OSX, Linux, Windows.

Do I first have to run a flow att the system and then use virtual file system?

What flow is the best one and what setting do I need to have if I want to list any file on Mac OS? MAC TSK? Windows OS? Windows TSK?

il try Windows for example and use \**50 and for Mac /**50

Is it wrong please can you give me some hints?

I want to have a list of the whole file systems in TSK and OS?

What kind of wildcards for listing a whole file system?

Dennis

**Comment by grrrrrrrrr** [comment]
Discussing this on the mail thread on grr-users instead.

**Comment by melorium** [comment]
Ok sorry

Skickat från min iPhone
