### ISSUE TITLE
Yara flows not available on 3.2.2

### ISSUE THREAD

**Issue by wagga40** [google/grr#575]
Hello, 

after a fresh 3.2.2 install the yara folder is empty in the "Flows view". I've seen it work on a production install. What I have got to do to make it work ? I've check the docs, I found nothing.

Config : Ubuntu 16.04.4 fresh install

Thanks.

**Comment by grrrrrrrrr** [comment]
I think the Yara flows are still advanced, you need to set your UI to advanced view to see them. We should make them standard...

**Comment by grrrrrrrrr** [comment]
Made BASIC in https://github.com/google/grr/commit/8f604b3061897652d1501be618b8600fa7c169b1

**Comment by wagga40** [comment]
Thanks !
