### ISSUE TITLE
Consider changing dependencies for plist support

### ISSUE THREAD

**Issue by joachimmetz** [google/grr#577]
GRR currently uses binplist, I've recently discovered an issue in binplist that could cause the client to consume vast amount of memory. See: https://github.com/google/binplist/issues/8

After talking with the maintainer I recommend considering moving away from binplist, seeing that it will unlike provide Python 3 support. An alternative we are considering for plaso (log2timeline) is https://pypi.org/project/biplist/

**Comment by grrrrrrrrr** [comment]
We switched to biplist.
