### ISSUE TITLE
ArtifactCollector cannot find WindowsUserRecentFiles and WindowsUserRegistryFiles

### ISSUE THREAD

**Issue by voilaviola** [google/grr#578]
Hello,
I am running GRR on Ubuntu Xenial 16.04 in a virtualenv, and used Artifact Collector flow on a windows 10 and a windows 7 client. The collector terminates without error when collecting WindowsUserRecentFiles and WindowsUserRegistryFiles, but says "Found and processed 0 files" in message and gives no result. Considering the fact that in windows 7 these artifacts are stored in different places, I uploaded a client artifact to artifact manager as below: 

> # Test : Win 7 Artifacts

name: Windows7UserRecentFiles
doc: Windows 7 user specific recent files.
sources:
- type: FILE
  attributes:
    paths:
      - '%%users.appdata%%\Microsoft\Windows\Recent Items\*'
    separator: '\'
labels: [Users]
supported_os: [Windows]
---
name: Windows7UserRegistryFiles
doc: Windows 7 user specific Registry files.
sources:
- type: FILE
  attributes:
    paths:
      - '%%users.localappdata%%\Microsoft\Windows\UsrClass.dat'
      - '%%users.userprofile%%\NTUSER.DAT'

    separator: '\'
labels: [Users]
supported_os: [Windows]

Both my Windows7UserRecentFiles, Windows7UserRegistryFiles and the original artifact WindowsUserRecentFiles, WindowsUserRegistryFiles terminate as "Artifact data collection WindowsUserRecentFiles completed successfully in flow ArtifactCollectorFlow with 0 responses". If I use file finder to find and download the same files, the flow won't terminate, and with a debug client I have in client Application.evtx:

> 2018-04-24 16:28:21,585:DEBUG:requests.packages.urllib3.connectionpool:"POST /control?api=3 HTTP/1.1" 200 616
> 2018-04-24 16:28:21,585:INFO:root:aff4:/C.efd95ad227f151ad: Sending 0(634), Received 0 messages in 0.0 sec. Sleeping for 5.0 sec.

wget //server:8080/server.pem works well from client command line.

**Comment by Karneades** [comment]
Did you use "useTSK"?

**Comment by voilaviola** [comment]
No, I use artifact paths like '%%users.userprofile%%\NTUSER.DAT'. I also tried a specific path like 'C:\Users\User1\NTUSER.DAT', but the result doesn't change.

**Comment by Karneades** [comment]
UseTSK is needed for accessing these files.

AN Di., Apr. 24, 2018 bei 17:09, voilaviola <notifications@github.com> Schrieb:

> No, I use artifact paths like '%%users.userprofile%%NTUSER.DAT'. I also tried a specific path like 'C:UsersUser1NTUSER.DAT', but the result doesn't change.

**Comment by Karneades** [comment]
@voilaviola did it work with use tsk in the artifact collector flow?

**Comment by voilaviola** [comment]
Hi, sorry for my late response. It works with "Use tsk" checked, thank you. Is this always needed when launching artifact collector flows?

**Comment by Karneades** [comment]
No, the [sleuthkit (tsk)](https://github.com/sleuthkit/sleuthkit) is only used for some specific flows, e.g. when accessing the file system and the files are locked otherwise, as it is with the registry files.

**Comment by voilaviola** [comment]
OK. Thanks again!

**Comment by grrrrrrrrr** [comment]
I think this has been resolved.
