### ISSUE TITLE
Unable to open database files when running flows

### ISSUE THREAD

**Issue by voilaviola** [google/grr#580]
Hello, 
I get the following error message when launching LinuxServices Collector flow:

> ERROR:2018-05-03 17:03:14,914 sqlite_data_store:274] DB error in file: /home/user/GRR_ENV/lib/python2.7/site-packages/grr/var/grr-datastore/files/nsrl/3ef.sqlite for query: ('PRAGMA sychronous = NORMAL',)
Traceback (most recent call last):
   File "/home/user/GRR_ENV/local/lib/python2.7/site-packages/grr/server/data_stores/sqlite_data_store.py", line 271, in Execute
OperationalError: unable to open database file
ERROR:2018-05-03 17:03:14,915 flow_runner:604] Flow aff4:/C.20fykijug658zkut546/flows/F:76RD5685 raised unable to open database file.

I've got the same error message for many .sqlite files when running other flows too, and I tried to change the permission to these files and folders:
`sudo chmod 777 -R /home/user/GRR_ENV/lib/python2.7/site-packages/grr/var/grr-datastore`
`setfacl -d -m -R g::rwx /home/user/GRR_ENV/lib/python2.7/site-packages/grr/var/grr-datastore`
`setfacl -m -R g::rwx /home/user/GRR_ENV/lib/python2.7/site-packages/grr/var/grr-datastore`
`setfacl -d -m -R o::rwx /home/user/GRR_ENV/lib/python2.7/site-packages/grr/var/grr-datastore`
`setfacl -m -R o::rwx /home/user/GRR_ENV/lib/python2.7/site-packages/grr/var/grr-datastore`
I now have rwx permission for all the existing and newly-created files in grr_datastore, but the same error still occurs.
I would like to know does it has something to do with the query 'PRAGMA sychronous = NORMAL'? Or do I need to modify other file permissions?

**Comment by grrrrrrrrr** [comment]
It's hard to tell what's going on but we have seen db file corruption with SQLite before which is why we urge people to move to the MySQL instead. Maybe this happened in your case too?

**Comment by voilaviola** [comment]
Thanks a lot, I'll test the MySQL solution.
