### ISSUE TITLE
How to run winrar sfx executable file using LaunchBinary?

### ISSUE THREAD

**Issue by Luckypapa76** [google/grr#586]

**Comment by grrrrrrrrr** [comment]
What's the issue you are facing? Does the standard procedure as outlined in http://grr-doc.readthedocs.io/en/latest/investigating-with-grr/pushing-code.html#deploying-executables not work?

**Comment by Luckypapa76** [comment]
Normal executable files are working well, but winrar sfx format files not work for me. Maybe GRR temp (C:\Windows\System32\GRR\<version>\temp\) directory permission problem?

**Comment by grrrrrrrrr** [comment]
The GRR windows installer uses unzipsfx which probably works in a similar fashion and there are no issues running it from GRR. Does the file work fine if you run it on the machine without GRR? Have you tried running it as system?
