### ISSUE TITLE
Help | Modifing the Client's code

### ISSUE THREAD

**Issue by jarvisjarb** [google/grr#587]
Hey, 
The documentation is a bit unclear to me regarding modifing the client(AKA the agent that is being installed on a certain endpoint). 
I know I can repack it with modified .yml file, but I would like to modify it more by adding some indipendet python code that will run from withing the client's exe. 

Is this possible? Is there better documentation regarding the structure of the client's python code and how to modify it?

**Comment by grrrrrrrrr** [comment]
Hey,

Modifying the client code is of course possible but it's a bit tricky. You basically have to set up a development environment on the platform you are targeting.

Have a look at http://grr-doc.readthedocs.io/en/latest/maintaining-and-tuning/building-custom-client-templates.html to start.

As mentioned we have scripts that set up client build environments. Mac and Linux versions are are at https://github.com/google/grr/tree/master/vagrant, Windows version at https://github.com/google/grr/tree/master/appveyor

Note that if the code you want to run is small, it might be easier to just send the script to the client as described in http://grr-doc.readthedocs.io/en/latest/investigating-with-grr/pushing-code.html#deploying-arbitrary-python-code

Hope that helps!
