### ISSUE TITLE
Could not connect to GRR servers(I don’t see my clients)

### ISSUE THREAD

**Issue by w44p** [google/grr#589]
Could not connect to GRR servers(I don’t see my clients)

grr version:3.2.2.0
install server from-released-pip,follows : https://grr-doc.readthedocs.io/en/latest/installing-grr-server/from-released-pip.html
server start with : grr_server --component admin_ui --verbose
windows client and centos client can not connect with server.
LOG(windows):
INFO:2018-05-30 09:42:30,686 connectionpool:207] Starting new HTTP connection (1): 192.168.1.160
INFO:2018-05-30 09:42:31,687 comms:256] Could not connect to GRR servers [u'http://192.168.1.160:9998/'], directly or through these proxies: [''].

LOG(centos):
 [root@localhost grr_3.2.2.0_amd64]# grrd --config=/usr/lib64/grr/grr_3.2.2.0_amd64/grrd.yaml --verbose
DEBUG:2018-05-30 10:45:55,937 __init__:1619] Initializing CommunicatorInit
DEBUG:2018-05-30 10:45:55,937 __init__:1619] Initializing CommsInit
DEBUG:2018-05-30 10:45:55,937 __init__:1619] Initializing VFSInit
DEBUG:2018-05-30 10:45:55,937 __init__:1619] Initializing InitHook
INFO:2018-05-30 10:45:55,941 __init__:1611] Starting client aff4:/C.1a0d984178480494
DEBUG:2018-05-30 10:45:55,946 __init__:1619] Sending startup information.
INFO:2018-05-30 10:45:55,949 connectionpool:207] Starting new HTTP connection (1): 192.168.1.160
INFO:2018-05-30 10:45:55,950 __init__:1611] Could not connect to GRR servers [u'http://192.168.1.160:9998/'], directly or through these proxies: [''].

INFO:2018-05-30 11:06:01,944 connectionpool:207] Starting new HTTP connection (1): 192.168.1.160
INFO:2018-05-30 11:06:01,945 __init__:1611] Could not connect to GRR servers [u'http://192.168.1.160:9998/'], directly or through these proxies: [''].

during installing server,there are some warnings:
grr-response-core 3.2.2.post0 has requirement wheel==0.30, but you'll have wheel 0.31.1 which is incompatible.
grr-response-proto 3.2.2.post0 has requirement protobuf==3.3.0, but you'll have protobuf 3.5.2.post1 which is incompatible.

Is this the reason why it cannot work?

server.pem cannot get
[root@localhost ~]# wget http://192.168.1.160:9998/server.pem
--2018-05-30 10:47:51--  http://192.168.1.160:9998/server.pem
正在连接 192.168.1.160:9998... 失败：拒绝连接。

centos client and grr_server are in the same PC.so i think something is correct in server?

port 9998 is not open?

[root@localhost bin]# netstat -npl | grep 999
tcp6       0      0 :::9999                 :::*                    LISTEN      5004/python2

**Comment by w44p** [comment]
[centos_client_log.txt](https://github.com/google/grr/files/2052288/centos_client_log.txt)
[windows_client_log.txt](https://github.com/google/grr/files/2052289/windows_client_log.txt)

![admin_ui](https://user-images.githubusercontent.com/24778449/40697382-8b890b18-63fc-11e8-8055-7f38fbdafd05.jpg)

**Comment by w44p** [comment]
grr-response-core 3.2.2.post0 has requirement wheel==0.30, but you'll have wheel 0.31.1 which is incompatible.
grr-response-proto 3.2.2.post0 has requirement protobuf==3.3.0, but you'll have protobuf 3.5.2.post1 which is incompatible.

I correct the version of wheel and protobuf with command:pip install wheel==0.30 
and pip install protobuf==3.3.0
but I still don’t see my clients.

**Comment by grrrrrrrrr** [comment]
Do you have a frontend process running? You need to see the frontend listen on the port with netstat before the client can connect. Maybe you can check the server logs if the frontend has problems starting up.

**Comment by grrrrrrrrr** [comment]
The admin_ui component is the process that serves the web interface which is working for you. You want to run the frontend component instead.

**Comment by w44p** [comment]
How to run the frontend component?
grr_server --component grr_frontend  --verbose?

(GRR_ENV) [root@localhost wangsiping]# grr_server --component grr_frontend  --verbose
Traceback (most recent call last):
  File "/home/wangsiping/GRR_ENV/bin/grr_server", line 11, in <module>
    sys.exit(GrrServer())
  File "/home/wangsiping/GRR_ENV/lib/python2.7/site-packages/grr/server/distro_entry.py", line 60, in GrrServer
    flags.StartMain(grr_server.main)
  File "/home/wangsiping/GRR_ENV/lib/python2.7/site-packages/grr/lib/flags.py", line 122, in StartMain
    main(sys.argv)
  File "/home/wangsiping/GRR_ENV/lib/python2.7/site-packages/grr/tools/grr_server.py", line 44, in main
    "%s." % flags.FLAGS.component)
RuntimeError: No valid component specified. Got: grr_frontend.

**Comment by w44p** [comment]
Oh,I get it.
Run the following command in server:
source GRR_ENV/bin/activate
grr_server --component frontend  --verbose
grr_server --component admin_ui --verbose
grr_server --component worker --verbose

and repack client package, reinstall client package in client machine.
SO I can see my clients!
Tks~~~

PS：I still recommend adding these commands to the grr's document.
