### ISSUE TITLE
Document better that any client can connect to any server.

### ISSUE THREAD

**Issue by scudette** [google/grr#596]
This might just be a documentation issue but the page discussing the cryptographic algorithms here:
https://grr-doc.readthedocs.io/en/latest/maintaining-and-tuning/key-management/which-keys-and-how.html?highlight=encryption

```
 The CA public key is deployed to the client so that it can ensure it is
 communicating with the correct server. 
```

While this is technically true, the client is the only one that is checking that it is communicating with the correct server (by verifying the CA signed the server cert). There is absolutely nothing to stop any client from just ignoring that check and proceeding to enrol with any server (Even if the client does not have the CA key or any other information about the server).

This is problematic because someone can just grab an open source GRR client and point it at another installation and automatically join it *without having a valid client config*. I don't think this is exactly expected. This allows the adversaries to watch any hunts, or IOCs such as yara sigs. Furthermore since GRR uses file deduplication by default it is possible for the attackers to determine if certain files have been collected in the filestore by their hashes (so they can get early warning of their tool chain compromise).

If clients were also verified then it would make it a little bit harder (attackers would need to find an actual packed client so they can recover the config file with keys). It may not be that much harder in reality but at least it is more expected.

**Comment by grrrrrrrrr** [comment]
Thanks for pointing this out. The wording is correct but it's a bit subtle to see what this exactly means. I added a note to explain this a bit better. Currently the sphinx build has issues so it might take a bit until readthedocs will be updated. The change can be previewed at https://github.com/google/grr-doc//blob/master/maintaining-and-tuning/key-management/which-keys-and-how.md

**Comment by scudette** [comment]
This would be so easy to fix - simply include a nonce in the client config which the client must present during enrollment (in the CSR). This way clients which do not have the original config will simply be unable to enroll. This behavior is much less surprising then the current behavior which leaks a lot of information.

I think that the documentation change does not spell out clearly enough that an attacker can trivially join a GRR server network without any prior keys.
