### ISSUE TITLE
IE/Edge/Safari Browser Support

### ISSUE THREAD

**Issue by Athletesrun** [google/grr#598]
Does GRR support browser artifact flows from Internet, Explorer, Edge, or Safari? The administrator interface on the server only includes options for `CacheGrep`, `ChromeHistory`, and `FirefoxHistory` under Browser in the Start New Flows tab. I appreciate any help.

**Comment by grrrrrrrrr** [comment]
Hm we should probably remove those old flows, they add confusion and don't add much functionality nowadays. Please have a look at the ArtifactCollector flow, there should be artifacts for all the use cases you mention.

**Comment by Athletesrun** [comment]
That is what I was looking for. Thank you for your help.

**Comment by grrrrrrrrr** [comment]
Cool in that case I'll close this issue.
