### ISSUE TITLE
Python API SSL Verification Failed

### ISSUE THREAD

**Issue by cgbriggs** [google/grr#601]
I'm trying make a script that calls the grr_client_api, but the hostname that I'm using does not match the name of the server. This is necessary because the server is using single sign on. 

I'm trying to use something similar to what the python request system allows you to do. Which is: requests.get('https://example.com', verify=False)

Here is an example of the script I'm trying to run:
```
# Test

#!/usr/bin/env python

from grr_api_client import api

grrapi = api.InitHttp(api_endpoint = "https://127.0.0.1",auth = ("usr", "pwd"), verify = False)

search_result = grrapi.SearchClients("*")

result = {}

print (result)
```

**Comment by mbushkov** [comment]
Hi! 
Thanks for opening the issue. `api.InitHttp` doesn't accept the "verify" parameter at the moment. In the next grr-api-client's release we'll add support for passing additional configuration options to requests library (I will submit a change in the beginning of next week).

In the meantime this hack may help as a temporary solution:
https://stackoverflow.com/questions/48391750/disable-python-requests-ssl-validation-for-an-imported-module

**Comment by cgbriggs** [comment]
Hi, 

Thank you for such a quick response! I'll implement this hack and see if it temporarily solves my issue.

By chance, do you know when the next grr-api-client release will be?

Thank you for all the help!

**Comment by mbushkov** [comment]
No worries :) I'll cut a minor grr-api-client release as soon as the change is implemented (and we have a full GRR+grr-api-client release planned this month anyway).

**Comment by mbushkov** [comment]
I'd suggest we keep the issue open so that we can track the progress here.

**Comment by cgbriggs** [comment]
Oh, sorry about that

**Comment by mbushkov** [comment]
Quick note: GRR 3.2.3.0 was just released, but corresponding grr-api-client doesn't have necessary changes yet. I'm working on it at the moment, will cut a new minor release for the grr-api-client when I'm done.

**Comment by mbushkov** [comment]
Hi! I've made a minor release of grr-api-client PIP package (https://pypi.org/project/grr-api-client/, version 3.2.3.post1).

api.InitHttp() now has "verify", "proxies" and "cert" arguments that get forwarded to the underlying requests library (see https://github.com/google/grr/blob/master/api_client/python/grr_api_client/api.py#L57).

Setting "verify" to False will turn off SSL certificates checking.

**Comment by cgbriggs** [comment]
Great, that is awesome! Thanks so much for your help! 👍
