### ISSUE TITLE
how do I convert last_seen_at to date and time

### ISSUE THREAD

**Issue by GalacticMaster** [google/grr#603]
I am writing some logic to check if client is online or not before running the flow.
According to client API it shows that Last_seen_at from client_data should help me to conclude this. but when I capture the last_seen_at from client_data it is giving me 16 digit number. According to client API it says that data type is RDFtime but I am not able to see any class which I can import to print it in RDFtime.

**Comment by GalacticMaster** [comment]
thank you ! this worked for me. I have one more query on client status. I want to know how can we check client status green, yellow etc using client API? Let me know if I need to open new issue.

**Comment by mbushkov** [comment]
In the UI we infer client status from the last_seen_at time. Effectively:
```python
diff = time.time() - last_seen_at / 1000000.0
if diff < 60 * 15:
  # client status green
elif diff < 60 * 60 * 24:
  # client status yellow
else:
  # client status red
```
