### ISSUE TITLE
ImportError: No module named grr_api_client

### ISSUE THREAD

**Issue by cgbriggs** [google/grr#606]
```
Traceback (most recent call last):
  File "test2.py", line 7, in <module>
    from grr_api_client import api
ImportError: No module named grr_api_client
```
GRR Server Version: 3.2.3.0
PIP Package Version: grr-api-client 3.2.3.post1

New issue after updating to current versions of GRR Server and PIP Package.

**Comment by mbushkov** [comment]
Can you try installing grr-api-client in a separate clean virtualenv and check if it works there?

**Comment by cgbriggs** [comment]
grr-api-client 3.2.3.post1 did work in a clean virtualenv.
