### ISSUE TITLE
Question:  Best way to deal with expired server/client cert?

### ISSUE THREAD

**Issue by soundwave01** [google/grr#609]
Hi,

Hope someone can help, I'm looking for advice on the best way to deal with an expired cert.

While trying to understand why a newly package client was failing to register (in prep for upgrading all production agents), I found this.

INFO:2018-07-19 16:10:42,434 comms:1191] Unable to verify server certificate at http://xxxxxxxx:xxxxx/server.pem: Server cert is invalid: Certificate expired!

While I know I can generate a new cert and repackage the client to make it work.  I'm trying to understand how to do it without breaking the communication for the existing 10k clients if possible.

Any advice would be greatly appreciated! 

Thanks

**Comment by mbushkov** [comment]
Hi! We have a dedicated doc page here:
https://grr-doc.readthedocs.io/en/latest/maintaining-and-tuning/key-management/rotating.html?highlight=certificate#rotating-server-keys
Effectively, if the certificate is signed by the same CA, clients will
accept it.

Cheers,
Misha
