### ISSUE TITLE
Artifact LinuxUserProfiles missing from registry. 

### ISSUE THREAD

**Issue by cwilsonwoof** [google/grr#611]
I am seeing this error on 3.2.3.2
"Artifact LinuxUserProfiles missing from registry. You may need to sync the artifact repo by running make in the artifact directory."

I dont see a makefile in /grr/artifacts, however.

**Comment by demonchild2112** [comment]
Fix submitted.

**Comment by cwilsonwoof** [comment]
Thanks, Ill give it a shot!

**Comment by cwilsonwoof** [comment]
Seeing an error when starting frontend after replacing artifact_registry.py -
ImportError: No module named future.utils

**Comment by mbushkov** [comment]
Patching GRR code this way (i.e. replacing a single file) is error prone.
In this case, there was a dependency change since the last release: we
added dependency to the "future" module. So you need to do "pip install
future" in GRR server's virtualenv.

I'd generally advise to simply try the HEAD DEB package - this is much more
robust way of trying out the latest build:
http://grr-doc.readthedocs.io/en/latest/installing-grr-server/from-head-deb.html

Cheers,
Misha

**Comment by cwilsonwoof** [comment]
Thanks Misha!
Looks like trying to run the get server after just swapping that file really screwed things up. 
When I scroll down in the UI, it no longer retrieves new files. Should I do a pip reinstall?

**Comment by mbushkov** [comment]
Hi Casey! Do I understand it correctly that the DB got lost after swapping just a single artifact_registry.py file? Or did you patch more files?

In general, when doing GRR server updates, doing a GRR DB backup is a reasonable precaution measure. If something goes wrong, you can simply restore the DB from backup and reinstall previous server DEB.

**Comment by cwilsonwoof** [comment]
Im really not sure. I hope this is just an AdminUI issue that isnt populating new machines. All our adminUI accounts were lost though, this was noticed after restoring the old artifact_registry.py file, 

Im doing a pip install --upgrade grr-response-server right now to see if that irons things out, but Im unsure if the core files were replaced.

**Comment by cwilsonwoof** [comment]
I see this from the server output, but more systems never load.
 - - [25/Jul/2018 20:55:05] "GET /api/clients?count=50&offset=50 HTTP/1.1" 200 18

**Comment by cwilsonwoof** [comment]
Should I do a --force-reinstall?

**Comment by mbushkov** [comment]
Casey, how did you install GRR originally? From a DEB package, from PIP package? How did you do the last upgrade you mentioned (to the version 3.2.3.2)?

**Comment by cwilsonwoof** [comment]
PIP package. Ill use DEB from now on though.
3.2.3.2 is a fresh install through PIP, its a small server for a little project.

**Comment by mbushkov** [comment]
I see. PIP is a valid way to install things too, just requires a bit more work than installing from DEB.

Using force-reinstall is ok, just make sure that all GRR server packages (their names are starting with "grr-response") have the same version. Also, to clarify: your current goal is still to install HEAD version or to revert to the latest stable release?

**Comment by cwilsonwoof** [comment]
HEAD version preferred. Try and implement the fix you posted earlier.

**Comment by cwilsonwoof** [comment]
Ive completed a pip --upgrade --force-reinstall, however there are still only 23 systems showing up in Admin_UI.

**Comment by cwilsonwoof** [comment]
OK, looks like it trashed the database. Ill have to be more careful in the future, making backups of things before I perform operations. Thanks for your help today!
