### ISSUE TITLE
Object X is of type AFF4Volume, but required_type is GRRFlow

### ISSUE THREAD

**Issue by cwilsonwoof** [google/grr#614]
After some issues yesterday, my GRR database was cleared. Devices started checking in right away, but some are having problems. I see this error when certain devices attempt to check it:

ERROR:2018-07-26 22:15:56,693 6885 MainProcess 139826678458112 Thread-16051 frontend:233] Had to respond with status 500: Object aff4:/C.1ace815e488d4548/flows/F:F4F3D976 is of type AFF4Volume, but required_type is GRRFlow.

Unfortunately I cannot touch the clients at this point (well, it would be very difficult). Does this happen to be a server-side, frontend error I can resolve?

**Comment by grrrrrrrrr** [comment]
Hm this means that, again, your data is inconsistent. GRR tries to run a flow but can't find it in the db. What data store are you using?

It should be easy to fix this by deleting the stale data in the console but you should probably find the underlying reason for the data corruption first.
