### ISSUE TITLE
How can I find my python hacks?

### ISSUE THREAD

**Issue by davidk176** [google/grr#615]
Hi,

I'm trying to execute a python file, I've uploaded via grr_config_updater upload_python --file=myfile.py --platform=linux (just like it is written in the documentation).

Now I'm troubeling how to execute it in the GRR GUI. Does somebody know, which path I should enter in hack name?

![grafik](https://user-images.githubusercontent.com/41790853/43716814-c02c9f88-9985-11e8-9a9a-0e03093614cf.png)

Thank you!
David

**Comment by grrrrrrrrr** [comment]
Sorry for this, it's a long standing known issue. GRR stores python hacks by platform so you need to prefix your filename with linux/. The correct name is also shown in the manage binaries tab, if you c&p that name it should work for sure.

**Comment by davidk176** [comment]
Thank you very much! That solved my problem!
