### ISSUE TITLE
GRR fronentend site is not accessable on port 8080

### ISSUE THREAD

**Issue by tdg88** [google/grr#616]
I am trying to access GRR frontend site on port 8080 but not able to access.

**Comment by grrrrrrrrr** [comment]
I think you will have to provide a bit more info. Is the frontend actually running? Anything in the logs? Is this on a local machine? If not, is there a firewall?

**Comment by tdg88** [comment]
Firewall is disabled. I am able to access admin UI which is on port 8000. 8080 port is open. No its on remote machine. There is not a single file in /var/log/grr/. Is there any other place where logs we can check?
Thank you.

**Comment by grrrrrrrrr** [comment]
The log location depends on how you installed GRR. You can run one of the GRR processes on the command line and append --config_help, it will show the values for all settings, look for Logging.*

If you can reach the UI, there is also a settings overwiew which should give you the same info.

**Comment by grrrrrrrrr** [comment]
This seems obsolete.
