### ISSUE TITLE
Prometheus Stats Endpoint

### ISSUE THREAD

**Issue by magikman** [google/grr#625]
Hello Team!

I would like to request GRR support Prometheus stats output. The JSON data that is exported today is indeed helpful, but I would prefer to not maintain prom exporter code. I am sure this would be helpful to others.

Thanks!

**Comment by max-vogler** [comment]
Starting with 87b7bd87f6ec6bfc452dd320b4626606c1337e9b, we have added support for Prometheus metrics. Every GRR process now exposes an additional route `/prometheus_metrics` under `Monitoring.http_port`. Documentation will follow with the next release.

We're happy about any feedback, especially to smooth out some rough edges before the official release.

**Comment by grrrrrrrrr** [comment]
Docs are out for a while now: https://grr-doc.readthedocs.io/en/latest/maintaining-and-tuning/monitoring.html
