### ISSUE TITLE
Cron'd hunts get hidden in the UI if there are > 50 active hunts

### ISSUE THREAD

**Issue by destijl** [google/grr#63]
To make the hunt UI usable we sort the children of aff4:/hunts/ by age (i.e. last activity), take the most recent 50, then open them all and present them in the UI.

Since default lifetime is 1 month, starting a few hunts each week can easily tip you over 50 active hunts. I couldn't find the end to end test cron hunt in the list, which was weird since it was created just a few hours ago.  But since it has a short lifetime there were > 50 active hunts with the default lifetime that had been updated more recently.  So I had to scroll down, wait, then click the robot, then search in the list.  Not exactly obvious.

Ideas:

1. take a bigger slice == slower load time
2. make default hunt lifetime shorter.  this is probably ok, the benefit between 2 weeks and one month is marginal
3. take an age range slice of 2 days rather than an arbitrary fixed number of hunts

3 seems best to me, open to better ideas.

**Comment by destijl** [comment]
Blocking on #115

**Comment by pidydx** [comment]
This can be closed now can't it?

**Comment by destijl** [comment]
Yes I think this is good now, thanks misha.
