### ISSUE TITLE
Initializing the GRR API object

### ISSUE THREAD

**Issue by Shubham-gupta007** [google/grr#635]
Traceback (most recent call last):
  File "ui.py", line 1, in <module>
    from grr_api_client import api
  File "/home/ubuntu/.local/lib/python2.7/site-packages/grr_api_client/api.py", line 5, in <module>
    from grr_api_client import client
  File "/home/ubuntu/.local/lib/python2.7/site-packages/grr_api_client/client.py", line 5, in <module>
    from grr_api_client import flow
  File "/home/ubuntu/.local/lib/python2.7/site-packages/grr_api_client/flow.py", line 6, in <module>
    from grr_api_client import utils
  File "/home/ubuntu/.local/lib/python2.7/site-packages/grr_api_client/utils.py", line 8, in <module>
    from builtins import map  # pylint: disable=redefined-builtin
ImportError: No module named builtins

>>ui.py
from grr_api_client import api
grrapi = api.InitHttp(api_endpoint="http://localhost:1234",
                      auth=("user", "pwd"))

I am  new to grr  and can't understand what's wrong.?
can anyone help me out please.

**Comment by mrhania** [comment]
Looks like I forgot to include the `future` package in the list of dependencies of `grr-api-client` and since people usually use `grr-api-client` alongside the "normal" distribution which has this dependency specified, the bug went unnoticed.

As a temporary workaround you can do

    pip install future

from within your virtual environment.

**Comment by Shubham-gupta007** [comment]
i had already done that
(GRR_ENV) ubuntu@ubuntu:~$ pip install future
Requirement already satisfied: future in ./GRR_ENV/lib/python2.7/site-packages (0.16.0)
 
@mrhania

**Comment by Shubham-gupta007** [comment]
It works thank you

**Comment by mrhania** [comment]
The issue has been resolved in dd7ab4ab2d6e4480895b6b30cf176b23ca513539, new PIP packages (`grr-response-proto 3.2.4.post3`, `grr-api-client 3.2.4.post3`) have been uploaded to PyPI.
