### ISSUE TITLE
Client last seen

### ISSUE THREAD

**Issue by Shubham-gupta007** [google/grr#637]
>lastseen.py
from grr_api_client import api
grrapi = api.InitHttp(api_endpoint="http://ubuntu:8000",
                      auth=("admin", "qwerty"))
search_result = grrapi.SearchClients("host:192.168.110.165")
result = {}
for client in search_result:
  client_id = client.client_id
  client_last_seen_at = client.data.last_seen_at
  result[client_id] = client_last_seen_at
print result

o/p
(GRR_NEW) ubuntu@ubuntu:~$ python firstseen.py 
{}

my code works fine.But can't see the client last seen.
can anyone help me out.
thanks in advance

**Comment by mbushkov** [comment]
What happens if you search for "host:192.168.110.165" in GRR AdminUI? Do you see the results you expect?

**Comment by Shubham-gupta007** [comment]
no @mbushkov 
i think host is not connected with grr server.

**Comment by grrrrrrrrr** [comment]
This looks WAI, please reopen if there is still an issue.
