### ISSUE TITLE
Server Load not Loading

### ISSUE THREAD

**Issue by pidydx** [google/grr#65]
When I try to check server load for windows greater than 1hr the page never seems to finish loading.  Watching the slow queries log on our SQL server seems to indicate it gets responses in a similar timeframe to the 1hr window that loads properly so it appears to be part of the processing to make the graphs.

**Comment by destijl** [comment]
@mbushkov has a change coming that should make this load a lot faster.

**Comment by pidydx** [comment]
I am going to go ahead and close this.  We mostly got it working by limiting the stats expiration time and I think enough factors have changed that more specific issues can be opened if anything comes up.
