### ISSUE TITLE
grr-server_3.2.4-5_amd64.deb is being quarantined by Defender

### ISSUE THREAD

**Issue by mouzclik** [google/grr#651]
Windows Defender is automatically detecting and quarantining latest GRR deb release packet.

![image](https://user-images.githubusercontent.com/29256737/50193976-e4832d80-0306-11e9-805d-fbed0c2b046f.png)

**Comment by mbushkov** [comment]
This is obviously a false positive - Windows Defender complains about https://github.com/google/grr/blob/36b8a2e5d13c1a464f65b1ce522508ff26fa409e/grr/server/grr_response_server/gui/static/Gulpfile.js, a build file for GRR Web UI. It doesn't make much sense.

Can you simply turn Windows Defender off temporarily when downloading the deb?

**Comment by mouzclik** [comment]
Absolutely, it’s pretty simple to bypass, just thought I’d let you guys know since it doesn’t yell at me when I download other versions.

**Comment by grrrrrrrrr** [comment]
I'll close this issue, there is nothing left for us to do. Thanks for letting us know about this!
