### ISSUE TITLE
GRR 3.2.4-5 couldn't package windows clients

### ISSUE THREAD

**Issue by mmogilko** [google/grr#652]
Hello!

Yesterday I updated GRR from 3.2.3.2 to 3.2.4-5 and migrated from sqlight to mysql. After that GRR could not generate/repack Windows clients:

```
Repacking template: /usr/share/grr-server/grr-response-templates/templates/GRR_3.2.4.5_i386.exe.zip  
Using context: [u'ClientBuilder Context', u'ClientBuilder Context', u'Arch:i386', u'Platform:Windows', u'Target:Windows', u'Target:Windows'] and labels: []  
ERROR:2018-12-19 11:08:11,502 958 MainProcess 140282782283584 MainThread build:448] Build Config Error: Logging.path starts with /, probably has Unix path. /var/log/grr  
ERROR:2018-12-19 11:08:11,502 958 MainProcess 140282782283584 MainThread repacking:192] Repacking template /usr/share/grr-server/grr-response-templates/templates/GRR_3.2.4.5_i386.exe.zip failed:  
Traceback (most recent call last):  
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_core/lib/repacking.py", line 190, in RepackTemplate  
    output_path)  
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_core/lib/build.py", line 509, in MakeDeployableBinary  
    return self.MakeSelfExtractingZip(zip_data.getvalue(), output_path)  
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_core/lib/build.py", line 588, in MakeSelfExtractingZip  
    client_config_content = self.GetClientConfig(context)  
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_core/lib/build.py", line 344, in GetClientConfig  
    self.ValidateEndConfig(new_config)  
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_core/lib/build.py", line 449, in ValidateEndConfig  
    raise RuntimeError("Bad configuration generated. Terminating.")  
RuntimeError: Bad configuration generated. Terminating.  
Failed to repack /usr/share/grr-server/grr-response-templates/templates/GRR_3.2.4.5_i386.exe.zip.  
Repacking as debug installer: /usr/share/grr-server/grr-response-templates/templates/GRR_3.2.4.5_i386.exe.zip.  
Repacking template: /usr/share/grr-server/grr-response-templates/templates/GRR_3.2.4.5_i386.exe.zip  
Using context: [u'ClientBuilder Context', u'ClientBuilder Context', u'Arch:i386', u'Platform:Windows', u'Target:Windows', u'Target:Windows', u'DebugClientBuild Context'] and labels: []  
ERROR:2018-12-19 11:08:15,190 958 MainProcess 140282782283584 MainThread build:448] Build Config Error: Logging.path starts with /, probably has Unix path. /var/log/grr  
ERROR:2018-12-19 11:08:15,190 958 MainProcess 140282782283584 MainThread repacking:192] Repacking template /usr/share/grr-server/grr-response-templates/templates/GRR_3.2.4.5_i386.exe.zip failed:  
Traceback (most recent call last):  
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_core/lib/repacking.py", line 190, in RepackTemplate  
    output_path)  
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_core/lib/build.py", line 509, in MakeDeployableBinary  
    return self.MakeSelfExtractingZip(zip_data.getvalue(), output_path)  
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_core/lib/build.py", line 588, in MakeSelfExtractingZip  
    client_config_content = self.GetClientConfig(context)  
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_core/lib/build.py", line 344, in GetClientConfig  
    self.ValidateEndConfig(new_config)  
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_core/lib/build.py", line 449, in ValidateEndConfig  
    raise RuntimeError("Bad configuration generated. Terminating.")  
RuntimeError: Bad configuration generated. Terminating.  
Failed to repack /usr/share/grr-server/grr-response-templates/templates/GRR_3.2.4.5_i386.exe.zip.  
```

Thanks in advance!

**Comment by mbushkov** [comment]
Thanks for reporting this!
Unfortunately, I can't reproduce this on a clean deployment. However, the root cause here seems to be:
```
Build Config Error: Logging.path starts with /, probably has Unix path. /var/log/grr  
```

Do you have custom overrides in your config? Can it be that you've overridden Logging.path globally for all the platforms?

**Comment by mmogilko** [comment]
Thanks for a quick answer!
Yes, you are right, I have in `Logging.path: /var/log/grr` in `/etc/grr/server.local.yaml`. When I've commented out this variable, the `grr_config_updater repack_clients` command runs with success. But GRR stoped writing any logs in /var/log/grr, but in `/var/log/syslog`.
For me solution is to move `Logging.path: /var/log/grr` in `/usr/share/grr-server/install_data/etc/grr-server.yaml`. Now I have logs in right place and the agents are packaging without errors.
Is this solution correct?

**Comment by grrrrrrrrr** [comment]
Hm something doesn't seem right here. It shouldn't matter which of the two files you put the config options in, they are treated the same.

The grr-server.yaml has more specific logging config options like

Target:Linux:
  Logging.path: /var/log

Those should override the global option you set. We'll have a look if this works as expected or if there's a bug.

If the configuration you have now works for you then it's ok. You just need to be aware that the main grr-server.yaml will be overwritten with the next update.

**Comment by mmogilko** [comment]
I know that  grr-server.yaml has more specific logging config options, that's why firstly I tried to change it in this way:
```
Target:Linux:
Logging.path: /var/log/grr
```
But nothing happened, logs continued wiritting into /var/log/syslog.
I made a conclusion, that in my installation variable `Logging.path` in `/etc/grr/server.local.yaml` overwrites all `/etc/grr/server.local.yaml` vars in `/usr/share/grr-server/install_data/etc/grr-server.yaml`.
But you should note, that all it happened after upgrade. I'll try the same on a clean installation, but I don't know when. This week or next. Maybe it is not relevant for new installations, because @mbushkov couldn't reproduce that.
Thank you!

**Comment by grrrrrrrrr** [comment]
The Target:Linux context is what gets put into the client during repacking. So you are basically configuring your Linux clients' logging path like this, not the server.

**Comment by soundwave01** [comment]
I had this with the following config

```
Logging.path: /var/log/grr/grr_client.log
Client Context:
Logging.path: /var/log/grr/grr_client.log
  Platform:Windows:
    Logging.path: c:\\windows\\system32\\grr.log
```
which I took from https://grr-doc.readthedocs.io/en/v3.2.4/maintaining-and-tuning/configuration/contexts.html

Removing the top level "Logging.path:"  and just having the Platform:Windows  allowed me to generate the client.
