### ISSUE TITLE
Does GRR support MySQL SSL

### ISSUE THREAD

**Issue by coonsmatthew** [google/grr#656]
Do you all know if GRR supports the MySQL_SSL and MySQL_SSL_CA_File directives? We're setting up our GRR server to have a remote MySQL database, and we were curious if these features were supported, and if they were, how to specify them in the "server.local.yml" config file. 

Thank you!

**Comment by demonchild2112** [comment]
GRR does not currently support encrypted connections: #643 

We may add support in the future, but I can't provide an ETA at the moment.

**Comment by coonsmatthew** [comment]
Thanks @demonchild2112

**Comment by mbushkov** [comment]
@coonsmatthew, just in case - please see @grrrrrrrrr's comment here: https://github.com/google/grr/issues/643#issuecomment-452303650. We're working on SSL MySQL connections at the moment and they will make it into HEAD version fairly soon.
