### ISSUE TITLE
Error updating keys

### ISSUE THREAD

**Issue by emmonsk** [google/grr#665]
I am running GRR Server 3.2.4
Server was working fine, but after reboot, my client is not able to connect back to the host. I am able to successfully wget the host on port 8080, to get server.pem.

Logs from my client system GRR.log : 

> DEBUG:2019-01-28 11:12:48,017 connectionpool:205] Starting new HTTP connection (1): REDACTED:8080
DEBUG:2019-01-28 11:12:48,227 connectionpool:393] http://REDACTED:8080 "GET /server.pem HTTP/1.1" 200 1005
INFO:2019-01-28 11:12:48,230 comms:1045] Unable to verify server certificate at http://REDACTED:8080/server.pem: Server cert is invalid: 
INFO:2019-01-28 11:12:48,232 comms:256] Could not connect to GRR servers [u'http://1REDACTED:8080/'], directly or through these proxies: [u''].

Command I am trying to run 
`sudo grr_config_updater generate_keys --overwrite_keys`

Error that is returned to me

> Using configuration <GrrConfigManager  file="/usr/share/grr-server/install_data/etc/grr-server.yaml"  file="/etc/grr//server.local.yaml" >
Traceback (most recent call last):
  File "/usr/share/grr-server/bin/grr_config_updater", line 11, in <module>
    sys.exit(ConfigUpdater())
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/distro_entry.py", line 24, in ConfigUpdater
    flags.StartMain(config_updater.main)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_core/lib/flags.py", line 147, in StartMain
    main(sys.argv)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/bin/config_updater.py", line 293, in main
    config_updater_util.GenerateKeys(
AttributeError: 'module' object has no attribute 'GenerateKeys'

>

**Comment by mbushkov** [comment]
Hi @emmonsk , this issues was fixed https://github.com/google/grr/commit/a90faeb2f6f9b0cb75ebf56d56d5489d271338f0#diff-cfe5c9b1c404b1b4d6ac90d5ba5ebfbd

Which release do you have exactly? The issue was found after GRR 3.2.4.5 was released and fixed in GRR 3.2.4.6 release.

**Comment by emmonsk** [comment]
via the web client, it appears that I am running GRR 3.2.4.6

I downloaded the deb from here: https://storage.googleapis.com/releases.grr-response.com/grr-server_3.2.4-6_amd64.deb

**Comment by mbushkov** [comment]
@emmonsk , what is the output of the following? 
```grr_config_updater version```

**Comment by mbushkov** [comment]
Yes, it's the same. Hm, this is strange.
```
$ sudo grr_config_updater generate_keys --overwrite_keys
Using configuration <GrrConfigManager  file="/usr/share/grr-server/install_data/etc/grr-server.yaml"  file="/etc/gr
r//server.local.yaml" >
All keys will have a bit length of 2048.
Generating executable signing key
Generating CA keys
Generating Server keys
Generating secret key for csrf protection.
Not updating csrf key as it is already set.

$ grr_config_updater version
GRR configuration updater 3.2.4post6
```

Just in case, do you still have the DEB you installed GRR from? Can we double check that it's the same file?
```
$ cat grr-server_3.2.4-6_amd64.deb | md5sum
c18d2ab3eb689e8483b9c050b1c9f4b7  -
```

**Comment by emmonsk** [comment]
Unfortunately I do not. Just doing some initial testing with GRR in our environment so  I am going to try reinstalling. I will close this issue and reopen if the problem continues. 

Thanks for the help!
