### ISSUE TITLE
GRR Docker image does not work MySQL fail

### ISSUE THREAD

**Issue by yinko216** [google/grr#666]

**Comment by yinko216** [comment]
Following the documentation to setup GRR docker image fails with 
` * Starting MySQL database server mysqld
   ...fail!`
Followed Quickstart instructions, downloaded image, used provided run command.

**Comment by demonchild2112** [comment]
I can't provide an ETA for the fix at the moment. If you would like to try out GRR, I recommend using a Xenial host. Running a GRR container inside a Virtualbox Xenial VM inside a MacOS host doesn't seem to work either.

**Comment by theshades** [comment]
Tried running the following:  docker run -P -p 8000:8000 --name=responder --network dockernet  grrdocker/grr:latest
 * Starting MySQL database server mysqld
   ...fail!

Docker Version: Docker version 18.09.6, build 481bc77
Host OS:
lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial

I tried to link it to my other mysql docker instance, but that appears to have no effect.

**Comment by theshades** [comment]
If wondering I tried without the network command too.

**Comment by demonchild2112** [comment]
@theshades I'm unable to reproduce the failure on a clean Xenial VM. Does this happen with the latest release version (currently v3.2.4.6, released 5 months ago)? You can set `DISABLE_INTERNAL_MYSQL=true` to skip starting up the MySQL installation inside the docker container, as described [here](https://grr-doc.readthedocs.io/en/v3.2.4/installing-grr-server/via-docker.html).

**Comment by grrrrrrrrr** [comment]
I'll close this due to lack of activity. If this is still an issue, please feel free to reopen.

**Comment by yinko216** [comment]
Can you add MacOS support to a feature request list or something so this issue can eventually be addressed?

**Comment by grrrrrrrrr** [comment]
So we could but supporting macOS is really low priority for us. We see the Docker image as a way to quickly try GRR without having to set up a proper server. If for that you need an Ubuntu machine / cloud instance that seems reasonable. If you want to run GRR at scale, we don't recommend using the Docker image or macOS at this point anyways.

**Comment by mbushkov** [comment]
@grrrrrrrrr there's one scenario when we may be interested in macOS support for our Docker image: if we use docker containers for end-to-end testing. Given that Docker can be used on Mac and Windows, we can use potentially use it to instrument Travis to do full end-to-end testing cycle on all the platforms on every commit.
