### ISSUE TITLE
Supported MacOS versions

### ISSUE THREAD

**Issue by kaustavbhattacharjee** [google/grr#669]
I am not being able to install the GRR client on macOS Mojave 10.14.2 . 
Is it supported on this OS version?
![screenshot 2019-02-14 at 12 17 49 am](https://user-images.githubusercontent.com/7832958/52735638-1b677e00-2fee-11e9-9aa3-1685e09a9966.png)
![screenshot 2019-02-14 at 12 18 09 am](https://user-images.githubusercontent.com/7832958/52735639-1b677e00-2fee-11e9-8e8f-02bf5ec2511e.png)

**Comment by demonchild2112** [comment]
What gets printed when you install the package from a terminal?

E.g:

```bash
sudo installer -verbose -pkg grr_3.2.4.6_amd64.pkg -target /
```

**Comment by kaustavbhattacharjee** [comment]
This is the output:

```
installer: Package name is grr
installer: Installing at base path /
installer: Preparing for installation….....
installer: Preparing the disk….....
installer: Preparing grr….....
installer: Waiting for other installations to complete….....
installer: Configuring the installation….....
installer: 	
#
installer: Writing files….....
#
installer: Writing files….....
#
installer: Running package scripts….....
installer: Validating packages….....
#
installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
```

**Comment by demonchild2112** [comment]
I downloaded the latest release server deb from https://github.com/google/grr/releases (3.2.4.6) and was able to install the included MacOS template on Mojave.

A few questions to help shed a bit more light on this:
- How did you install GRR on your server, and what version of GRR did you install?
- Did you use the package that gets repacked during installation of the GRR server deb?
- Are you able to find any more debug information about the failed installation, e.g. by running `cat /var/log/system.log | grep grr`?
- Can you repro this on an older MacOS version (e.g you can try installing an older version of MacOS in a VM)

**Comment by kaustavbhattacharjee** [comment]
Thanks on your update.
I would like to replicate this issue on an older macOS but am not sure how to use macOS on a VM.
Actually all my machines are physical Mac devices hence not sure how to put this image on a VM.

Can you help me on this part?

**Comment by demonchild2112** [comment]
I've never done it myself, but here are a couple of links I found:

https://docs.vmware.com/en/VMware-Fusion/11/com.vmware.fusion.using.doc/GUID-474FC78E-4E77-42B7-A1C6-12C2F378C5B9.html

http://osxdaily.com/2018/10/21/download-macos-high-sierra-from-mojave/

I'm still curious about how you installed the GRR server, as I asked before.

**Comment by grrrrrrrrr** [comment]
As mbushkov@ said, we can't reproduce this issue. The GRR client installs on Mojave just fine for us (on lots of machines :) ). I'll close here, let me know if this is still a problem for you.
