### ISSUE TITLE
travis/fetch_client_templates.sh requires authentication

### ISSUE THREAD

**Issue by huskyjag** [google/grr#670]
Hi all,

we are rolling our own RPM packages from the GRR source to deploy the GRR server. We are performing mostly the same steps as you do when building the DEBs. However, since [0abb895bb0a1f0c030807b768bd1bd9746cd9fa2](https://github.com/google/grr/commit/0abb895bb0a1f0c030807b768bd1bd9746cd9fa2) the GCS buckets containing the client templates require authentication. Thus, travis/fetch_client_templates.sh ends up in an endless loop trying to authenticate. Running travis/set_up_gcs_auth.sh does not work since we do not contain the keys :-)

Is there any other possibility to fetch the client templates?

Thanks!

**Comment by demonchild2112** [comment]
Thanks for reporting this. The GCS bucket was made private, but that was unintentional. I've made it public again.
