### ISSUE TITLE
GRR datastore opent connections #

### ISSUE THREAD

**Issue by vorsklaa** [google/grr#673]
Hello,

Testing GRR version 3.2.4.8 with MySQLAdvancedDataStore in prod. Each GRR component has been split off and has its own box - things appear to be operating as they should.

Problem: it does not look like open connections to MySQL are getting cleaned up very well and eventually datastore server dies and requires a reboot of box before being usable again.

Is there anything I can do for the "established" connections? Especially when grr-server(s) are not even running anymore and there are still established connections left on MySQL server. Or is there something else I'm missing?

Any and all advice/assistance is much appreciated, as rebooting the MySQL box every 24h does not seem like a good solution to this problem. 

Thank you in advance and GRR is awesome!

**Comment by mbushkov** [comment]
Hi! A few questions:
* Do I understand it right, that you see "established" connections on MySQL box even when connecting processes are already dead?
* Do you have more data on the origins of the connections? Do they come from GRR workers or frontends or AdminUI or are they evenly distributed between different GRR components?

**Comment by vorsklaa** [comment]
Do I understand it right, that you see "established" connections on MySQL box even when connecting processes are already dead? - yes sir, this is correct. 
Do you have more data on the origins of the connections? Do they come from GRR workers or frontends or AdminUI or are they evenly distributed between different GRR components? - I do not want to give incorrect info here, but off the top of my head it seemed to be mostly frontends.
I'm testing it one more time tomorrow and will confirm for sure.
Any other info I should gather for this?

**Comment by vorsklaa** [comment]
> Hi! A few questions:
> 
> * Do I understand it right, that you see "established" connections on MySQL box even when connecting processes are already dead?
> * Do you have more data on the origins of the connections? Do they come from GRR workers or frontends or AdminUI or are they evenly distributed between different GRR components?

Looks like it's all of the components and not just the frontends. I just have the most frontends running.

**Comment by mbushkov** [comment]
@vorsklaa , sorry, I don't have enough context to understand what may cause the problem. This may be something that is specific to your deployment (we haven't seen this kind of behaviour before). The fact that it's MySQL server itself that can't drop the connections is especially strange. Is it MySQL or MariaDB? Did you do any changes to its standard configuration? If you run in the cloud, would it be possible to experiment with running against cloud-hosted MySQL service (something like "Cloud SQL for MySQL" on Google cloud) and see if the issue persists?

**Comment by vorsklaa** [comment]
@mbushkov , no worries, I understand. Was hoping for ideas or maybe something easy I may have missed.
> Is it MySQL or MariaDB? 
It is MySQL

> Did you do any changes to its standard configuration?
Yes, minimally. Mostly to raise open files limits, packets, max connections and this sort of things. I am also going to need to do a lot more work to get MySQL to be up to "standard". This is, most likely, the root of the issues.
I am guessing this behavior is related to MySQL crashing, but it is just a guess at this point.

> If you run in the cloud, would it be possible to experiment with running against cloud-hosted MySQL service (something like "Cloud SQL for MySQL" on Google cloud) and see if the issue persists?
I started with an Amazon RDS, but numbers of connections got out of control and since there is no os-level access there it was actually more difficult to troubleshoot so MySQL server was created to replace it.

Thank you very much and if you guys ever get a chance to put out "best practices" for GRR and MySQL configuration  - example my.cnf optimized for large GRR deployment would be extra-helpful!

**Comment by soundwave01** [comment]
I have also noticed this happening after upgrading to 3.2.4.8 as well, as soon as I start any big hunts.  With mysql max connects set to 2k, 20 workers and 10 front end workers.

**Comment by grrrrrrrrr** [comment]
The new data store should behave much better, I hope this is not a problem anymore. I'll close this issue, let me know if this still happens in your environment with GRR >= 3.3.0.0
