### ISSUE TITLE
Audit log

### ISSUE THREAD

**Issue by chinguunhr** [google/grr#674]
HI, Folks

I just want to know what threat hunters did on clients computers using GRR. So is there any audit log ?

**Comment by demonchild2112** [comment]
I'm not sure I understand what you are asking. An audit log of what?

GRR allows you to collect a wide variety of forensic information from machines, but it is ultimately up to you to specify what pieces of data you want to collect, e.g. which files on system, or which registry keys, etc. Artifacts are one way of telling GRR what information you want to collect. You can find documentation on artifacts here: https://grr-doc.readthedocs.io/en/latest/investigating-with-grr/artifacts/overview.html

**Comment by mbushkov** [comment]
@chinguunhr , if you're interested in what GRR users did on specific GRR clients, then you should look in 2 places:

- Flows in "Managed launched flows" of every individual client. Flows can't be deleted and GRR users can only interact with any machine by running flows. By looking at flows you'll see everything that was collected/downloaded from the machine.
- If you're interested in a finer-grained audit log (who approved what, etc), we have a few audit reports available in "Server Stats" in the AdminUI.

**Comment by grrrrrrrrr** [comment]
To make this issue even more confusing, there is also a proper audit log written to the database but we are not exposing it anywhere in the UI.

You need to use the console, the functions to read it are at https://github.com/google/grr/blob/8c60d9198cc0875a8ea80b90237eb0a8272082ff/grr/server/grr_response_server/flows/general/audit.py#L40

This is not very well documented since we are going towards the new datastore soon.

**Comment by siftuser** [comment]
> * Server Stats
Hi @mbushkov , I dont see Server Stats in adminui ... using v3.2.4. Thanks in advance!

**Comment by siftuser** [comment]
> audit.py

Hi @grrrrrrrrr, sorry to bother - how do I use this script from console ? Thanks!

**Comment by grrrrrrrrr** [comment]
Console snippet to read audit logs:
```
start_time = rdfvalue.RDFDatetime.Now() - rdfvalue.Duration("52w")
end_time = rdfvalue.RDFDatetime.Now()
for collection in audit.LegacyAuditLogsForTimespan(start_time, end_time):
     for event in collection:
         print event
```

That gives you a list of event that look like:

```
message AuditEvent {
 action : RUN_FLOW
 flow_name : u'PurgeClientStats'
 id : 4032094871
 timestamp : RDFDatetime:
    2019-05-09 09:10:30
 urn : RDFURN:
    aff4:/cron/PurgeClientStats/F:7235062F
 user : u'GRRCron'
}
message AuditEvent {
 action : HUNT_CREATED
 description : u'Interrogate'
 flow_name : u'Interrogate'
 id : 1545890286
 timestamp : RDFDatetime:
    2019-05-09 09:10:31
 urn : RDFURN:
    aff4:/hunts/H:20107D1E
 user : u'GRRWorker'
}
message AuditEvent {
 action : HUNT_STARTED
 description : u'Interrogate run by cron to keep hostinfo fresh.'
 id : 4259142169
 timestamp : RDFDatetime:
    2019-05-09 09:10:31
 urn : RDFURN:
    aff4:/hunts/H:20107D1E
 user : u'GRRWorker'
}
```

Hope that helps...
