### ISSUE TITLE
GRR UI behind Apache to protect UI traffic via SSL

### ISSUE THREAD

**Issue by siftuser** [google/grr#676]
Configured GRR UI behind Apache to protect UI traffic via SSL as suggested in https://grr-doc.readthedocs.io/en/v3.2.4/maintaining-and-tuning/user-management/running-behind-apache.html. 

When I browse => **https://my_grr_server** it does not load grr gui .. however the gui loads on default http://my_grr_server ... any clue/help will be greatly appreciated! Thanks

**Comment by mbushkov** [comment]
Hi @siftuser ! A few questions:

- What does "does not load" mean precisely? What kind of errors does Chrome show?
- Do you see anything in Apache logs when you try to load https://my_grr_server?

**Comment by siftuser** [comment]
My bad ... apologies ... firewall was blocking ingress traffic ... fixed it ... all good now ... many thanks! sorry again :(

**Comment by mbushkov** [comment]
No worries. Glad that the issue is resolved :)
