### ISSUE TITLE
Question: how to clean up a large datastore

### ISSUE THREAD

**Issue by soundwave01** [google/grr#677]
Hi,

We have reasonable size deployment which has been running for a few years now.  As a result our datastore (mysql) is now over 100GB in size.  I would like to try to bring this down by cleaning out old stuff of active clients, old flows, old host information etc.

But I'm a but stuck on how todo this.  Any pointers would be greatly appreciated!

We already make use of the cron to remove inactive clients, but the problem is not them, it's the very long running active clients.

Given the next version will have a complete schema change with no data migration, maybe I just wait for that?

Thank you in advance for any help.

**Comment by demonchild2112** [comment]
One option would be to start over from an empty database. Existing clients should be able to re-enroll with their previous client ids.

**Comment by mbushkov** [comment]
@soundwave01 , +1 to what @demonchild2112 suggested. You can archive your existing database and then just start with an empty one.

It's also true that you might want to simply wait for the next GRR version with a new datastore implementation, as there will be no way to migrate the data and you'll have to start with an empty datastore anyway. As @demonchild2112 pointed out, starting from scratch won't affect already-deployed clients, they will continue to check in with their existing client ids.

**Comment by soundwave01** [comment]
Thank you for the suggestion ill give it a go

**Comment by pidydx** [comment]
There should be a number of cron jobs that control inactive data cleanup.  If you configure the TTLs for those cron jobs they will start purging old data.

**Comment by soundwave01** [comment]
@pidydx thanks, ill double check. I though I had them all set.  I know I had the inactive clients set for 60 days.

Something I had not anticipated from a database wipe is the additional load all clients enrolling and first interrogation.   Need to add a new more servers to clear the back log.

Thank you again for all of the suggestions

**Comment by pidydx** [comment]
Yeah, that can be devastating in a large environment.  I am still working through some issues, but hopefully I will be able to get my branches reintegrated and sent as PRs soon.  I rearranged the Enrollment process to prevent that from happening and to prevent the double Interrogate that happens when a new client enrolls.

**Comment by grrrrrrrrr** [comment]
I will close this issue here. One of the nice things in the new datastore which is now default for new deployments is that it stores data much more efficiently and also deleting objects is just a simple SQL delete.
