### ISSUE TITLE
High volume of WORKER_STUCK errors during hunt

### ISSUE THREAD

**Issue by soundwave01** [google/grr#681]
I have upgraded GRR server to 3.2.4.6, but virtually all of the clients are running 3.2.3.2.

As part of that upgrade, I cleaned out the datastore (as per suggestion in #677).  This resulted in all the agents registering and requiring an initial interrogation and placed a high load on the servers.  End result we had a number of clients enrolled, but the initial interrogation failed.

So I ran a hunt to interrogate all clients.  This resulted in a number of (3.5 pages worth in the hunt errors) "1040, \'Too many connections\')\n' network_bytes_sent : 324 status : GENERIC_ERROR "  similar to what is detailed in #673

But that was dwarfed by the number of 

```
message GrrStatus {
 child_session_id : SessionID:
    aff4:/hunts/H:A0279596/C.987697d32ecea908/H:35236D6F
 cpu_time_used :   message CpuSeconds {
     system_cpu_time : 0.4375
     user_cpu_time : 0.71875
    }
 error_message : u'Traceback (most recent call last):\n  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/flow_runner.py", line 568, in RunStateMethod\n    method(responses)\n  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/flows/general/discovery.py", line 265, in ProcessKnowledgeBase\n    "Error while collecting the knowledge base: %s" % responses.status)\nFlowError: Error while collecting the knowledge base: message GrrStatus {\n child_session_id : SessionID:\n    aff4:/hunts/H:A0279596/C.987697d32ecea908/H:35236D6F/H:7A0AD873\n cpu_time_used :   message CpuSeconds {\n     system_cpu_time : 0.015625\n     user_cpu_time : 0.078125\n    }\n error_message : u\'Stuck in the worker\'\n network_bytes_sent : 739\n status : WORKER_STUCK\n}\n'
 network_bytes_sent : 8958
 status : GENERIC_ERROR
}

```
I have 800+ clients with this error.  We noticed issues starting with 3.2.3.2 where clients some hung (clients were reporting as alive, but would not accept any more flows).   However we could not replicate the issue consistently enough or find any direct errors to raise an issue for it.  I don't know if the that issue and this issue are linked or not.

Would anyone have any idea what the issue might be for this WORKER_STUCK error?  I will attempt to try to replicate it to get debug logs from a client, as I cant globally rollout the debug version of the client.

Thank you in advance for any help.

**Comment by mbushkov** [comment]
@soundwave01 - thanks for a detailed report!

WORKER_STUCK is a server-side error. It gets reported when a flow is detected as stuck by GRR worker. The flow may get stuck if a notification for it is not correctly written to the database, or when a notification is read for processing, but then the worker dies while processing it and never updates the flow state. The above may happen if a GRR worker has troubles connecting to the database - "too many connections open" errors in your case could have triggered the issue.

When you ran a hunt to interrogate the clients after emptying the database, what client rate did you set?

**Comment by soundwave01** [comment]
rate was set at 30 clients per min. After 3 days of running there is still about 45% of the estate left (out of ~10k clients) around 1k errors and 3 crashes.

**Comment by mbushkov** [comment]
Client rate of 30 per min seems reasonable. On the other hand, taking 3 days to process ~5k clients is way below this rate. It seems that either the workers or frontends (or both) are overloaded.

Interrogate hunt is supposed to be scheduled by GRR Cron on a weekly basis. Were such hunts completing fine before? Or did they have the same issue?

**Comment by soundwave01** [comment]
All servers are currently idle, at the start of the hunt they were maxed out.  We don't tend to need to use big hunts, so I don't have good case history.

However I did a test interrogate hunt limited to 100 machines, that appears to have only completed 59 in 4 days.

Cron wise, after the datastore wipe, I'm only left with a single cron job "LastAccessStats"  there were around 10 or before that.  Should I expect to see an interrogate cron job?

**Comment by mbushkov** [comment]
I'd expect InterrogateClientsCronFlow to be present in the list. It should be initialized automatically on every worker restart (see https://github.com/google/grr/blob/b719185ad29ad8aa7b5b156b3954366a30c71b83/grr/server/grr_response_server/aff4_objects/cronjobs.py#L326).

Just in case: you've restarted the workers after the database wipe, right?

Also, what happens if you try to run an interrogate hunt with a client limit of 100 and a client rate of, say, 5. How many clients complete after 30-40 mins?

**Comment by soundwave01** [comment]
I thought I has restarted the workers, but have just done it case I had not.  still only one cron job.

I ran a quick test hunt as you suggested.  The results of which are:

```
Name
    GenericHunt
Description
    another hunt test
Hunt ID
    H:90DEAD3E
Creator
    xxxxxxxxx
Start Time
    2019-03-26 14:19:53 UTC 
Expiry Time
    2019-03-26 15:20:01 UTC 
Crash Limit
    100 
Client Limit
    100 
Client Rate (clients/min)
    5 
Status
    PAUSED
Clients Queued
    0
Clients Scheduled
    100
Clients Outstanding
    21
Clients Completed
    79
Clients with Results
    79
Results
    79
Total CPU Time Used
    2m 3s 
Total Network Traffic
    8.5MiB 
```

seemed better, but only managed a client rate of 1.3 per min by the end of the hour.

cherry picking some of the outstanding clients, there is no consistent pattern.  Some appear to be waiting for previous interrogations to be completed, some might have 1/2 of of the interrogate flows still running, some only had one flow still running.
  
Again thank you for your help on this.

**Comment by soundwave01** [comment]
I have done some more playing with this.  I have rerun the full estate hunt, but lowered the Client Rate to 5/mins

It seems a lot happier at this speed.  only 10 WORKER_STUCK errors of the 6k machines completed so far.

I'll try to look to see why all the system cron jobs appear to be missing.

**Comment by soundwave01** [comment]
lowering the speed did the trick, full run ran without issues.

Thank you for the suggestions!
