### ISSUE TITLE
Cookie Security：Overly Broad Path

### ISSUE THREAD

**Issue by 360CodeSafe** [google/grr#684]
grr-master/grr/server/grr_response_server/gui/wsgiapp.py  69
![image](https://user-images.githubusercontent.com/39950310/56420737-c1c34e80-62d1-11e9-8085-1708a9a9e875.png)
Suggest setting path（‘/childpath’）,Narrow the Cookie path

**Comment by mbushkov** [comment]
GRR Admin UI does not support running on a subpath, so there's nothing that we can narrow down the cookie path to.
