### ISSUE TITLE
Proxy Auto-Config

### ISSUE THREAD

**Issue by indigocarmen** [google/grr#690]
Is there a way to turn off the Windows environment proxy auto-configuration? We run a mainly Windows shop, and can easily bypass the proxy for our GRR addresses. However, the auto-detection function is still populating the Proxy fields that we use and breaking functionality. 

I have also tried to configure 'no' proxy through 
```Client.proxy_servers: [""]```

But this appears to do nothing and the client still attempts to use the Windows Proxies. Also, on according to https://github.com/google/grr/issues/631 the FTP failure should be fixed. I am running 3.2.4.6 but still seeing that failure, not sure if it is impactful yet, as all the proxies are impactful right now. 

Thanks in advance!

**Comment by mbushkov** [comment]
At the moment there seems to be no way to disable the proxies (see https://github.com/google/grr/blob/0671ba57bc585c4e1baaabfafae001d19dcc397a/grr/client/grr_response_client/comms.py#L173). However, if all the proxies fail, a direct connection should be made (see https://github.com/google/grr/blob/0671ba57bc585c4e1baaabfafae001d19dcc397a/grr/client/grr_response_client/comms.py#L179).

Why using client proxies is impactful? Do I understand it right, that proxies can't access GRR frontends?

**Comment by indigocarmen** [comment]
Thanks for your response! That gave me the answer I need. So I edited that file:
```
 def _GetProxies(self):
    """Gather a list of proxies to use."""
    # Detect proxies from the OS environment.
     result = client_utils.FindProxies()

```
``` 
 def _GetProxies(self):
    """Gather a list of proxies to use."""
    # Detect proxies from the OS environment.
   # result = client_utils.FindProxies()
    result=[]
```
