### ISSUE TITLE
Hunts are stopped after 11 crashes

### ISSUE THREAD

**Issue by Karneades** [google/grr#692]
Hi

I run into a hunt stop due to crash limits. I set the crash limit to 100 but two tests stopped the hunt at 11 crashs.

Some references:

https://github.com/google/grr/blob/a182f8cd21dda52057c9a94faa1b814bed522ea3/grr/proto/grr_response_proto/hunts.proto#L76
https://github.com/google/grr/blob/a182f8cd21dda52057c9a94faa1b814bed522ea3/grr/core/grr_response_core/config/server.py#L246
https://github.com/google/grr/blob/a182f8cd21dda52057c9a94faa1b814bed522ea3/grr/server/grr_response_server/rdfvalues/hunts.py#L82
https://github.com/google/grr/blob/a182f8cd21dda52057c9a94faa1b814bed522ea3/grr/server/grr_response_server/rdfvalues/hunt_objects.py#L98

Does my hunt stop due to the default value in hunts.proto which does not get overwritten by our hunt definition?

Thanks for any hints.

**Comment by mbushkov** [comment]
`optional uint64 crash_limit = 11` means that crash_limit is a protobuf field with an index number 11. I.e. this line has no relation to a crash_limit default value. The fact that you have 11 crashes may be a pure coincidence. Hunt's crash limit should be clearly indicated in the GRR UI. What do you see on the hunt details page (in the "Crash Limit" line)?

How many clients completed before the hunt got stopped (see "Clients Completed" line on the hunts details page)?

**Comment by Karneades** [comment]
OK, sorry for mixing up the protobuf field index :/

I see 100 for crash limit in the UI for both hunts. And above 1000 clients completed. Once 11 and once 13 crashes stopped the hunt without any user interaction.

**Comment by Karneades** [comment]
There's also no "hunt stopped by to many crashes" in the log as it would according to the source code. So I'll check the logs again because it doesn't seem to be a default value issue :)

**Comment by mbushkov** [comment]
Unfortunately at the moment the UI does not present a clear reason for why the hunt was stopped.

But the fact that you have exactly 1000 clients completed is a good indicator that one of the "average limits" kicked in. These limits can be configured in the "Advanced" section of "Hunt parameters" when scheduling the hunt.

<img width="510" alt="Screen Shot 2019-05-13 at 10 00 57 PM" src="https://user-images.githubusercontent.com/904981/57650249-b0b4e700-75ca-11e9-871e-2ce88b5b5647.png">

After the hunt processes 1000 clients, it calculates average CPU usage, average network usage and average number of results per client. If any of these values exceeds the average limit (you see the defaults on the picture above), the hunt is going to be stopped.

Default values for these average limits are controlled by configuration options: Hunt.default_avg_results_per_client_limit, Hunt.default_avg_cpu_seconds_per_client_limit and Hunt.default_avg_network_bytes_per_client_limit. See https://github.com/google/grr/blob/88880d18483588359f86d4b77267081fc315ed15/grr/core/grr_response_core/config/server.py#L253 for more details.

**Comment by Karneades** [comment]
@mbushkov Thanks so much for the hint regarding the averages after 1000 clients... I was not aware of that. It was indeed probably an CPU average issue.

FTR Under stats in the UI theses averages are shown and also the worst performers.

**Comment by Karneades** [comment]
FTR The docs already describes these options: https://grr-doc.readthedocs.io/en/latest/investigating-with-grr/hunts/limits.html.
