### ISSUE TITLE
psutil.getloadavg() on windows issue

### ISSUE THREAD

**Issue by AgainCrazyCode** [google/grr#693]
```
# coding=utf-8
import psutil
import time

while True:
    result = psutil.getloadavg()
    print(result)
    time.sleep(5)

```

C:\X>python psutil.test.py
(0.0, 0.0, 0.0)
(0.0, 0.0, 0.0)

C:\X>python -V
Python 3.7.3

C:\X>ver

Microsoft Windows [版本 10.0.17763.475]

why only 2 times ?
and then exit nothing message tips

**Comment by grrrrrrrrr** [comment]
Hey, this is a psutil issue, not a GRR one. Your bug is already filed at https://github.com/giampaolo/psutil/issues/1510 , please follow that issue instead.

Cheers,
-Andy

**Comment by AgainCrazyCode** [comment]
Oh...,sorry
Thank you
