### ISSUE TITLE
Issue with config on startup

### ISSUE THREAD

**Issue by TheEagle13** [google/grr#702]
GRR seems to be having a fit with one of the options in my server.local.yaml.

I followed the config guide for setting up email, but upon starting the server, I get the following error then none of the configs are applied.

`grr_response_core.lib.config_lib.MissingConfigDefinitionError: Missing config definition for Worker.smpt_port. This option is likely deprecated or renamed. Check the release notes.`

My config for the port is:

`Worker.smpt_port: 587`

If I comment out this line, it uses a default of port 25, which is not usable as port 25 is blocked.

Any suggestions? Thanks in advance!

**Comment by mbushkov** [comment]
Hi! There's a typo in your config file. You have Worker.sm***pt***_port. It should be Worker.sm***tp***_port.

**Comment by TheEagle13** [comment]
Thank you @mbushkov . I didn't bother spell checking since I copy and pasted from the docs.... 
I went back and looked at the official documentation, and it appears that the official documentation has that typo too, and should be updated.

https://grr-doc.readthedocs.io/en/latest/maintaining-and-tuning/email-configuration.html

https://github.com/google/grr-doc/blob/master/maintaining-and-tuning/email-configuration.md

**Comment by mbushkov** [comment]
@TheEagle13 , thanks for pointing this out!
I've fixed the docs: https://github.com/google/grr-doc/commit/63dc8be8182eea25765a4ef6d9069ee7e5b704a1

https://grr-doc.readthedocs.io will update itself shortly.
