### ISSUE TITLE
Tag 3.3.0.0 release at dockerhub

### ISSUE THREAD

**Issue by atkinsj** [google/grr#703]
Most recent tag at https://hub.docker.com/r/grrdocker/grr/tags is still 3.2.4.6. Would you mind tagging a 3.3.0.0 release?

**Comment by mbushkov** [comment]
@atkinsj , we had some issues with the way our GitHub/DockerHub integration is set up. Consequently, there's a delay with building the latest Docker image. We're looking into this and will keep you updated.

**Comment by atkinsj** [comment]
Thanks!

**Comment by mbushkov** [comment]
@atkinsj , our DockerHub integration is still lacking, but I've built and pushed the new image by hand. Please see `v3.3.0.0` in https://hub.docker.com/r/grrdocker/grr/tags.

**Comment by atkinsj** [comment]
Perfect, thank you!

**Comment by mbushkov** [comment]
One note. I noticed that the new relational datastore (REL_DB) wasn't enabled by default in the v3.3.0.0 Docker image.
Fixed that: https://github.com/google/grr/commit/01e089aa0eaea573b9933f9de3443813b9df2605
I re-uploaded the image. Hope this doesn't create any inconveniences.
