### ISSUE TITLE
CleanHuntsCronJob Error

### ISSUE THREAD

**Issue by clairmont32** [google/grr#706]
Hello,

It seems like the CleanHuntsCronJob is having issues clearing out the expired. I unfortunately cannot attach a screenshot at this time, however, here's a copy paste of the error in the table. There does not seem to be a log entry in `/usr/share/grr-server/lib/python2.7/site-packages/grr_response_core/var/log/grr-ui.log ` related to this job but another issue with `InterrogateClientsCronJob` (will add my log snippet to issue #701). 

 Run ID | Started At | Finished At | Log Message | Backtrace 
 EC2B6DED | 2019-05-30 19:07:34 UTC | 2019-05-30 19:07:34 UTC | Relational database not supported.

Version 3.3.0.0
`Linux <hostname> 4.4.0-148-generic #174-Ubuntu SMP Tue May 7 12:20:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by mbushkov** [comment]
Hi! At the moment ClearHuntsCronJob is a no-op. It doesn't actually error out - it simply does nothing.
https://github.com/google/grr/blob/0671ba57bc585c4e1baaabfafae001d19dcc397a/grr/server/grr_response_server/flows/cron/data_retention.py#L78

 We'll add a proper implemention into the next GRR release. Given that `DataRetention.hunts_ttl` is expected to be set to a relatively large value (90d, 180d) and given that you need to start with a fresh database when using the new REL_DB datastore, the lack of CleanHuntsCronJob shouldn't be an issue for the time being.

**Comment by clairmont32** [comment]
Cool thanks!

**Comment by clairmont32** [comment]
> Hello,
> 
> It seems like the CleanHuntsCronJob is having issues clearing out the expired. I unfortunately cannot attach a screenshot at this time, however, here's a copy paste of the error in the table. There does not seem to be a log entry in `/usr/share/grr-server/lib/python2.7/site-packages/grr_response_core/var/log/grr-ui.log ` related to this job but another issue with `InterrogateClientsCronJob` (will add my log snippet to issue #701).
> 
> Run ID | Started At | Finished At | Log Message | Backtrace
> EC2B6DED | 2019-05-30 19:07:34 UTC | 2019-05-30 19:07:34 UTC | Relational database not supported.
> 
> Version 3.3.0.0
> `Linux <hostname> 4.4.0-148-generic #174-Ubuntu SMP Tue May 7 12:20:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

@mbushkov I just noticed the same error for CleanInactiveClientsCronJob as well.
