### ISSUE TITLE
upgrading 3.2.4.6 to 3.3.0

### ISSUE THREAD

**Issue by siftuser** [google/grr#707]
a) I could not find procedure to upgrade on documentation site
b) How does it affect clients running 3.2.4.6 while server is upgraded to 3.3 ? 
c) Would the software upgrade work without changes to DB ?
d) finally, if client upgrade is advisable, is it using new binaries  ? 

Many thanks in advance!

**Comment by mbushkov** [comment]
Hi! Please see the answers below:
a) If you installed GRR from the DEB package, then upgrading GRR should be equivalent to just installing the new GRR server DEB. Of course, backing up your server before the upgrade is recommended anyway. Please see the following documentation page for the details on how to switch to the new REL_DB datastore (if you decide to): https://grr-doc.readthedocs.io/en/latest/maintaining-and-tuning/grr-datastore.html#switching-an-aff4-based-deployment-to-use-rel-db
b) 3.2.4.6 clients are compatible with 3.3 server. Still, we advise to eventually upgrade the clients to the latest version after the server upgrade.
c) Yes.
d) The 3.3.0.0 server is shipped with the 3.3.0.0 client templates which should be repacked during the installation and available for download in the "Binaries" page of the GRR Admin UI.

**Comment by siftuser** [comment]
Many thanks @mbushkov !

I just upgraded the test environment using deb pkg. used default / previous setting. But the 3246 test client does not connect to 3300 server. 

client run in verbose mode => 
```
INFO:2019-06-04 12:10:30,877 comms:1344] Starting client aff4:/client_id
DEBUG:2019-06-04 12:10:30,882 admin:353] Sending startup information.
DEBUG:2019-06-04 12:10:30,885 connectionpool:205] Starting new HTTP connection (1): server:port
DEBUG:2019-06-04 12:10:30,961 connectionpool:393] http://server:port "GET /server.pem HTTP/1.1" 200 1005
INFO:2019-06-04 12:10:30,965 comms:1045] Unable to verify server certificate at http://server:port/server.pem: Server cert is invalid:
```

**Comment by mbushkov** [comment]
Hm, it seems that the server keys were regenerated.

During the installation have you seen something like the message below?
```
Step 2: Key Generation")
Since you have imported keys from another installation in the last step,
you probably do not want to generate new keys now.

You already have keys in your config, do you want to overwrite them? [yN]: 
```

Do you have a backup version of your GRR server config somewhere (etc/grr/server.local.yaml)? Do you think you can diff the old and the new configuration and see if the keys have changed?

**Comment by siftuser** [comment]
sorry I dont ... and dont recollect either. which dirs you suggest to copy for backup/restore ? thanks in advance
