### ISSUE TITLE
osquery.path error

### ISSUE THREAD

**Issue by siftuser** [google/grr#709]
I defined Osquery.path option (/usr/local/bin/osqueryi) in the server GRR configuration. It is reflected under server (v3.3.0.0) settings too. 

However continue to get the error  `Osquery action invoked on a client without osquery path specified.`

Appreciate any help. Thanks

**Comment by mbushkov** [comment]
IIUC, you have to repack the clients after you set this setting. @mrhania , is that correct?

**Comment by siftuser** [comment]
Many Thanks @mbushkov ! that worked like a charm!
