### ISSUE TITLE
Active Directory Integration

### ISSUE THREAD

**Issue by clairmont32** [google/grr#710]
Hello,

My manager was inquiring about assigning labels or queries agents based on AD group (Sales, Finance, Executive, etc). I know this is not implemented currently but I'd be awesome for agent management and targeted queries to be able to have this functionality.

**Comment by demonchild2112** [comment]
You can query AD via WMI, and GRR does support WMI queries. I would recommend taking a look at [artifacts documentation](https://grr-doc.readthedocs.io/en/latest/investigating-with-grr/artifacts/overview.html), as well as [examples](https://github.com/ForensicArtifacts/artifacts/blob/294a2976a3e5d6297a0c198e6661e36960460f7f/data/wmi.yaml#L3) of artifacts that use GRR's WMI functionality. If there isn't an artifact already included in your server installation that fetches the data you need, you should be able to write your own. You can then run a hunt that collects results for the artifact from all Windows machines in your fleet. Finally, you should be able to use [GRR's API](https://grr-doc.readthedocs.io/en/latest/investigating-with-grr/automation-with-api.html) to iterate the results, adding labels to clients as you go.

**Comment by clairmont32** [comment]
Thanks. I'll review the references to see if they meet our AD integration desires.

**Comment by clairmont32** [comment]
Do you happen to have an example of what this hunt would look like? I think I have a rough idea of how it would be built but it seems likea  very ad-hoc means of achieving the goal of a single piece of what a true AD integration would look like.

**Comment by demonchild2112** [comment]
You can test the `ArtifactCollectorFlow` with your artifact on a single machine, then create a hunt from the flow as described [here](https://grr-doc.readthedocs.io/en/latest/investigating-with-grr/hunts/starting.html).

**Comment by mbushkov** [comment]
> I think I have a rough idea of how it would be built but it seems likea very ad-hoc means of achieving the goal of a single piece of what a true AD integration would look like.

@clairmont32 - do you think you can go into a bit more details regarding how you see a true AD integration? What features are missing/required? Is it only assigning labels to clients based on AD groups (understanding the mapping between groups and labels would be helpful too, btw), or do you have something else in mind?

**Comment by clairmont32** [comment]
@mbushkov sorry for the delay, didnt see the notification of your reply. Access control via AD security groups, assignment of labels, and job batching against specific OUs instead of labels are ones that come to mind quickly. I'm sure there's more usecases that can be thought of though.
