### ISSUE TITLE
Ubuntu desktops all appear as 'localhost' instead of their actual hostname

### ISSUE THREAD

**Issue by atkinsj** [google/grr#713]
I suspect this is because a gethostbyname() call that uses /etc/hosts and we don't update /etc/hosts with the hosts actual hostname. `/bin/hostname` returns correctly, could we expand the interrogate workflow for Linux to be a little more robust?

**Comment by demonchild2112** [comment]
I assume you are referring to the FQDN, which is used prominently in the Admin UI to identify clients. We use Python's `socket` library to fetch FQDNs for host machines. The library [seems](https://github.com/python/cpython/blob/1f11cf9521114447b3e32e2ac88f075ffaa37555/Lib/socket.py#L674) to invoke the same [syscall](https://linux.die.net/man/2/gethostname) used by the `hostname` command to obtain the fallback value to use as the FQDN. Are you able to try running the following code in a **grr_console** on one of the client machines (or on the server if it has the same issue)?

```
In [1]: import socket
In [2]: socket.gethostname()
In [3]: socket.gethostbyaddr(socket.gethostname())
```

I find it surprising that the library returns a different value for the hostname. The code above just verifies that.

**Comment by atkinsj** [comment]
I don't have a grr_console binary on a host that has GRR installed, but here's the output from a python2 prompt:

```
>>> import socket
>>> socket.gethostname()
'$correct_hostname'
>>> socket.gethostbyaddr(socket.gethostname())
('localhost', [], ['127.0.0.1'])
>>> 
````

where $correct_hostname is the non-fqdn. on this system, `hostname` and `hostname -f` return the short form non-fqdn.

They show up in the UI as:
<img width="295" alt="Screen Shot 2019-06-11 at 8 41 04 AM" src="https://user-images.githubusercontent.com/10431664/59286470-ac5d0780-8c24-11e9-830d-f734ef9469d5.png">
<img width="208" alt="Screen Shot 2019-06-11 at 8 40 58 AM" src="https://user-images.githubusercontent.com/10431664/59286472-ac5d0780-8c24-11e9-9d78-5b5655804f68.png">

**Comment by demonchild2112** [comment]
Thanks, that was helpful! It should be fairly straightforward to have GRR return the hostname instead of just 'localhost'. I'll submit the fix tomorrow.

**Comment by demonchild2112** [comment]
This is now fixed in HEAD.
