### ISSUE TITLE
BigQueryOutputPlugin fails under 3.3.0.0

### ISSUE THREAD

**Issue by atkinsj** [google/grr#714]
File Finder flow generated this:

```
ERROR:2019-06-11 00:53:04,274 17 MainProcess 140688129767168 flow_processing_pool-419875690 flow_base:771] Plugin BigQueryOutputPlugin <<BigQueryOutputPluginArgs('message BigQueryOutputPluginArgs {\n export_options :   message ExportOptions {\n     annotations : [\n      ]\n    }\n}')>> failed to process 2 replies.

Traceback (most recent call last):
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/flow_base.py", line 751, in _ProcessRepliesWithFlowOutputPlugins
    output_plugin.Flush(output_plugin_state.plugin_state)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/output_plugins/bigquery_plugin.py", line 174, in Flush
    urn_str = self.source_urn.RelativeName("aff4:/").replace("/", "_").replace(
AttributeError: 'unicode' object has no attribute 'RelativeName'
```

Artifact from AFF4 -> REL_DB?

**Comment by mbushkov** [comment]
Hm, this seems to be a typing issue not caught by the unit test.

The line in question (  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/output_plugins/bigquery_plugin.py", line 174, in Flush) should look like:

urn_str = **rdvalue.RDFURN(self.source_urn)**.RelativeName("aff4:/").replace("/", "_").replace(

We should also change the unit test to assign a unicode value to the plugin's source_urn.

**Comment by demonchild2112** [comment]
Thanks for reporting this @atkinsj. I've just submitted a fix, which is included in the latest HEAD server deb.
