### ISSUE TITLE
tsk filefinder results not showing in Browse Virtual Filesystem>fs>tsk v. 3.3.0.0

### ISSUE THREAD

**Issue by vorsklaa** [google/grr#715]
tsk results not showing in Browse Virtual Filesystem>fs>tsk
Error:
> 

Backtrace | Traceback (most recent call last): File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/flow_base.py", line 564, in RunStateMethod method(responses) File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/flows/general/filesystem.py", line 189, in List raise flow.FlowError(str(responses.status)) FlowError: message FlowStatus { backtrace : u'' client_id : u'C.51a51cf2cde50b32' cpu_time_used : message CpuSeconds { system_cpu_time : 0.0 user_cpu_time : 0.0 } error_message : u'path \\ is not mounted under C:' flow_id : u'DC5945FA' network_bytes_sent : 127 request_id : 2 response_id : 1 status : IOERROR }
-- | --

Running just File Finder flow to hash files in %%environ_systemdrive%%/* via tsk - completed with no errors but still shows nothing in Browse Virtual Filesystem>fs>tsk view

Trying to run "refresh" on `Browse Virtual Filesystem>fs>tsk>\\?\Volume{~` after File Finder does not produce IOERROR anymore and just shows nothing outside flow results in Manage Launched Flows

I would appreciate any and all guidance or advice on what may be broken/misconfigured and/or how to fix it :)

Thanks!

**Comment by demonchild2112** [comment]
The flow that failed appears to be a ListDirectory flow. What arguments did you use for that?

**Comment by vorsklaa** [comment]
> The flow that failed appears to be a ListDirectory flow. What arguments did you use for that?

![image](https://user-images.githubusercontent.com/48221993/59356669-32895480-8cde-11e9-83ed-34d49f8bb4c1.png)

No argumenta - just the blue refresh button. Error is from before File Finder tsk flow. If I refresh the directory again there is no more error but no results (or filelisting) showing under tsk.

Thanks!

**Comment by demonchild2112** [comment]
I see. The stack trace in your initial post comes from a failed flow though. It should be accessible in the Admin UI with the following URL:

https://$HOST:$PORT/#/clients/C.51a51cf2cde50b32/flows/DC5945FA

**Comment by demonchild2112** [comment]
To clarify: The refresh buttons launch ListDirectory and RecursiveListDirectory flows respectively on the selected directory.

**Comment by vorsklaa** [comment]
> I see. The stack trace in your initial post comes from a failed flow though. It should be accessible in the Admin UI with the following URL:
> 
> https://$HOST:$PORT/#/clients/C.51a51cf2cde50b32/flows/DC5945FA
> To clarify: The refresh buttons launch ListDirectory and RecursiveListDirectory flows respectively on the selected directory.

Thanks in advance for trying to help. ListDirectory (not touching RecursiveListDirectory lol) launched via button is what fails initially with the funny looking `IOERROR` (example is what I initially posted).
Arguments from one of the ListDirectory failed flows 
```

Pathspec | PathtypeTSKPath/ | Pathtype | TSK | Path | /
-- | -- | -- | -- | -- | --
Pathtype | TSK
Path | /

```

 After just going to FileFinder and using tsk for the hash of everything in %%environ_systemdrive%%/*: it works with no errors BUT nothing shows in the Browse Virtual Filesystem in the Admin UI (like it does in fs>os>C:>FILES)
Arguments used for FileFinder:
```

Paths | %%environ_systemdrive%%$MFT
-- | --
Pathtype | TSK
Action | ActionHASHHashCollect extended attributesfalse | Action | HASH | Hash | Collect extended attributesfalse | Collect extended attributes | false
Action | HASH
Hash | Collect extended attributesfalse | Collect extended attributes | false
Collect extended attributes | false

```

Not sure if these issues are related but posting the info I have here and hoping for advice

Thanks!

**Comment by demonchild2112** [comment]
The path wasn't set correctly for the failed `ListDirectory` flow (it is just `/`). The forward-slash is 'normalized' to a backslash on the client, hence the error. What happens when you make a copy of the failed flow and then specify `C:/` as the path argument? Do you see any results in the `Results` tab of the completed flow?

**Comment by vorsklaa** [comment]
> The path wasn't set correctly for the failed `ListDirectory` flow (it is just `/`). The forward-slash is 'normalized' to a backslash on the client, hence the error. What happens when you make a copy of the failed flow and then specify `C:/` as the path argument? Do you see any results in the `Results` tab of the completed flow?

This illustrates my issue well. Following your instructions did a ListDirectory flow with just `C:/` as an argument:
![image](https://user-images.githubusercontent.com/48221993/59728175-c9c63e80-91ed-11e9-9f9e-d9f5048ca2af.png)
No errors and the flow returned file listing as it should:
![image](https://user-images.githubusercontent.com/48221993/59728191-dc407800-91ed-11e9-9a41-573943793228.png)

TSK section of `Browse Virtual Filesystem` is still blank and I'm still not sure how to fix it to show data:
![image](https://user-images.githubusercontent.com/48221993/59728207-f7ab8300-91ed-11e9-97ad-8a97b6faa2cd.png)

**Comment by demonchild2112** [comment]
This was helpful, thanks!

I actually don't think you are doing anything wrong. Files should appear in the VFS browser in the Admin UI after they are collected. What I think is going wrong is that collected file paths end up with a leading forward slash that shouldn't be there. Therefore, any database queries to fetch directory contents fail to match the intended paths.

**Comment by mrhania** [comment]
Should be fixed in c2fd4051a8a85ae0e50d25b325e70d3a40ae062f.

**Comment by vorsklaa** [comment]
![image](https://user-images.githubusercontent.com/48221993/61553776-13ce5a00-aa10-11e9-966a-ba76c5c35383.png)
On ui v 3.3.0.4 the above error occurred while deploying ListDirectory through Browse Virtual Filesystem > Refresh this directory (button)

**Comment by mbushkov** [comment]
@vorsklaa thanks for reporting this! Do you see any folders under Browse Virtual Filesystem "TSK"? Or is it empty?
What happens if you search for "C:\*" with pathtype TSK with FileFinder?

**Comment by vorsklaa** [comment]
> @vorsklaa thanks for reporting this! Do you see any folders under Browse Virtual Filesystem "TSK"? Or is it empty?
> What happens if you search for "C:*" with pathtype TSK with FileFinder?

TSK is empty (not even a drive is shown)
![image](https://user-images.githubusercontent.com/48221993/61976482-bbafce80-afa0-11e9-8161-840036e07365.png)
FileFinder C:\* for TSK STAT completes without errors and filesystem is shown under "TSK" in Browse Virtual Filesystem afterwards as expected

**Comment by mbushkov** [comment]
@vorsklaa, do I understand it correctly that doing FileFinder with TSK for "C:/*" produces entries that you then see in Browse Virtual Filesystem?
At the moment, using FileFinder (or ClientFileFinder) to make paths appear under TSK is a workaround you have to use. After the paths are there, you can use the "Refresh" button to browse them. 
I've opened a more specific https://github.com/google/grr/issues/727 to track this issue.
