### ISSUE TITLE
GRR UI notification errors

### ISSUE THREAD

**Issue by vorsklaa** [google/grr#721]
Have been unable to find other reports for this and my apologies if it has been reported or fixed.

If there are no new notifications and you click on the notifications button nothing loads and there is a MySQL error displayed at bottom bar:
![image](https://user-images.githubusercontent.com/48221993/60748072-08266200-9f3f-11e9-9f52-4c7dfb74742a.png)
Error: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1")

Notifications load fine if there are new notifications waiting.

**Comment by mbushkov** [comment]
@vorsklaa - thanks for reporting this! This was fixed in the latest bugfix release (3.3.0.4): https://grr-doc.readthedocs.io/en/latest/release-notes.html#july-3-2019
