### ISSUE TITLE
Script for download hunt results as csv

### ISSUE THREAD

**Issue by victorgomezg93** [google/grr#723]
Hello and thanks for your job. I'm trying to write a script for throw multiple hunts and download the results as CSV. Actually my script can create the hunts correctly but when I try to use the function GetExportedResults the api shows the next error: "No plugin with name attribute 'csv'.

As far I know (not much) the csv is allowed so I don't know which can be the error. My call is grrapi.Hunt(str(hunt)).GetExportedResults("csv").WriteToFile("results.csv") as i saw in other thread.

If somebody could tell me what I'm doing wrong I would apreciate it really much. Really sorry I'm not native english as you probably saw.

**Comment by demonchild2112** [comment]
The correct plugin name is 'csv-zip', which produces a **zip** file containing results for the hunt. So, this is essentially what you want:

```python
grrapi.Hunt(hunt_id).GetExportedResults("csv-zip").WriteToFile("results.zip")
```

**Comment by victorgomezg93** [comment]
> The correct plugin name is 'csv-zip', which produces a **zip** file containing results for the hunt. So, this is essentially what you want:
> 
> ```python
> grrapi.Hunt(hunt_id).GetExportedResults("csv-zip").WriteToFile("results.zip")
> ```

Thanks is working thank you very much I will close the thread
