### ISSUE TITLE
File Finder flow issues

### ISSUE THREAD

**Issue by vorsklaa** [google/grr#726]
File Finder flows does not consistently complete download. I was able to find the following error on the worker:

`ERROR:2019-07-26 23:18:21,189 6578 MainProcess 140202193041152 flow_processing_pool-969796252 flow_base:593] Flow 0F92B1F2 on C.336c6dd2a6a27f78 raised Could not find one of referenced blobs: BlobID('9cb02054842153070bcf5c3769716c62e87cbd1ec699b051be8bbf347514719f').`

This error does not make it to the UI. 

File Finder Download flow does not complete if this error gets encountered. 
Testing using TSK against $MFT. Stat works. File Finder download does not.

Is there anything I can do to get the downloads to work consistently again? Any advice or help is much appreciated and I thank you in advance.

**Comment by mbushkov** [comment]
@vorsklaa , thanks for reporting this! What GRR version are you running?
Do I understand it correctly that all FileFinder downloads are consistently failing or just for that one file? I.e. does FileFinder finish the download for files other than $MFT? What happens if you collect some other file in OS mode?
Are there any errors in the MySQL error log?

**Comment by mbushkov** [comment]
I think I can reproduce this on my setup. 
There are 2 issues here. First, there were max_allowed_packet complaints in the log. I increased the setting to 1073741824. These warnings disappeared, but trying to download a large file ($MFT is a few hundred megs) resulted in an exception in ReleaseProceeedFlow: `Data truncated for column 'flow' at row 1`.

Seems like the issue happens for large files only. @vorsklaa , can you please double check that TSK-collecting small files works fine?

**Comment by mbushkov** [comment]
@vorsklaa , can you please try the following and then collect a file ($MFT) again?

In you MySQL root prompt:
```
SET GLOBAL max_allowed_packet=160971520;
USE grr;
ALTER TABLE flows MODIFY COLUMN flow MEDIUMBLOB;
```

**Comment by vorsklaa** [comment]
> I think I can reproduce this on my setup.
> There are 2 issues here. First, there were max_allowed_packet complaints in the log. I increased the setting to 1073741824. These warnings disappeared, but trying to download a large file ($MFT is a few hundred megs) resulted in an exception in ReleaseProceeedFlow: `Data truncated for column 'flow' at row 1`.
> 
> Seems like the issue happens for large files only. @vorsklaa , can you please double check that TSK-collecting small files works fine?

This is correct. Small files are not affected.
 My mysql was at max_allowed_packet	= 1600M

Did the commands:
```
SET GLOBAL max_allowed_packet=160971520;
USE grr;
ALTER TABLE flows MODIFY COLUMN flow MEDIUMBLOB;
```
Testing it now. Seems to have helped fix. ❤️ 

Thank you very much!

**Comment by vorsklaa** [comment]
This has been tested and confirmed as fixed. File Finder is now completing flow as it should and thank you very much for all you do and your assistance!

**Comment by mbushkov** [comment]
@vorsklaa , thanks for confirming that the suggestion above actually fixes the issue!
I'll keep the GitHub issue open until the bug is fixed in the release version of GRR (we'll do a minor release with the fix soon).

**Comment by mbushkov** [comment]
Hi Keith,
We fixed a race condition in the code that could affect collection of large
files. Do you think you can try installing GRR from HEAD
<https://grr-doc.readthedocs.io/en/latest/installing-grr-server/from-head-deb.html>
and
checking if you still have an issue?

Cheers,
Misha

**Comment by grrrrrrrrr** [comment]
I'll assume this issue is fixed and I can close it. Please reopen if the problem persists.
