### ISSUE TITLE
How to set the value Client.proxy_servers

### ISSUE THREAD

**Issue by AdelleParker** [google/grr#734]
I tried to modify the value of "Client.proxy_servers" in my grr server but failed. Here's how I do it:

1. Open the file /etc/grr/grr.local.yaml
2. Insert a new line into the file
<img width="332" alt="grr" src="https://user-images.githubusercontent.com/55340675/64917401-a4cc7200-d7c2-11e9-9d83-09d8c501535d.png">
3. Restart the grr-server ( sudo systemctl restart grr-server)

But the parameter "Client.proxy_servers" is still empty in GRR's web UI.
<img width="842" alt="grr2" src="https://user-images.githubusercontent.com/55340675/64917443-1a384280-d7c3-11e9-8847-82134a9924b8.png">

However, some values like Monitoring.alert_email can be modified successfully. How do I modify the value of "Client.proxy_servers"?

Thank you for your help.

**Comment by demonchild2112** [comment]
Just so I'm sure you have the writeback path right, could you open up a `grr_console` and run the following?

```bash
In [1]: config.CONFIG["Config.writeback"]
```
(The default writeback location is `/etc/grr/server.local.yaml`)

**Comment by AdelleParker** [comment]
The return value is 
Out[1]: u'/etc/grr//server.local.yaml'
![image](https://user-images.githubusercontent.com/55340675/65213097-5cb99200-dad7-11e9-85f4-d9e8a7effda1.png)

**Comment by demonchild2112** [comment]
The path you gave previously is `/etc/grr/grr.local.yaml`, so that might be the issue (correct path is `/etc/grr/server.local.yaml`).

To check whether the config option is being correctly parsed from the writeback, you can run the following in a `grr_console` and check that the output matches what you expect:

```
In [1]: config.CONFIG["Client.proxy_servers"]
```

**Comment by grrrrrrrrr** [comment]
Did you ever find out what the issue was here?
