### ISSUE TITLE
Cannot deploy properly windows Binaries

### ISSUE THREAD

**Issue by tee2015** [google/grr#738]
- Windows Binaries with Psexec and without are registered missing Host , OS version , MAc, usernames, Client and OS install details data.

Any Idea !! thanks all in Advance :)

**Comment by mbushkov** [comment]
Hi @tee2015 ! What version of GRR did you try to install? Was it a release or a HEAD version? How was the GRR server deployed (from sources, from a DEB package)?

Do I understand it correctly that you see the client in GRR, but it has no client information?

**Comment by tee2015** [comment]
Hi mbushkov, the version of grr client was a binary exe file, the grr server is a docker image.
That's true I can see the client but there is no client information.

**Comment by mbushkov** [comment]
What was the version of the Docker image used? Was it grrdocker/grr:latest or grrdocker/grr:v3.3.0.4?

**Comment by tee2015** [comment]
Grr docker/grr:latest Version

**Comment by mbushkov** [comment]
In this commit from Sep. 25 - https://github.com/google/grr/commit/4fb39cd50438dff381c5f49af4cc9eac4b01ae40 - we fixed an issue that caused the behavior you described.

When did you set up your GRR environment - before or after Sep. 25? If the answer is "before", then please try deploying GRR Docker with "grr:latest" again. The current "grr:latest" version is expected to work correctly on Windows.

**Comment by tee2015** [comment]
Yes before 25 okay I will do that and if all work well I will close the issue thank you :)

**Comment by tee2015** [comment]
Thank you @mbushkov  now all sorted out and make sense :) appreciated. Closing the issue.
