### ISSUE TITLE
Where Is the Config path file for GRR_Docker instance

### ISSUE THREAD

**Issue by tee2015** [google/grr#739]
I want to defined Osquery.path in the config where Is the config file on docker instance:
it is not under (/usr/local/bin/osqueryi) 

@mbushkov  can you please point me to the config file thank you in advance man appretiated :)

I can see that I must actiate the virtualenv  but also under the virtualenv I just have 4 files (pip - pip2-pip2.7- vitualenv). 
I installed the latest docker version.

**Comment by tee2015** [comment]
hmm I can see why its under virtualenv

**Comment by mbushkov** [comment]
Hi @tee2015 ! 
Our docker image itself doesn't contain the server.local.yaml configuration file that you're normally expected to edit. This file gets created and initialized in the entrypoint script when you do `docker run`: https://github.com/google/grr/blob/master/docker/docker-entrypoint.sh#L15

After the file is written, it will be located here: 
```
/usr/share/grr-server/install_data/etc/server.local.yaml
```

If you want to add an Osquery.path setting, you can modify the entrypoint script to add a configuration line after `grr_config_updtaer --initialize` is called. For example, like this:
```
echo "Osquery.path: /foo/bar" >> /usr/share/grr-server/install_data/etc/server.local.yaml
```

Please tell me if this works for you

**Comment by tee2015** [comment]
The challenge I am facing that I directly pulled the docker image and iniate the docker instance 

![image](https://user-images.githubusercontent.com/14360476/66555883-12d64000-eb9b-11e9-99d2-c03e88d6e247.png)

**Comment by demonchild2112** [comment]
@tee2015 

It sounds like you might want to have your config files live on the host, rather than inside the container. This is described [here](https://grr-doc.readthedocs.io/en/latest/installing-grr-server/via-docker.html#advanced-usage-non-ephemeral-configs-external-mysql-instance). Let me know if you have any questions. This is an alternative to the approach given by @mbushkov (which involves building your own image [also described in the link above]).

**Comment by tee2015** [comment]
Hi @demonchild2112  thank you for your reply, I reinstall using your guidance I will pass the commands for other dont waste time on configuring: 
![image](https://user-images.githubusercontent.com/14360476/66837585-f8430300-efae-11e9-9e13-48f8eb55bfaf.png)

All worked well except the path of osquery still empty, Just wondering if I just add it in specific place, I added her : 
![image](https://user-images.githubusercontent.com/14360476/66837827-62f43e80-efaf-11e9-97de-d7048c416b30.png)

Any feedback on that, Thank you :)

**Comment by tee2015** [comment]
Hi, I am facing an issue related to the docker IP I cannot call the page or the server on 8080 from the grr client I reckon I need to change the default docker subnet to be as the local host subnet ? I can see the docker have a different subnet.

**Comment by demonchild2112** [comment]
Hey @tee2015 

If you do not need to use the MySQL instance installed on the host, you can actually drop these arguments from the command used to start the container:

- `network`
- `DISABLE_INTERNAL_MYSQL`
- `GRR_MYSQL_HOSTNAME`
- `GRR_MYSQL_PASSWORD`

The MySQL instance inside the container will be used instead (which is the default behavior). I'll update the documentation to make that clearer.

JFYI using host networking mode disables publishing of ports, which is what you ran into.

**Comment by tee2015** [comment]
Hi demonchild2112, thank you for your reply, actually i need the mysql on the host so I can freely change the config (example osquery path). i will update the host network configs and see how it goes.

**Comment by demonchild2112** [comment]
What I meant previously is that you can use the configs on the host without connecting to the host's MySQL instance. All you need for that is the `-v` argument to `docker run`.

**Comment by tee2015** [comment]
Its working now demonchild2112, thank you 🍻 
I just stopped the local MySQL , removed the server.local.yaml file which contains the local configs of MySQL , start the docker and include -v option, and after it started once I stopped the docker edit the new created file server.local.yaml with :
Osquery.path: C:\\Windows\\Program Files\\osquery\\osqueryi.exe
https://grr-doc.readthedocs.io/en/latest/investigating-with-grr/osquery.html

Start the grr server again
Repack the build agent and install on the endpoint and connect properly to the grr server
I started a new hunt osquery:
SELECT * FROM processes;
 My hunt is failing and giving errors will provide screenshot of the errors. Any issue with the above steps 🤔

**Comment by tee2015** [comment]
![image](https://user-images.githubusercontent.com/14360476/67052159-0c425c80-f189-11e9-8511-08ff10855404.png)

**Comment by demonchild2112** [comment]
I find that odd - GRR should be running with Admin privileges. On the Windows host, try running the following command in a Powershell console with Admin privileges:

    &'C:\Windows\Program Files\osquery\osqueryi.exe' '--S' '--json' 'SELECT * FROM processes;'

The output should be a JSON string containing info about running processes. This is essentially the same command that the GRR process runs.

**Comment by tee2015** [comment]
Hi @demonchild2112 I am able to run osqueries from CMD and have a result , however this command couldn't run it in powershell, I tested on a win 10 machine which I have admin privileges.
I run the test again on grr and have same result error as above 🤔 :
1- admin privileges no issues and osquery run from CMD and have a result back
2- path is defined on server and match the agent osquery location + I compiled the agent again to have the osquery path in the config too
3- what options do we still have to check 🤔? 
I will check again why your provided command didn't run.

**Comment by demonchild2112** [comment]
Don't worry about getting the command to work in Powershell; using CMD instead is perfectly fine - I just wanted to verify that there is nothing wrong with the command run by GRR.

I think there's a permissions issue specific to your Windows box. Although **you** have permission to run osquery, it seems to be the case that GRR does not. I would recommend double-checking the read/execute permissions for `osqueryi.exe` and all directories above it (right click on file/folder, select 'Properties' in the pop-up menu, then go to the 'Security' tab in the dialog box that appears).
