### ISSUE TITLE
Client Not Showing in Add/Remove programs for administrator

### ISSUE THREAD

**Issue by theshades** [google/grr#740]
With no information on how to to uninstall on the wiki, having a /uninstall or having it in add/remove programs could be useful.

**Comment by demonchild2112** [comment]
Uninstallation of GRR on windows is already [documented](https://grr-doc.readthedocs.io/en/latest/deploying-grr-clients/on-windows.html#uninstalling-on-windows). Not having the agent show up in the installed programs list is something we do on purpose.

Please let me know if you have further questions.
