### ISSUE TITLE
Error deleting a client

### ISSUE THREAD

**Issue by mmogilko** [google/grr#745]
Hi all!
Trying to remove dead host I'm getting an error:

`In [8]: print data_store.REL_DB.ReadClientSnapshot(u"C.35890586b71d1f08").knowledge_base.fqdn`
`---------------------------------------------------------------------------`
`NameError                                 Traceback (most recent call last)`
`/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/bin/console.pyc in <module>()`
`----> 1 print data_store.REL_DB.ReadClientSnapshot(u"C.35890586b71d1f08").knowledge_base.fqdn`

`NameError: name 'data_store' is not defined`

grr-server: 3.3.0-8

**Comment by demonchild2112** [comment]
You need to import the `data_store` module first:

```python
from grr_response_server import data_store
```

The `data_store` module used to be auto-imported when you start up a `grr_console`, but that doesn't seem to be the case any more. I checked our documentation and it doesn't mention needing to import the module manually. So we will either fix the documentation or add the module back to the auto-import list. Sorry for the trouble. :)

**Comment by mmogilko** [comment]
Thanks! Now I'm able to execute this query.
But I've got another error (on every client deletion, not only one special). An output is much bigger, please, look at an attachment.
[delete_client_error.txt](https://github.com/google/grr/files/3793146/delete_client_error.txt)

**Comment by onchaosteam** [comment]
I had this issue i had to modify the database to add ON DELETE CASCADE to the client_paths_ibfk_2 and client_paths_ibfk_3 constraints in the client_paths table that fixed the issue for me

**Comment by mbushkov** [comment]
@onchaosteam - this is exactly the way we're going to fix the issue. We'll submit this fix soon.

**Comment by mrhania** [comment]
This has been fixed and pushed in 3440b0058a4fa6dfa72690a9d81a7ee704a73436.
