### ISSUE TITLE
Issue creating a hunt download Plugin

### ISSUE THREAD

**Issue by onchaosteam** [google/grr#750]
Hey Team,

I want to create a hunt download plugin, Like the csv-zip , sqlite-zip etc to do a json-zip 

My steps ( i thought to do this was to perform the follwing)

-     Copy grr_responce_server/output_plugins/sqlite_plugin.py to grr_responce_server/output_plugins/json_plugin.py
-     Inside the plugin.py change plugin name from "sqlite-zip" "to json-zip" and a few other details 
-     update grr_responce_server/output_plugins/__init__.py in the directory to import the new plugin  ( from grr_response_server.output_plugins import json_plugin )
-     Modify download-collection-as-directive.js to add the json-zip
-     Restarted GRR

But it doesnt show up as an option to download, is there something critical I am missing here ? Ive greped the whole config for sqlite-zip and sqlite_plugin and those seem like the only places its referenced

I have a very specific use case for this API wont suit my needs,  Once i get the basic modification working i can write some code in to make it do what I want..

Any ideas?

Thanks
Tim

**Comment by mbushkov** [comment]
Hi Tim! Did you install GRR from source? (following https://grr-doc.readthedocs.io/en/latest/installing-grr-server/from-source.html)

If so, the issue is likely that you have to recompile the JS sources:
```bash
source $HOME/INSTALL/bin/activate
cd grr/server/grr_response_server/gui/static
npm run gulp compile
```

**Comment by grrrrrrrrr** [comment]
Also one small thing to add, GRR has all these local folders, for example grr_response_server/output_plugins/local/ that are meant to hold your custom additions. If you put your custom output plugin there, you might have fewer problems merging updates that change the directory you are working in now. What you are doing currently should work too though...
