### ISSUE TITLE
MySQL timeout

### ISSUE THREAD

**Issue by makitos666** [google/grr#753]
Because GDPR I have the SQL database and GRR in separated machines in different VLANS with a firewall between them.

The problem is that the firewall has a waiting time that kills the sessions from a certain time. So the connection between the GRR and the SQL server is established only once.

When the firewall kills the session, an exception is generated and no attempt is made again to establish it, so that service stops working.

Is this something I can solve by modifying the GRR configuration or is it inherent in the code?

**Comment by mbushkov** [comment]
Hi @makitos666 , thanks for reporting this. Quick question - which GRR server version is this? Do you think you can also post an exception traceback, if you see one in the logs?

I'd expect dropped connections to be handled correctly by GRR, so this looks like a bug. Would appreciate a bit more data (please see my questions above) to investigate further.

**Comment by makitos666** [comment]
Hi @mbushkov the GRR versión is 3.3.0.0 (amd64).

Here you have the error from the Logs:
```
ERROR:2020-01-08 10:08:26,147 26111 MainProcess 140598413608704 message_handler mysql_flows:110] _LeaseMessageHandlerRequests raised (2006, 'MySQL server has gone away').
Traceback (most recent call last):
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql_flows.py", line 104, in _MessageHandlerLoop
    msgs = self._LeaseMessageHandlerRequests(lease_time, limit)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/db_utils.py", line 44, in Decorator
    result = f(*args, **kwargs)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql_utils.py", line 259, in Decorated
    return self._RunInTransaction(Closure, readonly)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql.py", line 526, in _RunInTransaction
    connection.rollback()
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql_pool.py", line 136, in rollback
    self.con.rollback()
OperationalError: (2006, 'MySQL server has gone away')
ERROR:2020-01-08 11:38:59,196 26111 MainProcess 140598788966144 grr_cron cronjobs:331] CronWorker uncaught exception: (2006, 'MySQL server has gone away')
```

Another clarification: the firewall sends a reset (at IP level) against the GRR when it reaches timeout, the GRR sends an ack through another port to maintain the connection, and the firewall blocks this new connection out of state.

**Comment by mbushkov** [comment]
I think there may be a significant difference in MySQL datastore behaviour between different GRR releases. 
I see "MySQL server has gone away" error being handled explicitly in v.3.4.0.1: https://github.com/google/grr/blob/v3.4.0.1/grr/server/grr_response_server/databases/mysql.py#L563
There's no such code in the v3.3.0.0 release: https://github.com/google/grr/blob/v3.3.0.0/grr/server/grr_response_server/databases/mysql.py#L514

@makitos666 , do you think you can check the latest v3.4.0.1 release and see if the issue persists?

**Comment by mbushkov** [comment]
Will close this for now. @makitos666 , please reopen in case you encounter the same issue with the latest release.
