### ISSUE TITLE
Error on new install

### ISSUE THREAD

**Issue by TheEagle13** [google/grr#755]
Hey all,

I have a fresh install after following the docs. However I am having an issue with ANY client I try to add. Every single time I add a client, it tries to do the interrogate and fails with the following backtrace: (Happens on windows and linux)

`Traceback (most recent call last): File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/server/flow_runner.py", line 589, in RunStateMethod direct_response=direct_response, request=request, responses=responses) File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/server/flow.py", line 301, in Decorated res = f(*args[:f.func_code.co_argcount]) File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/server/flows/general/discovery.py", line 168, in InstallDate response = responses.First() File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/server/flow.py", line 203, in First for x in self: File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/server/flow.py", line 197, in __iter__ client_action_name)) RuntimeError: Response type was RDFDatetime but expected [<class 'grr.lib.rdfvalues.protodict.DataBlob'>] for GetInstallDate.`

**Comment by mbushkov** [comment]
@TheEagle13 , thanks for reporting this! How did you install - using the release DEB? What's your GRR server version?
I see that Python 2.7 is used in the stacktrace, but the latest released GRR version is Python 3. Can you please double check that GRR v3.4.0.1 has the issue (see https://grr-doc.readthedocs.io/en/latest/installing-grr-server/from-release-deb.html)?

**Comment by TheEagle13** [comment]
I just realized that (I had pulled the deb last month and just got around to installing). I just updated to the latest deb, and now I cannot seem to access the GRR webui. Systemctl says it's running, but I do not see any of the normal open ports in a netstat (except for mysql)

**Comment by mbushkov** [comment]
AdminUI should run on port 8000. Do you see the admin UI component running if you do "ps axww"? Anything suspicious in the logs? What Ubuntu version do you use to run the server?

**Comment by TheEagle13** [comment]
right, and II was in the adminui before the upgrade. don't see it with a ps either. There doesn't appear to be anything in var/log/ relating to grr.
It's on Ubuntu 18.04

**Comment by mbushkov** [comment]
What happens if you try to start the admin ui manually?
(see https://grr-doc.readthedocs.io/en/latest/maintaining-and-tuning/troubleshooting.html#any-some-of-the-grr-services-are-not-running-correctly)

```bash
sudo grr_server --component adminui --verbose
```

**Comment by TheEagle13** [comment]
well, I started getting click-happy because nothing was working and I did a clean install since I didn't have much to lose, I'll let you know the outcome shortly. (Side note the docs have incorrect syntax. I tried doing what you just suggested, but using the document syntax and it kept yelling at me.... https://grr-doc.readthedocs.io/en/latest/installing-grr-server/troubleshooting.html

**Comment by TheEagle13** [comment]
Okay, well a new clean install appears to have solved things. I will chalk this one up to a layer 8 issue.
