### ISSUE TITLE
specify filepath containing space

### ISSUE THREAD

**Issue by siftuser** [google/grr#756]
how would I include SPACE char in the file path while using filefinder flow ? for example "Application Support" ? Thanks

**Comment by mbushkov** [comment]
Spaces are treated as parts of a filename in GRR. You should be able to
just  use it as it is.

Cheers,
Misha

**Comment by mbushkov** [comment]
To be more precise: you don't need to escape space characters or anything.
I.e.
%%users.homedir%%/Library/Application Support/*

Cheers,
Misha
