### ISSUE TITLE
collect grr results for analytics using ELK/ Splunk /etc.

### ISSUE THREAD

**Issue by arimb00r** [google/grr#759]
what are the options for 3rd party applications ELK/ Splunk /etc to connect GRR DB for analytics, visualization, etc.

**Comment by joachimmetz** [comment]
@arimb00r what type of analytics, visualization, etc. are you thinking about?

We use plaso / dfTimeWolf / TimeSketch for our needs but not sure if those match your use case(s)

**Comment by demonchild2112** [comment]
We plan on adding an output plugin for Splunk some time this year. @max-vogler should know more.

**Comment by max-vogler** [comment]
Yes, as said in #757, I will open-source a Splunk OutputPlugin in the next weeks.

Generally, if you want to connect GRR to other systems, OutputPlugins are the way to go. We have existing ones for BigQuery, CSV, SQLite, and YAML. Furthermore, we support [monitoring with Prometheus](https://grr-doc.readthedocs.io/en/latest/maintaining-and-tuning/monitoring.html)

**Comment by arimb00r** [comment]
awesome .....

**Comment by max-vogler** [comment]
SplunkOutputPlugin is available in HEAD and documented at [Output Plugins](https://grr-doc.readthedocs.io/en/latest/investigating-with-grr/output-plugins.html).

**Comment by arimb00r** [comment]
when I update the file /etc/grr/server.local.yaml with the following, the GRR is not starting 

Splunk.url: https://192.168.0.100:8088
Splunk.token: bb7e1f36-8d57-4d3c-8ef5-5b2de06cdee4

**Comment by max-vogler** [comment]
Please open an issue with logs including error messages and a detailed description of your setup.
