### ISSUE TITLE
Mysql don't start on my GRR server

### ISSUE THREAD

**Issue by yassoudsec** [google/grr#775]
Hello
i've a problem with my grr server. i installed it and all was working fine but today i tried to access on the administration console but it didn't work and i ckecked the mysql and it didn't start. 

see bellow the status of mysql 

root@grr_server:/home/yassou# service mysql status
● mysql.service - MySQL Community Server
   Loaded: loaded (/lib/systemd/system/mysql.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2020-05-15 14:47:37 UTC; 13min ago
  Process: 1347 ExecStart=/usr/sbin/mysqld --daemonize --pid-file=/run/mysqld/mysqld.pid (code=exited, status=1/FAILURE)
  Process: 1324 ExecStartPre=/usr/share/mysql/mysql-systemd-start pre (code=exited, status=0/SUCCESS)

May 15 14:47:37 grr_server systemd[1]: mysql.service: Failed with result 'exit-code'.
May 15 14:47:37 grr_server systemd[1]: Failed to start MySQL Community Server.
May 15 14:47:37 grr_server systemd[1]: mysql.service: Service hold-off time over, scheduling restart.
May 15 14:47:37 grr_server systemd[1]: mysql.service: Scheduled restart job, restart counter is at 5.
May 15 14:47:37 grr_server systemd[1]: Stopped MySQL Community Server.
May 15 14:47:37 grr_server systemd[1]: mysql.service: Start request repeated too quickly.
May 15 14:47:37 grr_server systemd[1]: mysql.service: Failed with result 'exit-code'.
May 15 14:47:37 grr_server systemd[1]: Failed to start MySQL Community Server.
root@grr_server:/home/yassou#

thank you for your help.

**Comment by max-vogler** [comment]
Given the scarce logs you posted, this looks like a MySQL issue unrelated to GRR. If further debugging indicates that this is an issue caused by GRR, please update this issue.

**Comment by yassoudsec** [comment]
yes i think. you this resolt 

root@grr_server:/home/yassou# journalctl -xe
May 15 15:25:48 grr_server grr_server[3423]:     sys.exit(main(argv))
May 15 15:25:48 grr_server grr_server[3423]:   File "/usr/share/grr-server/lib/python3.6/site-packages/grr_response_server/bin/grr_server.py", line 46, in main
May 15 15:25:48 grr_server grr_server[3423]:     worker.main([argv])
May 15 15:25:48 grr_server grr_server[3423]:   File "/usr/share/grr-server/lib/python3.6/site-packages/grr_response_server/bin/worker.py", line 48, in main
May 15 15:25:48 grr_server grr_server[3423]:     server_startup.Init()
May 15 15:25:48 grr_server grr_server[3423]:   File "/usr/share/grr-server/lib/python3.6/site-packages/grr_response_core/lib/utils.py", line 1350, in _OneTimeF
May 15 15:25:48 grr_server grr_server[3423]:     _OneTimeFunction.result = fn(*args, **kwargs)
May 15 15:25:48 grr_server grr_server[3423]:   File "/usr/share/grr-server/lib/python3.6/site-packages/grr_response_server/server_startup.py", line 87, in Init
May 15 15:25:48 grr_server grr_server[3423]:     data_store.InitializeDataStore()
May 15 15:25:48 grr_server grr_server[3423]:   File "/usr/share/grr-server/lib/python3.6/site-packages/grr_response_server/data_store.py", line 101, in Initial
May 15 15:25:48 grr_server grr_server[3423]:     REL_DB = db.DatabaseValidationWrapper(cls())
May 15 15:25:48 grr_server grr_server[3423]:   File "/usr/share/grr-server/lib/python3.6/site-packages/grr_response_server/databases/mysql.py", line 501, in __
May 15 15:25:48 grr_server grr_server[3423]:     _SetupDatabase(**self._connect_args)
May 15 15:25:48 grr_server grr_server[3423]:   File "/usr/share/grr-server/lib/python3.6/site-packages/grr_response_server/databases/mysql.py", line 305, in _S
May 15 15:25:48 grr_server grr_server[3423]:     ca_cert_path=ca_cert_path)) as conn:
May 15 15:25:48 grr_server grr_server[3423]:   File "/usr/share/grr-server/lib/python3.6/site-packages/grr_response_server/databases/mysql.py", line 391, in _C
May 15 15:25:48 grr_server grr_server[3423]:     conn = MySQLdb.Connect(**connection_args)
May 15 15:25:48 grr_server grr_server[3423]:   File "/usr/lib/python3/dist-packages/MySQLdb/__init__.py", line 86, in Connect
May 15 15:25:48 grr_server grr_server[3423]:     return Connection(*args, **kwargs)
May 15 15:25:48 grr_server grr_server[3423]:   File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 204, in __init__
May 15 15:25:48 grr_server grr_server[3423]:     super(Connection, self).__init__(*args, **kwargs2)
May 15 15:25:48 grr_server grr_server[3423]: _mysql_exceptions.OperationalError: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/my
May 15 15:25:48 grr_server systemd[1]: grr-server@frontend.service: Service hold-off time over, scheduling restart.
May 15 15:25:48 grr_server systemd[1]: grr-server@frontend.service: Scheduled restart job, restart counter is at 34.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Automatic restarting of the unit grr-server@frontend.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
May 15 15:25:48 grr_server systemd[1]: Stopped GRR frontend.

**Comment by max-vogler** [comment]
Your posted stack trace only shows that GRR cannot connect to MysQL. You seem to have problems with MySQL, not with GRR.
