### ISSUE TITLE
Trouble installing - dependency issue - mysql 

### ISSUE THREAD

**Issue by mckechg** [google/grr#780]
As seen below there is a dependency issue with MySQL 

Ubuntu 20.4 LTS
Physical Server

mckechg@nbc-dev00:~$ sudo apt install -y ./grr-server_3.2.1-1_amd64.deb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'grr-server' instead of './grr-server_3.2.1-1_amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 grr-server : Depends: python-mysqldb but it is not installable
E: Unable to correct problems, you have held broken packages.
mckechg@nbc-dev00:~$ ls
grr-server_3.2.1-1_amd64.deb
mckechg@nbc-dev00:~$

**Comment by mbushkov** [comment]
@mckechg , two questions/notes:

1. Is there any reason why you install GRR server version 3.2.1.1? The latest one is [3.4.0.1](https://github.com/google/grr/releases/tag/v3.4.0.1).

1. The latest GRR server version - 3.4.0.1 - is tested on Ubuntu 18.04. Previous releases were targeting 16.04. Given that you combine the latest Ubuntu release with an old GRR release, things are expected to get broken.
