### ISSUE TITLE
Unable to install GRR on Ubuntu Xenial

### ISSUE THREAD

**Issue by jonbornstein** [google/grr#784]
I've followed the guide to a T: https://grr-doc.readthedocs.io/en/v3.4.0/installing-grr-server/from-release-deb.html

This is a fresh install of Ubuntu running in Azure.  Nothing additional was updated or installed.

When I try to install the .deb, I get the following:

```
root@grr-console:/home/grr-admin# sudo apt install -y ./grr-server_3.4.0-1_amd64.deb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'grr-server' instead of './grr-server_3.4.0-1_amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 grr-server : Depends: rpm but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by mbushkov** [comment]
Sorry, the docs were misleading on this one. GRR 3.4.0 has to be installed on Ubuntu 18.04 Bionic. Updated the docs: https://github.com/google/grr-doc/commit/29503e077ad0b575a0ec552b5849b70b30825909

Closing for now, please reopen in case you have issues on Bionic too.

**Comment by jonbornstein** [comment]
I just spun up a new VM with Bionic and unfortunately still having the same exact issue:

```
root@grr-console:/home/grr-admin# sudo apt install -y ./grr-server_3.4.0-1_amd64.deb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'grr-server' instead of './grr-server_3.4.0-1_amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 grr-server : Depends: rpm but it is not installable
E: Unable to correct problems, you have held broken packages.
root@grr-console:/home/grr-admin# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```

**Comment by mbushkov** [comment]
I could reproduce. This error happens on a vanilla Ubuntu 18 images. This has helped:
```
sudo apt-get update
```

@jonbornstein - can you please confirm that it helps in your case as well? I'll update the docs to explicitly mention this.

**Comment by joachimmetz** [comment]
what does: `dpkg --show grr-server_3.4.0-1_amd64.deb` say regarding dependencies?

**Comment by jonbornstein** [comment]
@mbushkov thanks, that did the trick! I can now load the console in a web browser.

Normally I would have run an update before installing, but when I did that on Ubuntu Xenial, it seemed to increase the errors I received.

**Comment by joachimmetz** [comment]
> what does: dpkg --info grr-server_3.4.0-1_amd64.deb say regarding dependencies?

never mind, @mbushkov explained rpm is a necessary dependency
