### ISSUE TITLE
404 not found error in "install_grr_from_gcs.sh" file

### ISSUE THREAD

**Issue by jgbae** [google/grr#794]
I tried to build GRR version 3.2.4.6 using Dockerfile.

But there was an error while executing command in "install_grr_from_gcs.sh" file.

wget --quiet "https://storage.googleapis.com/autobuilds.grr-response.com/_latest_server_deb/grr-server_${DEB_VERSION}.tar.gz"

When I tried to get file using wget, output was as below. (${DEB_VERSION} = 3.2.4-6)

wget https://storage.googleapis.com/autobuilds.grr-response.com/_latest_server_deb/grr-server_3.2.4-6.tar.gz--2020-07-06 21:58:23--  https://storage.googleapis.com/autobuilds.grr-response.com/_latest_server_deb/grr-server_3.2.4-6.tar.gz
Resolving storage.googleapis.com (storage.googleapis.com)... 34.64.4.112, 34.64.4.80, 34.64.4.16, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|34.64.4.112|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-07-06 21:58:23 ERROR 404: Not Found.

**Comment by mbushkov** [comment]
Hi @jgbae ! Any reason why you use version 3.2.4.6 and not one of the later releases? This is an old GRR version that we no longer mainatin (the latest is 3.4.2.0).

IIUC, install_grr_from_gcs.sh only lets you to install the latest GRR version, as only the latest GRR deb package is stored in the autobuilds.grr-response.com/_latest_server_deb location.

I.e., at the moment the following file exists:
https://storage.googleapis.com/autobuilds.grr-response.com/_latest_server_deb/grr-server_3.4.2-0_amd64.deb

This means that running with DEB_VERSION = 3.4.2-0 should work.

If you do need to build an older GRR version, you'd need to use another link to download the deb:
https://storage.googleapis.com/releases.grr-response.com/grr-server_3.2.4-6_amd64.deb

I guess that, if you need to build a Docker image for 3.2.4-6, you can modify the install script to reference that file. Make sure to also use the appropriate version of the Dockerfile from the corresponding GitHub branch: https://github.com/google/grr/tree/v3.2.4.6

**Comment by mbushkov** [comment]
I assume this one is resolved.
