### ISSUE TITLE
Clients UP but no hunt/flow successful

### ISSUE THREAD

**Issue by Zakaren** [google/grr#801]
Hi all,

I installed some grr agents on some Windows 7/10 virtual machines (ESXI).

I have an Opensense Firewall between the ESXI and the GRR server. (the flow is allowed and I can see the clients sending requests to GRR server)

![image](https://user-images.githubusercontent.com/27960829/86922873-88247080-c12d-11ea-89fd-36cacbcbe47d.png)

I can see the clients on which I installed the agents on GRR GUI. But I can't launch any flaw/hunt or interrogate these clients.

The list of lunched flows : 
![image](https://user-images.githubusercontent.com/27960829/86923088-da659180-c12d-11ea-94b3-db9464df2787.png)

Have you an idea of what could be the origin of this problem ?

PS: I have other clients on which the flaw/hunts work properly.

Thank you.

Regards,

**Comment by mbushkov** [comment]
Hi @Zakaren ! Which GRR server and clients version are you using?

This clearly looks like an issue with the client. The only straight-forward way to debug it is to install a debug Windows client on a machine in question and look at the console output. See https://grr-doc.readthedocs.io/en/latest/deploying-grr-clients/troubleshooting.html#i-dont-see-my-clients for details.

**Comment by Zakaren** [comment]
Hi @mbushkov ,

3.4.0 for the server and 3.3.0.6. 

Ok, I will do that,

Thank you

**Comment by mbushkov** [comment]
Hey, there were no updates here for a while. I'll close the issue - please feel free to reopen, if needed.
