### ISSUE TITLE
ExecutePythonHack should return a non-primitive struct

### ISSUE THREAD

**Issue by mbushkov** [google/grr#817]
At the moment ExecutePythonHack returns a plain string as a [result](https://github.com/google/grr/blob/b2969c7ed6f5c6e62919fa66625d992e7b5e0b34/grr/server/grr_response_server/flows/general/administrative.py#L370). This is likely the only GRR flow that returns a primitive value instead of a proper protobuf-based struct.

This behavior confuses GRR API client, since it doesn't expect primitive types to be returned as flow results. It can't deserialize it and puts `UnknownProtobuf` into the payload.

**Comment by panhania** [comment]
This has been fixed and is available since 02d3b45707055444015d76ee300bd57b803d9879.
