### ISSUE TITLE
osx 10.14.6 can't list safari folder

### ISSUE THREAD

**Issue by siftuser** [google/grr#828]
`listdir Operation not permitted: '/Users/userid/Library/Safari'` 

any help ? Thanks

**Comment by mbushkov** [comment]
@siftuser , I'd expect it to be the same problem as in https://github.com/google/grr/issues/786.
Have you managed to sign/notarize the client to ensure it has Full Disk Access permissions?

**Comment by siftuser** [comment]
Thanks @mbushkov
