### ISSUE TITLE
Installation of GRR on Ubuntu version 20

### ISSUE THREAD

**Issue by tej7gandhi** [google/grr#877]
**Environment**
-from release
- grr-server_3.4.2-3_amd64.deb 
- Ubuntu 20
- What operating system does the affected GRR client run on, if applicable? [e.g. Windows 10]

Installation on Ubuntu Version 20
![Screen Shot 2020-10-29 at 5 20 14 PM](https://user-images.githubusercontent.com/13482291/97634080-80097d00-1a0b-11eb-97a3-044fdf0070b1.png)

**Comment by mbushkov** [comment]
Unfortunately, our pre-packaged server DEB only supports Ubuntu 18.04 at the moment:
https://grr-doc.readthedocs.io/en/latest/faq.html#what-operating-system-versions-does-the-server-support

**Comment by tej7gandhi** [comment]
Hello Google/GRR,

The documentation states Ubuntu Xenial that is 16.04 ,would it support
Ubuntu 18.04 as well?

Thanks and Regards
Tej Gandhi

**Comment by mbushkov** [comment]
At the moment we support only the Ubuntu 18.04 version for the GRR server deb. If docs still mention Xenial, it's a mistake - where do you see Xenial referenced?

**Comment by tej7gandhi** [comment]
Hello Grr,

I saw it in  "What operating system versions does the server support?"

Thanks and Regards
Tej Gandhi
