### ISSUE TITLE
Failing async inserts during interpreter shutdown.

### ISSUE THREAD

**Issue by pidydx** [google/grr#90]
It appears that during process shutdown (I noticed it with grr_config_updater) the flusher thread may not be complete and can lose access to necessary modules before it is done inserting.  I'm not entirely certain that this is what is happening as it is very difficult to reproduce and I have only seen it happen a few times.  When using the MySQLAdvanced connector the flusher thread would report that an attribute error exception happened in Execute() due to NoneType having no attribute Error.  I am assuming that the Mysqldb.Error is the line it hits and the thread exception does mention that it probably happened during interpreter shutdown.  

Is there a safe way to ensure that the various pieces of GRR allow the flusher thread to complete any database transactions before exiting?

**Comment by destijl** [comment]
We should join the flusher thread on exit.

**Comment by grrrrrrrrr** [comment]
We don't use MySQLAdvanced anymore, obsolete.
