### ISSUE TITLE
Non-approvers are able to approve requests 

### ISSUE THREAD

**Issue by knsankar** [google/grr#902]
**Environment**
- How did you install GRR? [e.g. from release DEB, HEAD DEB, PIP package, source] 
**PIP**
- What GRR version are you running?: [e.g. 3.1.2.3]
**3.4.2.4**
- What operating system does the GRR server run on? [e.g. Ubuntu 18.04]
**CentOS7**
- What operating system does the affected GRR client run on, if applicable? [e.g. Windows 10]
**N/A**

I have a list of approvers configured in approvers.yaml. But, any GRR user can be added in the request and approve the requests.

**approvers.yaml:**
label: <machine label>
requester_must_be_authorized: True
num_approvers_required: 1
users:
  - "joe"

**server config:**

AdminUI.bind: "::"

#AdminUI.webauth_manager: BasicWebAuthManager

AdminUI.webauth_manager: RemoteUserWebAuthManager

AdminUI.remote_user_trusted_ips:
  - 127.0.0.1
  - ::ffff:127.0.0.1

AdminUI.use_precompiled_js: True

#API.DefaultRouter: ApiCallRouterWithoutChecks
API.RouterACLConfigFile: /srv/grr/install_data/etc/api_acls.yaml
API.DefaultRouter: ApiCallRouterWithApprovalChecks

**Comment by mbushkov** [comment]
Hi Sankar! Limiting the approvers to a certain set of users is only possible for a certain label. I've noticed that in your configuration you set the label to empty (`label: `). Unfortunately this won't work - GRR won't treat an empty string as "no label".

One of the options for you might be to burn the label into the GRR clients you install (https://grr-doc.readthedocs.io/en/latest/maintaining-and-tuning/repacking-clients.html#repacking-clients-with-custom-labels-multi-organization-deployments). Then each client will have a default label that you'd be able to use in your configuration.

**Comment by knsankar** [comment]
HI @mbushkov 
Thanks for the clarification. Fortunately I have 'location' labels brunt in the clients already.
