### ISSUE TITLE
RedhatPackagesList

### ISSUE THREAD

**Issue by pidydx** [google/grr#91]
This artifact runs successfully, but it returns a set of repeating errors where XXX is different numbers.
This is on a RHEL 6.5 test machine.

error: rpmdbNextIterator: skipping h# XXX Header V3 RSA/SHA256 Signature, key ID fd431d51: BAD

**Comment by destijl** [comment]
I'm going to close this out, if anyone can reproduce and wants to get it fixed I suspect it's probably just a case of supplying slightly different parameters to the command for older versions. The command used is here:
https://github.com/google/grr/blob/master/grr/artifacts/flow_templates/linux.yaml#L54
