### ISSUE TITLE
Interrogate/Artifact issues

### ISSUE THREAD

**Issue by pidydx** [google/grr#93]
The latest version of the server running with 3.0.0.3 clients seems to have some serious performance problems with the new artifacts getting run on interrogate.  The worker processes spike with heavy CPU usage and lots of failures on /usr/sbin/system_profiler returning with -1.

What is the best way to disable these additional artifacts on Interrogate while this gets looked at?

**Comment by pidydx** [comment]
OSX hosts have the Interrogate marked complete with the crash noted for the system_profiler artifact
Windows systems seem to all get hung with the Interrogate showing incomplete, next status MarkDone, current status "could not enumerate interfaces", and current state seems to always bee ProcessKnowledgeBase or more often EnumerateFileSystems.

**Comment by grrrrrrrrr** [comment]
Hey thanks for reporting. If you are having troubles, you can remove artifacts from interrogation by either adding them to Artifacts.interrogate_store_in_aff4_skip or removing them from Artifacts.interrogate_store_in_aff4. I'd suggest disabling LinuxHardwareInfo and OSXSPHardwareDataType based on your description.

We'll investigate why the cpu usage is high when running those artifacts.

**Comment by pidydx** [comment]
I paused the Hunt and the system eventually recovered.  I disabled those artifacts through the Artifacts.interrogate_store_in_aff4_skip and unpaused the hunt.  I can see in the hunt log that it seems to be moving again, but the Hunt overview doesn't appear to be updating with more scheduled/completed clients.
