### ISSUE TITLE
'Recently Accessed Cients' and 'Help/Documentation' Links not working

### ISSUE THREAD

**Issue by careyer** [google/grr#930]
**Environment**
- How did you install GRR? [e.g. from release DEB, HEAD DEB, PIP package, source] : DEB
- What GRR version are you running?: [e.g. 3.1.2.3] : 3.4.3.1
- What operating system does the GRR server run on? [e.g. Ubuntu 18.04] Ubuntu 18.04
- What operating system does the affected GRR client run on, if applicable? [e.g. Windows 10] Windows 10

**Describe the issue**
**Problem 1:** After install the GRR Admin UI can successfully be accessed via Browser and GRR is for the most part working  correctly. However even though clients habe been managed in the past they do not show up on the startpage under the section "Recently Accessed clients". This section always stays empty (even though flows have been issued and have been processed by clients).
![grafik](https://user-images.githubusercontent.com/6156251/119975139-c8931400-bfb5-11eb-967c-01dbbd1c3b61.png)
^Client has been managed

![grafik](https://user-images.githubusercontent.com/6156251/119975233-e06a9800-bfb5-11eb-9d99-f9b959485120.png)
^does not show up on the main screen

**Problem 2**: The integrated help/documentation does no load correctly. When clicking the "Help" Link (http://hostname:8000/help/index.html) or clicking the many context help icons ("?") just empty pages are loading:
![grafik](https://user-images.githubusercontent.com/6156251/119975910-b4034b80-bfb6-11eb-8a2c-3b93ed065f9f.png)

 

**Error logs**
```
Copy-and-paste logs from the command you executed, GRR server log files, or flow logs.
```

**Additional context**

**Comment by mbushkov** [comment]
Hi @careyer ,
Thanks for bringing this up.

> Problem 1: After install the GRR Admin UI can successfully be accessed via Browser and GRR is for the most part working correctly. However even though clients habe been managed in the past they do not show up on the startpage under the section "Recently Accessed clients". This section always stays empty (even though flows have been issued and have been processed by clients).

The way "Recently accessed clients" is implemented is: it checks for latest client approvals (requested or granted) - see https://grr-doc.readthedocs.io/en/latest/maintaining-and-tuning/approval-based-workflow.html. Unless you have approval system turned on, unfortunately, "Recently accessed clients" will stay empty. TBH, I think we should change the wording and rename "Recently accessed clients" to "Recent approvals". Then there will be no confusion.

> Problem 2: The integrated help/documentation does no load correctly. When clicking the "Help" Link (http://hostname:8000/help/index.html) or clicking the many context help icons ("?") just empty pages are loading:

Hm, sounds like a bug will take a closer look and double-check this.

**Comment by careyer** [comment]
Thank you very much! We indeed cot the ACL.Router thing working now and it works as expected =)
Problem 2 persists however which is a little bit sad - especially if you are new to grr and you can't consult the inline help

**Comment by panhania** [comment]
Regarding the help links: I created a completely fresh GRR installation on Ubuntu 18.04 and it seems to work fine for me:

  * "?" near the search bar takes me to ["Searching for a client"](https://grr-doc.readthedocs.io/en/v3.4.3/investigating-with-grr/searching-for-client.html) help page.
  * "?" near the robot button in "Hunts" view takes me to ["Hunt controls"](https://grr-doc.readthedocs.io/en/v3.4.3/investigating-with-grr/hunts/controlling-hunts.html) help page.

Can you tell me exactly which buttons didn't work for you?

**Comment by panhania** [comment]
Also, could you tell me what is the value of `AdminUI.docs_location` setting in your GRR configuration? By default, it should point to https://grr-doc.readthedocs.io/en/latest.

**Comment by careyer** [comment]
Thanks! The problem was that I had the client deployed in a internet-denied environment. So it could not load the internet based help pages! Thank you for looking into this!
