### ISSUE TITLE
Suggestion: max_allowed_packet instructions in installation documentation

### ISSUE THREAD

**Issue by alwashmi** [google/grr#947]
[Here in the documentation](https://grr-doc.readthedocs.io/en/latest/installing-grr-server/from-release-deb.html), the installation instructions point people to modify ```max_allowed_packet``` global variable by running ```SET GLOBAL max_allowed_packet=41943040;```. However, this setting doesn't persist.
I suggest modifying the file ```/etc/mysql/my.cnf``` by adding the following two lines:
```
[mysqld]
max_allowed_packet=40M
```
Then, restarting the mysql service as follows 
```
service mysql restart
```
This way the setting persists.

**Comment by panhania** [comment]
We will discuss this issue — thanks for reporting that!

**Comment by mbushkov** [comment]
Thanks for the suggestion! Updated the docs: https://grr-doc.readthedocs.io/en/latest/installing-grr-server/from-release-deb.html
