### ISSUE TITLE
AnalyzeClientMemory Error

### ISSUE THREAD

**Issue by pidydx** [google/grr#98]
Flow: AnalyzeClientMemory
status: ERROR Needed profile v1.0/nt/GUID/64ECD0C7871F4B9E94D7C26826C285282 not found! 

Host Info
OS_RELEASE: 2008ServerR2 
OS_VERSION: 6.1.7601SP1
Uname: Windows-2008ServerR2-6.1.7601SP1 

It appears that this profile does not exist in the rekall-profiles repo, but reporting here since it was specifically a GRR flow issue something else may be root cause.

**Comment by scudette** [comment]
Thanks. Added to rekall profile repo.

**Comment by pidydx** [comment]
Great, thanks!
