### ISSUE TITLE
Windows on ARM, Support?

### ISSUE THREAD

**Issue by sidd-kishan** [google/grr#984]
**Environment**
Please let us know when can we have an ARM64 version for Windows on ARM OS. We can help you test We have Windows on Rasberry Pi setup. Please pursue it we at Windows on Rasberry Pi community will be glad to extend support in testing your drivers and tools for ARM64.

**Comment by max-vogler** [comment]
We can't give an ETA for official Windows ARM64 support. This is very low priority for us now and we will likely not find time for it in 2022.

**Comment by mbushkov** [comment]
@sidd-kishan, even though we currently can't handle this ourselves, you could try building your own ARM64 templates. We have some relevant [docs](https://grr-doc.readthedocs.io/en/latest/maintaining-and-tuning/building-custom-client-templates.html#building-the-templates) and would be happy to consult you on the matter.

Fundamentally building an ARM64 windows template boils down to the following:
* Install key GRR and Fleetspeak Python packages on an ARM64 system as described [here](https://grr-doc.readthedocs.io/en/latest/installing-grr-server/from-source.html).
* Use the `grr_client_build` command as documented [here](https://grr-doc.readthedocs.io/en/latest/maintaining-and-tuning/building-custom-client-templates.html#building-the-templates).

You can then even set up your own CI jobs and share generated templates with the community - I'm sure that would be much appreciated.
