### ISSUE TITLE
GRR Client installation error - Permission Denied (PublicKey) 

### ISSUE THREAD

**Issue by Amikumar0** [google/grr#994]
**Environment**
- How did you install GRR? [e.g. from release DEB, HEAD DEB, PIP package, source] 
- DEB
- What GRR version are you running?: [e.g. 3.1.2.3]
- GRR 3.4.6.0
- What operating system does the GRR server run on? [e.g. Ubuntu 18.04]
- Ubuntu 18.04
- What operating system does the affected GRR client run on, if applicable? [e.g. Windows 10]
- CentOS 7

**Describe the issue**
I have setup GRR server in aws but I am not able to deploy grr agent on my centos system. when i am running grr client package it shows permission denied (Publickey)
**Error logs**

```
Copy-and-paste logs from the command you executed, GRR server log files, or flow logs.
ssh -v host sudo rpm -i /tmp/client_version.rpm
Permission Denied (Publickey)

```
**Additional context**

**Comment by max-vogler** [comment]
Hey! `Permission Denied (Publickey)` is not a GRR error. It sounds like a problem that you have with connecting to your host in AWS, independent of GRR.
